### ISSUE TITLE
Lists not getting shared while under load

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2267] opened 2017-02-01 01:54 UTC
### Sync Gateway version
1.4-55

### Operating system
CentOS7

### Config file
https://gist.github.com/sethrosetter/54d365660305d5baf4369c1c2e787a87

### Log output
https://s3.amazonaws.com/cbmobile-bucket/issues/issue_2267_test_fest/sync_gateway_error.log

### Package capture
https://s3.amazonaws.com/cbmobile-bucket/issues/issue_2267_test_fest/reproduce_issue_missing_lists.pcap

### Expected behavior
All lists should be shared

### Actual behavior
A few devices are missing lists. Restarting the app does not help. Only reinstalling the app brings the missing lists to the devices.

### Steps to reproduce
1.  Test fest with the following topology
   - Raghu: Android 7.1.1 (1.4-31), iOS 8 (1.4-35)
   - Pasin: iOS 10 (1.4-35)
   - Hideki: Android 6.0 (1.4-31), Android (5.1.0) (1.4-31)
   - James: iOS (1.4-35), Android (1.4-31)
   - Jim: .NET (1.4-32)
   - Seth: .NET (1.4-32) 
2. Load tool creates list for each user
3. Each user shares with everyone else
4. Some users do not get all of the shared lists (possibly due to a backfill issue?) 
     - rahgu does not see james's list on iOS
     - james did not see jim's list on both Android / iOS

**Comment by sethrosetter** [comment] 2017-02-01 02:00
Raghu's missing list id = james.123
James's missing list id = jim.123

**Comment by tleyden** [comment] 2017-02-01 02:16
In packet 19816, the channel grant happens:

From wireshark:

```
ce{XEA>@@=V/x$0#W
BHTTP/1.1 201 Created
Content-Length: 69
Content-Type: application/json
Server: Couchbase Sync Gateway/1.4
Date: Wed, 01 Feb 2017 01:31:53 GMT

[{"id":"james.123.raghu","rev":"1-1e7677e807d84ca74d2c40bf32d0d635"}]
``` 

From ngrep:

```
T 86.180.22.47:60964 -> 172.31.61.20:4984 [AP]
POST /todo/_bulk_docs HTTP/1.1.
Host: ec2-184-72-196-121.compute-1.amazonaws.com:4984.
Content-Type: application/json.
Accept-Encoding: gzip, deflate.
Connection: keep-alive.
Accept: application/json.
User-Agent: CouchbaseLite/1.3 (iOS 1.3.1/6f0d9e4eb2c50387b13c79f04b5aa8eeb4713c14).
Authorization: Basic amFtZXM6cGFzcw==.
Content-Length: 255.
Accept-Language: en-gb.
.

#
T 86.180.22.47:60964 -> 172.31.61.20:4984 [AP]
{"docs":[{"username":"raghu","_id":"james.123.raghu","_rev":"1-1e7677e807d84ca74d2c40bf32d0d635","type":"task-list.user","taskList":{"id":"james.123","owner":"james"},"_revisions":{"ids":["1e7677e807d84ca74d2c40bf32d0d635"],"start":1}}],"new_edits":false}
##
T 172.31.61.20:4984 -> 86.180.22.47:60964 [AP]
HTTP/1.1 201 Created.
Content-Length: 69.
Content-Type: application/json.
Server: Couchbase Sync Gateway/1.4.
Date: Wed, 01 Feb 2017 01:31:53 GMT.
.
[{"id":"james.123.raghu","rev":"1-1e7677e807d84ca74d2c40bf32d0d635"}]
```

**Comment by tleyden** [comment] 2017-02-01 02:22
Later, in packet 19848:

```
e{XcE@/#j=?x1imE
UGET /todo/james.123.raghu?rev=1-1e7677e807d84ca74d2c40bf32d0d635&revs=true&attachments=true HTTP/1.1
Host: ec2-184-72-196-121.compute-1.amazonaws.com:4984
Authorization: Basic cmFnaHU6cGFzcw==
Credential: raghu:pass
Accept-Encoding: gzip, deflate
Accept: multipart/related, application/json
Accept-Language: en-us
Connection: keep-alive
X-Accept-Part-Encoding: gzip
User-Agent: CouchbaseLite/1.3 (iOS 1.4/41eb2b9fadb337043f396ae085134c344444bee9)


```

Must have gotten in previous changes response.

To see all of raghu's requests: `http.authorization == "Basic cmFnaHU6cGFzcw=="`

**Comment by tleyden** [comment] 2017-02-01 02:27
Changes response in 19819

```
{"results":[
{"seq":1231,"id":"james.123.raghu","changes":[{"rev":"1-1e7677e807d84ca74d2c40bf32d0d635"}]}
],
"last_seq":"1231"}

```

So far, does not look like an SG bug

**Comment by borrrden** [comment] 2017-02-01 02:47
Actually the above *should* have returned [this](https://gist.github.com/borrrden/30df9067fda1e13d420ea987ce5c65d4).  That response is missing the backfill.  `since=1231` (the next request) will start *after* the backfill.

**Comment by borrrden** [comment] 2017-02-01 05:34
[Here](https://gist.github.com/borrrden/b43808888a86195d3504c656ae35e515) is the complete conversation filtered to Raghu's iOS device.  The above mentioned response *should* have contained a backfill but it didn't, and so the backfill will never happen once that sequence is passed.  [This](https://gist.github.com/borrrden/30df9067fda1e13d420ea987ce5c65d4) is what the response should have looked like.

Observations:  

1. Raghu's device did not receive shares until very close to the end of the process (mostly after all of the documents were pushed by the loader), and four people shared with him at almost exactly the same time (seq 1214, 1216, 1218, 1219) while others are more spread out throughout the feed.
2. Raghu and James shared with each other at neighboring sequences (1231, 1232)
3. Seth's share document (seth.123.raghu) is missing but his backfill is present.  The reverse is true for James (his share document is present but his backfill is missing)

**Comment by adamcfraser** [comment] 2017-02-02 01:40
It looks to me like there's a race condition when a document grants a user access to a channel, but is also already in a channel that the user has access to.  The following events occur in this flow (using the james.123.raghu case as an example):

Write events
1. **Doc write**. Document james.123.raghu is written to the bucket, assigned to channel `raghu` (among others).
2. **User doc write**. Document _sync:user:raghu is updated in the bucket to nil out the channels (as a result of the access grant on james.123.raghu).
3. **Doc appears on TAP feed** Document james.123.raghu arrives on the server feed, gets added to the channel cache for channel `raghu`, and sends notification that there's been a change in `raghu`
4. **User doc appears on TAP feed** Document _sync:user:raghu arrives on the server feed, and sends notification that there's been a change to `_sync:user:raghu`.

Read events
1. **Longpoll Changes Request**. User raghu starts a longpoll changes feed, which goes into wait mode.
2. **Notification for channel `raghu` wakes up changes**.  The notification from write event W-3 wakes up the changes feed.
3. **Check for user update**.  After waking up, the changes feed checks whether there have been notifications of any changes to `_sync:user:raghu'
4. **Query for changes**  Query for changes and return

The race occurs when Read-3 doesn't detect a change to the user - it gets woken up by the change to channel `raghu`, and the user doc update hasn't arrived on the feed yet.  This is going to happen more often when there are multiple concurrent access grants happening for the same user, because the time taken for W-2 is going to increase based on contention for the user doc.  So the net result is a longer delay between W-3 and W-4, which makes it more likely for R-3 to not see the user update in time.

**Comment by adamcfraser** [comment] 2017-03-17 22:51
Closing as duplicate of https://github.com/couchbase/sync_gateway/issues/2068.

**Closed as completed by adamcfraser** 2017-03-17 22:51 UTC
