### ISSUE TITLE
Changes Feed repeats all the changes when a change is made

### ISSUE THREAD

**Issue by marpal** [couchbase/sync_gateway#621] opened 2015-01-31 13:46 UTC
Hi, 

I'm trying to implement a feature that performs an action when something appears in the changes feed of the sync_gateway. I'm using couchbase server 2.2 and the sync_gateway HEAD in master branch. 
I'm requesting the changes feed by connecting to the admin port and using continuous mode. 
The issue I'm seeing is that everytime I make a change instead of only sending on the stream the change  I made, all the changes appear, repeating every time all the changes. 

Below is a link to the log.

https://gist.github.com/marpal/5de2d9ff63463d1ca312

And a link to the discussion I had with Jens Afke on the forum. 

https://groups.google.com/forum/#!topic/mobile-couchbase/WHwZfAP3NEc

Thanks,
Martin

**Comment by marpal** [comment] 2015-01-31 17:40
I have the same bug using couchbase 3.0.1

**Comment by adamcfraser** [comment] 2015-02-01 06:25
Hi Martin,

Can you provide a bit more detail on the exact sequence of actions you're taking, so that we can try to reproduce and get to the bottom of the reset that seems to be happening on your changes feed?

Thanks,
Adam

**Comment by marpal** [comment] 2015-02-01 12:32
Hi Adam, 
The sequence of actions.

1) Listen to changes feed curl http://XXX.XXX.XXX.XXX:4985/nearup/_changes?feed=continuous
2) Create a new document through couchbase lite for iOS and save it. Document is added correctly to the DB.
3) All the changes are repeated on the stream. 

I tested that using couchbase 3.0.1 and 2.2 community edition.
I can give you access to the server if you would like over private conversation. My e-mail is marpal@gmail.com

Thanks,
Martin

**Comment by adamcfraser** [comment] 2015-02-02 06:57
Thanks - I'll try to reproduce tomorrow.  A few other questions in the meantime:
- Do you see the same behaviour when listening to the changes feed on the public (non-admin) API?
- Is your sync function assigning any particular access/channel information based on the document being created in (2)?

Adam

**Comment by marpal** [comment] 2015-02-02 12:03
Hi Adam,

1) I only tried with the admin API. I will try later with the non admin
2) Yes. I'm accining channel and access to the document that I save. The
channel is conversation-"IdOfConservation". But I think the same happens
with any change.

Best,
Martin

**Comment by marpal** [comment] 2015-02-03 19:11
Hi,

I tried in non-admin port and I have the same behavior.

Thanks, 
Martin

**Comment by adamcfraser** [comment] 2015-02-04 00:55
Hi Martin,

I haven't been able to reproduce yet - I'm only seeing the new (expected) entries coming through on the feed.  I suspect I'm not replicating exactly what's going on in your environment from a channel management perspective.  Can you share your sync function (or at least an excerpt that's doing the channel/access management)?  The full sync gateway log might also be helpful.

Thanks,
Adam

**Comment by zgramana** [comment] 2015-03-20 21:15
@marpal Unless you have any updates, we will close this issue in 7 days.

**Comment by zgramana** [comment] 2015-03-27 17:27
Closed due to inactivity. Please reopen is it's still an issue.

**Closed as completed by zgramana** 2015-03-27 17:27 UTC
Labels: bug

**Comment by atom992** [comment] 2015-09-09 16:02
I have the same problem on Sync Gateway 1.1.0-28 + Couchbase 3.0.2-1603 Enterprise Edition (build-1603)  + CBL android 1.1.0 with PhoneGap plugin. @adamcfraser

**Comment by adamcfraser** [comment] 2015-09-09 16:03
@atom992 Can you file a new issue for this, with details on how to reproduce?
