### ISSUE TITLE
_changes feed with "longpoll" and "since" sometimes returns empty results

### ISSUE THREAD

**Issue by mjq** [couchbase/sync_gateway#916] opened 2015-06-10 00:09 UTC
Bug found on master (`34dbbae`).
### Scenario
- Android app opens a continuous pull replication with Sync Gateway. This `POST`s to `_changes` with payload `{"style":"all_docs", "heartbeat":300000, "feed":"longpoll", "limit":50, "since":26564}`.
- The Android app has already processed all the changes (26564 is the `last_seq`), so the expectation is that the change feed request will remain open until a new change has been received.
- **But**, Sync Gateway responds immediately, with result

``` javascript
{"results"[
],
"last_seq":"26564"}
```
- Since a response from a longpoll changes feed normally means changes were received, Android loops over the (zero) changes and then makes a new longpoll request
- ...which returns the exact same response, causing an **infinite loop of requests to Sync Gateway**.
### The code

For background, the database has a `changeListener` object that maintains, among other things, [a monotonically increasing `counter` and a `keyCounts` map](https://github.com/couchbase/sync_gateway/blob/34dbbae5623680e887711860ebe5ee06e6610f4f/src/github.com/couchbase/sync_gateway/db/change_listener.go#L19-L20). `counter` starts at 1 and gets incremented every time SG gets a change from Couchbase. `keyCounts` maps from keys (e.g. a channel name, user name, or `*`) to the value of the `counter` when the last update to that key was received. Every time a channel gets an update, [the listener's Notify method](https://github.com/couchbase/sync_gateway/blob/34dbbae5623680e887711860ebe5ee06e6610f4f/src/github.com/couchbase/sync_gateway/db/change_listener.go#L81-L94) is called, updating the counter and the keyCounts. This state is used when a client opens the `_changes` feed in order to know when new changes come in: you can watch the map and wait for the value of any key you care about to increase. This is coordinated by [the `changeWaiter` object](https://github.com/couchbase/sync_gateway/blob/34dbbae5623680e887711860ebe5ee06e6610f4f/src/github.com/couchbase/sync_gateway/db/change_listener.go#L141-L146).

So, here's what happens in the scenario above.
- the [MultiChangesFeed](https://github.com/couchbase/sync_gateway/blob/34dbbae/src/github.com/couchbase/sync_gateway/db/changes.go#L160) func is responsible for sending `ChangeEntry`s for a change feed response.
- Since this is a longpoll request, `options.Wait` is true. [So, a `changeWaiter` is created](https://github.com/couchbase/sync_gateway/blob/34dbbae/src/github.com/couchbase/sync_gateway/db/changes.go#L197-L208). The [changeWaiter is initialized](https://github.com/couchbase/sync_gateway/blob/34dbbae/src/github.com/couchbase/sync_gateway/db/changes.go#L199) with the channels passed to `MultiChangesFeed`, and the key for the user. If no channels were explicitly passed to the request to the change feed (which they weren't in this scenario), [`*` is passed](https://github.com/couchbase/sync_gateway/blob/34dbbae5623680e887711860ebe5ee06e6610f4f/src/github.com/couchbase/sync_gateway/rest/changes_api.go#L109).
- `NewWaiterWithChannels` ends up [asking the listener for the `lastCounter`](https://github.com/couchbase/sync_gateway/blob/34dbbae5623680e887711860ebe5ee06e6610f4f/src/github.com/couchbase/sync_gateway/db/change_listener.go#L121-L135). This looks up the given channels in the `keyCounts` map (see above) and returns the highest `counter` value for them all.
- At this point, the keys passed to `listener.CurrentCount` are `["*", "_sync:user:e85f2981-ec2e-422e-852f-bfd5599bd259"]`. So, it returns the counter for whichever key was most recently updated.  _(You might be able to spot the bug at this point.)_ Let's say, for argument, that `lastCounter` is `4`.
- `MultiChangesFeed` continues onward into its main loop. [At this point, the users channels are expanded](https://github.com/couchbase/sync_gateway/blob/34dbbae/src/github.com/couchbase/sync_gateway/db/changes.go#L221-L231). So, instead of `*`, you get the user's real channels. So now the list might be `["_sync:user:e85f2981-ec2e-422e-852f-bfd5599bd259", "g_43", "dm_9"]`. [The `changeWaiter` is updated with this expanded set of channels](https://github.com/couchbase/sync_gateway/blob/34dbbae/src/github.com/couchbase/sync_gateway/db/changes.go#L229-L231). **Note that, because this user doesn't actually have access to `*`, that channel has disappeared from the list.**
- After doing a bunch of work to try to get changes, if there were no changes (_which is true in the scenario above, since `since` is the latest change_), you get to [this conditional](https://github.com/couchbase/sync_gateway/blob/34dbbae/src/github.com/couchbase/sync_gateway/db/changes.go#L415-L421). [`changeWaiter.Wait()`](https://github.com/couchbase/sync_gateway/blob/34dbbae5623680e887711860ebe5ee06e6610f4f/src/github.com/couchbase/sync_gateway/db/change_listener.go#L176-L179) blocks until it gets changes, [using the listener's `keyCounts` again](https://github.com/couchbase/sync_gateway/blob/34dbbae5623680e887711860ebe5ee06e6610f4f/src/github.com/couchbase/sync_gateway/db/change_listener.go#L106-L118) to see if changes have been made.
- **Here's the bug**: If the new highest `counter` value doesn't match the `lastCounter` we got at the beginning, then the code thinks we have changes. When `keyCounts` was first checked, the keys were `["*", "_sync:user:e85f2981-ec2e-422e-852f-bfd5599bd259"]`. Now, the keys are `["_sync:user:e85f2981-ec2e-422e-852f-bfd5599bd259", "g_43", "dm_9"]`. That means that if `*` had the highest value of all our keys in `keyCounts`, then now the counter has _decreased_ (to, say, `2`), making the changeWaiter stop waiting and the change feed return its response _even though there aren't any changes_. In fact, it's _very likely_ for this to happen, because _every_ document change updates the value in `keyCounts` for `*`. The only way for this code to work properly is if the latest change to SG (before the longpoll request is made) was to a document that was inside the requesting user's channels (since then `*` and their channel would have the same `counter` value), or to a document that updated the user's channel access (since then the user's key would have the highest `counter` value).
### The fix

The `changeWaiter` needs to have the user's actual, expanded channels from the start.
e.g., from [this](https://github.com/couchbase/sync_gateway/blob/34dbbae/src/github.com/couchbase/sync_gateway/db/changes.go#L199):

``` go
changeWaiter = db.tapListener.NewWaiterWithChannels(chans, db.user)
```

to

``` go
var channelsSince channels.TimedSet
if db.user != nil {
    channelsSince = db.user.FilterToAvailableChannels(chans)
} else {
    channelsSince = channels.AtSequence(chans, 0)
}
changeWaiter = db.tapListener.NewWaiterWithChannels(channelsSince.AsSet(), db.user)
```

(this expansion code is [just duplicated from here](https://github.com/couchbase/sync_gateway/blob/34dbbae/src/github.com/couchbase/sync_gateway/db/changes.go#L221-L226)).

I can say that, in practice, this does fix the bug. Requests to `_changes` in the given scenario now hang until a change is received, at which point it is written to the response and the response is closed. I haven't tried to write a unit test yet and I'm not 100% confident that this doesn't have any other ramifications. Hoping someone else can look into it/confirm.

This bug affects essentially all of our Android clients, meaning that our Sync Gateway was getting hammered. I'm a bit surprised no one else has come across this, so maybe there's something about our setup that makes it more likely? I don't know yet. If it is a general issue, it's pretty serious. That's a lot of server resources and client bandwidth for nothing.

**Comment by adamcfraser** [comment] 2015-06-10 05:48
Thanks very much for the detailed analysis @mjq.  I think I agree with the proposed fix - I just want to verify that it also works when the user's set of channels changes between iterations of the main changes loop.  In particular I'm wondering whether [the call to changesWaiter.updateChannels](https://github.com/couchbase/sync_gateway/blob/34dbbae/src/github.com/couchbase/sync_gateway/db/changes.go#L230) should be resetting the waiter counters, to handle this case as well as the continuous changes case.

It looks like this issue was exposed when the changes in https://github.com/couchbase/sync_gateway/pull/743 were made.  That PR was intended to address issues similar to this one - where `*` as Star Channel were being confused with `*` as channel wildcard, but obviously missed the initial changeWaiter setup.  

Thanks again - I'll try to get a fix for this on master asap.

**Comment by adamcfraser** [comment] 2015-06-12 07:02
@mjq I still agree with your proposed change, but I haven't been able to reproduce your issue via unit test.  I'm able to reproduce the underlying problem - [curCounter != counter here](https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/change_listener.go#L113)

However, when this returns to the changes processing and does another iteration,  [this conditional](https://github.com/couchbase/sync_gateway/blob/34dbbae/src/github.com/couchbase/sync_gateway/db/changes.go#L411) is still evaluating to false (`sentSomething==false` and `changeWaiter` isn't nil), so the changes loop doesn't send anything or terminate.  The changes loop is just doing another iteration, and [hitting the wait again](https://github.com/couchbase/sync_gateway/blob/34dbbae/src/github.com/couchbase/sync_gateway/db/changes.go#L419) , this time with the updated keys.

Again, I still agree that `*` should be getting expanded from the outset, but I'd like to be able to reproduce the issue via unit test to completely understand what's going on in your scenario.

I've pushed the unit test to the feature/issue_916 if you're interested in having a look.  I'm going to switch to testing against a real Sync Gateway to see if I can find any differences there.

**Comment by adamcfraser** [comment] 2015-06-16 16:07
Was able to reproduce an issue with the same root cause when running a continuous changes feed.  Turning that into a unit test, and then will merge the fix.

**Closed as completed** 2015-06-17 21:26 UTC
Labels: bug, P2: medium
