### ISSUE TITLE
FATAL: Error opening database todo: Error installing principals for role: 409 Already exists -- rest.RunServer() at config.go:773

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3180] opened 2018-01-10 00:05 UTC
With this [SG config](https://gist.github.com/d4dc687cdbc59449d32b40bafc57536f) and this [SG Accel config](https://gist.github.com/922a0ac6f4b74eaaf58b2e2ce8206c57), I'm getting the following error after restarting Sync Gateway with a non-empty bucket:

```
2018-01-09T15:56:24.375-08:00 Opening db /todo as bucket "todo", pool "default", server <http://localhost:8091>
2018-01-09T15:56:24.375-08:00 GoCBCustomSGTranscoder Opening Couchbase database todo on <http://localhost:8091> as user "todo"
2018-01-09T15:56:24.986-08:00 GoCB Opening Couchbase database todo_index_bucket on <http://localhost:8091> as user "todo_index_bucket"
2018-01-09T15:56:24.990-08:00 GoCB Opening Couchbase database todo_index_bucket on <http://localhost:8091> as user "todo_index_bucket"
2018-01-09T15:56:25.282-08:00 Access: Computed channels for "moderator": !:1,task-list.user1.F88F897F-0745-4B75-BC62-A95E2DEC9193:13.1
2018-01-09T15:56:25.283-08:00 FATAL: Error opening database todo: Error installing principals for role: 409 Already exists -- rest.RunServer() at config.go:773
```

I'm not sure if this is a bug or a misconfiguration, but it's making it hard to run Sync Gateway.  The workaround is to flush the bucket.

(Not sure if SGA has anything to do with this, just mentioning for completeness)

SG commit: 2ba4297a270d155ee5b461643eec085f65549a59 (latest on `feature/issue_2653_blip_active_replicator`), which has been recently re-based off of master.

**Comment by adamcfraser** [comment] 2018-01-10 00:07
I think this is a duplicate of https://github.com/couchbase/sync_gateway/issues/3178 (although 3178 doesn't do a good job of making that obvious)

**Comment by tleyden** [comment] 2018-01-10 00:19
Stacktrace:

```
2018-01-09T16:14:37.649-08:00 FATAL: Error opening database todo: 409 Already exists
Error installing principals for role
github.com/couchbase/sync_gateway/rest.(*ServerContext)._getOrAddDatabaseFromConfig
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:585
github.com/couchbase/sync_gateway/rest.(*ServerContext).getOrAddDatabaseFromConfig
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:262
github.com/couchbase/sync_gateway/rest.(*ServerContext).AddDatabaseFromConfig
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:713
github.com/couchbase/sync_gateway/rest.RunServer
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/config.go:772
github.com/couchbase/sync_gateway/rest.ServerMain
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/rest/config.go:830
main.main
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/main.go:40
runtime.main
	/usr/local/go/src/runtime/proc.go:195
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2337 -- rest.RunServer() at config.go:773

Process finished with exit code 1

```

**Comment by tleyden** [comment] 2018-01-10 00:29
Looks like the problem is that this comparison is not returning true:

```
	// GoCB handling
	if unwrappedErr == gocb.ErrKeyExists {
		return true
	}
```

<img width="1403" alt="screen shot 2018-01-09 at 4 26 44 pm" src="https://user-images.githubusercontent.com/296876/34750096-ef9f004c-f559-11e7-92ea-97e0f0e0f7f3.png">

**Comment by tleyden** [comment] 2018-01-10 00:38
## Workaround

```
func IsCasMismatch(err error) bool {
	if err == nil {
		return false
	}

	unwrappedErr := pkgerrors.Cause(err)

	// GoCB handling
	if unwrappedErr == gocb.ErrKeyExists {
		return true
	}

	// Temp workaround for https://github.com/couchbase/sync_gateway/issues/3180
        // ^^^^^^^^^^^^^^^^^^^
	if strings.Contains(unwrappedErr.Error(), "Already exists") {
		return true
	}

	// GoCouchbase/Walrus handling
	if strings.Contains(unwrappedErr.Error(), "CAS mismatch") {
		return true
	}

	return false
}
```

**Closed as completed** 2018-01-10 01:45 UTC
