### ISSUE TITLE
SG-Replicate panic while running replication

### ISSUE THREAD

**Issue by tyh0** [couchbase/sync_gateway#1996] opened 2016-07-25 18:46 UTC
I am currently trying to run SG-Replicate to migrate all data from one couchabse/sync-gateway DB to another, and experienced the following: https://gist.github.com/tyh0/475f964b0c08caabe21b65973f954f68

Do you have any idea what caused this, and how it can be prevented? The process stopped at 60908 / 72055 documents, so SG-Replicate is leaving many documents behind.

**Comment by tyh0** [comment] 2016-07-25 18:50
This is the config file that was used to run SG-Replicate: https://gist.github.com/tyh0/bb167145bd7e1adbcc4c73874deb6122

**Comment by tyh0** [comment] 2016-07-25 18:53
This was the result of retrying the replication using the same config file: https://gist.github.com/tyh0/f220c7065cd706a35e93556165489b5c. Now the number of documents in the destination database is 60954.

**Comment by tleyden** [comment] 2016-07-25 18:56
@tyh0 it looks like it got a timeout trying to push docs to the target sync gateway:

```
2016/07/25 11:38:34 Replicate: [db-local] bulk get resp: <nil>, err: Post http://104.197.40.118:4985/orkdb/_bulk_docs: net/http: timeout awaiting response headers
2016/07/25 11:38:34 Replicate: [db-local] Error getting bulk get: Post http://104.197.40.118:4985/orkdb/_bulk_docs: net/http: timeout awaiting response headers
```

There are lots of reasons why that may have failed, but I think the first thing to check would be to make sure there aren't any errors / panics (crashes) in the target Sync Gateway logs.

Can you either upload to a gist and attach to the ticket or send me the gist over gitter?

**Comment by adamcfraser** [comment] 2016-07-25 18:58
@tyh0 On the secondary question (why only 60954/72055 docs) - are all of those 72055 docs application data, or is that just the raw number of documents in the bucket (which would include non-replicated data like users, sessions, checkpoints, etc)?

**Comment by tyh0** [comment] 2016-07-27 18:19
I just sent Traun the logs for both sg pods over gitter. As for the number of documents, 72055 is the number of total documents based on what is displayed in the cb web interface of the source DB.

**Comment by tleyden** [comment] 2016-07-27 19:34
@tyh0 is there any chance something else is modifying the couchbase server doc directly?  (as opposed to sync gateway being the only thing that modifies docs in the couchbase server bucket)

**Comment by tyh0** [comment] 2016-07-27 19:40
As far as I know, the only service that is making changes to CB should be SG. The only types of pods in the GKE cluster are app-etcd, nginx, couchbase, couchbase-admin, and sync gateway.

**Comment by tleyden** [comment] 2016-07-27 19:49
Were the two log zips both from the target server?  Eg, different runs?

**Comment by tleyden** [comment] 2016-07-27 19:50
> both sg pods

do you mean two SG instances in the target cluster behind a load balancer?

**Comment by tleyden** [comment] 2016-07-27 19:59
> This was the result of retrying the replication using the same config file: https://gist.github.com/tyh0/f220c7065cd706a35e93556165489b5c. Now the number of documents in the destination database is 60954.

Can you hit the `_all_docs` endpoint on the source sync gateway and the target sync gateway and see if the `total_rows` result matches up?  At the end of the `_all_docs` response you should something like:

```
total_rows: 28,
update_seq: 115
```

**Comment by tleyden** [comment] 2016-07-27 20:09
If you run the `_all_docs` curl requests on both the source and the target sync gateways, and the `total_rows` is identical, then that confirms that the replication was successful.

As @adamcfraser mentioned, there are a number of documents that _won't_ replicate with the sg-replicate tool:
- User docs
- Session docs
- Local (_local) docs

The first run where it [panicked](https://github.com/couchbase/sync_gateway/issues/1996#issue-167437336) may have been a sporadic issue.  To reduce the chance of that happening you could try [increasing the timeouts](https://github.com/couchbaselabs/sg-replicate/blob/9313a67a9234d96f3073a979b22bea5b322b56d6/synctube.go#L41-L48) and re-building the code and re-running it.

If you can reliably reproduce the panics](https://github.com/couchbase/sync_gateway/issues/1996#issue-167437336) then we can investigate to try to find the root cause, but if it's not easily reproducible it could have been a one-off issue due temporarily low resources.

**Comment by tleyden** [comment] 2016-07-27 20:10
@tyh0 I'm going to proactively close this, but if you are seeing a different number of `total_rows` in the `_all_docs` response, or you can reliably reproduce the panic you saw, we can re-open it.

**Closed as completed by tleyden** 2016-07-27 20:10 UTC
