### ISSUE TITLE
Unable to resurrect tombstones when using xattr

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2556] opened 2017-05-11 23:47 UTC
Attempting to mutate the doc body and xattr for a document that's been tombstoned (doesn't have a document body) is returning a key not found error, instead of updating the body+xattr, even though the AccessDeleted flag is set for the operation.

https://github.com/couchbase/sync_gateway/blob/master/base/bucket_gocb.go#L866

**Comment by tleyden** [comment] 2017-05-12 16:35
Is there a failing test this is linked to?

**Comment by adamcfraser** [comment] 2017-05-12 17:46
Pending test: https://github.com/couchbaselabs/mobile-testkit/issues/1131

**Comment by sethrosetter** [comment] 2017-06-26 22:06
Is this a potential server bug?

**Comment by sethrosetter** [comment] 2017-06-27 22:57
Is this a duplicate of this - https://github.com/couchbase/sync_gateway/issues/2641?

If so, the doc resurrection tests are passing and I think this is no longer an issue.

**Closed as completed** 2017-07-31 19:45 UTC
Labels: P1: high
