### ISSUE TITLE
Collect system stats with Splunk locally 

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#597] opened 2015-01-23 18:34 UTC
Includes server, switch, etc., system resource usage.

**Comment by tleyden** [comment] 2015-01-28 00:01
This [perfrunner test run](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/567/artifact/gateway_expvar_1.json) is jumping out as being particularly bad:

```
lag-tap-225100ms: 141,
lag-tap-225200ms: 145,
lag-tap-225300ms: 153,
lag-tap-225400ms: 156,
lag-tap-225500ms: 118,
lag-tap-225600ms: 137,
lag-tap-225700ms: 151,
lag-tap-225800ms: 134,
lag-tap-225900ms: 137,
lag-tap-226000ms: 125,
```

This means that 141 documents had a "tap lag" -- the round trip time it took for a Sync Gw to write the doc to Couchbase Server and then receive it on its own tap feed -- of  225.1 seconds.  (nearly 4 minutes)

Likewise, 145 docs had a tap lag of 225.2 seconds.

Also noteworthy in those stats is `view_queries: 963`.  I think it's possible that the view queries are putting a heavy strain on couchbase server, such that they cause the tap lag to skyrocket.

**Comment by tleyden** [comment] 2015-01-28 00:04
On the other hand, this [perfrunner test](http://ci.sc.couchbase.com/view/sync%20gateway/job/cen006-p0-cbsgw-real-perf/584/artifact/gateway_expvar_1.json) had 982 view_queries, yet its max tap-lag was only 6 seconds, so a high number of view_queries does not always mean a high max tap-lag.

Another noteworthy thing that was noticed on that same test run was a copious amount of indexing/compacting happening on couchbase server:  http://cl.ly/image/1E0L0o1R1U3Q?_ga=1.81219796.257213425.1401744125

**Comment by tleyden** [comment] 2015-03-27 17:54
- Install splunk locally 
- Run TodoLite
- Run Sync Gw locally
- Collect System Stats

**Comment by tleyden** [comment] 2015-05-15 18:12
Closing as duplicate of #760

**Closed as completed by tleyden** 2015-05-15 18:12 UTC
Labels: performance, chore
