### ISSUE TITLE
Changes feed returning duplicates for * channel

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1384] opened 2015-12-24 22:37 UTC
Using "Couchbase Sync Gateway/1.2.0(14;dc01e66)"

I have 2 users
user_1 has channels ["ABC"]
user_2 has channels ["*"]

user_1 pushes 7000 docs with ["ABC"] channel
user_2 pushes 3000 docs with ["*"] channel

when issuing a _changes request from user_1, I get back the expected 7000 docs
when issuing a _changes request from user_2, I get back 12951 doc with lots of duplicates

I expect to get back 10000 docs "ABC" plus "*" channel docs
This test is reproducible here https://github.com/couchbaselabs/sync-gateway-testcluster/blob/master/functional_tests/test_users_channels.py#L127-L155

This test used to pass consistently.

 Logs here - https://s3.amazonaws.com/sync-gateway-logs/functional_tests-test_users_channels.py-test_single_user_single_channel-2015-12-24-14-25-07-sglogs.zip

**Comment by adamcfraser** [comment] 2016-01-26 18:44
Root cause is described in #1353.  Closing as duplicate.

**Closed as completed by adamcfraser** 2016-01-26 18:44 UTC
Labels: bug
