### ISSUE TITLE
Trying to post attachment with simple user authentication returns err 400

### ISSUE THREAD

**Issue by vladoatanasov** [couchbase/sync_gateway#1368] opened 2015-12-17 18:07 UTC
Hi,
I am trying to post an attachment with an authenticated user. I am passing the username and password in the url. Sync gateway returns error 400. Posting the body of the document works fine, also if I post with the GUEST, the request passes.

the request is: 
PUT /default/document HTTP/1.1
Host: localhost:4984

PUT /default/document/attachment.png?rev=1-59201569daabb81a0295ff7bb91914ff HTTP/1.1
Host: localhost:4984
Content-Type: image/png

posting to http://user:pass@localhost:4984/db/... fails on the attachment with the following error: 
#021:     --> 400 user defined top level properties beginning with '_' are not allowed in document body  (0.5 ms)

I spoke with @jamiltz and he was able to reproduce the issue.

I haven't tried authenticating via the admin port and creating the session, but I would rather not do that, because I can't deploy an authentication service on the sync gateway box.

Regards,
Vladimir

**Comment by vladoatanasov** [comment] 2015-12-18 09:57
Small update, creating a session and authenticating with a cookie works.

**Comment by ajres** [comment] 2015-12-18 11:25
I can't repro this on a setup with a default sync function and GUEST disabled and a single user defined with admin_channels = ["*"]

@vladoatanasov or @jamiltz can you add your SG config to the ticket and the exact steps, including the initial document contents, that you used to produce this.

**Comment by ajres** [comment] 2015-12-18 12:33
From @jamiltz 

config file:

```
{
  "log": ["*"],
  "databases": {
    "testappdemo": {
      "server": "walrus:",
      "bucket": "default",
      "users": {
        "GUEST": { "disabled": false, "admin_channels": ["*"] },
        "user": {"password": "letmein"}
      },
      "sync": `function(doc, oldDoc) {

        }`
    }
  }
}
```

create attachment: $ touch hello.txt
create document: $ curl -H 'Content-Type: application/json' -vX PUT 'http://localhost:4984/testappdemo/123' -d '{}'
save attachment: $ curl -H 'Content-Type: application/json' -vX PUT 'http://user:letmein@localhost:4984/testappdemo/123/hello?rev=<rev number from doc insertion>' -T 'hello.txt'

**Comment by ajres** [comment] 2015-12-18 12:37
The above steps do reproduce the issue.

The issue is not seen if the "user" object is changed to:

```
"user": {"password": "letmein", "admin_Channels":["*"]}
```

In the call to revision.go containsUserSpecialProperties() for the failing case the body contains the property '_removed', which is not in the acceptable list of special properties.

In the passing case the '_removed' property is not present.

**Comment by ajres** [comment] 2015-12-18 12:46
For this test scenario, the issue is that the calling user does not have access to the revision via any channel, the revision is not _deleted, so SG gateway assumes that the document must have been removed from access to the user after they got the revision in a _changes feed. SG adds the _removed property to the document body, which fails the special property check later.

There are a couple of issues here, why the behaviour when using cookies is different to basic auth.

Should containsUserSpecialProperties() be updated to accept _removed

**Comment by vladoatanasov** [comment] 2015-12-18 14:06
Hi @ajres,
I'm sorry I misled you earlier. I didn't realize I was testing the cookie auth without requireUser in the config file. I am getting exactly the same error when I try to authenticate with a cookie. Again, the document works, attachment fails with the err 400

The user that I'm authenticating, was created via the REST API 

Regards,
Vladimir

**Comment by ajres** [comment] 2015-12-18 18:10
A short term workaround for this issue is to ensure that the user has access to the doc revision via at least one channel.

**Comment by vladoatanasov** [comment] 2015-12-18 21:12
Yes, I did that. The issue is not a blocker

Thank you

**Comment by adamcfraser** [comment] 2020-02-07 00:15
Closing based on age.

**Closed as completed by adamcfraser** 2020-02-07 00:15 UTC
Labels: icebox
