### ISSUE TITLE
[REST] Inconsistent behavior between POST :4984/db/ and :4984/db  

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1386] opened 2015-12-28 22:12 UTC
Using "Couchbase Sync Gateway/1.2.0(14;dc01e66)" Possible dupe of https://github.com/couchbase/sync_gateway/issues/1326, however, I wanted to filed a separate issue, as this is an inconsistency on a public REST endpoint and the other issue includes only Admin endpoints as examples.

Expected behavior
Posting a doc to :4984/db/ and 4984/db should both succeed
Actual behavior
Posting a doc to :4984/db/ succeeds and Posting a doc to :4984/db fails

**Comment by adamcfraser** [comment] 2015-12-28 22:19
I agree this is a duplicate of #1326 - added a note there to clarify the fix should cover both public and admin endpoints.

**Closed as completed by adamcfraser** 2015-12-28 22:19 UTC
