### ISSUE TITLE
Sync Gw write throughput is not increasing with sg-accelerator

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2583] opened 2017-05-17 10:45 UTC
### Sync Gateway version
1.4.1

### Operating system
RedHat 7.2

### Setup Details
3* CBS nodes
2* syncgateway
2* syncgateway replicators

With defined specific traffic of we are not seeing any improvement on syncgateway writes per second with adding sg-accelerator compared to without sg-accelerator.

sg-acceleator configuration
"cluster_config": {
"server": "http://cbs:8091",
"bucket": "ptxdata",
"data_dir": "."
},
"maxFileDescriptors": 250000,
"couchbaseKeepaliveInterval": 0,
"databases":{
"ptxdata":{
"server":"http://cbs:8091",
"bucket":"ptxdata",
"channel_index": {
"writer": true,
"server": "http://cbs:8091",
"bucket": "channel_bucket"
},
"revs_limit" : 60,
}
}
 
### Expected behavior
On adding sg-accelerator writes per second should increase

### Actual behavior
No improvement of adding sg-accelerator

### Steps to reproduce
1.  Have setup mentioned above and run traffic with defined config
2.  Add same number of sg-accelerator as syncgateway and run same traffic

**Comment by adamcfraser** [comment] 2017-05-26 18:55
Seems like duplicate of https://github.com/couchbase/sync_gateway/issues/2535 - see comments there.

**Closed as completed by adamcfraser** 2017-05-26 18:55 UTC

**Comment by ArihantRk** [comment] 2017-06-01 09:39
@adamcfraser This is separate issue from 2535.

We have 2 clusters, with 2 sync gw and 3 CBS nodes in each cluster and we are using sg-replicator to replicate between clusters.
When we add SG-accelerator to the cluster, sync gw  throughput is not increasing and does not see any improvement compared without sg-accelerator. During our traffic testing, we could see sync gw throughput is below the value achieved without sg-accelerator.

**Comment by adamcfraser** [comment] 2017-06-01 15:11
From #2535:

> The primary purpose of sg-accelerator is to support horizontal scalability of the Sync Gateway cluster, to support distribution of overall load across the cluster.

> Unfortunately this doesn't help with cluster-to-cluster replication - that's still currently limited to a single node, and so doesn't benefit from scaling out the SG cluster. There have been initial discussions about how to deliver horizontal scalability for cluster-to-cluster replication, but that feature hasn't been implemented yet.
