### ISSUE TITLE
SG is not upgrading from 1.5 to 2.0

### ISSUE THREAD

**Issue by hrajput89** [couchbase/sync_gateway#3178] opened 2018-01-09 19:18 UTC
SG upgrade is failing from 1.5.1-4 to 2.0.0-731

### Sync Gateway version
S

### Operating system
Centos7

### Log output
[sync_gateway_error.log](https://github.com/couchbase/sync_gateway/files/1616322/sync_gateway_error.log)

### Expected behavior
upgrade should happen without any error

### Actual behavior
Fatal erro is thrown

### Steps to reproduce
1.  install SG 1.5.1-4
2.  stop SG using "service sync_gateway stop" or "systemctl stop sync_gateway" command
3.  upgrade SG to 2.0.0-731
 rpm -Uvh couchbase-sync-gateway-enterprise_2.0.0-731_x86_64.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:couchbase-sync-gateway-2.0.0-731 ################################# [ 50%]

You have successfully uninstalled Couchbase sync_gateway.

Cleaning up / removing...
   2:couchbase-sync-gateway-1.5.1-4   ################################# [100%]

You have successfully installed Couchbase sync_gateway.

You can find sample sync_gateway configuration files in the /opt/couchbase-sync-gateway/examples folder.

You can control the Couchbase sync_gateway service by using the following command:

  systemctl start sync_gateway

That's it! sync_gateway is now running on port 4984. We've setup a simple in-memory database
which works great for exploring sync_gateway's capabilities. A limited console is available
by opening your browser to http://localhost:4985/_admin/.

The command-line options are:

  -adminInterface=":4985": Address to bind admin interface to
  -bucket="sync_gateway": Name of bucket
  -dbname="": Name to assign to this database (defaults to name of bucket)
  -interface=":4984": Address to bind to
  -log="": Log keywords, comma separated
  -personaOrigin="": Base URL that clients use to connect to the server
  -pool="default": Name of pool
  -pretty=false: Pretty-print JSON responses
  -url="walrus:": Address of Couchbase server
  -verbose=false: Log more info about requests

By using this software you agree to the End User License Agreement.
See /opt/couchbase-sync-gateway/LICENSE.txt.

**Comment by adamcfraser** [comment] 2018-01-09 19:20
@hrajput89 Can you include the config file you're using?

**Comment by raghusarangapani** [comment] 2018-01-09 20:59
@hrajput89 is probably using this
https://github.com/couchbaselabs/mobile-testkit/blob/master/resources/sync_gateway_configs/testfest_todo_cc.json

**Comment by adamcfraser** [comment] 2018-01-10 01:46
Duplicate of #3180, has been fixed.

**Closed as completed by adamcfraser** 2018-01-10 01:46 UTC

**Comment by hrajput89** [comment] 2018-01-10 07:20
@adamcfraser PFA config file


[testfest_todo_cc.log](https://github.com/couchbase/sync_gateway/files/1617817/testfest_todo_cc.log)
