### ISSUE TITLE
Sync Gateway doesn't create reduce function when creating view

### ISSUE THREAD

**Issue by timritzer** [couchbase/sync_gateway#3345] opened 2018-02-28 21:46 UTC
This occurs on Sync Gateway 1.5.1. We are currently on 1.4.1, and this functionality works fine. This was found while testing for upgrade path due to other bugs fixed in the 1.5 timeframe. Have removed the view and tried on 1.4.1 and then back again on 1.5.1 to verify it works fine on 1.4.1.

Occurs on Windows environments. Have tested on Windows 10 as well as Server 2008 R2

Configuration:
Nothing special on the config, using the provided example for pointing at a real bucket, only changing the URL to our server, and the bucket to our bucket. (Also occurs on other environment with multiple buckets currently running 1.4.1 successfully)

Relevant Logs
Unfortunately, even with all logging turned on, I get no logs about the creation other than the HTTP ones. Keys enabled: CRUD, CRUD+, HTTP, HTTP+, Bucket, Replicate, Events, Attach, Feed, Cache, Auth, Access
Only logs generated:

15:18:19.004809 2018-02-28T15:18:19.004-06:00 HTTP:  #009: PUT /db/_design/keylookup_withreduce  (ADMIN)
15:18:19.055023 2018-02-28T15:18:19.055-06:00 HTTP+: #009:     --> 201 OK  (50.2 ms)

Expected:
Expected the view to have both the map and reduce functions associated to it.

What Happens:
The view is created with a map, but no reduce.

Steps to reproduce:

1. Create view through Sync Gateway. We usually do this in the back end application, but for reference created using CURL in windows:
`curl -v -X PUT http://localhost:4985/db/_design/keylookup_withreduce -H "Content-Type: application/json" -d "{ \"views\": {\"keylookup_withreduce\": { \"map\": \"function (doc, meta) { if(doc._deleted) { return; } for(var i in doc.channels) { emit(doc.channels[i], doc.keyid);}}\" , \"reduce\": \"function (keys, values, rereduce) { if (rereduce) { var result = []; for (var i = 0; i ^< values.length; i++) { var distinct = values[i]; for (var j = 0; j ^< distinct.length; j++){result.push(distinct[j]);}} return result.filter(function (e, i, arr) { return arr.lastIndexOf(e) === i;}); } return values.filter(function (e, i, arr) { return arr.lastIndexOf(e) === i; } );} \" }}}"`

2. Query view through Sync Gateway. Again, usually done in code, but for purposes of recreation here is a CURL request:
`curl -v http://localhost:4985/db/_design/keylookup_withreduce/_view/keylookup_withreduce?key=%22env_1%22&group=true`

3. Note that the following response is returned despite the passed in view definition including a reduce function:
`{"error":"Internal Server Error","reason":"Internal error: query_parse_error - Invalid URL parameter 'group' or  'group_level' for non-reduce view."}`

Note that viewing the view definition in the Couchbase cluster shows that it is missing the reduce, and if added in the web interface on the cluster itself it works with the same CURL request as above. However manually editing this is not something we can do in production, and we are always creating the views through Sync Gateway as all documentation indicates this is critical.

The exact same steps works properly on 1.4.1

**Comment by adamcfraser** [comment] 2018-02-28 22:32
I was able to reproduce this with the 1.5.1 binary against CBS 5.0 (the view definition doesn't include the reduce).  I'm not able to repro w/ SG master, though - this looks like it's already fixed in 2.0.0.

**Comment by tleyden** [comment] 2018-02-28 22:36
@timritzer if you have a support contract, I'd encourage you to file a [support ticket](https://www.couchbase.com/support/working-with-technical-support) which would most likely result in a 1.5.2 fix.  

Regardless, I'll try to make sure that this fix makes it into a 1.5.2 release if that happens for other reasons.

**Comment by tleyden** [comment] 2018-02-28 22:40
> this looks like it's already fixed in 2.0.0.

Just to clarify, that hasn't quite been released yet, should be just around the corner.

**Comment by timritzer** [comment] 2018-02-28 23:03
Thanks @tleyden We have existing support tickets open that were relatively involved and part of their troubleshooting was urging us to upgrade. I have referenced these two issues in that ticket.

Thanks!

**Closed as completed** 2018-08-22 18:33 UTC
Labels: bug
