### ISSUE TITLE
multitenancy - Update DB Config to support a namespace per database

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2125] opened 2016-10-07 16:28 UTC
e.g. config.json

{
    "databases": {
        "multiDB1": {
            "server": "http://shared-server/shared-bucket",
            "namespace" : "com.example.myNamespace1"
        },
        "multiDB2" : {
            "server": "http://shared-server/shared-bucket",
            "namespace" : "com.example.myNamespace2"
        }
    }
}

**Comment by adamcfraser** [comment] 2016-10-11 18:54
Instead of defining tenant name in the db config, might be easier to just set a 'multitenancy' flag in the config, and use the database name as the tenant name.  Probably simplifies debugging, etc.

**Comment by adamcfraser** [comment] 2016-10-14 18:11
Duplicate of #2124.

**Closed as completed** 2016-10-14 18:12 UTC
