### ISSUE TITLE
TestSkippedViewRetrieval failing under go 1.9

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2433] opened 2017-03-29 06:11 UTC
When running w/ go 1.8, getting the following error when running TestSkippedViewRetrieval:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x43797c6]

goroutine 22 [running]:
testing.tRunner.func1(0xc420190000)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x4684340, 0x4c0f020)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
golang.org/x/text/collate.newCollator(0x0, 0x0, 0x0)
	/Users/adam/Development/sg_bootstrap/godeps/src/golang.org/x/text/collate/option.go:32 +0x146
golang.org/x/text/collate.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420065b01)
	/Users/adam/Development/sg_bootstrap/godeps/src/golang.org/x/text/collate/collate.go:50 +0x104
github.com/couchbase/sg-bucket.(*JSONCollator).compareStrings(0xc4200162f8, 0xc4203acac0, 0x3, 0xc420327be7, 0x1, 0x470c7a0)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbase/sg-bucket/collate.go:101 +0xc7
github.com/couchbase/sg-bucket.(*JSONCollator).Collate(0xc4200162f8, 0x464b060, 0xc4203acd70, 0x464b060, 0xc4203acca0, 0x50)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbase/sg-bucket/collate.go:57 +0x217
github.com/couchbase/sg-bucket.(*JSONCollator).Collate(0xc4200162f8, 0x463f4e0, 0xc420399060, 0x463f4e0, 0xc420398ca0, 0xa)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbase/sg-bucket/collate.go:65 +0x325
github.com/couchbase/sg-bucket.(*ViewResult).Less(0xc4200162c0, 0x1, 0x0, 0x473e501)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbase/sg-bucket/views.go:220 +0x7b
sort.insertionSort(0x4aa7c60, 0xc4200162c0, 0x0, 0x6)
	/usr/local/go/src/sort/sort.go:29 +0x71
sort.quickSort(0x4aa7c60, 0xc4200162c0, 0x0, 0x6, 0x6)
	/usr/local/go/src/sort/sort.go:211 +0x1eb
sort.Sort(0x4aa7c60, 0xc4200162c0)
	/usr/local/go/src/sort/sort.go:220 +0x79
github.com/couchbaselabs/walrus.(*lolrus).updateView(0xc4200be510, 0xc42015fce0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbaselabs/walrus/views.go:256 +0x7f2
github.com/couchbaselabs/walrus.(*lolrus).View(0xc4200be510, 0x473fe16, 0xc, 0x473c4cd, 0x8, 0xc420010b10, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbaselabs/walrus/views.go:151 +0x30f
github.com/couchbaselabs/walrus.(*lolrus).ViewCustom(0xc4200be510, 0x473fe16, 0xc, 0x473c4cd, 0x8, 0xc420010b10, 0x462b020, 0xc420016280, 0xc420018301, 0xc420016280)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbaselabs/walrus/views.go:265 +0x84
github.com/couchbase/sync_gateway/base.(*LeakyBucket).ViewCustom(0xc420175b80, 0x473fe16, 0xc, 0x473c4cd, 0x8, 0xc420010b10, 0x462b020, 0xc420016280, 0xa7, 0xac)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbase/sync_gateway/base/leaky_bucket.go:113 +0x8c
github.com/couchbase/sync_gateway/db.(*DatabaseContext).getChangesInChannelFromView(0xc420176b40, 0x47367a1, 0x1, 0x3, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, ...)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbase/sync_gateway/db/changes_view.go:40 +0x7c1
github.com/couchbase/sync_gateway/db.(*changeCache).CleanSkippedSequenceQueue.func1(0xc42017c3c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbase/sync_gateway/db/change_cache.go:213 +0x21a
github.com/couchbase/sync_gateway/db.(*changeCache).CleanSkippedSequenceQueue(0xc42017c3c0, 0xc42000e210)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbase/sync_gateway/db/change_cache.go:232 +0x40
github.com/couchbase/sync_gateway/db.TestSkippedViewRetrieval(0xc420190000)
	/Users/adam/Development/sg_bootstrap/godeps/src/github.com/couchbase/sync_gateway/db/change_cache_test.go:811 +0x644
testing.tRunner(0xc420190000, 0x47660c8)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
```

After reverting my go version to 1.7.5, the test passed successfully.

Since the failing code is in golang.org/x/text, this may be an issue with our (old) pinned commit on golang.org/x/text.

**Comment by adamcfraser** [comment] 2017-03-29 16:14
After moving to the tip of golang/text, this test passes.

Currently our manifest pulls this repo from couchbasedeps.  Moving to the latest on couchbasedeps does NOT fix this issue, so we either need to get couchbasedeps bumped to the latest on golang/text, or switch the manifest.

I've validated that the tests pass when running with the latest from golang/text with both go 1.8 and go 1.7.5

**Comment by adamcfraser** [comment] 2017-03-29 16:15
@ceejatec What's the process to move the commit on a couchbasedeps mirror?

**Comment by adamcfraser** [comment] 2017-03-29 16:54
After additional testing, the minimum commit we need from golang/text appears to be https://github.com/golang/text/commit/09c7ea1fcb3345da09be5a32c9c52303acd1dc2c

**Comment by adamcfraser** [comment] 2017-04-17 17:48
Should be done for 2.0.

**Comment by tleyden** [comment] 2017-09-26 22:00
Closing this as a duplicate of https://github.com/couchbase/sync_gateway/issues/2706

**Closed as completed by tleyden** 2017-09-26 22:00 UTC
Labels: P1: high
