### ISSUE TITLE
Empty reply from server with invalid Json data for POST _bulk_docs

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#738] opened 2015-03-14 13:38 UTC
I'm trying to post invalid json for _bulk_docs like:

```
 curl -v -H 'Content-Type: application/json' -d '{"docs":"[{\"doc1\":\"valu1\"}, {\"doc2\":\"valu2\"}]"}' -X POST http://127.0.0.1:4985/sync_gateway/_bulk_docs
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4985 (#0)
> POST /sync_gateway/_bulk_docs HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:4985
> Accept: */*
> Content-Type: application/json
> Content-Length: 55
> 
* upload completely sent off: 55 out of 55 bytes
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```

logs from SG(commit 5d231):

```
16:32:55.351615 HTTP:  #003: POST /sync_gateway/_bulk_docs  (ADMIN)
2015/03/14 16:32:55 http: panic serving 127.0.0.1:43292: interface conversion: interface is string, not []interface {}
goroutine 51 [running]:
net/http.func·011()
    /usr/local/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x9fdb60, 0xc2080de3c0)
    /usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/couchbase/sync_gateway/rest.(*handler).handleBulkDocs(0xc208024090, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/bulk_api.go:376 +0x1a4
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc208024090, 0xd25bd8, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:159 +0x430
github.com/couchbase/sync_gateway/rest.func·015(0x7faffa9b49f8, 0xc2081ea000, 0xc208266000)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:86 +0x7c
net/http.HandlerFunc.ServeHTTP(0xc2081276a0, 0x7faffa9b49f8, 0xc2081ea000, 0xc208266000)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208019630, 0x7faffa9b49f8, 0xc2081ea000, 0xc208266000)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x288
github.com/couchbase/sync_gateway/rest.func·017(0x7faffa9b49f8, 0xc2081ea000, 0xc208266000)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:226 +0xd4
net/http.HandlerFunc.ServeHTTP(0xc2081d4cc0, 0x7faffa9b49f8, 0xc2081ea000, 0xc208266000)
    /usr/local/go/src/pkg/net/http/server.go:1235 +0x40
net/http.serverHandler.ServeHTTP(0xc2080a9e00, 0x7faffa9b49f8, 0xc2081ea000, 0xc208266000)
    /usr/local/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc2080ac000)
    /usr/local/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
    /usr/local/go/src/pkg/net/http/server.go:1721 +0x313
```

expected behavior could be like:

```
curl -v -H 'Content-Type: application/json' -d '{"docs":"[{"doc1":"valu1"}, {"doc2":"valu2"}]"}' -X POST http://127.0.0.1:4985/sync_gateway/_bulk_docs
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4985 (#0)
> POST /sync_gateway/_bulk_docs HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:4985
> Accept: */*
> Content-Type: application/json
> Content-Length: 47
> 
* upload completely sent off: 47 out of 47 bytes
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
* Server Couchbase Sync Gateway/unofficial is not blacklisted
< Server: Couchbase Sync Gateway/unofficial
< Date: Sat, 14 Mar 2015 13:30:22 GMT
< Content-Length: 43
< 
* Connection #0 to host 127.0.0.1 left intact
{"error":"Bad Request","reason":"Bad JSON"}
```

**Comment by zgramana** [comment] 2015-03-27 23:01
Duplicate of #739

**Closed as completed** 2015-03-27 23:01 UTC
