### ISSUE TITLE
Panic when using latest version of gomemcached / go-couchbase

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1585] opened 2016-02-12 18:56 UTC
From https://github.com/couchbase/sync_gateway/issues/1572

I noticed the following [panic](https://gist.github.com/tleyden/0f2b8ae9606bada96aee) when running the functional tests via `py.test -s -k “test_users_channels"`

```
panic: runtime error: slice bounds out of range

goroutine 42 [running]:
github.com/couchbase/gomemcached.(*MCRequest).Receive(0xc820423280, 0x7fb2c5088550, 0xc820024e08, 0xc820437d40, 0x18, 0x18, 0x0, 0x0, 0x0)
    /workspace/src/github.com/couchbase/gomemcached/mc_req.go:181 +0xbcc
github.com/couchbase/gomemcached/client.(*Client).runFeed(0xc820429ad0, 0xc82043b140, 0xc820437d20)
    /workspace/src/github.com/couchbase/gomemcached/client/tap_feed.go:270 +0x149
created by github.com/couchbase/gomemcached/client.(*Client).StartTapFeed
    /workspace/src/github.com/couchbase/gomemcached/client/tap_feed.go:251 +0x428
```

Note: there were also errors when running the same functional tests against the master branch of Sync Gateway, however I didn't notice any panics (which doesn't mean there wasn't any).  Having trouble interpreting the [functional test output](https://gist.github.com/tleyden/50d96764d1542f43ade0) from that run.

https://github.com/couchbase/sync_gateway/issues/1572#issuecomment-183124990

https://github.com/couchbase/sync_gateway/issues/1572#issuecomment-183128371

**Comment by adamcfraser** [comment] 2016-05-30 19:33
Looked into this - it looks like a regression in gomemcached after the changes made in https://github.com/couchbase/gomemcached/commit/f4caed221d0550525f11a843e22855b6582ef116.

Sent a note to @ysui6888 to try to get more details - it looks to me like an incorrect version of bodyLen is being used to calculate valueLen, and that's causing the slice out of range panic.

**Comment by adamcfraser** [comment] 2016-10-05 18:45
This has been fixed in go-couchbase.

**Closed as completed** 2016-10-05 18:45 UTC
