### ISSUE TITLE
Slow queries for changes_view and unstable replications

### ISSUE THREAD

**Issue by ont** [couchbase/sync_gateway#3358] opened 2018-03-07 18:42 UTC
### Sync Gateway version
```
{"couchdb":"Welcome",
"vendor":{"name":"Couchbase Sync Gateway","version":1.5},
"version":"Couchbase Sync Gateway/1.5.1(4;cb9522c)"}
```

### Operating system
Using official docker container `1.5.1-community     4e8916a9642c`

### Configuration
- Two servers with 112Gb RAM.
- Couchbase has 50Gb RAM for its main bucket on each server (100GB in total) and forms cluster.
- Sync gateway has 30Gb available RAM on each server.
- We have over 45,000,000 (45 million) documents in our main bucket sharded over 2-server couchbase cluster
- Over 7000 active online users balanced over two sync-gatway instances.
- Each user have from 2 to 8 channels.
- 1-3 of this channels may have more than 3000 documents

### Config file
```javascript
{
  "log": ["HTTP+"],
  "compressResponses": false,
  "couchbaseKeepaliveInterval": 10,
  "databases": {
    "babycare": {
      "rev_cache_size": 500,
      "revs_limit": 100,
      "sync": "function sync(doc, oldDoc) {... some complex sync function ...}",
      "username": "...",
      "password": "...",
      "server": "http://some-server:8091",
      "bucket": "some-bucket"
    }
  }
}
```

### Log output
Part of log for two retries to `changes_view` for `1cac3667-1ee9-4e6b-9ac1-ba8297170af7`
https://gist.github.com/ont/7795f1bae03823de27f5ba6ddc125d98

### Expected behavior
After nginx/sync-gateway/couchbase restarting system work as expected:

- stable connections for longpolls
- minimal reconnections from client to nginx balancer
- fast responses from sync gateway

### Actual behavior
After more than 5 hours of downtime for one of our couchbase servers we got strange behavior of whole stack (nginx + sync-gateway + couchbase). 
What happens:
1. after each reboot for one of the nginx or sync-gateway all of our >10000 active connections are dropped
2. each mobile client then try to reconnect to nginx
3. we observe big spike of requests to nginx
4. after some time we can see **very slow** requests to **changes_view** in sync-gateway logs:
    ```
    2018-03-07T13:48:29.947Z changes_view: Query took 8m41.557951084s to return 198 rows, options = db.Body{"stale":false, "startkey":[]interface {}{"1cac3667-1ee9-4e6b-9ac1-ba8297170af7", 0x1}, "endkey":[]interface {}{"1cac3667-1ee9-4e6b-9ac1-ba8297170af7", 0x5513016}}
    ```
    Query took `8m41.557951084s`!!! It is very slow.
5. seems that it doesn't depend on amount of returned rows. We can see slow queries even for 1-2 rows returned.
6. when query time becomes larger than nginx's timeout settings then nginx drops active connections and client retry its request again. We have this settings:
```
keepalive_requests 1000;
keepalive_timeout  360s;
proxy_read_timeout 360s;
proxy_send_timeout 360s;
```
7. query time to changes_view doesn't decrease over time

### Steps to reproduce
1. stop nginx, SG or couchbase for long period
2. make some new documents on clients
3. bring nginx+SG+couchbase online again  
4. observe slow  changes_view queries under heavy loading during client reconnections.

### Some more info
Some metrics from grafana:
![graphs](https://user-images.githubusercontent.com/350218/37109909-fd95797e-226d-11e8-8a7e-e8c024cc1be8.png)
Here you can observe orange periodical spikes (requests per seconds). During this periods nginx writes lot timeout-to-upstream messages to error log.  After a while this spikes are gone but nginx timeouts and slow queries are not.

In couchbase admin panel we can observe never completed `babycare/_design/sync_gateway` view.
![couch](https://user-images.githubusercontent.com/350218/37110233-ebc9eddc-226e-11e8-8d97-9277d9ae664e.png)
It always stuck around 1-5% of progress.

During problems on SG we are able to successfully execute one-shot replications requests and longpolls which are returns **small amount** of rows. 
```
curl 'http://some-server/database/_changes?feed=normal&heartbeat=30000&style=all_docs&filter=sync_gateway%2Fbychannel&channels=some-channel-uuid' --cookie 'SyncGatewaySession=....'
```
Unfortunately queries which are returns thousand of rows stuck forever.

### Questions
1. Does it our problem that we store many documents in single channel?
2. Does horizontal or vertical scaling resolves our problem? (more couchbase servers and sync-gateway instances or more RAM/cache for couchbase/sync-gateway)
3. What is proper way for recovering big amount of data from sync-gateway+couchbase cluster? Currently we recover all user's documents via single longpoll query.

**Comment by adamcfraser** [comment] 2018-03-07 23:01
@ont As you've identified, the root of the problem appears to be slow Couchbase Server view response times.  I think there are a few possible scenarios:

1. Reindexing downtime caused by Couchbase Server failover.
 When a Couchbase Server node fails over, it has to completely rebuild its view indexes.  Until that's complete, Sync Gateway queries will time out.  

We have plans to move Sync Gateway from views to GSI in an upcoming release (2.1.0), which will avoid this problem - GSI allows you to define index replicas, so that the entire index doesn't need to be rebuilt on node failure.

2. Channel cache flush due to Sync Gateway restart
Sync Gateway will attempt to use its channel cache to serve _changes requests - it only issues a view query if the client requests changes not resident in the cache.  After a restart the caches are empty, and are initially populated by new mutations arriving over the server's mutation feed.  Client requests for older data (particularly since=0 requests) will trigger a changes view query.  This would result in the spike in view requests after a SG restart.


There are a few things you could consider to mitigate the issues you're seeing.  Some questions/comments:

1. There seem to be a relatively high number of feed=normal, since=0 _changes queries in the log excerpt provided - 9837 in total.  Do you know what's generating these requests?  Couchbase Lite only uses those parameters on initial replication of an empty database - do you expect that many new clients to be doing initial replication in the 10 minutes window shown in these logs?  These seem most likely to be triggering view queries (versus the requests with a since value provided).

2. Are your channels shared between users?  e.g. for 7000 users w/ 8 channels having up to 3000 docs - does that represent 56K distinct channels?  If the channels are shared, you can cut down on view queries by increasing your channel cache size.  If there's room in the cache, the view results will be cached for subsequent requests against that channel.  If there's no room in the cache, though, subsequent requests will trigger another channel view query.

3. Even if your channels aren't significantly shared between users, you could consider increasing the size of the channel cache to maximize the number of _changes queries that are served by the channel cache.  This will increase SG memory usage, but you've got a relatively large amount of memory available to SG here (30GB) - storing 3K docs for 56K channels may be feasible (note that the channel cache doesn't store document bodies - just docid/revid/sequence/flags for each entry).

4. Normally Couchbase Server and Sync Gateway aren't codeployed on the same server node.   Avoiding SG-based CPU pressure while the views are reindexing may improve indexing time.

5. Indexing shouldn't be getting 'stuck' at 1-5%, even under the load described.  That may be a server issue.  This might be helped by not colocating the nodes (as mentioned above), but that might be an issue that could be followed up on the server side.  What version of Couchbase Server are you running?

**Comment by ont** [comment] 2018-03-08 08:47
@adamcfraser thank you for response!

> What version of Couchbase Server are you running?

Official docker image `community-5.0.1   (7bf07062afde)`
```
# couchbase-server -v
Couchbase Server 5.0.1-5003 (CE)
```


> Reindexing downtime caused by Couchbase Server failover.

Before enabling nginx + SG we wait for couchbase to completely warmup and finish any activity for views. And this doesn't helps.


> Channel cache flush due to Sync Gateway restart

Yes. That sounds convincing. But may be this is not the root of the problem because I can able to fix slow queries with this actions:

1. We created two additional servers with 32Gb RAM and 8 vCPUs. And scaled old two servers to 64Gb RAM and 8 vCPUs.  Now I have 32 vCPUs in total and same memory limits as before for SG and couchbase. The only difference is for total amount of vCPUs  (8 vCPUs vs 32 vCPUs at current moment).
2. We moved two sync gateway instances to new servers.
2. After waiting for couchbase warmup + view building we bring fresh SG and nginx online.
3. The problem seems to be still here with 3-4 min SG view queries which appeared in logs immediately after nginx startup.
4. After that I disabled nginx and waited until all slow queries are done. It took about 10-15 minutes for SG to complete them.  It seems that this queries waits for each other as I can see messages about "Query took 10.57 **seconds**" after 5-6 **minutes** after nginx was disabled.
5.  After all queries to changes_view was done we enabled nginx again. And now all queries took around 3-4 seconds as expected.

We try to apply the same procedure when we have lower amount of vCPUs and it doesn't works.

> There seem to be a relatively high number of feed=normal, since=0 _changes queries in the log excerpt provided - 9837 in total. Do you know what's generating these requests? Couchbase Lite only uses those parameters on initial replication of an empty database - do you expect that many new clients to be doing initial replication in the 10 minutes window shown in these logs? These seem most likely to be triggering view queries (versus the requests with a since value provided).

**Very** interesting :) I totally agree with you that this queries are very heavy. Currently I have no idea what can cause this queries. Yes, this queries are produced by our **old users** which already initialized their DB. Do you think this is not normal?  What actions and options for replicators on mobile client can cause this type of requests?

> Are your channels shared between users? e.g. for 7000 users w/ 8 channels having up to 3000 docs - does that represent 56K distinct channels?

We have this types of channels:
- `{user-uuid}` -- stores user's profile document (1-2 document in channel)
- `sync-{user-uuid}` -- stores user's profile document + user owned children. This channel is for fast bootstrap data retrieve via one-shot replication during recovering from cloud. (1-10 documents in this channel)
- `{child-uuid}` -- stores child's profile and all its events (1-3000 documents)

`{user-uuid}` and `{child-uuid}` may be shared between two or more users. I estimate the amount of channels for online users as `7000 * 4 = 28000` (typical user have 3 channels when there is no shared child and 4-5 channels when user owns child and got one more shared child).

> Even if your channels aren't significantly shared between users, you could consider increasing the size of the channel cache to maximize the number of _changes queries that are served by the channel cache.

Does you mean `databases.foo_db.cache.channel_cache_max_length` and 
`databases.foo_db.cache.channel_cache_min_length` options?

> Avoiding SG-based CPU pressure while the views are reindexing may improve indexing time.

Seems to be true. Possibly CPU was bottleneck for long queries. During our problem I also can see large IO write traffic to disk on our couchbase servers and relatively small traffic for disk IO reads. HDD disks was busy near 99% on both servers. Currently disks are busy 50-60% on both servers.

> Indexing shouldn't be getting 'stuck' at 1-5%, even under the load described.

I can confirm that `babycare/_design/sync_gateway` continues to get "stuck" around 1-5% despite the fact that view queries are now fast. May reindexing cycle be so fast that admin panel shows it as "beginning at 1-5%" every time?

**Comment by ont** [comment] 2018-03-23 08:06
Some update to this issue:

1. we found some problem on mobile client. Mobile clients sometimes accidentally started two parallel pull replication which cause race-condition writes to `/{db}/_local/{hash}` and at a certain point in time mobile SDK saw mismatch between local/remote `since` and decided to execute "full query" without `since` arg.
2. we released new version of application with fix. But it doesn't help much.

Problem is **still here** (but now with increased amount of vCPUs system can stabilize on its own) and looks similar as before. We can however see less active connections and slightly more percentage of single-connection clients. Also amount of "heavy" `changes_view` queries (thousand of returned rows) during stable state decreased.

There is problem before patch (nginx reboot at 01:18):
![before](https://user-images.githubusercontent.com/350218/37817384-318371d6-2ea9-11e8-80a0-fa850218ff9b.png)


Some points worth paying attention to:

- after nginx reboot we see increased amount of log entries for `changes_view`
- query time for `changes_view` greatly increse (2min at maximum)
- at every moment of time there are two groups of `change_view` requests: relatively fast and relatively slow (you can see it in `changes_view: query time distribution graph` as two "curves")
- halve or even more of `changes_view` queries returns 1-2 rows
- there are also big amount of "heavy" `changes_view` queries during unstable phase (probably for old clients with big amount of data)
- distribution of returned rows doesn't change. It is only become more saturate (because of requests amount)


There is problem after fix release (about 90% of users updated; couchbase server reboot at 02:10):
![after](https://user-images.githubusercontent.com/350218/37817557-c359c8b2-2ea9-11e8-9642-2c1764d9e01c.png)

Two different reboots looks same. The `changes_view` requests/per seconds graph didn't change visually. We can see same 10-15 requests per second.

Looks like it is problem with **forced closure** for `longpoll` and/or forced closure for `/{db}/_local/{hash}` queries. Clients don't handle timeout/broken connections properly and do "full query".

P.S. it is very difficult and error prone to parse `changes_view` duration for metrics...
 (`<minutes>m<seconds>s<milliseconds>ms` human-readable form).

**Comment by adamcfraser** [comment] 2018-03-23 16:11
What's unexpected to me is that you're seeing a spike in changes view queries (resulting in the slow `changes_view` logging) after just an nginx reboot.  A restart of Sync Gateway (or an automatic restart triggered by Couchbase Server restart) would result in the channel cache needing to be rebuilt, which would require view queries.  This shouldn't be the case for just an nginx reboot, though.

Your suggestion that clients are falling back to  `since=0` `_changes` requests after getting an error back from a terminated `longpoll` or `_local` request might explain it (for channels that aren't 100% resident in the cache).  

That seems like something that might be better handled by the client.  What client build/version are you using?

**Comment by ont** [comment] 2018-03-23 17:21
@adamcfraser it seems that I incorrectly remembered what we have rebooted, sorry for disinformation :)

I can confirm that nginx rebooting doesn't affect changes view queries. But SG rebooting does:
![nginx-reboot-sg-reboot](https://user-images.githubusercontent.com/350218/37843180-c8a9f358-2ef6-11e8-8ea7-5b6340d3b475.png)
First I rebooted nginx, then I rebooted two SG instances.

Is it normal? Do I correctly understand that SG stores `/{db}/_local/{hash}` values in local memory? So after SG rebooting any client will get mismatch between local and remote `since` values and do "full query".

If so it is very dangerous because we already got situation where mobile clients are able to DDoS couchbase + SG cluster when `changes_view` query doesn't automatically stabilized on its own. It can appears again and it is slightly difficult to debug and predict (how many vCPUs we need and similar).

And how SG behave if we randomly distribute requests between multiple SG? Does every fresh not-initialized instance of SG cause mobile client to do "full query" and store `since` value into SG's `/{db}/_local/{hash}` again and again?

**Comment by adamcfraser** [comment] 2018-03-23 17:30
No, it's not the case that the `_local` docs are kept in memory - they are persisted to the bucket.

If there's a SG restart, we'd expect a spike in view queries associated with repopulating the in-memory channel caches after restart. 

These wouldn't necessarily be associated with since=0 requests - any requests with a since value earlier than the value of `_sync:seq` at SG startup time would trigger a view query.

Are you able to confirm from your SG logs that you're still seeing clients issue `since=0` changes requests after Sync Gateway restart, even after making your client fix?

**Comment by ont** [comment] 2018-03-23 18:06
Yes, I can confirm that mobile clients issue `_changes?feed=normal&heartbeat=30000&style=all_docs` after SG restarting and even after long period of time after it. Seems that SG's restarts doesn't correlates with this queries and mobile clients do this requests randomly at any time. 

Stable phase (more than hour after SG restart):
![changes_queries](https://user-images.githubusercontent.com/350218/37846104-2aba1d68-2eff-11e8-8769-6e7b87a4bb12.png)

I can see even multiple requests from same client during short period of time.
![changes_queries_single](https://user-images.githubusercontent.com/350218/37846114-329745b0-2eff-11e8-9df9-ad54daaa0b1f.png)

**Comment by adamcfraser** [comment] 2018-03-23 18:23
If these client requests are unexpected (these aren't new clients, or existing clients starting new replications), it's probably worth digging into why the client is issuing those requests.

What client version/build are you using?

**Comment by ont** [comment] 2018-03-23 18:48
Yes, very probably, this requests are unexpected. We will check soon for "starting new replications" but this clients exactly are not new clients.

Version of SDK in `app/build.gradle`:
```
dependencies {
    ...
    compile 'com.couchbase.lite:couchbase-lite-android:1.4.1'
}
```

**Comment by ont** [comment] 2018-10-31 16:51
@adamcfraser   currently we can't observe any spike anymore for **amount** of view queries. Nevertheless we still can see pike in query time for such queries:
![pike at graph](https://i.imgur.com/Wl8wDPL.png)

Here I rebooted two SG and you can see pike in query_time parameter extracted from SG logs. It seems that the amount of view queries slightly increased after reboot but is not too high. Also I can see some anomalies in number of rows returned from changes_view query (after reboot there are slightly more heavy queries).

**Comment by adamcfraser** [comment] 2018-10-31 17:04
I suspect the spike in query time after restart would also be related to the cache initialization I mentioned earlier.  This would depend on your cache size and number of docs per channel, but it definitely looks like expected behaviour for the first post-startup request for documents not resident in the cache. 

Closing this ticket for the time being, as I don't see an actionable issue on our side.  If you find something that looks like unexpected SG behaviour, please feel free to reopen.

**Closed as completed by adamcfraser** 2018-10-31 17:04 UTC
Labels: P1: high
