### ISSUE TITLE
Store attachments in a different bucket

### ISSUE THREAD

**Issue by djpongh** [couchbase/sync_gateway#2625] opened 2017-06-08 20:15 UTC
We have learned that, SERVER best practice is to always separate Binary and JSON data.

This would be a short-term solution for pluggable storage (issue #1943).

**Comment by adamcfraser** [comment] 2017-06-09 04:35
Closing as duplicate of https://github.com/couchbase/sync_gateway/issues/2629, which has a bit more information.

**Closed as completed by adamcfraser** 2017-06-09 04:35 UTC
