### ISSUE TITLE
Don't reuse allocated sequence numbers

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#2700] opened 2017-06-29 18:30 UTC
https://github.com/couchbase/sync_gateway/blob/master/rest/api_test.go#L832

Here we do the following:

* Send 3 updates to SG1's bulk_docs, one gets rejected, but the sequence number is still allocated (and skipped)
* Send 3 updates to SG2's bulk_docs, all is well, 3 more sequence numbers allocated
* Send 3 more updates to SG1's bulk_docs, the first uses the previously unused sequence number and 2 more are allocated

The problem is, the mutation that gets seq 3 happened *after* the one that got (for example) 8. If I checkpoint between those two, I'll never see that sequence number/revision.

I might be missing something here with regards to `::` separated sequence numbers - but I can't easily step through that scenario in my head ;). Raising this ticket so the conversation about this doesn't get forgotten, but happy to be proved wrong.

**Comment by ajres** [comment] 2017-06-30 18:25
This is current behavior for new documents, and should be caught by late arriving sequences logic, would be good to have test to prove that.

We recently fixed an issue where older sequences were being used for new doc revisions. But this does not cover the new doc case.

**Comment by adamcfraser** [comment] 2017-07-20 21:07
Prior to 1.5, this is only an issue in the scenario where a sequence (#3 in this example) goes unused for more than an hour before being assigned to a new document.  

In general, until (any) SG node sees sequence three, it's not going to move your since value (checkpoint) past sequence 3.  It may treat that sequence as skipped (and so send you sequence 8, etc), but that will result in a composite sequence (like 2::8), where '2' represents the latest contiguous sequence Sync Gateway has seen.  It will wait up to an hour before giving up on sequence 3 and abandoning skipped sequences.

However, we've already made the change in 1.5 to release sequences on a failed update, so that we don't get into the skipped/abandon scenario in the first place.
@ajres doesn't the change here already cover this scenario?  If not, can you provide an update on this ticket about the scenario you don't think it covers?
https://github.com/couchbase/sync_gateway/blob/master/db/crud.go#L1008

**Comment by ajres** [comment] 2017-08-01 13:02
@adamcfraser I agree we should never have an unused old sequence available on initial document create rev 1. So this case should also be covered.

We should create a unit test to demonstrate this is the case and catch potential regressions.

**Comment by ajres** [comment] 2017-08-01 16:40
We already have a unit test 'TestBulkDocsUnusedSequencesMultipleSG' covering the new doc scenario in api_test.go

In this case the unused sequence from the first _bulk_docs is used in a subsequent _bulk_docs call for the first rev of a new doc.

**Comment by adamcfraser** [comment] 2017-12-15 06:26
Closing this as covered, based on discussion above.

**Closed as completed by adamcfraser** 2017-12-15 06:26 UTC
Labels: P1: high
