### ISSUE TITLE
SyncGateway restart after node automatic failover is taking more time

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2396] opened 2017-03-17 12:35 UTC
### Sync Gateway version
1.4.0  

### Operating system
RedHat 7.2

From https://forums.couchbase.com/t/syncgateway-restart-taking-more-time-after-node-automatic-failover/12115

Cluster of 3 nodes is having 60 GB with each document is having size of 10kb. syncgateway restarted after node is fail-over.

### Expected behavior
syncgateway should restart immediately

**Comment by adamcfraser** [comment] 2017-03-17 21:26
Is this a new issue you're seeing with 1.4, or something that was also occurring with earlier versions of Sync Gateway?

Is Couchbase Server appearing ready/green in the Couchbase Server Admin Console when Sync Gateway is started?

**Comment by ArihantRk** [comment] 2017-03-20 04:05
@adamcfraser Issue we are seeing in earlier versions also.  Couchbase server is appearing as green status for cluster of 2 nodes. 
But we could see index is building in couchbase .

**Comment by adamcfraser** [comment] 2017-03-21 04:51
Gist from forum post (with startup logs):
https://gist.github.com/ArihantRk/190481e8d29f0590212bc926012f1a1c

**Comment by adamcfraser** [comment] 2017-03-21 05:04
@ArihantRk Can you reproduce this issue with either `"*"` or `"Debug"` logging enabled?  This may provide some additional information about what Sync Gateway is waiting for.

**Comment by ArihantRk** [comment] 2017-03-23 05:56
@adamcfraser, Issue is reproduced with "*"  enabled. please have a look at gist below
https://gist.github.com/ArihantRk/d6fdb189a69dd55502edd6262c997770

**Comment by adamcfraser** [comment] 2017-03-23 06:03
That's helpful - it looks like the initial principals view query (triggered by the config validation that happens when there are no users in the system) is taking 5m to return results from Couchbase Server.  

This slow query may be the result of reindexing on Couchbase Server after the failover (and that Couchbase Server is actually taking that long to produce the response to the view query).

**Comment by ArihantRk** [comment] 2017-03-23 06:42
Thanks @adamcfraser , This issue seeing every time which is blocking for us.  For applications it is completely outage as syncgateway not starting whenever one couchbase node failover. Any fix for this.

**Comment by kirangandhi** [comment] 2017-03-28 07:30
@adamcfraser, Any update on this issue? Any work around available to resolve the issue will be very helpful. Please advise.

**Comment by adamcfraser** [comment] 2017-04-03 23:44
@kirangandhi You could avoid this particular startup view query by defining a disabled user in the config.  However, if the slow view response is a Couchbase Server issue, you're just going to hit it on the next view query (e.g. channel backfill, user access grant, etc).

**Comment by adamcfraser** [comment] 2018-04-16 17:46
This is addressed in Sync Gateway 2.1.  When using GSI, you have the ability to define multiple index replicas to avoid reindexing downtime after index node failover.

**Closed as completed by adamcfraser** 2018-04-16 17:46 UTC
Labels: performance, P1: high, ffc
