### ISSUE TITLE
[Perf, GSI] Channel cache enforces limit of one concurrent query per channel

### ISSUE THREAD

**Issue by agyryk** [couchbase/sync_gateway#3532] opened 2018-05-03 18:42 UTC
**Setup:**
Sync Gateway 2.1.0-38, GSI, XATTRs
1M docs, 100K unique channels, 100K users.
Users are assigned to [*] channel.
SuncGateway cache is disabled

**Test:**
_getChanges requesting 200 recent docs (since=<last seq>-200)

**Behavior:**
When requesting changes for * channel the N1QL query to "allDocs" index  is being triggered. The query latency is 880ms (which is  high!), so with single client requesting the changes I can get about 1.1 request/sec maximum thoughput. But increasing the amount of clients doesn't increase throughput. Max throughput is still 1.1 req/sec.
Please find CPU profile attached. I ran three tests: 1 client, 5 clients and 10 clients.
Once concurrency is added the requests are hanging on "cccpLooper()" call. Which is really weird as cccpLooper is simple request to ns_server for cluster stats/maps afaik.

[starchannel_changes_CPUprofiles.zip](https://github.com/couchbase/sync_gateway/files/1972173/starchannel_changes_CPUprofiles.zip)

![screen shot 2018-05-03 at 11 26 04 am](https://user-images.githubusercontent.com/20347420/39596068-21169ade-4ec6-11e8-8afb-56829eb9a7cf.png)

**Comment by adamcfraser** [comment] 2018-05-03 23:02
@agyryk Is this the only index/query that's showing this behaviour, or are you seeing this for other queries as well?

**Comment by raghusarangapani** [comment] 2018-05-04 17:35
This might be related to https://github.com/couchbase/sync_gateway/issues/3522
I am observing that the changes request hangs and then fails, when the test is continuously issuing changes request
```
~ » http post 192.168.33.22:4985/db/_changes feed=longpoll style=all_docs since=202
HTTP/1.1 200 OK
Cache-Control: private, max-age=0, no-cache, no-store
Content-Type: application/json
Date: Fri, 04 May 2018 17:32:56 GMT
Server: Couchbase Sync Gateway/2.1.0
Transfer-Encoding: chunked


http: error: ConnectionError: HTTPConnectionPool(host='192.168.33.22', port=4985): Read timed out.
```

**Comment by agyryk** [comment] 2018-05-04 17:46
@adamcfraser I can't tell for all queries at this moment but this issue doesn't reproduce with channel query.
Attaching CPU  profile for similar changes request but hitting Channels index and not allDocs
[gsi_20ch_per_doc.svg.zip](https://github.com/couchbase/sync_gateway/files/1975386/gsi_20ch_per_doc.svg.zip)

**Comment by adamcfraser** [comment] 2018-05-04 18:13
@agyryk When you don't reproduce this with the channel query, is that for queries against multiple channels, or a single channel?

**Comment by adamcfraser** [comment] 2018-05-04 18:34
I think this is a simple deadlock based on Sync Gateway's channel cache handling - it's built to avoid issuing redundant view queries when multiple callers are attempting to query the same channel (based on the assumption that the initial query results will be prepended to the cache, and subsequent callers should first check whether the cache can now be used to serve their requests).

There's currently a bug in the allDocs index/query that's exacerbating this problem, but even with that bug fixed this is a known bottleneck when multiple callers are querying changes beyond the channel cache capacity.  This is primarily to ensure Sync Gateway doesn't overload Couchbase Server with redundant queries when multiple users initially connect.

In a real-world scenario, this issue is commonly addressed by tuning the cache size appropriately, but now that we've got generally higher throughput potential with GSI/N1QL, we should consider whether the limit on the number of concurrent queries for a channel should be greater than 1.

**Comment by agyryk** [comment] 2018-05-16 21:42
@adamcfraser The * channel query looks good on build 92. As well as rest of the queries:
http://showfast.sc.couchbase.com/#/timeline/Linux/syncgateway/query/all
So I don't have any concerns on moving this particular issue to 3.0

**Comment by adamcfraser** [comment] 2018-06-26 17:20
Closing this as working as intended - we're intentionally avoiding duplicate queries for a given channel.

**Closed as completed by adamcfraser** 2018-06-26 17:20 UTC
Labels: P1: high, P2: medium
