### ISSUE TITLE
SSL fails on startup when using gocb bucket

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2496] opened 2017-04-25 00:39 UTC
### Sync Gateway version
 1.4.2-337 and Couchbase Server 5.0.0-2703

### Operating system
CentOS 7

### Config file
```javascript
{
        "adminInterface": "0.0.0.0:4985",
        "compressResponses": false,
        "databases": {
            "db": {
                "bucket": "data-bucket",
                "password": "password",
                "server": "https://cbl.0:18091"
            }
        },
        "interface": ":4984",
        "log": [
            "*"
        ],
        "maxCouchbaseConnections": 16,
        "maxFileDescriptors": 90000,
        "maxIncomingConnections": 0,
        "slowServerCallWarningThreshold": 500
}
```

### Log output
https://gist.github.com/sethrosetter/c422631641dd5906b3d7d3cc4519c8fc

### Expected behavior
Sync Gateway should launch. 

### Actual behavior
The bucket exists but Sync Gateway will not launch

### Steps to reproduce
1.  Start SG 1.4.2-337 targeting Couchbase Server 5.0.0-2703 with the provided config

**Comment by sethrosetter** [comment] 2017-04-25 00:42
This works with `http:cbl.0:8091` as the server

**Comment by adamcfraser** [comment] 2017-04-26 00:02
Need to review what the proper approach is to specify the server SSL endpoint when using gocb.

**Comment by tleyden** [comment] 2017-08-03 16:39
I did some recent testing on this as reported in https://github.com/couchbase/sync_gateway/issues/1552#issuecomment-319838291  

This syntax is working:

```
"server": "couchbases://cbl.0"
```

Whereas this syntax is not working:

```
"server": "https://cbl.0:18091"
```

**Comment by tleyden** [comment] 2017-08-03 16:39
@djpongh is this a duplicate of https://github.com/couchbase/sync_gateway/issues/1552?

**Closed as completed** 2017-08-07 17:11 UTC
Labels: bug, functional-test-failure

**Comment by adamcfraser** [comment] 2017-09-05 18:35
Fixed with https://github.com/couchbase/sync_gateway/pull/2772 - the support for multiple URLs also includes support for the couchbases:// protocol, used for SSL communication between SG and CBS.
