### ISSUE TITLE
Post-convergence expiry can tombstone unexpected revision

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#2942] opened 2017-09-29 14:01 UTC
Post convergence (with xattrs enabled), expiry is a delete, not a purge. However because we use a CB TTL, this will affect the current winner regardless of which branch actually had the expiry set (as SG essentially sees it as an SDK delete).

* Create a document with a few previous revisions:

```
$ curl -X POST -d '{"new_edits":false,"docs":[{"_id":"test","_rev":"9-abc","_revisions":{"start":9,"ids":["abc","abc","abc","abc","abc","abc","abc","abc","abc"]},"foo":"foo"}]}' localhost:4984/db/_bulk_docs -H "Content-type: application/json"
[{"id":"test","rev":"9-abc"}]
```

* Create a conflicting (losing) revision:

```
$ curl -X POST -d '{"new_edits":false,"docs":[{"_id":"test","_rev":"1-def","_revisions":{"start":1,"ids":["def"]},"foo":"bar"}]}' localhost:4984/db/_bulk_docs -H "Content-type: application/json"
[{"id":"test","rev":"1-def"}]
```

![image](https://user-images.githubusercontent.com/6731951/31019204-db64653c-a526-11e7-9950-94e8a482df57.png)

* Update the conflicting revision, adding an expiry:

```
$ curl -X PUT :4984/db/test -d '{"_rev":"1-def", "_exp":60}' -H "Content-type: application/json"
{"id":"test","ok":true,"rev":"2-0db374803cfee46a3a1929088d57a718"}
```

![image](https://user-images.githubusercontent.com/6731951/31019061-5fdf2b68-a526-11e7-857d-73ba96d8e467.png)

* Check the document:

```
$ curl :4984/db/test
{"_id":"test","_rev":"9-abc","foo":"foo"}
```

* Tea Break

```
☕️
```

* Check document again:

```
$ curl :4984/db/test
{"_id":"test","_rev":"2-0db374803cfee46a3a1929088d57a718"}
```

Here we see that the previous current winner was expired, despite the expiry being set on `2-0db374803cfee46a3a1929088d57a718`.

![image](https://user-images.githubusercontent.com/6731951/31019195-d4d6afe0-a526-11e7-9c86-56fa907094c4.png)

**Comment by adamcfraser** [comment] 2017-09-29 16:25
Expiry isn't intended to be a revision-specific property, so I think the real question here is whether expiry (and more generally SDK delete) should tombstone all open revisions, instead of just tombstoning the active revision.

**Comment by adamcfraser** [comment] 2017-09-29 16:30
I think there are compelling arguments for both approaches:

Tombstone all:
 - Avoids the document popping back into existence after an SDK delete

Tombstone active:
 - At the time of delete, the SDK user doesn't have any visibility into the non-winning revision bodies, and so shouldn't be able to tombstone data they don't know anything about.
- This would include SDK users who are deleting documents based on some criteria that the non-winning revisions may not meet.

**Comment by adamcfraser** [comment] 2017-09-29 16:35
If we leave the behaviour as 'tombstone active', we could consider ignoring the expiry property when non-winning revisions are added to the rev tree.

**Comment by adamcfraser** [comment] 2020-03-25 18:33
Closing based on age, and based on the above discussion about whether this is actually the intended behaviour.  Can be reopened in JIRA if there's updated use case information.

**Closed as completed by adamcfraser** 2020-03-25 18:33 UTC
Labels: icebox, P1: high
