### ISSUE TITLE
SG Admin console can not loading documents

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#1239] opened 2015-10-24 04:35 UTC
I am using Couchbase Sync Gateway/master(d63f1a5+CHANGES)
and from SG Admin console, I found some errors from JS console:
    1. update rejected by sync function
when loading documents, it looks like _admin console will modify docs(I don't know why)'s type property,but in my sync function,I will reject this operation.
    2. Uncaught TypeError: Cannot read property 'changed' of undefined
onChangeWDoc @ demodata:580
onChange @ demodata:580
(anonymous function) @ demodata:580
(anonymous function) @ demodata:579
on_end @ demodata:579
on_state_change @ demodata:579

this error should be the same as:
https://github.com/couchbase/sync_gateway/issues/989

```
3. (when loading documents by ID)Uncaught TypeError: Cannot read property 'access' of undefined
```

transformPreview @ GST:USR:atom:580(anonymous function) @ GST:USR:atom:580(anonymous function) @ GST:USR:atom:579on_end @ GST:USR:atom:579on_state_change @ GST:USR:atom:579
localhost/:1 GET https://localhost:5985/favicon.ico/ 400 (Bad Request)
    4. /_admin/<sg_db>/sync shows Loading... with no data
    5. /_admin/<sg_db>/channels shows 0 channels
    6. /_admin/<sg_db>/users shows the right docs.but when access some users's channels, the channels Access is empty.

**Comment by zgramana** [comment] 2015-10-30 18:41
This is a duplicate of #989. Make sure your Sync Function javascript itself does not have any syntax or runtime.

**Closed as completed** 2015-10-30 18:42 UTC
