### ISSUE TITLE
Support multiple couchbase server URLs in config

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#2058] opened 2016-08-27 01:19 UTC
Problem:

If Sync Gateway is configured with a single Couchbase Server URL from a Couchbase Cluster, and that Couchbase Server node is rotated out of the cluster, Sync Gateway can't connect

**Comment by adamcfraser** [comment] 2016-08-27 01:23
Duplicate of #1019?

**Closed as completed** 2016-08-27 01:25 UTC

**Comment by tleyden** [comment] 2016-08-27 01:39
Yup good call!  Closed as dupe
