### ISSUE TITLE
IE when request /db/_changes?since=%22start_seq%3A%3Aend_seq%22

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#1175] opened 2015-09-30 11:49 UTC
test https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/sg_changes_feed_last_seq.js#L147

request with format since=%22153%3A%3A163%22 worked in previous releases, but don't in the latest SG version

```
     { seq: 152, id: 'newchange_range_8', changes: [Object] },
     { seq: 153, id: 'newchange_range_9', changes: [Object] } ],
  last_seq: '153' }
=====================1 "153::163"
2015-09-30T14:43:55.510+03:00 HTTP:  #174: GET /db/_changes?since=%22153%3A%3A163%22
2015-09-30T14:43:55.510+03:00 HTTP:  #174: GET /db/_changes?since=%22153%3A%3A163%22

2015-09-30T14:43:55.512+03:00 WARNING: Couldn't interpret error type *strconv.NumError, value strconv.ParseUint: parsing "\"153": invalid syntax -- base.ErrorAsHTTPStatus() at error.go:63
2015-09-30T14:43:55.512+03:00 WARNING: Couldn't interpret error type *strconv.NumError, value strconv.ParseUint: parsing "\"153": invalid syntax -- base.ErrorAsHTTPStatus() at error.go:63

2015-09-30T14:43:55.512+03:00 HTTP: #174:     --> 500 Internal error: strconv.ParseUint: parsing "\"153": invalid syntax  (2.3 ms)
2015-09-30T14:43:55.512+03:00 HTTP: #174:     --> 500 Internal error: strconv.ParseUint: parsing "\"153": invalid syntax  (2.3 ms)
```

it works without quotes

```
2015-09-30T14:43:02.513+03:00 HTTP:  #184: GET /db/_changes?since=163%3A%3A173
2015-09-30T14:43:02.513+03:00 HTTP:  #184: GET /db/_changes?since=163%3A%3A173
```

**Comment by zgramana** [comment] 2015-12-11 19:23
Refs #1168

**Comment by ajres** [comment] 2015-12-14 15:01
Tested this against SG master, quoted composite since value was parsed correctly, is it possible this is specific to the distributed_index branch as per #1168?

**Comment by ajres** [comment] 2015-12-14 18:08
Closing this ticket as this is not reproducible on master and the ticket does not specify a particular branch.

Any open issues will be tracked via #1168

**Closed as completed** 2015-12-14 18:08 UTC
