### ISSUE TITLE
Not storing OpaqueSet values causes Sync Gateway panic during CBGT reshard

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1371] opened 2015-12-18 01:05 UTC
Factored out of https://github.com/couchbase/sync_gateway/issues/1259
- CBGT handover to a new SG node
- New SG node trying to pick up where the old one left off

**Current Behavior**

When starting the DCP feed on the new node, all we are passing is the sequence, which is stored in the Stable Clock.

**Required Behavior**

In addition to the sequence, we must also pass the value passed to us via `OpaqueSet()`, _at the point in time that corresponds to the Stable Clock sequence we are passing_.

[Failing functional test](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/188/)

**Comment by tleyden** [comment] 2015-12-18 01:23
- [x] Check how many times OpaqueSet gets called over the course of the test, we can then compare to #docs, to see if it's roughly 1 doc per snapshot

**Comment by steveyen** [comment] 2015-12-18 01:39
I see this thread was moved here from issue #1259, and there was a question for me on the older thread...

> @steveyen it actually works for us fine 9 out of 10 times, any theories on that?

Gut reaction would be "probably a race".  Also, I'd probably need to understand your test better.

In general, though, to help diagnose, need to grab some more info...

cbgt uses cbdatasource underneath the hood, and cbdatasource has some (obscene?) number of metrics/counters, especially when it hits error conditions...

   https://godoc.org/github.com/couchbase/go-couchbase/cbdatasource#BucketDataSourceStats

If you got the cbgt REST API all hooked up, you can just do a "curl http://HOST:PORT/api/diag"; although, I recall you may or may have not wanted to register your cbgt REST handlers into the some sync-gateway specific URL prefix due to your namespacing requirements.

In any case, that /api/diag REST endpoint grabs as much stuff as we could think of for cbgt, in one shot, including those cbdatasource metics/counters.  You can see what it grabs here...

```
https://github.com/couchbase/cbgt/blob/master/rest/rest_diag.go#L53
```

**Comment by tleyden** [comment] 2015-12-18 01:52
We do have the cbgt REST api hooked up, for example to get the cfg: `HOST:4985/_cbgt/api/cfg`

But unfortunately, this error is hard to reproduce and we've already restarted the Sync Gateways since it was last reproduced.

@sethrosetter I'll file a ticket for you to collect this CBGT diagnostics on functional test failures.

**Comment by tleyden** [comment] 2015-12-18 02:13
@adamcfraser Here are the OpaqueSet stats from running commit 29fe0e0559be416b34d8b74441768031748db3e0 in [func test 200](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/200/console)
- SG 172.23.106.195: OpaqueSet called 6646 times
- SG 172.23.107.80: OpaqueSet called 811 times

**Comment by tleyden** [comment] 2015-12-18 04:25
For whatever reason, the workaround in https://github.com/couchbase/sync_gateway/commit/b59e0034fb7a9f732750c59b852a29e6b150f0cd minimizes the issue from happening:

[Functional Test 207](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/207/) ran 5 times with no failures.  

If we can't get the root problem addressed in 1.2, we should consider adding this workaround which shouldn't have any side effects.

**Comment by adamcfraser** [comment] 2015-12-18 05:59
If the usual test has 10000 docs, I think the total OpaqueSet count of 7457 means that 75% of the time, each snapshot only has a single doc in it.  In those scenarios, I suspect our current approach for mocking up the Opaque data (setting SeqStart, SnapStart, and SnapEnd to the high sequence value) is a valid DCP restart point, and we're only failing when (a) we restart in the middle of a multi-sequence snapshot, and (b) we happen to use the second entry in the snapshot to restart.  

If this guess were correct, we should be able to hit the problem more frequently by increasing vbucket throughput (either by increasing the overall throughput, or by targeting a single vbucket with updates (most easily done by sending rapid updates for the same doc id).

**Comment by adamcfraser** [comment] 2015-12-18 18:43
A potential fix might be to only update our stable sequence for full snapshots - if the stable clock always represents a full snapshot, I don't think we'll hit this issue.

**Comment by tleyden** [comment] 2015-12-18 18:45
- [ ] Create functional test which targets a single vbucket with updates (most easily done by sending rapid updates for the same doc id).

Possibly:
- [ ] Change write buffering

**Comment by tleyden** [comment] 2015-12-19 00:33
> Create functional test which targets a single vbucket with updates (most easily done by sending rapid updates for the same doc id).

I attempted this in https://github.com/couchbaselabs/sync-gateway-testcluster/commit/b17435f71a129c9ef5ae8a2d7fb86ea104d8e6f4, but I don't think it worked.  In [func test 211](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/211/console), it failed .. but I'm having trouble interpreting why it failed.  @sethrosetter any thoughts?

**Comment by tleyden** [comment] 2015-12-19 00:37
I pushed the "magic workaround" to the [feature/issue_1371_opaque_set_panic_magic_workaround](https://github.com/couchbase/sync_gateway/tree/feature/issue_1371_opaque_set_panic_magic_workaround) branch.

With the workaround in place, it fixes it 90% of the time (still looking for the failure case, got lost in the func test runs)

@adamcfraser came up w/ a theory regarding why this workaround works:

> it's possible that the abs_high_seqno lookup on the server is putting the server into a different state, and that's related

**Comment by tleyden** [comment] 2015-12-19 00:56
I found the functional test failure which happened even with the magic workaround:

[func test 206](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/206)

The actual branch being tested was [feature/issue_1259_dcp_reshard_abs_highseqno](https://github.com/couchbase/sync_gateway/tree/feature/issue_1259_dcp_reshard_abs_highseqno), but it's the same commit as in  [feature/issue_1371_opaque_set_panic_magic_workaround](https://github.com/couchbase/sync_gateway/tree/feature/issue_1371_opaque_set_panic_magic_workaround)

In the logs (`/tmp/test_dcp_reshard.py-test_dcp_reshard_sync_gateway_goes_down-2015-12-17-19-22-32-sglogs.zip`) I'm not seeing any errors whatsoever .. no panics, no warnings, no dcp rollbacks .. so the reason it failed is something of a mystery.

The test output does show that the changes feed doesn't get the expected number of items:

```
 -> |traun| expected (num_docs: 2000 num_revisions: 0) _changes (num_docs: 704 updates: 0)
```

**Comment by tleyden** [comment] 2016-01-05 01:25
Recent test failure:  http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests/43/testReport/junit/functional_tests/test_dcp_reshard/test_dcp_reshard_sync_gateway_goes_down/

**Comment by tleyden** [comment] 2016-01-05 18:10
TODO: create a branch with this workaround commit and re-test:

https://github.com/couchbase/sync_gateway/commit/1ccf2c038914d35bd7f74c455cbd56fe871e3f37

**Comment by adamcfraser** [comment] 2016-01-06 19:01
Starting point would be to validate assumption that the current failures are due to attempting to start a DCP feed midway through a snapshot.

**Comment by zgramana** [comment] 2016-01-07 19:33
This is known issue for 1.2, to be fully resolved in the next release.

**Comment by adamcfraser** [comment] 2016-01-18 22:42
Can also be reproduced/should be verified against the scenario described in https://github.com/couchbase/sync_gateway/issues/1471.

**Comment by adamcfraser** [comment] 2016-09-21 05:21
Still pending: 
- [ ] Handling for multiple nodes working the same stream, both attempting to persist Opaque values

**Closed as completed** 2016-09-27 23:01 UTC
Labels: P1: high

**Comment by tleyden** [comment] 2017-01-26 02:41
> Still pending:  Handling for multiple nodes working the same stream, both attempting to persist Opaque values

@adamcfraser I just stumbled across this comment .. is it done or should we spin off a new ticket?
