### ISSUE TITLE
:4985/{db}/_role/ returns deleted roles

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1558] opened 2016-02-03 02:51 UTC
Using Couchbase Sync Gateway/1.2.0(77;490449e)

Steps to reproduce
- Create two roles 

```
curl -X "PUT" "http://localhost:4985/db/_role/tv_role" \
    -d $'{
  "admin_channels": [
    "ABC"
  ],
  "name": "tv_role"
}'
```

```
curl -X "POST" "http://localhost:4985/db/_role/" \
    -d $'{
  "admin_channels": [
    "KTEK"
  ],
  "name": "dj_role"
}'
```
- Get the roles

```
curl -X "GET" "http://localhost:4985/db/_role/"
```

Response:

```
["dj_role","tv_role"]
```
- Delete one role

```
curl -X "DELETE" "http://localhost:4985/db/_role/tv_role"
```
- Try to get the deleted role by name

```
curl -X "GET" "http://localhost:4985/db/_role/tv_role"
```

Response:

```
{
  "error": "not_found",
  "reason": "missing"
}
```

It appears the role has been deleted.
- Get all the roles again.

```
curl -X "GET" "http://localhost:4985/db/_role/"
```

Response:

```
["dj_role","tv_role"]
```

Expected: The deleted role would not show up in the last step.
Actual: The deleted role shows up in in the last step.

**Comment by sethrosetter** [comment] 2016-02-03 03:25
Logs - https://gist.github.com/sethrosetter/2a84fc3069dffb385af9#file-sg-log-L19

**Comment by adamcfraser** [comment] 2016-02-03 06:39
Expect this to be the same root cause as #1557 - same scenario.  Closing as duplicate, will add note about roles to #1557.

**Closed as completed by adamcfraser** 2016-02-03 06:39 UTC
