### ISSUE TITLE
Store attachments outside the bucket

### ISSUE THREAD

**Issue by snej** [couchbase/sync_gateway#197] opened 2013-10-17 18:00 UTC
Currently we store attachments as individual binary docs in the bucket. That's problematic, especially because there's a 20mb size limit.

We should switch to external storage, probably CBFS which was created specifically to solve this problem.

I think CBFS will make it easier to GC attachments too.

**Comment by brendand** [comment] 2015-06-07 21:15
:+1: Seems this has been on the table for a couple of years now. Well, here's my up-vote for it. I'm assuming this would extend to some sort of equivalent implementation in Couchbase Lite?

**Comment by snej** [comment] 2015-06-07 21:49
@brendand: No, CBL already stores attachments in the (normal) filesystem, which gives them unlimited size, and is scaleable enough for a client database.

**Comment by brendand** [comment] 2015-06-10 17:04
@snej Ah I see. Ok, well the main purpose of using CBL is to sync to a server, so it's still limited. But I guess there would be no limitation for peer-to-peer syncing then?

**Comment by snej** [comment] 2015-06-10 18:09
Right. Or for syncing to CouchDB/BigCouch/Cloudant servers.

**Comment by jburich** [comment] 2016-11-21 18:52
Are there any plans to implement this? I would really like to be able to sync large files through Couchbase Lite/Sync Gateway and chunking them up to store them in Couchbase Server documents is less than ideal.

**Comment by tleyden** [comment] 2016-11-22 13:40
@jburich it's definitely on the roadmap, but it's not scheduled for immediate implementation

**Comment by snej** [comment] 2016-11-22 18:32
You can implement your own attachment system using something like S3. When an app creates a new attachment, have it upload it to that server and add the resulting URL to the document. Then of course the app will need to manage downloading (and probably caching) attachments.

It's definitely more work, but it gets around the 20MB limit and gives you other flexibility too (like using a CDN to increase availability of attachments), and it takes some of the load off of SG and Couchbase Server.

**Comment by jburich** [comment] 2016-11-22 19:56
Agreed, we could implement this ourselves and that is what we will probably end up doing. As we've started laying this out there is a lot of work to do: fetching, caching, peer to peer sharing, our tablets are offline 75% of the time so we need to be network aware, we plan to use sync_gateway as an edge server, etc. We also have a Ruby app that will connect to the sync gateway so we'll need to write the logic there and given it is a multi platform (ios, Android and Windows) we'll need to implement it in all three native apps. Was hoping to centralize this logic inside the sync_gateway instead of writing everywhere.

**Comment by jburich** [comment] 2016-11-29 18:59
After much deliberation here. We have decided that chunking is not performant enough on Android. we have some fairly large videos and reconstructing the chunks into a playable file results in way to much lag time between clicking Play and the video actually playing. 

We also considered writing out the files and purging the attachments, but then we loose the peer to peer replication that we want. And if we keep the chunks around to support peer to peer we are talking an extra 100 gb of data.

So we are left with either write the S3 code into our apps and the ruby apps which would most likely mean we give up on peer to peer replication in the short term or we get S3 backed buckets implemented. 

I have some spare time and given that either way we are writing some code to make this happen I think we as a company are better served by supporting the open source platform we will be using and building out this functionality rather than writing a bunch of custom code. 

I saw this was at one point labeled "size-large". I would expect this to be a fair amount of work, and wondering if anybody has put thought into it that could point me/us in the right direction. If not I will start checking out code and reading through documentation to get a better understanding of how this would work. 

Note I have not gotten full buy in from the client to spend their money working on this so while I'm fully expecting us to be able to contribute here I do not know for sure that we will be able to.

**Comment by jburich** [comment] 2016-12-08 12:26
My client says depending on how much effort it is they would be willing to spend the time/money to have me and my team implement this feature. But they want me to put together and estimate first. Is there anybody from the couchbase team that would be willing to take a few minutes to help me understand what all would need to get done to make this happen?

**Comment by snej** [comment] 2016-12-08 17:09
@jburich I've been out of the loop on Sync Gateway for a year or more, but this seems like a great opportunity, so if no one on the team has time to talk I'd be glad to step up.

**Comment by mikemliu** [comment] 2016-12-09 09:04
How does the 20MB limit affect overall document size when there are attachments? Use case is multiple attachments that are each well under 20MB but entire document + attachments is well over. Thought that somewhere in the docs indicated that this is supported since sync gateway stores each attachment as a separate doc in couchbase server. My testing seems to indicate that sometimes the push to sync gateway will fail with 413 "request too large" even though any single attachment should be well ~1-2MB.

**Comment by jburich** [comment] 2016-12-09 15:52
@mikemliu I haven't see that particular problem. In fact I have 500+ mb files that I'm attaching. I do it by chunking the file into 20 mb chunks and storing each chunk as a separate attachment, but all on one document. Those documents work just fine, but I'm seeing the actual storage size be close to 40% greater than the raw file sizes. 

For example I have 4 videos that are all 215 mb each, which should add up to 860mb, but the total size in the buckets ends up being 1.2gb. And because of that our performance really suffers, but the data does replicate successfully.

**Comment by snej** [comment] 2016-12-09 18:12
@jburich The 20MB limit is per attachment, not per document. I don't know why the storage would be greater than the total attachment size; that's worth filing a new issue about.

**Comment by mikemliu** [comment] 2016-12-09 19:40
@jburich @snej Confirmed that it was a reverse proxy server in between that was complaining. Thanks!

**Comment by tleyden** [comment] 2018-09-20 23:48
I think the best approach here is to assume that SG is talking to an S3 compatible API, which would allow the following backends for blob storage:

- AWS S3
- [Minio](https://www.minio.io/) in private data center
- Google, Azure and other cloud storage via S3 compatible [Minio gateway](https://www.minio.io/)

**Comment by househippo** [comment] 2019-05-20 16:05
AFTER WRITE
If you want to move the attachement after its written to CB can we have Couchbase Eventing do this instead?

**Comment by adamcfraser** [comment] 2019-12-20 20:11
Closing based on age. Valid use case, but would be implemented as a more comprehensive set of enhancements to attachment handling.

**Closed as completed by adamcfraser** 2019-12-20 20:11 UTC
Labels: enhancement, performance, known-issue, icebox
