### ISSUE TITLE
SyncGateway/SyncGateway replicator memory keeps growing continuosly and resulting in OOM crash

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2218] opened 2017-01-12 11:38 UTC
### Sync Gateway version
1.3.1

### Operating system
ReDHat 7.2

### Setup details
###2 clusters
3*couchbase nodes
2*syncgateway nodes
2*sg-replicate nodes
on each of clusters.

We could see that syncgateway memory usage is keeps on increasing during traffic. once the traffic stopped memory is not released. 
As per documentation memory is related to number channels and docs in channels, we have set cache config as
"cache": {
                    "channel_cache_max_length": 50,
                    "channel_cache_min_length": 10
                    },

we have created 10k channels initially with 50 documents in channel. later inserted 250 docs in each of channels in same 10k channels

### Expected behavior
Memory should grow till each channels have 10 docs. after reaching, older unused documents should be evicted from syncgateway memory after reaching expiry of 60 seconds(default channel_cache_expiry). memory consumption should not increase gradually.

### Actual behavior
Memory usage is keeps on increasing with traffic.

**Comment by ajres** [comment] 2017-01-12 12:40
@ArihantRk memory will also be consumed for each open tcp connection on the Sync Gateway host.

During the test run you can monitor the number of open connections using netstat e.g.

`netstat -at`

After the test completes, if you still see a large number of connections in the TIME_WAIT state, these can take minutes to close depending on your system configuration.

**Comment by ArihantRk** [comment] 2017-01-12 13:23
@ajres we have 200 persistent connections made to syncgateway and no TIME_WAIT state we have observed after execution of test.

**Comment by adamcfraser** [comment] 2017-01-12 17:40
Memory usage is also expected to grow until the revision cache is full.  Are you tuning rev_cache_size in your testing?

**Comment by ArihantRk** [comment] 2017-01-13 04:44
we have not tuned rev_cache_size in test. size of each document is 4kb. default it will be 5000.

**Comment by adamcfraser** [comment] 2017-01-13 05:07
We'll need more specifics on the memory usage you're seeing, and the specific concerns you have, in order to provide additional recommendations.

**Comment by ArihantRk** [comment] 2017-01-13 05:33
could you please let me know what are the info you need. The concern we have is when syncgateway memory consumption stops growing. What is limit on syncgateway memory usage.

i would be happy to provide any info you need.

**Comment by ArihantRk** [comment] 2017-01-18 04:53
@adamcfraser 

we are having 2 vm's . each of containing below nodes.
Each of vm has 120GB memory. syncgateway container has limited to 24GB.
3*CBS
2*SYNCGW
2*SYNCGWREP(* based replication)

Below config are set and rest all are default 
revs_limit=5

we are updating same documents every 15 seconds(30 cps ).
syncgateway memory growing continuously and could see sudden increase in memory usage from 5GB to 9GB. memory usage increases till OOM and gets crash.

below are some info of expvar 
https://gist.github.com/ArihantRk/78eb5a0aa5df104ba1fc6bd297f8f7ba/b8063ff59193f54a7589d399e9bb7a82e96a5069

**Comment by tleyden** [comment] 2017-01-18 06:59
@ArihantRk is it possible for you to do memory profiling per the instructions in [profiling-go-programs](https://blog.golang.org/profiling-go-programs)

We have some example collection scripts in [mobile-testkit/sync_gateway_collect_profile.py](https://github.com/couchbaselabs/mobile-testkit/blob/46c75d21a82f9d3c3649a5bf42501ad91415d65f/libraries/provision/ansible/playbooks/files/sync_gateway_collect_profile.py#L48) that might be helpful to look at

**Comment by ArihantRk** [comment] 2017-01-20 10:21
@tleyden , below is the memory profiling data from latest crash. Attachment contains RSS memory snapshots where increase is observed, sync gw log snapshot when memory started increaseing and Go profiling data. 
This is seen in our both sync gw nodes and sg replicator node.

[SyncGwMemoryIncrease.txt](https://github.com/couchbase/sync_gateway/files/719054/SyncGwMemoryIncrease.txt)

**Comment by ArihantRk** [comment] 2017-01-20 10:27
Attaching full snapshot of heap data just before crash.

[SyncGW_200117_082001.profile.heap.txt](https://github.com/couchbase/sync_gateway/files/719088/SyncGW_200117_082001.profile.heap.txt)
[SyncGW_200117_081001.profile.heap.txt](https://github.com/couchbase/sync_gateway/files/719089/SyncGW_200117_081001.profile.heap.txt)

**Comment by ArihantRk** [comment] 2017-01-24 03:51
@tleyden , we are seeing this issues very frequently, any insights on this?

**Comment by adamcfraser** [comment] 2017-01-24 04:17
It looks like a significant amount of memory is associated with document bodies.  Have you tried modifying rev_cache_size, as discussed previously?

**Comment by ArihantRk** [comment] 2017-01-24 06:27
@adamcfraser we have set rev_cache_size=500 in other setup but could not notice any difference in memory growth.

but we have observed below with default revs_cache_size. seeing memory increasing to 15-20GB is not possible with revs_cache_size=5000.
Total container memory is 23GB. 
Our observation is when memory increases, Skipped sequence warning messages are observed in syncgw logs. When this warning is not present, then memory growth is not observed.
I am attaching memory growth observed in 2 syncgw's. One syncgw went to max size  (20GB) and got killed due to OOM and warning messages is observed continuously till crash. Another syncgw memory grew to 7GB but came down and during this time, skipped sequence warning message is not observed.

can i get insight on this skipped sequence  and memory increase.

As seen from below snapshots memory was almost constant for hours, but suddenly increased at some point(seen WARNING: Skipped Sequence 13812316 didn't show up in MaxChannelLogMissingWaitTime, and isn't available from the * channel view.  If it's a valid sequence, it won't be replicated until Sync Gateway is restarted. -- db.(*changeCache).CleanSkippedSequenceQueue.func1() at change_cache.go:220 )

![syncgw1_rss_4](https://cloud.githubusercontent.com/assets/13716346/22236526/2dc3726e-e22c-11e6-84ec-dcff6fe686c2.png)
![syncgw2_rss_4](https://cloud.githubusercontent.com/assets/13716346/22236527/2dc3eb0e-e22c-11e6-8ade-3f8dc57250a5.png)

**Comment by adamcfraser** [comment] 2017-01-24 17:42
When skipped sequences are about to be abandoned, we perform a view query to validate that the sequence isn't in the database before abandoning. This could be related to the memory spike you're seeing.  How many skipped sequence log messages are you seeing at the time the spike occurs?

**Comment by tleyden** [comment] 2017-01-24 18:10
@ArihantRk in order to disentangle the replicator memory usage with the Sync Gateway memory usage, do you think you can try to run [sg-replicate](https://github.com/couchbaselabs/sg-replicate) in standalone mode and reproduce the issue?

Unfortunately there aren't any prebuilt binaries for `sg-replicate`, but building it shouldn't be too hard.

This will be helpful so that we can isolate the source of the problem.   Also, anything information you can provide to help us reproduce the issue on our end would be super helpful.

**Comment by ArihantRk** [comment] 2017-01-30 08:28
@tleyden , currently we are running sg-replicate in standalone mode only. No clients hitting to sg-replicate nodes. sg-replicate nodes query data from couchbase cluster and replicate to another sg-replicate.

@adamcfraser , what exactly meaning of abandoning sequence, is it ignoring sequence? in this case clients will miss this particular document permanently?. 
we are getting many skipped sequence log messages at the time of spike. Also during non spike time also these log messages are seen but not frequently
Also what are the possible scenarios where we hit into skipped sequence warning messages in syncgateway logs.

**Comment by kirangandhi** [comment] 2017-02-01 06:05
@tleyden , @adamcfraser: 
I am in same team as Arihant. Did you get a chance to look into the issue? We are hitting into this issue frequently and not able to proceed further.

**Comment by ArihantRk** [comment] 2017-02-06 05:11
@tleyden, @adamcfraser: We are seeing OOM crash very frequenctly. Any luck on this.

**Comment by adamcfraser** [comment] 2017-02-06 08:07
@ArihantRk What is 'many' skipped sequence log messages, exactly?  If you're seeing more than a few, I expect there's something else going on that's causing the skipped sequences in the first place.  

I haven't had time to try to reproduce the memory spike during skipped sequence view execution, but it may merit trying to work out why sequences are being allocated and then apparently not used.

**Comment by tleyden** [comment] 2017-02-06 15:59
> @tleyden , currently we are running sg-replicate in standalone mode only. No clients hitting to sg-replicate nodes. sg-replicate nodes query data from couchbase cluster and replicate to another sg-replicate.

I think we have some confusion, because I think when you say "No clients hitting to sg-replicate nodes" it sounds like you are running sg-replicate *inside* of sync gateway.  What I was suggesting is to build and run sg-replicate as a standalone binary that runs in it's own process rather than being embedded inside of a sync gateway process.  That would allow us to determine if the extra memory utilization is inside the sync gateway process or inside the sg-replicate process.

**Comment by adamcfraser** [comment] 2017-02-07 08:00
@ArihantRk A followup to my previous comment - the default maximum wait time to retain skipped sequences is one hour.  Given the sudden spike in your memory usage, it may be useful to review the SG logs one hour previous to the OOM to try to work out what's causing the surge in skipped sequences.

**Comment by kirangandhi** [comment] 2017-02-13 09:27
@adamcfraser  If we observe frequent skipped sequence, does memory increases suddenly in sync gateway? What we are seeing is memory is spiking suddenly from 1-2GB to 24GB within 10-12 mins and going to OOM. 24GB is memory limit for sync gateway container. Our current bucket size is around 3-4 GB. Not able to detect root cause for the memory consumption. Same pattern is observed in sync gateway replicator (replicator running with sync gateway binary). What causes memory consumption in sync gateway? Is there any sync gateway documentation available on troubleshooting memory consumption in sync gateway? Require your help to unblock this issue.

**Comment by kirangandhi** [comment] 2017-02-16 05:13
@adamcfraser Any inputs from you will be very helpful.

**Comment by adamcfraser** [comment] 2017-02-16 07:26
@kirangandhi In order to provide additional insight into this problem, can you provide the answer to my previous question?
> What is 'many' skipped sequence log messages, exactly? If you're seeing more than a few, I expect there's something else going on that's causing the skipped sequences in the first place.

**Comment by kirangandhi** [comment] 2017-02-22 05:36
@adamcfraser Thanks for the reply. We will verify and will update the answer.

**Comment by ddash1** [comment] 2017-03-17 02:56
@kirangandhi can you please update

**Comment by ArihantRk** [comment] 2017-03-17 07:45
@adamcfraser As our observations, we are getting OOM in syncgateway due to revision history growth . 

revs_limit is set to 60
We have seen revision history growth in below scenarios
1. More number of revisions history >60 due to conflicts in document
2. when more number > 60 updates happening in source cluster before replicating to destination cluster

And also we are seeing skipped sequence log messages , frequency of number of skipped sequences is varies. any insights on what can be the cause for skipping sequences ?

**Comment by adamcfraser** [comment] 2017-03-17 15:53
I suspect the skipped sequences are related to https://github.com/couchbase/sync_gateway/pull/2369, the fix for which will be included in 1.4.1.  If you're able to run a test against the latest master branch of Sync Gateway, you can see if that addresses your particular scenario.

**Comment by ArihantRk** [comment] 2017-03-24 05:03
Thanks @adamcfraser , we will verify the same in 1.4.1. Another cause for OOM we observerd is due to revision growth more than revs_limit.
We have tried the conflicts handling as per below https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/resolving-conflicts/index.html

but looks like below are missing in conflicts resolution

1. If one of conflicted revision is pruned from couchbase
2. Sometimes I could see conflicted revisions in **changes?activeonly=true&style=all_docs** response even after conflicted revision is deleted,  hence tool end up deleting the same old revision for every time.
3. Does not handle revision growth(with non-conflicted revisions) beyond revs_limit .
I have raised issue in forum and below is link
https://forums.couchbase.com/t/handling-revision-growth/12072

**Comment by ArihantRk** [comment] 2017-04-06 06:39
@adamcfraser A followup to your skipped sequence messages in logs, we have verified in the logs 1-2 hours before arrival of skipped sequence messages, and could see below observations

1. we have cron job which purges the old documents(_deleted documents, using _purge syncgateway endpoint)  as part of cleanup unused documents and could see many of below messages
- db.(*changeCache).DocChanged.func1() at change_cache.go:327
02:09:51.429260 2017-04-06T02:09:51.429+05:30 WARNING: changeCache: Error unmarshaling doc "s917800098960_ptx1489771369263_meta.doc": unexpected end of JSON input -- db.(*changeCache).DocChanged.func1() at change_cache.go:327
02:09:51.429291 2017-04-06T02:09:51.429+05:30 WARNING: changeCache: Error unmarshaling doc "s917800098984_ptx1489339528229_meta.doc": unexpected end of JSON input -- db.(*changeCache).DocChanged.func1() at change_cache.go:327

2. many of skipped sequences in the replicators nodes
03:40:43.980285 2017-04-06T03:40:43.980+05:30 WARNING: Skipped Sequence 36097477 didn't show up in MaxChannelLogMissingWaitTime, and isn't available from the * channel view.  If it's a valid sequence, it won't be replicated until Sync Gateway is restarted. -- db.(*changeCache).CleanSkippedSequenceQueue.func1() at change_cache.go:220

3.  changes_view queries are taking more time in 3-10 seconds
changes_view: Query took 4.214300597s to return 100 rows, options = db.Body{"stale":false, "startkey":[]interface {}{"PTX-919900231849-meta-CH", 0x206b156}, "endkey":[]interface {}{"PTX-919900231849-meta-CH", 0x21a583f}, "limit":100}


OOM is observerd and syncgateway replicator is restarted even-though conflicts resolved 

Potentially we are getting OOM independently from below issues
**1. Revision history growing beyond revs_limit(due to conflicts and replication lag)
2. Many WARNING: Skipped Sequence messages in replicator logs**

Please let us know what exactly skipped sequences means and in what scenarios we end-up having skipped seq messages.

**Comment by ArihantRk** [comment] 2017-04-10 05:39
@adamcfraser we are getting OOM very frequently. any insights will be helpful ,

**Comment by adamcfraser** [comment] 2017-04-10 05:44
@ArihantRk If you're able to generate the pdf of the heap profiles, it will provide more information than the text summaries included above.  That will help narrow down what's going on - otherwise there are too many different threads going on this ticket to narrow this down to a reproducible scenario.

**Comment by ArihantRk** [comment] 2017-04-17 07:33
@adamcfraser will share the results for next OOM.

**Comment by djpongh** [comment] 2017-07-31 18:18
We expect the 1.4.1.1 MP coming out will address this issue. Please reopen if it doesn't.

**Closed as completed by djpongh** 2017-07-31 18:18 UTC
Labels: bug, performance, P1: high, ffc
