### ISSUE TITLE
Missing doc in replication (not sent to client)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2340] opened 2017-02-22 07:17 UTC
### Sync Gateway version
1.4-102 (cc) + 4.5.1 CBS 

Using
- Android Nexus 5, Android 6.0.1, SQLite) - seth
- Android Nexus 6P Api 25 google emulator (SQLite) - seth
- Android Nexus 4 Api 16 google emulator (ForestDB) - jens
- Android ?? (ForestDB+Encryption) - pasin

### Operating system
CentOS 7

### Config file
todo config - https://gist.github.com/sethrosetter/989b45bc9b6fa66b6940fe7076ad87cf

### Log output
(1). Sync Gateway logs - https://s3.amazonaws.com/cbmobile-bucket/issues/issue_2340_test_fest/backfill-issue.log
(2). Sync Gateway all docs - http://XXX.compute-1.amazonaws.com:4985/todo/_all_docs?include_docs=true (https://gist.github.com/sethrosetter/8bd9979950126733ce28f3dd3ffad97d)
(3). adb device output - https://gist.github.com/pasin/6d86cd802f8070bbaf94fdc494e0d6a2
(4.) Pasin's docs - https://gist.github.com/pasin/6b0e8b36080c2e2a6b673c2370b74c84

The scenario:
seth creates s1 - s10 lists and shares with jens, pasin
jens creates j1 - j10 lists and shares with seth, pasin
pasin creates pasin1 - pasin10 lists and shares with seth, jens

All docs were sync'ed except `jens.962719c4-17f4-4e72-a9a5-2f93bfc8a174` (j3) list. The was never sent to pasin.

All of the docs that pasin sees in his local db is in (4.)
We looked through (3, Android device logs) and did not see the missing doc come in on the changes feed.

The doc was successfully pushed (2) to sync gateway from jens and it successfully sync'ed to the seth user as well. The difference between sending to the pasin user and the seth user may highlight what failed here.

**Comment by adamcfraser** [comment] 2017-02-22 09:12
Based on the SG logs, this looks like https://github.com/couchbase/sync_gateway/issues/2068.

1. Granting doc is cached to the pasin channel:
```
2017-02-22T06:16:20.995Z Cache:     #234 ==> channel "pasin"
```

2. Pasin's changes feed is woken up because the granting doc is in a channel he already has access to:
```
2017-02-22T06:16:20.995Z Changes+: Notifying that "data-bucket" changed (keys="{*, moderators, pasin, task-list.jens.962719c4-17f4-4e72-a9a5-2f93bfc8a174.users}") count=502
```

3. Pasin's changes feed reloads the user, but doesn't have access to `task-list.jens.962719c4-17f4-4e72-a9a5-2f93bfc8a174` (because the invalidation of Pasin's user doc hasn't happened yet).
```
2017-02-22T06:16:20.995Z Changes+: MultiChangesFeed reloading user &{roleImpl:{Name_:pasin ExplicitChannels_:pasin:8 Channels_:!:1,pasin:8,task-list.jens.07e4790d-52fa-496b-ad11-d3d5fcaa4d83:143,task-list.jens.3e80e458-5969-46f8-98ce-9598d31340c9:97,task-list.jens.40f5c957-ac73-41dc-bef8-f91355df5a71:144,task-list.jens.5bfdbce6-003f-4ffe-a6e1-e0fd1dd9d8d6:229,task-list.jens.7564256b-0028-45a2-8180-490614bf66fe:145,task-list.jens.bbf87431-086c-48ca-8120-cfc3d002db08:46,task-list.jens.c506c127-58f7-49f8-9a79-ddce5bad2554:142,task-list.jens.e18dbc53-3487-4c13-afdf-7d8fb642a54a:62,task-list.jens.fbbb026b-7a74-498d-8cf8-5b1ea7a60de9:226,task-list.pasin.09cc8455-0043-4301-a773-4fbbedbdbb6a.users:194,task-list.pasin.09cc8455-0043-4301-a773-4fbbedbdbb6a:194,task-list.pasin.355cb7f9-a6bd-4abf-869f-5911e7645c70.users:187,task-list.pasin.355cb7f9-a6bd-4abf-869f-5911e7645c70:187,task-list.pasin.42fcdaf3-4473-4de8-ad4a-2dbcc2914f9a.users:179,task-list.pasin.42fcdaf3-4473-4de8-ad4a-2dbcc2914f9a:179,task-list.pasin.49f1a316-5549-46d4-8b43-771a93cb5873.users:57,task-list.pasin.49f1a316-5549-46d4-8b43-771a93cb5873:57,task-list.pasin.574a9394-ad56-4cfc-bf0e-e75e968f8fc6.users:176,task-list.pasin.574a9394-ad56-4cfc-bf0e-e75e968f8fc6:176,task-list.pasin.5f9abb8d-9945-4b62-b009-9dc4198f0f71.users:183,task-list.pasin.5f9abb8d-9945-4b62-b009-9dc4198f0f71:183,task-list.pasin.65227260-f8c3-4680-8c53-399e8adb1743.users:109,task-list.pasin.65227260-f8c3-4680-8c53-399e8adb1743:109,task-list.pasin.999f1c71-e951-4d70-aaa8-d8fd0210695a.users:59,task-list.pasin.999f1c71-e951-4d70-aaa8-d8fd0210695a:59,task-list.pasin.9a0e1727-8b39-451c-9d71-a410aeeaddbe.users:198,task-list.pasin.9a0e1727-8b39-451c-9d71-a410aeeaddbe:198,task-list.pasin.a59e29d0-275a-4765-a31e-d320d20a85af.users:45,task-list.pasin.a59e29d0-275a-4765-a31e-d320d20a85af:45,task-list.pasin.aa4008dc-456f-4678-bea7-ceb8cc750e22.users:70,task-list.pasin.aa4008dc-456f-4678-bea7-ceb8cc750e22:70,task-list.pasin.aeb0ea6e-ca37-41d9-b581-9d766c7a4f58.users:189,task-list.pasin.aeb0ea6e-ca37-41d9-b581-9d766c7a4f58:189,task-list.pasin.b0ed89d4-055e-4cb7-a96b-7f03382c75ae.users:173,task-list.pasin.b0ed89d4-055e-4cb7-a96b-7f03382c75ae:173,task-list.pasin.efa5d67e-f769-4740-b39b-44ec1d30c374.users:104,task-list.pasin.efa5d67e-f769-4740-b39b-44ec1d30c374:104,task-list.pasin.effa7b35-abfc-4f85-8e5a-07314a671f1e.users:181,task-list.pasin.effa7b35-abfc-4f85-8e5a-07314a671f1e:181,task-list.pasin.f2506090-b48c-44a8-9b2a-56080bc68ed8.users:193,task-list.pasin.f2506090-b48c-44a8-9b2a-56080bc68ed8:193,task-list.seth.078e4600-bc7c-4c37-b9d6-e8b0e614f4e4:137,task-list.seth.0e93db0b-3194-4843-aad2-e757cdadfd22:138,task-list.seth.29c67083-e847-4545-9e77-0e16a24d092f:185,task-list.seth.4b2e3118-6feb-448d-aaa2-5be916be8300:200,task-list.seth.4fc43359-9d02-4417-a03a-42c83cde11b3:205,task-list.seth.5719e2df-dc84-4440-b146-f9835055d483:202,task-list.seth.69948c5c-267a-4bb1-904f-0037e2738009:191,task-list.seth.69fb5ece-8dbe-421f-8d92-4857e2172a70:188,task-list.seth.6fd9c241-3e4c-4a7b-b714-2474e0d56b10:140,task-list.seth.727e0290-bfcf-47a9-8796-69100e0a0e71:197,task-list.seth.9629d881-bcf8-4ea3-9c3c-152878685ca2:91,task-list.seth.a889c250-e25b-4f67-a306-f2dc9b38b073:195,task-list.seth.c1161efe-a779-4511-b20f-4c3736ad6b56:206,task-list.seth.c179d555-516d-4bec-859c-5e1cc686d8f3:139,task-list.seth.c8fd0626-82b1-4fd1-a696-9530ec7dd550:141,task-list.seth.e222b0c3-57fb-4c56-b7d1-4ea5bdb70066:182 Sequence_:8 PreviousChannels_: vbNo:<nil>} userImplBody:{Email_: Disabled_:false PasswordHash_:[36 50 97 36 49 48 36 49 51 102 116 48 119 97 115 99 57 71 113 105 50 75 111 73 46 76 87 100 101 107 114 51 115 105 49 48 47 107 55 66 84 102 87 68 67 101 122 120 106 105 57 99 79 70 99 68 100 105 113 75] OldPasswordHash_:<nil> ExplicitRoles_: RolesSince_: OldExplicitRoles_:[]} auth:0xc420a616e0 roles:[]}
```

4. Pasin's user doc channels are finally invalidated by the access grant:
```
2017-02-22T06:16:20.996Z Access: Invalidate access of "pasin"
...
2017-02-22T06:16:20.999Z Auth: Saved _sync:user:pasin: {"name":"pasin","admin_channels":{"pasin":8},"all_channels":null,"sequence":8,"passwordhash_bcrypt":"JDJhJDEwJDEzZnQwd2FzYzlHcWkyS29JLkxXZGVrcjNzaTEwL2s3QlRmV0RDZXp4amk5Y09GY0RkaXFL","rolesSince":{}}
```
5. Pasin's changes iteration continues, and the granting doc is sent to Pasin:
```
2017-02-22T06:16:21.000Z Changes+: MultiChangesFeed sending {Seq:234, ID:jens.962719c4-17f4-4e72-a9a5-2f93bfc8a174.pasin, Changes:[map[rev:1-41cba0a70769198dcdbae5ccf56c68f5]]}   (to pasin)
```

At this point Pasin's since value has run past the granting doc, and so won't trigger a backfill for the channel, even the next time Pasin's user doc is reloaded and picks up the new channel access.

**Comment by adamcfraser** [comment] 2017-02-22 17:37
Closing as a duplicate of https://github.com/couchbase/sync_gateway/issues/2068

**Closed as completed by adamcfraser** 2017-02-22 17:37 UTC
Labels: P1: high
