### ISSUE TITLE
cbheartbeat start delay causes DCP stream to not be re-sharded when SG node killed quickly

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1259] opened 2015-11-03 21:25 UTC
Using binary built from source - d760caa

The test consists of 4 sync_gateways. While adding docs via bulks and individual doc puts to sync_gateways 2 and 3, sync_gateway 1 is taken off line. This results in a sporadic crashing of the sync_gateways after issuing a /db/_changes request.

```
2015-11-03T12:39:25.080-08:00 DCache+: Add to channel index [ABC], vbNo=701, isRemoval:false
2015-11-03T12:39:25.080-08:00 DCache: block index for minSequence 2 is 0
2015-11-03T12:39:25.080-08:00 DCache+: Add to channel index [ABC], vbNo=701, isRemoval:false
2015-11-03T12:39:25.080-08:00 DCache: block index for minSequence 1 is 0
2015-11-03T12:39:25.080-08:00 DCache: block index for minSequence 3 is 0
2015-11-03T12:39:25.080-08:00 DCache+: Add to channel index [NBC], vbNo=700, isRemoval:false
2015-11-03T12:39:25.080-08:00 DCache+: Add to channel index [ABC], vbNo=701, isRemoval:false
2015-11-03T12:39:25.080-08:00 DCache: block index for minSequence 4 is 0
2015-11-03T12:39:25.080-08:00 DCache+: Add to channel index [ABC], vbNo=802, isRemoval:false
2015-11-03T12:39:25.080-08:00 DCache: block index for minSequence 2 is 0
2015-11-03T12:39:25.080-08:00 DCache+: Add to channel index [NBC], vbNo=700, isRemoval:false
2015-11-03T12:39:25.080-08:00 DCache: block index for minSequence 7 is 0
2015-11-03T12:39:25.080-08:00 DCache: block index for minSequence 3 is 0
panic: Update attempted to set clock to earlier sequence.  Vb: 542, currentSequence: 4, newSequence: 2

goroutine 22289 [running]:
github.com/couchbase/sync_gateway/base.(*SequenceClockImpl).UpdateWithClock(0xc2086eac30, 0x7fb18e762d28, 0xc2090d6420)
    /home/centos/sync_gateway/src/github.com/couchbase/sync_gateway/base/sequence_clock.go:276 +0x29e
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).writeClockCas(0xc208174480, 0x7fb18e762d28, 0xc2090d6420, 0x0, 0x0)
    /home/centos/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:378 +0x6f
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).AddSet(0xc208174480, 0xc2083f2000, 0x196, 0x7d0, 0x0, 0x0)
    /home/centos/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_channel_index.go:91 +0x304
github.com/couchbase/sync_gateway/db.(*kvChangeIndex).addSetToChannelIndex(0xc2080c8000, 0xc2081fb6b3, 0x3, 0xc2083f2000, 0x196, 0x7d0)
    /home/centos/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:839 +0xdc
github.com/couchbase/sync_gateway/db.func·037(0xc2081fb6b3, 0x3, 0xc2083f2000, 0x196, 0x7d0)
    /home/centos/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:654 +0x84
created by github.com/couchbase/sync_gateway/db.(*kvChangeIndex).indexEntries
    /home/centos/sync_gateway/src/github.com/couchbase/sync_gateway/db/kv_change_index.go:656 +0x5fe
```

Here are the full logs - https://s3.amazonaws.com/sync-gateway-logs/2015-11-03-12-53-18-sglogs.zip

**Comment by sethrosetter** [comment] 2015-11-04 18:20
While docs are continually being added, I think this has to do with a _changes request before all changes has been processed.

**Comment by tleyden** [comment] 2015-11-04 18:21
@sethrosetter are you able to reproduce this reliably?

**Comment by sethrosetter** [comment] 2015-11-04 23:04
jenkins run - http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/67/console
logs - https://s3.amazonaws.com/sync-gateway-logs/2015-11-04-14-50-36-sglogs.zip

**Comment by tleyden** [comment] 2015-11-06 19:34
TODO: catch up with @adamcfraser on this

**Comment by tleyden** [comment] 2015-12-11 19:34
DCP Reshard test which is failing nearly every time.

**Comment by tleyden** [comment] 2015-12-16 02:54
Here are some logs from a different run:

```
2015-11-04T14:48:36.220-08:00 DCache+: Add to channel index [CBS], vbNo=488, isRemoval:false
panic: Update attempted to set clock to earlier sequence.  Vb: 2, currentSequence: 5, newSequence: 1

goroutine 28132 [running]:
github.com/couchbase/sync_gateway/base.(*SequenceClockImpl).UpdateWithClock(0xc20883a7b0, 0x7f75c721b150, 0xc2098b2210)
    /home/couchbase/jenkins/workspace/sync-gateway-dev-build/feature/distributed_index/community/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/base/sequence_clock.go:276 +0x29e
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).writeClockCas(0xc208760000, 0x7f75c721b150, 0xc2098b2210, 0x0, 0x0)
```

I noticed in those same logs, that there a lot of [dcp rollback messages](https://gist.github.com/tleyden/eb2593b4e42a5d8bedc5)

I was surprised not to see vbucket 2 included in those rollback logs, but regardless this seems to have something to do with rollback where some in-memory state of the `SequenceClockImpl` struct is not getting updated on rollbacks.

**Comment by tleyden** [comment] 2015-12-16 03:05
@adamcfraser in our [rollback handling](https://github.com/couchbase/sync_gateway/blob/feature/distributed_index/src/github.com/couchbase/sync_gateway/base/sgw_pindex.go#L323-L334) for DCP messages received on the Index bucket, there doesn't seem to be anything that would update the [sequence clock per-vb value](https://github.com/couchbase/sync_gateway/blob/feature/distributed_index/src/github.com/couchbase/sync_gateway/base/sequence_clock.go#L274) -- does that seem like it might be the root cause of this issue?

**Comment by tleyden** [comment] 2015-12-17 00:52
I added some code to check whether the high seqno from the StableClock is higher than any of the high sequence numbers for the bucket in commit ec316bc3998805b25789a70cd2eaaac89d7cac79, and ran [func test 181](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/181/console).

The test failed, but looking at the logs in /tmp/test_dcp_reshard.py-test_dcp_reshard_sync_gateway_goes_down-2015-12-16-16-38-21-sglogs.zip:
- No panics
- No rollbacks

However, I did see the newly added warning message in the logs:

```
172.23.107.80/sync_gateway_error.log:2015-12-16T16:40:51.438-08:00 WARNING: issue_1259 highSeqnoFromStableClock (2) > highSeqnoFromBucket (1) for vb 704 -- base.(*SyncGatewayPIndex).SeedSeqnos() at sgw_pindex.go:130
```

It was only a single instance of the warning.

**Comment by tleyden** [comment] 2015-12-17 01:27
I managed to get this test to pass!  [func test 185](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/185/console)

This was using the [feature/dcp_reshard_testing](https://github.com/couchbaselabs/sync-gateway-testcluster/tree/feature/dcp_reshard_testing) branch of sync-gateway-testcluster, which increases the wait time from 10s -> 120s before requesting the changes feed, which is a known race condition inherent in the test.

It was also using commit ec316bc3998805b25789a70cd2eaaac89d7cac79 of the feature/issue_1259_dcp_reshard branch, although that shouldn't have altered any behavior, since it just added some logging.

I think we really need to enhance the functional test to distinguish between two types of failures:
- Test failures due to Sync Gateway panics
- Test failures due to inherent race condition in test (sleep timer).  <-- we should increase the sleep to a large value to minimize the occurrence of these types of failures.

**Comment by tleyden** [comment] 2015-12-17 01:30
From @adamcfraser: 

> just noticed something potentially interesting - the stats call returns both high_seqno and abs_high_seqno
> can't find any definitive documentation on it, but the reference on this ticket suggests that abs_high_seqno may be more correct for your purposes (comparing indexed to bucket state):
> https://issues.couchbase.com/browse/MB-13671

**Comment by tleyden** [comment] 2015-12-17 01:55
Failed run stats:
- Data bucket num docs cbsserver 10005
- Index bucket num docs cbsserver 10019

**Comment by tleyden** [comment] 2015-12-17 01:56
TODO: for http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/186/consoleFull, it seems that the reshard didn't work, and nothing is listening to those shards .. check logs and rest api

**Comment by tleyden** [comment] 2015-12-17 02:15
In [func test 186](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/186/) the system ended up in a state where we could examine it.

What happened is that the dcp shards were never re-assigned!  This is apparent by the [cbgt rest api output](https://gist.github.com/tleyden/7b52d18102ab8fafe9a3):
- It's listing [two nodedefsknown](https://gist.github.com/tleyden/7b52d18102ab8fafe9a3#file-gistfile1-txt-L69-L100), whereas it should only list one, since one is dead.
- [Some shards are being serviced by node 582e694c02484bf7](https://gist.github.com/tleyden/7b52d18102ab8fafe9a3#file-gistfile1-txt-L201)
- [Other shards are being serviced by node 4061db0541d6e0dd](https://gist.github.com/tleyden/7b52d18102ab8fafe9a3#file-gistfile1-txt-L1381)

Also, running this curl request repeatedly:

```
curl -X "POST" "http://172.23.106.186:4984/db/" \
    -H "Authorization: Basic dHJhdW46cGFzc3dvcmQ=" \
    -H "Content-Type: application/json" \
    -d "{\"hello\":\"world\",\"channels\":[\"ABC\"]}"
```

was only receiving DCP updates every other time on the remaining writer node, further confirming that half of the vbuckets were not having their DCP updates being monitored.

Next steps:
- Are we telling CBGT to reshard, and it's not doing it?
- Or are we not telling CBGT to reshard at all?

The logs in `/tmp/test_dcp_reshard.py-test_dcp_reshard_sync_gateway_goes_down-2015-12-16-17-38-07-sglogs.zip` will hopefully shed some light on this.

**Comment by tleyden** [comment] 2015-12-17 19:44
> Or are we not telling CBGT to reshard at all?

It's hard to tell due to lack of logging.

I'm seeing two heartbeat docs in couchbase server:
- _sync:heartbeat_timeout:4061db0541d6e0dd
- _sync:heartbeat:4061db0541d6e0dd

which is to be expected, since one writer node (node id 4061db0541d6e0dd) is still up and it's publishing it's heartbeat.  I can't tell if the other (now down) node ever published heartbeats or not.  

Rerunning with more logging.

**Comment by tleyden** [comment] 2015-12-17 20:34
I'm pretty sure I found the problem!  The :heartbeat: module is being invoked of an interval of 10 seconds, however it's waiting 10s before sending the first :heartbeat:.  The Sync Gateway process is being killed after 7 seconds, and so the first :heartbeat: is _never sent_, and so the other node never has an opportunity to detect that it stopped sending :heartbeat:'s .. since it never even started.

**Comment by tleyden** [comment] 2015-12-17 21:09
After commit https://github.com/couchbase/sync_gateway/commit/aae69b3f95d0c3776f462cb65aab8897f3ec9786 the situation has definitely improved, and now CBGT is being invoked to kick off the re-sharding.

However, it's still [panicking](https://gist.github.com/41edb7edc22e35678305).

```
2015/12/17 12:58:56 janitor: pindexes to add: 0
...skipping...
panic: Update attempted to set clock to earlier sequence.  Vb: 22, currentSequence: 2, newSequence: 1

goroutine 30217 [running]:
github.com/couchbase/sync_gateway/base.(*SequenceClockImpl).UpdateWithClock(0xc208454480, 0x7fb19b221d10, 0xc20a6f7260)
        /home/couchbase/jenkins/workspace/sync-gateway-dev-build/feature/issue_1259_dcp_reshard/community/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/base/sequence_clock.go:276 +0x29e
github.com/couchbase/sync_gateway/db.(*kvChannelIndex).writeClockCas(0xc2080d2300, 0x7fb19b221d10, 0xc20a6f7260, 0x0, 0x0)
```

also, there are many warnings about the high sequence number from the stable clock being higher than what's in the bucket:

```
2015-12-17T13:00:36.971-08:00 WARNING: issue_1259 highSeqnoFromStableClock (8) > highSeqnoFromBucket (6) for vb 881 -- base.(*SyncGatewayPIndex).SeedSeqnos() at sgw_pindex.go:130
2015-12-17T13:00:36.971-08:00 WARNING: issue_1259 highSeqnoFromStableClock (12) > highSeqnoFromBucket (6) for vb 964 -- base.(*SyncGatewayPIndex).SeedSeqnos() at sgw_pindex.go:130
2015-12-17T13:00:36.971-08:00 WARNING: issue_1259 highSeqnoFromStableClock (11) > highSeqnoFromBucket (6) for vb 802 -- base.(*SyncGatewayPIndex).SeedSeqnos() at sgw_pindex.go:130
2015-12-17T13:00:36.971-08:00 WARNING: issue_1259 highSeqnoFromStableClock (5) > highSeqnoFromBucket (3) for vb 734 -- base.(*SyncGatewayPIndex).SeedSeqnos() at sgw_pindex.go:130
2015-12-17T13:00:36.971-08:00 WARNING: issue_1259 highSeqnoFromStableClock (12) > highSeqnoFromBucket (7) for vb 982 -- base.(*SyncGatewayPIndex).SeedSeqnos() at sgw_pindex.go:130
2015-12-17T13:00:36.971-08:00 WARNING: issue_1259 highSeqnoFromStableClock (8) > highSeqnoFromBucket (6) for vb 1011 -- base.(*SyncGatewayPIndex).SeedSeqnos() at sgw_pindex.go:130
20
```

**Comment by tleyden** [comment] 2015-12-17 23:45
This functional  test had a panic, even after the cbheartbeat fix: http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/188/

**Comment by tleyden** [comment] 2015-12-17 23:59
Possible hand-wavey theory: DCP doesn't like to restart in between a snapshot

**Comment by tleyden** [comment] 2015-12-18 00:13
@steveyen -- trying to restart a DCP vbucket stream from a particular vbucket sequence, what do we need aside from the sequence number to be able to do that?  Does it require a failover value?  If so, what should that be.

Scenario:
- CBGT handover to a new SG node
- SG node trying to pick up where the old one left off
- What info do we need to have to able to do that?  Currently, all we have is sequence.
- In our sgw_index.go we are persisting the value of [OpaqueSet](https://github.com/couchbase/sync_gateway/blob/feature/distributed_index/src/github.com/couchbase/sync_gateway/base/sgw_pindex.go#L235) for the current SG node, but after a handover, the new SG node doesn't have access to that.. it only has the sequence.

**Comment by tleyden** [comment] 2015-12-18 00:18
> This functional test had a panic, even after the cbheartbeat fix

Current theory is that this panic is extremely sporadic, whereas the issue fixed with https://github.com/couchbase/sync_gateway/commit/aae69b3f95d0c3776f462cb65aab8897f3ec9786 was happening nearly every time.

**Comment by tleyden** [comment] 2015-12-18 00:26
Logs from the func test 188 panic: https://gist.github.com/f2e77ad69a59b7dc2c96

**Comment by tleyden** [comment] 2015-12-18 00:27
From @steveyen 

>  opaqueset has all the state (failover log, etc) needed by cbgt/cbdatasource in order to pickup where it left off.  Seqno isn't enough.

**Comment by tleyden** [comment] 2015-12-18 00:30
@steveyen it actually works for us fine 9 out of 10 times, any theories on that?

**Comment by tleyden** [comment] 2015-12-18 01:15
@steveyen moving the conversation over to https://github.com/couchbase/sync_gateway/issues/1371

**Comment by tleyden** [comment] 2015-12-18 23:01
Closing since https://github.com/couchbase/sync_gateway/issues/1370 has been merged.

**Closed as completed by tleyden** 2015-12-18 23:01 UTC
Labels: bug
