### ISSUE TITLE
sgcollect_info missing functionality on Windows

### ISSUE THREAD

**Issue by mattcarabine** [couchbase/sync_gateway#1931] opened 2016-07-02 16:36 UTC
I was looking at #1872 and realised that it is very difficult to perform the sanitisation on Windows due to the lack of utilities such as `sed`.

I then came to realisation that `sgcollect_info` on the whole has been written to work on Linux.

Some examples:

```
# Get static server config
    for sg_config_file in sg_config_files:
        task = AllOsTask(
            "sg config (%s)" % sg_config_file,
            "cat {}".format(sg_config_file),
            log_file=os.path.basename(sg_config_file),
        )
        collect_config_tasks.append(task)
```

Windows does not have `cat`, so this command will fail and it is pretty basic functionality

```
    for sg_log_file, path in sg_log_files.iteritems():
        task = AllOsTask(
            "sg logs (%s)" % sg_log_file,
            "cat {}".format(path),
            log_file=sg_log_file,
        )
        sg_tasks.append(task)
```

Again, on Windows this means that no log files will be collected.

```
def get_absolute_path(relative_path):

    try:
        sync_gateway_pid = subprocess.check_output(['pgrep', 'sync_gateway']).split()[0]
        sync_gateway_cwd = subprocess.check_output(['readlink', '-e', '/proc/{}/cwd'.format(sync_gateway_pid)]).strip('\n')
    except subprocess.CalledProcessError:
        sync_gateway_cwd = ''

    return os.path.join(sync_gateway_cwd, relative_path)
```

This code will not work on windows, although that's not such a big deal as `''` will be returned, which is fine.

```
    # Echo the command line args used to run sgcollect_info
    cmd_line_args_task = AllOsTask(
        "Echo sgcollect_info cmd line args",
        "echo options: {} args: ".format(options, args),
        log_file="sgcollect_info_options.log",
    )
```

Again, not sure this will work on Windows due to the use of echo.

---

These are just issues that I've noticed, I've not had a chance to test sgcollect on Windows yet although I shall now make it a priority.

The ideal situation will be to fix all of these issues prior to 1.3's release, although I am not sure of the timeframe, perhaps we could release sgcollect on Linux as part of 1.3 and then it gives us time to clean it up and fix it on Windows for 1.3.1 or 1.4.

**Comment by mattcarabine** [comment] 2016-07-02 16:39
It's worth noting that for the issues such as the lack of `cat` we can just create a Windows-specific task using `type` instead (this is what cbcollect does), so this should not be difficult to fix.

**Comment by mattcarabine** [comment] 2016-07-03 18:27
I've also realised that further to this, we do not look for the logs in the default Windows file locations... would someone from the sync gateway team mind letting me know where these are found by default?

**Comment by adamcfraser** [comment] 2016-07-04 20:03
@ajres Can you advise Matt on the Windows log locations?

**Comment by ajres** [comment] 2016-07-05 14:19
After looking at the SG service wrapper code and local Windows event logs where SG has been installed, it looks like the stdout and stderr are currently written to /dev/null on Windows.

The [service wrapper library](https://github.com/kardianos/service) SG uses supports redirecting stdout and stderr to files (in the examples).

Writing logs to disk will require changes to the SG Windows service wrapper classes.

**Comment by mattcarabine** [comment] 2016-07-05 14:33
Thanks @ajres, I think that's definitely something we should aim to add to 1.4 (or another future release) if possible as it is a very useful feature.

**Comment by mattcarabine** [comment] 2016-07-05 14:34
For now, I will just add a CLI flag to pass the path for the sync gateway log file, that way at least we can still collect logs on Windows.

**Comment by adamcfraser** [comment] 2016-07-12 20:13
@mattcarabine Can you post the full list of missing functionality below - we need to make a decision on whether we're going to leave it as-is for 1.3 or if it needs to get fixed.

**Comment by adamcfraser** [comment] 2016-07-12 20:14
Functionality not included in the Windows version of sgcollect_info:
- [ ] Including Sync Gateway logs (unless path is explicitly provided)
- [ ] Including Sync Gateway config (unless path is explicitly provided)
- [ ] Removing passwords from the Sync Gateway config

**Comment by mattcarabine** [comment] 2016-07-12 20:16
The config file won't be collected on Windows

**Comment by mattcarabine** [comment] 2016-07-13 11:32
Additionally, Windows is unable to use any 'curl' commands as unlike server we do not ship a version of curl (and it is not installed by default on Windows).

This is actually pretty critical as sgcollect relies heavily on being able to use curl to hit URLs and collect information - also to upload the log files.

**Comment by ajres** [comment] 2016-07-19 21:38
The stdout of running sgcollect_info on Windows from build 258, no .ZIP generated.

```
C:\Program Files (x86)\Couchbase\tools>sgcollect_info sgout.zip
Using Sync Gateway URL: http://127.0.0.1:4985
System information (systeminfo) - OK
Computer system (wmic computersystem) - OK
Computer OS (wmic os) - OK
Installed software (wmic product get name, version) - OK
Service list (wmic service where state="running" GET caption, name, state) - OK
Process list (wmic process) - OK
Process usage (tasklist /V /fo list) - OK
Swap settings (wmic pagefile) - OK
Disk partition (wmic partition) - OK
Disk volumes (wmic volume) - OK
Network configuration (ipconfig /all) - OK
Taking sample 2 after 10.000000 seconds - OK
Network status (netstat -ano) - OK
Network routing table (netstat -rn) - OK
Arp cache (arp -a) - OK
Network Interface Controller (wmic nic) - OK
Network Adapter (wmic nicconfig) - OK
Active network connection (wmic netuse) - OK
Protocols (wmic netprotocol) - OK
Hosts file (type %SystemRoot%\system32\drivers\etc\hosts) - OK
Cache memory (wmic memcache) - OK
Physical memory (wmic memphysical) - OK
Physical memory chip info (wmic memorychip) - OK
Local storage devices (wmic logicaldisk) - OK
Event log (wmic ntevent where "(LogFile='application' or LogFile='system') and E
ventType<3 and TimeGenerated>'20160618000000.000000-000'" get TimeGenerated,LogF
ile,SourceName,EventType,Message /FORMAT:list) - OK
Traceback (most recent call last):
  File "<string>", line 521, in <module>
  File "<string>", line 483, in main
  File "<string>", line 324, in get_paths_from_expvars
  File "<string>", line 332, in get_absolute_path
  File "subprocess.py", line 566, in check_output
  File "subprocess.py", line 710, in __init__
  File "subprocess.py", line 958, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
sgcollect_info returned -1
```

**Comment by tleyden** [comment] 2016-07-20 01:15
It looks like it's trying to call this code:

```

def get_absolute_path(relative_path):

    try:
        sync_gateway_pid = subprocess.check_output(['pgrep', 'sync_gateway']).split()[0]
        sync_gateway_cwd = subprocess.check_output(['readlink', '-e', '/proc/{}/cwd'.format(sync_gateway_pid)]).strip('\n')
    except subprocess.CalledProcessError:
        sync_gateway_cwd = ''

    return os.path.join(sync_gateway_cwd, relative_path)


```

which will certainly fail on windows

**Comment by tleyden** [comment] 2016-07-20 01:21
Ok I reproduced it on OSX by changing the code to call `sync_gateway_pid = subprocess.check_output(['invalid_binary', 'sync_gateway']).split()[0]`

And added exception handling to print an error rather than let the exception bubble up and break everything.

Pushed a fix as part of this PR: https://github.com/couchbase/sync_gateway/pull/1974

**Comment by tleyden** [comment] 2016-07-20 17:17
Closing this out since the bulk of work is done AFAIK.

@mattcarabine / @ajres please open new tickets for specific issues (or a single ticket with a github checklist listing the issues)

**Comment by ajres** [comment] 2016-07-20 17:18
Latest output from running sgcollect_info in Windows (build 259)

```
C:\Program Files (x86)\Couchbase\tools>sgcollect_info sgcollectinfo.zip
Using Sync Gateway URL: http://127.0.0.1:4985
System information (systeminfo) - OK
Computer system (wmic computersystem) - OK
Computer OS (wmic os) - OK
Installed software (wmic product get name, version) - OK
Service list (wmic service where state="running" GET caption, name, state) - OK
Process list (wmic process) - OK
Process usage (tasklist /V /fo list) - OK
Swap settings (wmic pagefile) - OK
Disk partition (wmic partition) - OK
Disk volumes (wmic volume) - OK
Network configuration (ipconfig /all) - OK
Taking sample 2 after 10.000000 seconds - OK
Network status (netstat -ano) - OK
Network routing table (netstat -rn) - OK
Arp cache (arp -a) - OK
Network Interface Controller (wmic nic) - OK
Network Adapter (wmic nicconfig) - OK
Active network connection (wmic netuse) - OK
Protocols (wmic netprotocol) - OK
Hosts file (type %SystemRoot%\system32\drivers\etc\hosts) - OK
Cache memory (wmic memcache) - OK
Physical memory (wmic memphysical) - OK
Physical memory chip info (wmic memorychip) - OK
Local storage devices (wmic logicaldisk) - OK
Event log (wmic ntevent where "(LogFile='application' or LogFile='system') and E
ventType<3 and TimeGenerated>'20160619000000.000000-000'" get TimeGenerated,LogF
ile,SourceName,EventType,Message /FORMAT:list) - OK
Exception trying to get absolute sync gateway path from expvars: [Error 2] The s
ystem cannot find the file specified
zip_dir: C:\Program Files (x86)\Couchbase\tools
Exception trying to get absolute sync gateway path from expvars: [Error 2] The s
ystem cannot find the file specified
Expvars sg_binary_path: C:\Program Files (x86)\Couchbase\\sync_gateway.exe sg_co
nfig_path: C:\Program Files (x86)\Couchbase\\serviceconfig.json
Command to collect pprof: go tool pprof -pdf -seconds=5 -output=C:\Program Files
 (x86)\Couchbase\tools\profile.pdf C:\Program Files (x86)\Couchbase\\sync_gatewa
y.exe http://127.0.0.1:4985/_debug/pprof/profile
Command to collect pprof: go tool pprof -text -seconds=5 -output=C:\Program File
s (x86)\Couchbase\tools\profile.text C:\Program Files (x86)\Couchbase\\sync_gate
way.exe http://127.0.0.1:4985/_debug/pprof/profile
Command to collect pprof: go tool pprof -raw -seconds=5 -output=C:\Program Files
 (x86)\Couchbase\tools\profile.raw C:\Program Files (x86)\Couchbase\\sync_gatewa
y.exe http://127.0.0.1:4985/_debug/pprof/profile
Command to collect pprof: go tool pprof -pdf -seconds=5 -output=C:\Program Files
 (x86)\Couchbase\tools\heap.pdf C:\Program Files (x86)\Couchbase\\sync_gateway.e
xe http://127.0.0.1:4985/_debug/pprof/heap
Command to collect pprof: go tool pprof -text -seconds=5 -output=C:\Program File
s (x86)\Couchbase\tools\heap.text C:\Program Files (x86)\Couchbase\\sync_gateway
.exe http://127.0.0.1:4985/_debug/pprof/heap
Command to collect pprof: go tool pprof -raw -seconds=5 -output=C:\Program Files
 (x86)\Couchbase\tools\heap.raw C:\Program Files (x86)\Couchbase\\sync_gateway.e
xe http://127.0.0.1:4985/_debug/pprof/heap
Command to collect pprof: go tool pprof -pdf -seconds=5 -output=C:\Program Files
 (x86)\Couchbase\tools\goroutine.pdf C:\Program Files (x86)\Couchbase\\sync_gate
way.exe http://127.0.0.1:4985/_debug/pprof/goroutine
Command to collect pprof: go tool pprof -text -seconds=5 -output=C:\Program File
s (x86)\Couchbase\tools\goroutine.text C:\Program Files (x86)\Couchbase\\sync_ga
teway.exe http://127.0.0.1:4985/_debug/pprof/goroutine
Command to collect pprof: go tool pprof -raw -seconds=5 -output=C:\Program Files
 (x86)\Couchbase\tools\goroutine.raw C:\Program Files (x86)\Couchbase\\sync_gate
way.exe http://127.0.0.1:4985/_debug/pprof/goroutine
Contents of /home\sg_accel\logs\sg_accel_error.log (pythontask) - log_file: sg_a
ccel_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/home\\sg
_accel\\logs\\sg_accel_error.log'
Exit code 1
Contents of /Users\sg_accel\logs\sg_accel_error.log (pythontask) - log_file: sg_
accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users\\s
g_accel\\logs\\sg_accel_error.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\sg_accel\logs\sg_
accel_error.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Progr
am Files (x86)\\Couchbase\\var\\lib\\couchbase\\sg_accel\\logs\\sg_accel_error.l
og'
Exit code 1
Contents of /home\sg_accel\logs\sg_accel_access.log (pythontask) - log_file: sg_
accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/home\\sg
_accel\\logs\\sg_accel_access.log'
Exit code 1
Contents of /Users\sg_accel\logs\sg_accel_access.log (pythontask) - log_file: sg
_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users\\s
g_accel\\logs\\sg_accel_access.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\sg_accel\logs\sg_
accel_access.log (pythontask) - log_file: sg_accel_access.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Progr
am Files (x86)\\Couchbase\\var\\lib\\couchbase\\sg_accel\\logs\\sg_accel_access.
log'
Exit code 1
Contents of /home\sync_gateway\logs\sync_gateway_access.log (pythontask) - log_f
ile: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/home\\sy
nc_gateway\\logs\\sync_gateway_access.log'
Exit code 1
Contents of /Users\sync_gateway\logs\sync_gateway_access.log (pythontask) - log_
file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users\\s
ync_gateway\\logs\\sync_gateway_access.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\sync_gateway\logs
\sync_gateway_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Progr
am Files (x86)\\Couchbase\\var\\lib\\couchbase\\sync_gateway\\logs\\sync_gateway
_access.log'
Exit code 1
Contents of /home\logs\sg_accel_error.log (pythontask) - log_file: sg_accel_erro
r.log.
Exception executing python task: [Errno 2] No such file or directory: '/home\\lo
gs\\sg_accel_error.log'
Exit code 1
Contents of /Users\logs\sg_accel_error.log (pythontask) - log_file: sg_accel_err
or.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users\\l
ogs\\sg_accel_error.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sg_accel_err
or.log (pythontask) - log_file: sg_accel_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Progr
am Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs\\sg_accel_error.log'
Exit code 1
Contents of /home\logs\sync_gateway_access.log (pythontask) - log_file: sync_gat
eway_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/home\\lo
gs\\sync_gateway_access.log'
Exit code 1
Contents of /Users\logs\sync_gateway_access.log (pythontask) - log_file: sync_ga
teway_access.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users\\l
ogs\\sync_gateway_access.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\logs\sync_gateway
_access.log (pythontask) - log_file: sync_gateway_access.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Progr
am Files (x86)\\Couchbase\\var\\lib\\couchbase\\logs\\sync_gateway_access.log'
Exit code 1
Contents of /home\sync_gateway\logs\sync_gateway_error.log (pythontask) - log_fi
le: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/home\\sy
nc_gateway\\logs\\sync_gateway_error.log'
Exit code 1
Contents of /Users\sync_gateway\logs\sync_gateway_error.log (pythontask) - log_f
ile: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: '/Users\\s
ync_gateway\\logs\\sync_gateway_error.log'
Exit code 1
Contents of C:\Program Files (x86)\Couchbase\var\lib\couchbase\sync_gateway\logs
\sync_gateway_error.log (pythontask) - log_file: sync_gateway_error.log.
Exception executing python task: [Errno 2] No such file or directory: 'C:\\Progr
am Files (x86)\\Couchbase\\var\\lib\\couchbase\\sync_gateway\\logs\\sync_gateway
_error.log'
Exit code 1
download_sg_expvars (pythontask) - log_file: expvars_json.log.
OK
Collecting sg pprof profile -- which can take several seconds: profile format: p
df (go tool pprof -pdf -seconds=5 -output=C:\Program Files (x86)\Couchbase\tools
\profile.pdf C:\Program Files (x86)\Couchbase\\sync_gateway.exe http://127.0.0.1
:4985/_debug/pprof/profile) - Exit code 1
Collecting sg pprof profile -- which can take several seconds: profile format: t
ext (go tool pprof -text -seconds=5 -output=C:\Program Files (x86)\Couchbase\too
ls\profile.text C:\Program Files (x86)\Couchbase\\sync_gateway.exe http://127.0.
0.1:4985/_debug/pprof/profile) - Exit code 1
Collecting sg pprof profile -- which can take several seconds: profile format: r
aw (go tool pprof -raw -seconds=5 -output=C:\Program Files (x86)\Couchbase\tools
\profile.raw C:\Program Files (x86)\Couchbase\\sync_gateway.exe http://127.0.0.1
:4985/_debug/pprof/profile) - Exit code 1
Collecting sg pprof profile -- which can take several seconds: heap format: pdf
(go tool pprof -pdf -seconds=5 -output=C:\Program Files (x86)\Couchbase\tools\he
ap.pdf C:\Program Files (x86)\Couchbase\\sync_gateway.exe http://127.0.0.1:4985/
_debug/pprof/heap) - Exit code 1
Collecting sg pprof profile -- which can take several seconds: heap format: text
 (go tool pprof -text -seconds=5 -output=C:\Program Files (x86)\Couchbase\tools\
heap.text C:\Program Files (x86)\Couchbase\\sync_gateway.exe http://127.0.0.1:49
85/_debug/pprof/heap) - Exit code 1
Collecting sg pprof profile -- which can take several seconds: heap format: raw
(go tool pprof -raw -seconds=5 -output=C:\Program Files (x86)\Couchbase\tools\he
ap.raw C:\Program Files (x86)\Couchbase\\sync_gateway.exe http://127.0.0.1:4985/
_debug/pprof/heap) - Exit code 1
Collecting sg pprof profile -- which can take several seconds: goroutine format:
 pdf (go tool pprof -pdf -seconds=5 -output=C:\Program Files (x86)\Couchbase\too
ls\goroutine.pdf C:\Program Files (x86)\Couchbase\\sync_gateway.exe http://127.0
.0.1:4985/_debug/pprof/goroutine) - Exit code 1
Collecting sg pprof profile -- which can take several seconds: goroutine format:
 text (go tool pprof -text -seconds=5 -output=C:\Program Files (x86)\Couchbase\t
ools\goroutine.text C:\Program Files (x86)\Couchbase\\sync_gateway.exe http://12
7.0.0.1:4985/_debug/pprof/goroutine) - Exit code 1
Collecting sg pprof profile -- which can take several seconds: goroutine format:
 raw (go tool pprof -raw -seconds=5 -output=C:\Program Files (x86)\Couchbase\too
ls\goroutine.raw C:\Program Files (x86)\Couchbase\\sync_gateway.exe http://127.0
.0.1:4985/_debug/pprof/goroutine) - Exit code 1
Contents of C:\Program Files (x86)\Couchbase\serviceconfig.json (pythontask) - l
og_file: serviceconfig.json.
OK
Contents of C:\Program Files (x86)\Couchbase\\serviceconfig.json (pythontask) -
log_file: serviceconfig.json.
OK
Collect server config (pythontask) - log_file: running_server_config.log.
OK
Collect db config for db: db (pythontask) - log_file: running_db_db_config.log.

OK
Collect server status (pythontask) - log_file: server_status.log.
OK
Collect db status for db: db (pythontask) - log_file: db_db_status.log.
OK
Echo sgcollect_info cmd line args (echo options: {'just_upload_into': None, 'syn
c_gateway_config': None, 'verbosity': 0, 'upload_ticket': None, 'sync_gateway_ur
l': None, 'upload_customer': None, 'upload_host': None, 'watch_stdin': False, 's
ync_gateway_executable': None, 'root': 'C:\\Program Files (x86)\\Couchbase', 'pr
oduct_only': False} args: ) - OK
Exception during compression: [Error 2] The system cannot find the file specifie
d
IMPORTANT:
  Compression using gozip failed.
  Falling back to python implementation.
  Please let us know about this and provide console output.
Traceback (most recent call last):
  File "<string>", line 519, in <module>
  File "<string>", line 510, in main
  File "tasks.py", line 288, in zip
  File "tasks.py", line 292, in _zip_fallback
  File "zipfile.py", line 778, in __init__
IOError: [Errno 13] Permission denied: 'sgcollectinfo.zip'
sgcollect_info returned -1
```

**Closed as completed by tleyden** 2016-07-20 17:17 UTC

**Comment by tleyden** [comment] 2016-07-20 17:22
@ajres can you open a separate a ticket for that last one and put the logs in a gist?  This ticket is getting a bit unwieldy
