### ISSUE TITLE
Write per second drastically reducing with custom syncgateway sync function

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2578] opened 2017-05-16 13:42 UTC
### Sync Gateway version
1.4.1
### Operating system
RedHat 7.2

### Setup Details on each of 2 cluster
3* CBS nodes
1* syncgateway
1* sg-accelerator
1* sg-replicator

syncgateway config with default sync configuration(No sync function mentioned)

  "maxFileDescriptors": 250000,
   "couchbaseKeepaliveInterval": 0,
 "databases":{
        "ptxdata":{
            "server":"http://cbs:8091",
            "bucket":"ptxdata",
            "channel_index": {
                    "server": "http://cbs:8091",
                    "bucket": "channelbucket"
                    },
            "revs_limit" : 60,
            "feed_type":"DCPSHARD"
       }
    }
	
 syncgateway config with custom sync function 

 "maxFileDescriptors": 250000,
   "couchbaseKeepaliveInterval": 0,
   "databases":{
        "ptxdata":{
            "server":"http://cbs:8091",
            "bucket":"ptxdata",
            "channel_index": {
                    "server": "http://cbs:8091",
                    "bucket": "channelbucket"
                    },
            "revs_limit" : 60,
            "feed_type":"DCPSHARD",
            "sync":`function(doc, oldDoc) {
			channel(doc.channels)
            }`
        }
    }

sg-accelerator configuration 

"cluster_config": {
        "server": "http://cbs:8091",
        "bucket": "ptxdata",
        "data_dir": "."
        },
   "maxFileDescriptors": 250000,
   "couchbaseKeepaliveInterval": 0,
   "databases":{
        "ptxdata":{
            "server":"http://cbs:8091",
            "bucket":"ptxdata",
            "channel_index": {
                    "writer": true,
                    "server": "http://cbs:8091",
                    "bucket": "channel_bucket"
                    },
            "revs_limit" : 60,
            }
        }

we have used sgload tool for testing. No reads involved in testing
We could see that syncgateway write per second was reaching to ~1600 to ~2000 with default syncgateway config mentioned above.

But when we add sync function in the configuration, we could see that writes per second is reaching ~230.
we could see no performance improvement after adding sg-accelerator. 
As per documentation we should see improvement in writes per seconds as but actual is not.

### Expected behavior
sg-accelerate should give improvement in write per second

### Actual behavior
No performance improvement using sg-accelerate

### Steps to reproduce
1.  setup as mentioned above
2.  run the traffic with and without accelerator(default and custom sync function) and observer writes per second

**Comment by ddash1** [comment] 2017-05-16 20:38
@adamcfraser @ssmotra 
Please advise.

**Comment by adamcfraser** [comment] 2017-05-16 20:44
The key benefit of sg-accelerator is that it allows you to horizontally scale your Sync Gateway cluster.  Without accel, each Sync Gateway node is working the full server mutation feed to build the channel cache, and higher system throughput results in each Sync Gateway node doing additional work.

This is not directly related to Sync Function execution - Sync Function processing occurs at write time, and not when the document is received over the mutation feed, and so is localized to the Sync Gateway node.

There is still a benefit to using sg-accel for this scenario - it would allow you to distributed the write work over more Sync Gateway nodes.  In your test deployment, with a single Sync Gateway node, you're not leveraging this benefit.

**Comment by ArihantRk** [comment] 2017-05-17 09:36
@adamcfraser 

setup details below
2 * syncgateway
2* syncgateway replicators
2* sg-accelerator

Below are the tests done
1. sg-acclratror with default sync function in syncgateway
2. sg-acclratror with custom sync function in syncgateway
"sync":function(doc, oldDoc) {  }
}

Find in syncgateway TPS with for above tests
![image](https://cloud.githubusercontent.com/assets/13716346/26146522/15b4093c-3b0e-11e7-930b-d9fd00547a72.png)

From the above it is clear that there is difference in mentioning explicit sync function in syncgateway configuration(with or without sg-acclrator) causing TPS rates down drastically from  ~1700 to ~230.


 Also with 2 syncgateway withput sg-acclrator , write per seconds was ~250
 but with bringing sg-acclrator we did not see any improvement in syncgateway TPS (writes per second ~240)compared with without syncgateway TPS.

**Comment by adamcfraser** [comment] 2017-05-18 16:30
Thanks for the additional information - will look into this.

**Comment by ajres** [comment] 2017-05-18 20:31
We have tried to reproduce this level of performance degradation using golang benchmark tests.

So far we have not observed the same behaviour using the default sync function and an explicitly defined version of the same function.

Tested against current git master

**Comment by ajres** [comment] 2017-05-19 17:18
Can you clarify the following:

You show two custom sync functions on the ticket, which one was used in testing:

`"sync":function(doc, oldDoc) { }`

or

`"sync":function(doc, oldDoc) { channel(doc.channels) }`

Can you provide the actual sgload command that you are running.

Can you provide more information on the test topology, the relationship between sgload, SG databases, CBS buckets and replication is not clear.

**Comment by ArihantRk** [comment] 2017-06-06 05:32
@ajres 
Setup details of both clusters below
3* CBS nodes
2* syncgateway
2* syncgateway replicators
2* sg-accelerators


Below is custom sync function used during the testing
"sync":function(doc, oldDoc) { }


**Traffic Tool**: sgload
sgload command ran during testing: 
sgload/bin/sgload gateload  --createreaders --createwriters --numupdaters 0 --numreaders 0 --numwriters 1000 --numdocs 350000 --numrevsperdoc 1 --batchsize 1 --numchannels 1 --docsizebytes 4096 --sg-url http://10.2.1.189:4984/ptxdata/ --writerdelayms 1000

syncgateway replicators are used for replication between both clusters. 


please find the below syncgateway,sg-replicator  and sg-accelerator configuration without sync function and with sync function we just added "sync":function(doc, oldDoc) { } into syncgateway and syncgateway replicator configuration

syncgateway configuration :

"maxFileDescriptors": 250000,
   "couchbaseKeepaliveInterval": 0,
   "databases":{
        "ptxdata":{
            "server":"http://cbs:8091",
            "bucket":"ptxdata",
            "channel_index": {
                    "server": "http://cbs:8091",
                    "bucket": "channelbucket"
                    },
            "revs_limit" : 60,
            "feed_type":"DCPSHARD"
       }
    }
	
sg-replicator configuration:

 "replications":[
   {
               "replication_id":"rep1-2",
               "source": "ptxdata",
               "target": "http://syncrepfqdn:4985/ptxdata/",
               "continuous":true,
               "changes_feed_limit":1000
    }],
    "maxFileDescriptors": 250000,
    "databases":{
        "ptxdata":{
            "server":"http://cbs:8091",
            "bucket":"ptxdata",
            "revs_limit" : 60,
            "channel_index": {
                    "server": "http://cbs:8091",
                    "bucket": "channelbucket"
                    },
            "feed_type" : "DCPSHARD"
            }
        }

	
	
sg-accelerator configuration:

"cluster_config": {
        "server": "http://cbs::8091",
        "bucket": "ptxdata",
        "data_dir": "."
        },
   "maxFileDescriptors": 250000,
   "couchbaseKeepaliveInterval": 0,
   "databases":{
        "ptxdata":{
            "server":"http://cbs:8091",
            "bucket":"ptxdata",
            "channel_index": {
                    "writer": true,
                    "server": "http://cbs:8091",
                    "bucket": "channel_bucket"
                    },
            "cache": {
                    "max_wait_pending" : 30000,
                    "channel_cache_max_length": 50,
                    "channel_cache_min_length": 10
                    },
            "revs_limit" : 60,
            }
        }

**Comment by ajres** [comment] 2017-06-06 13:29
@Arihant

Thank you for the additional info, this makes the test environment configuration a lot clearer.

Andy

**Comment by ajres** [comment] 2017-06-06 17:00
@ArihantRK

Is the sg_replicate target DB (http://syncrepfqdn:4985/ptxdata/) specifically the SG-Replicate instance on the other cluster?

**Comment by ajres** [comment] 2017-06-06 17:07
![sg issue 2578 - architecture](https://user-images.githubusercontent.com/7745210/26842408-a580ae22-4ae4-11e7-8257-c969a3636fed.png)

**Comment by ArihantRk** [comment] 2017-06-07 04:26
@ajres thanks for the quick one.

 Is the sg_replicate target DB (http://syncrepfqdn:4985/ptxdata/) specifically the SG-Replicate instance on the other cluster?
**-->**  yes. replication is between sg-replicators. target is FQDN of other cluster sg-replicator node.

Diagram is exactly is our deployment model.

**Comment by ajres** [comment] 2017-06-16 18:06
Running the above scenario on a single MacBook Pro, give the following results:

Default Sync Function: 

sgload writes at average  800 documents/sec

Custom Sync Function: "sync":function(doc, oldDoc) { } 

sgload writes at average  222 documents/sec

When running with the default sync function the number of retries does not exceed 2. When using the custom sync function, there are a higher number of retries (up to 6 observed) in the sgload log.

`WARN[06-16|19:24:32] HttpClientRetry                          url="http://localhost:4985/ptxdata/0-writer-user-595-11ac532c-4561-4dac-89c1-586576931b2e?new_edits=true" numAttempts=4`

When using a custom function also observe the following panic in sgload after approx 55000 docs.

```
panic: Error creating doc in datastore.  Doc: map[body:map[field_8:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_33:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_38:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_28:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_35:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_39:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_19:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_20:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_27:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_34:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_3:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_7:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_14:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_17:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_0:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_24:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_29:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_13:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_18:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_37:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_40:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_15:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_22:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_23:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_25:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_2:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_9:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_10:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_12:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_26:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_30:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_32:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_36:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_5:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_31:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_21:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_4:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_6:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_11:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa field_16:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa] _id:19-writer-user-327-11ac532c-4561-4dac-89c1-586576931b2e per_writer_doc_counter:19 bodysize:4096 created_at:2017-06-16T19:24:47.732734339+01:00 channels:[0-11ac532c-4561-4dac-89c1-586576931b2e]], Err: PUT http://localhost:4985/ptxdata/19-writer-user-327-11ac532c-4561-4dac-89c1-586576931b2e?new_edits=true giving up after 11 attempts

goroutine 442 [running]:
panic(0x426060, 0xc4223981f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbaselabs/sgload/sgload.(*Writer).Run(0xc420247bc0)
	/Users/andy/projects/go/src/github.com/couchbaselabs/sgload/sgload/writer.go:73 +0xabb
created by github.com/couchbaselabs/sgload/sgload.GateLoadRunner.startWriters
	/Users/andy/projects/go/src/github.com/couchbaselabs/sgload/sgload/gateload_runner.go:235 +0x1d0
```

**Comment by ajres** [comment] 2017-08-09 17:43
The performance improvement seen when using the default sync function vs the same code provided as an explicit sync function in the sync_gateway config is due to a difference in processing.

When using the default sync function no javascript interpreter is invoked, instead SG uses the channels property (if it exists) directly from the parsed document body.

see: https://github.com/couchbase/sync_gateway/blob/master/db/crud.go#L1090

**Comment by ajres** [comment] 2017-08-09 17:49
There is a community PR, which provides a solution to reduce the overhead of parsing the sync function JavaScript callback methods on every document revision.

Running the above load scenario with the PR fix merged, yields a 10-15% improvement in throughput.

**Closed as completed** 2017-08-10 22:23 UTC
Labels: bug, performance, P1: high, ffc
