### ISSUE TITLE
output_directory parameter is ignored on sg_collectinfo rest end point

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3559] opened 2018-05-11 19:07 UTC
### Sync Gateway version
2.1.0-82

### Operating system
Centos

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "logging":{
        "redaction_level": "partial"
    },
    "databases":{
        "db":{
            "import_docs": "continuous",
            "enable_shared_bucket_access": true,


            "num_index_replicas": 0,
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "password": "password"
        }
    }
}

```

### Log output
2018-05-10T12:38:55.895Z [INF] HTTP:  #100: POST <ud>/_sgcollect_info</ud> (as ADMIN)
2018-05-10T12:38:55.909Z [INF] Admin: sgcollect_info started with args: <ud>[--log-redaction-level partial --log-redaction-salt salting the customized --sync-gateway-executable /opt/couchbase-sync-gateway/bin/sync_gateway sgcollectinfo-2018-05-10t123855-sg@10.0.2.15.zip]</ud>

### Steps to reproduce
1.  Run this curl command : 
curl -X POST http://192.168.33.11:4985/_sgcollect_info -H 'Content-Type: application/json' -d '{"redact_level": "partial", "output_directory":"/home/test.zip", "redact_salt": "salting the customized"}'
2.  wait until sgcollect_info status says stopped

### Expected behavior
It should create zip file on the output_directory mentioned

### Actual behavior
output_directory parameter is ignored and it saves file on default location 
On Centos : /home/sync_gateway
Default files created under /home/sync_gateway : sgcollectinfo-2018-05-10t123855-sg@10.0.2.15-redacted.zip
sgcollectinfo-2018-05-10t123855-sg@10.0.2.15.zip

**Comment by sridevi-15** [comment] 2018-05-11 20:47
After discussing with Adam, I got the right parameter for output directory which I used output_dir. I used just folder name by removing zip file . 
'''
curl -X POST http://192.168.33.11:4985/_sgcollect_info -H 'Content-Type: application/json' -d '{"redact_level": "partial", "output_dir":"/home", "redact_salt": "salting the customized"}'
'''
It mentioned the args in sg logs , but do not see zip file at /home

**Comment by sridevi-15** [comment] 2018-05-16 19:27
Just wondering, is this change  pushed to build 94? I see that sg_collect info fails when output_dir is passed.
I enabled debug log level and log key Admin, I do not see anything on sg_info other than this

```
2018-05-11T23:16:14.233Z ==== Couchbase Sync Gateway/2.1.0(94;3385b25) ====
2018-05-11T23:16:14.233Z [INF] Console LogKeys: [Admin HTTP]
2018-05-11T23:16:14.233Z [INF] Console LogLevel: debug
2018-05-11T23:16:14.233Z [INF] Log Redaction Level: partial
2018-05-11T23:16:14.233Z [INF] requestedSoftFDLimit >= currentHardFdLimit (90000 >= 65535) capping at 65535
2018-05-11T23:16:14.233Z [INF] Configured process to allow 65535 open file descriptors
2018-05-11T23:16:14.233Z [INF] Opening db /db as bucket "data-bucket", pool "default", server <http://192.168.33.10:8091>
2018-05-11T23:16:14.233Z [INF] GoCBCustomSGTranscoder Opening Couchbase database data-bucket on <http://192.168.33.10:8091> as user "<ud>data-bucket</ud>"
2018-05-11T23:16:14.233Z [INF] Auth: Attempting credential authentication http://192.168.33.10:8091?http_idle_conn_timeout=90000&http_max_idle_conns=64000&http_max_idle_conns_per_host=256
2018-05-11T23:16:14.243Z [INF] Successfully opened bucket
2018-05-11T23:16:14.248Z [INF] Initializing indexes with numReplicas: 0...
2018-05-11T23:16:14.324Z [INF] Verifying index availability for bucket data-bucket...
2018-05-11T23:16:14.334Z [INF] Indexes ready for bucket data-bucket.
2018-05-11T23:16:14.335Z [INF] Cache: Initializing changes cache with options {ChannelCacheOptions:{ChannelCacheMinLength:0 ChannelCacheMaxLength:0 ChannelCacheAge:0s} CachePendingSeqMaxWait:5s CachePendingSeqMaxNum:10000 CacheSkippedSeqMaxWait:1h0m0s}
2018-05-11T23:16:14.335Z [INF] Initializing changes cache for database <ud>db</ud> with sequence: 11
2018-05-11T23:16:14.335Z [INF] DCP: Starting mutation feed on bucket data-bucket due to either channel cache mode or doc tracking (auto-import/bucketshadow)
2018-05-11T23:16:14.335Z [INF] DCP: Using DCP feed for bucket: "<ud>data-bucket</ud>" (based on feed_type specified in config file)
2018-05-11T23:16:14.386Z [INF] Using metadata purge interval of 3.00 days for tombstone compaction.
2018-05-11T23:16:14.398Z [INF] Using default sync function 'channel(doc.channels)' for database "db"
2018-05-11T23:16:14.398Z [INF] Starting admin server on <ud>0.0.0.0:4985</ud>
2018-05-11T23:16:14.403Z [INF] Starting server on <ud>:4984</ud> ...
2018-05-11T23:16:14.438Z [INF] DCP: Backfill in progress: 13% (7 / 53)
2018-05-11T23:16:14.439Z [INF] DCP: Backfill complete




2018-05-11T23:16:32.944Z [INF] HTTP:  #001: POST /_sgcollect_info (as ADMIN)
2018-05-11T23:16:32.959Z [INF] Admin: sgcollect_info started with args: <ud>[--log-redaction-level partial --sync-gateway-executable /opt/couchbase-sync-gateway/bin/sync_gateway /home/vagrant/sgcollectinfo-2018-05-11t231632-sg@10.0.2.15.zip]</ud>
2018-05-11T23:16:32.959Z [INF] HTTP+: #001:     --> 200   (15.7 ms)
2018-05-11T23:16:33.097Z [WRN] Admin: sgcollect_info failed after 103.687ms with reason: exit status 1. Check debug logs with log key 'Admin' for more detail. -- rest.(*sgCollect).Start.func2() at sgcollect.go:94


```

This is the curl request I used
curl -v -X POST http://192.168.33.11:4985/_sgcollect_info -H 'Content-Type: application/json' -d '{"redact_level": "partial", "upload": false, "output_dir": "/home/vagrant"}'

**Comment by bbrks** [comment] 2018-05-16 20:29
@sridevi-15 does this happen *only* when output_dir is specified?

- What about a different directory, like `/tmp`? I suspect file permissions on /home/vagrant don't allow the sync_gateway user to write there.
- What if you run the sgcollect_info tool manually using the same parameters? What do you see?
`./tools/sgcollect_info --log-redaction-level partial --sync-gateway-executable /opt/couchbase-sync-gateway/bin/sync_gateway /home/vagrant/sgcollectinfo-2018-05-11t231632-sg@10.0.2.15.zip`

It's strange that there's no output from sgcollect_info at Debug level with the Admin Log Key, but the python script is definitely exiting with a non-zero exit code.

**Comment by sridevi-15** [comment] 2018-05-17 06:06
@bbrks : 

- I tried with /tmp, it works fine with /tmp, some how it does not work with /home/vagrant (vagrant is a user to my vm machine)

- I tried with sg_collect_tool, it works with /tmp and /home/vagrant and I do not see any issue with tool. I tried same command that you gave and it worked fine with tool

**Comment by adamcfraser** [comment] 2018-05-17 07:16
@sridevi-15 Can you confirm that you ran the sg_collect_tool as the sync_gateway user?

**Comment by sridevi-15** [comment] 2018-05-17 21:08
I ran the tool as a sync_gateway user and it shows error that it does not have permission. Earlier I tried the tool as  a root user and that is why it did not have any issues with permissions. So, is rest end point uses sync_gateway user? though I enabled log level debug, I did not see  any information about permissions and why it failed

**Comment by bbrks** [comment] 2018-05-17 21:14
The rest endpoint will run sgcollect_info as the sync_gateway user. Also worth noting that the rest endpoint for sgcollect_info will not work on CentOS6 due to #2598  

I will test debug-level sgcollect_info log output again tomorrow.

**Comment by tleyden** [comment] 2018-05-17 21:16
@bbrks looks like the centos6 issues got resolved in https://github.com/couchbase/sync_gateway/issues/2598#issuecomment-306961907 / https://github.com/couchbase/sync_gateway/commit/d2c9607069c9d37818b478d135519d1d93e4d3b2

**Comment by adamcfraser** [comment] 2018-05-17 21:17
@bbrks On the log output question - do we have any early documentation on how to view the sgcollect output in the SG logs?  I think it makes sense to include that in our official docs for the sgcollect REST API, and it sounds like it would be useful for QE here.  I'm thinking of details like "To see the sgcollect results, set your logging config to [x] and look in file [y]"

**Comment by bbrks** [comment] 2018-05-17 21:58
@tleyden that commit fixed issues with the older python version, but the rest endpoint is kicking off the compiled binary, which wasn't compiled with a compatible libc library for CentOS6. The workaround was to download the python script and run it.

**Comment by bbrks** [comment] 2018-05-17 21:59
@adamcfraser Debug log level and "Admin" log key should output sgcollect_info stdout line by line to the console and the debug log file (if enabled) as it is running.

**Comment by bbrks** [comment] 2018-05-18 13:40
@sridevi-15 I confirmed `sgcollect_info` output is fed back into debug level Admin log key under these different scenarios:

- Normal run
- Invalid ticket number
- Non-writable output_dir

<img width="1386" alt="screen shot 2018-05-18 at 14 39 30" src="https://user-images.githubusercontent.com/1525809/40237790-50b0c6cc-5aa9-11e8-90f4-f14a84b78886.png">

**Closed as completed** 2018-06-04 17:49 UTC
Labels: bug, in progress
