### ISSUE TITLE
Inbound REST calls which reset can prevent offline from draining

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1527] opened 2016-01-27 23:17 UTC
Curl request:

```
$ curl -X POST http://ec2-54-145-244-2.compute-1.amazonaws.com:4985/todolite12rc2b-cc/_offline

```

(^^^ blocks for a long time)

[SG logs](https://gist.github.com/tleyden/2e9292a59e13f79ea17d)

DB state:

```
curl http://ec2-54-145-244-2.compute-1.amazonaws.com:4985/todolite12rc2b-cc/

{
committed_update_seq: 390,
compact_running: false,
db_name: "todolite12rc2b-cc",
disk_format_version: 0,
instance_start_time: 1453933328760928,
purge_seq: 0,
state: "Stopping",
update_seq: 390
}
```

**Comment by tleyden** [comment] 2016-01-27 23:18
Going to `http://ec2-54-145-244-2.compute-1.amazonaws.com:4985/todolite12rc2b-cc/_changes` hangs rather than returning a 503

**Comment by tleyden** [comment] 2016-01-27 23:32
[SG logs after sending SIGQUIT](https://gist.github.com/tleyden/0de0a064a4ff9dc58cf1)

**Comment by adamcfraser** [comment] 2016-01-28 04:07
There are 11 goroutines in those SG logs that are blocked at https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/change_listener.go#L149, but I'm not sure whether that's expected.  @ajres?

**Comment by ajres** [comment] 2016-01-28 16:59
No, the change listener waiters should get released after each change is closed out.

I have found one issue, that might be indirectly related to this ticket, for an admin user the Wait sync.Cond never gets Broadcst called.

From the logs for this ticket, the _changes feeds were closed for each client, and the reason was the _offline API call.

After each _changes feed is closed, a Broadcast should be sent to the Wait sync.Cond to cause all the waiters to cycle, but this did not happen, still investigating.

It's not clear that this issue would cause the _offline to block, there may still be another underlying cause for that.

**Comment by ajres** [comment] 2016-01-29 00:25
The HTTP request line is not called until after the attempt to get the ReadLock, this means that if there is a deadlock between requests we wont see non Offline requests in the log.

**Comment by adamcfraser** [comment] 2016-01-29 00:52
From the stack trace after the SIGQUIT:

goroutine 9093 is waiting for the AccessLock write lock, and has been waiting 20 minutes at the time of the SIGQUIT.

goroutine 994 has the readlock, and looks like it's hung partway through an attachment upload.  Looks like possibly a client disconnected midway through the PUT, and SG hasn't detected the half-closed connection.  994 has been waiting for 57 minutes at the time of the SIGQUIT.

```
goroutine 994 [IO wait, 57 minutes]:
net.runtime_pollWait(0x7f9a921a4250, 0x72, 0xc82000e150)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8204798e0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204798e0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820479880, 0xc82182c000, 0x1000, 0x1000, 0x0, 0x7f9a9216d050, 0xc82000e150)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc821057158, 0xc82182c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc821843a68, 0xc82182c000, 0x1000, 0x1000, 0x560, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc821c22660, 0xc82182c000, 0x1000, 0x1000, 0x560, 0x0, 0x0)
    /usr/local/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc8217f0000)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8217f0000, 0xc822ad3e8b, 0x175, 0x175, 0x560, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:207 +0x260
io.(*LimitedReader).Read(0xc822aeef20, 0xc822ad3e8b, 0x175, 0x175, 0xc821b10c58, 0x0, 0x0)
    /usr/local/go/src/io/io.go:427 +0xbd
net/http.(*body).readLocked(0xc8206f6480, 0xc822ad3e8b, 0x175, 0x175, 0x560, 0x0, 0x0)
    /usr/local/go/src/net/http/transfer.go:632 +0x98
net/http.(*body).Read(0xc8206f6480, 0xc822ad3e8b, 0x175, 0x175, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transfer.go:624 +0x110
bufio.(*Reader).fill(0xc822abfd40)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc822abfd40, 0x1000, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
mime/multipart.partReader.Read(0xc821b5f220, 0xc822e0de00, 0x4000, 0x4000, 0x0, 0x0, 0x0)
    /usr/local/go/src/mime/multipart/multipart.go:156 +0x146
mime/multipart.(*Part).Read(0xc821b5f220, 0xc822e0de00, 0x4000, 0x4000, 0xe78, 0x0, 0x0)
    /usr/local/go/src/mime/multipart/multipart.go:137 +0x6d
bytes.(*Buffer).ReadFrom(0xc8235f3010, 0x7f9a9032d920, 0xc821b5f220, 0x3e00, 0x0, 0x0)
    /usr/local/go/src/bytes/buffer.go:173 +0x23f
io/ioutil.readAll(0x7f9a9032d920, 0xc821b5f220, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/ioutil/ioutil.go:33 +0x154
io/ioutil.ReadAll(0x7f9a9032d920, 0xc821b5f220, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/io/ioutil/ioutil.go:42 +0x51
github.com/couchbase/sync_gateway/db.ReadMultipartDocument(0xc8203e5900, 0xc8203e5900, 0x0, 0x0)
    /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/db/attachment.go:338 +0x775
github.com/couchbase/sync_gateway/rest.(*handler).readDocument(0xc820a60c60, 0xd81730, 0x0, 0x0)
    /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:387 +0xd87
github.com/couchbase/sync_gateway/rest.(*handler).handlePutDoc(0xc820a60c60, 0x0, 0x0)
    /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/doc_api.go:233 +0x85
github.com/couchbase/sync_gateway/rest.(*handler).invoke(0xc820a60c60, 0xfc1c88, 0x0, 0x0)
    /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/handler.go:201 +0x7b4
github.com/couchbase/sync_gateway/rest.makeHandler.func1(0x7f9a92180c58, 0xc822ae69a0, 0xc822dfce00)
    /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/habler.go:90 +0x77
net/http.HandlerFunc.ServeHTTP(0xc820492c00, 0x7f9a92180c58, 0xc822ae69a0, 0xc822dfce00)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82043a460, 0x7f9a92180c58, 0xc822ae69a0, 0xc822dfce00)
    /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/gorilla/mux/mux.go:86 +0x2a6
github.com/couchbase/sync_gateway/rest.wrapRouter.func1(0x7f9a92180c58, 0xc822ae69a0, 0xc822dfce00)
    /home/couchbase/jenkins/workspace/sync-gateway-unix-builds/0.0.0/enterprise/app-under-test/sync_gateway/src/github.com/couchbase/sync_gateway/rest/routing.go:301 +0x32d
net/http.HandlerFunc.ServeHTTP(0xc8204b14e0, 0x7f9a92180c58, 0xc822ae69a0, 0xc822dfce00)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc820491da0, 0x7f9a92180c58, 0xc822ae69a0, 0xc822dfce00)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc821843a20)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by adamcfraser** [comment] 2016-01-29 01:14
Based on the stack trace above, the root cause appears to be a half-closed client PUT doc operation (with attachments), that's still holding the read lock.  The DB _offline is going to block until that half-closed connection gets released by Sync Gateway.

Currently we're only closing half-closed connections (using CloseNotifier) for changes requests.  To address this issue, we could add the CloseNotifier handling for all operations that have the potential to have an open ioutil.ReadAll.

**Comment by ajres** [comment] 2016-02-02 18:01
Following code paths the following REST API handlers use ioutil.ReadAll
- [ ] handleCreateTarget
- [ ] handlePostDoc
- [ ] handlePutDoc
- [ ] handleDBOnline
- [ ] handleSetLogging
- [ ] putRole
- [ ] putUser
- [ ] handleHeapProfiling
- [ ] handleProfiling
- [ ] handleChanges
- [ ] handlePutAttachment
- [ ] handlePersonaPost
- [ ] handler.invoke() (calling downstream to CBS)

**Comment by ajres** [comment] 2016-02-02 18:53
Next step is to create a unit test to repro the original issue.

**Comment by ajres** [comment] 2016-02-12 18:05
I have written a unit test that terminates a client connection before all data has been read from the request input stream in SG.

So far I haven't reproduced the same blocked reader deadlock seen in the original goroutine dump.

This is likely a timing issue.

**Comment by adamcfraser** [comment] 2020-02-07 01:06
Closing based on age, and lack of repro scenario.

**Closed as completed by adamcfraser** 2020-02-07 01:06 UTC
Labels: bug, icebox
