### ISSUE TITLE
Unable to start sync_gateway service after installation of Sync Gateway 2.0 Beta on Ubuntu14 via dpkg

### ISSUE THREAD

**Issue by anne-couchbase** [couchbase/sync_gateway#3339] opened 2018-02-26 23:22 UTC
### Sync Gateway version
Sync Gateway 2.0 Beta

### Operating system
Ubuntu14

On Ubuntu14, the installation of Sync Gateway 2.0 Beta (`couchbase-sync-gateway-enterprise_2.0.0-beta1_x86_64.deb`) via dpkg appears to have been successful:

```
$ sudo dpkg -i couchbase-sync-gateway-enterprise_2.0.0-beta1_x86_64.deb 
Selecting previously unselected package couchbase-sync-gateway.
(Reading database ... 67236 files and directories currently installed.)
Preparing to unpack couchbase-sync-gateway-enterprise_2.0.0-beta1_x86_64.deb ...
Unpacking couchbase-sync-gateway (2.0.0-773) ...
Setting up couchbase-sync-gateway (2.0.0-773) ...
sync_gateway start/pre-start, process 3014

You have successfully installed Couchbase Sync Gateway.

You can find sample sync_gateway configuration files in the /opt/couchbase-sync-gateway/examples folder.

You can control the Couchbase Sync Gateway service by using the following command:

  service sync_gateway start

That's it! Sync Gateway is now running on port 4984. We've setup a simple in-memory database
which works great for exploring Sync Gateway's capabilities. A limited console is available
by opening your browser to http://localhost:4985/_admin/.

The command-line options are:

  -adminInterface=":4985": Address to bind admin interface to
  -bucket="sync_gateway": Name of bucket
  -dbname="": Name of CouchDB database (defaults to name of bucket)
  -interface=":4984": Address to bind to
  -log="": Log keywords, comma separated
  -personaOrigin="": Base URL that clients use to connect to the server
  -pool="default": Name of pool
  -pretty=false: Pretty-print JSON responses
  -url="walrus:": Address of Couchbase server
  -verbose=false: Log more info about requests


By using this software you agree to the End User License Agreement.
See /opt/couchbase-sync-gateway/LICENSE.txt.

```

After installation, Sync Gateway was not started, and /home/sync_gateway/logs/sync_gateway_error.log shows only:

```
start-stop-daemon: --start needs --exec or --startas
Try 'start-stop-daemon --help' for more information.
start-stop-daemon: --start needs --exec or --startas
Try 'start-stop-daemon --help' for more information.
start-stop-daemon: --start needs --exec or --startas
Try 'start-stop-daemon --help' for more information.
start-stop-daemon: --start needs --exec or --startas
Try 'start-stop-daemon --help' for more information.
start-stop-daemon: --start needs --exec or --startas
Try 'start-stop-daemon --help' for more information.
start-stop-daemon: --start needs --exec or --startas
Try 'start-stop-daemon --help' for more information.
start-stop-daemon: --start needs --exec or --startas
Try 'start-stop-daemon --help' for more information.
start-stop-daemon: --start needs --exec or --startas
Try 'start-stop-daemon --help' for more information.
start-stop-daemon: --start needs --exec or --startas
Try 'start-stop-daemon --help' for more information.
start-stop-daemon: --start needs --exec or --startas
Try 'start-stop-daemon --help' for more information.
start-stop-daemon: --start needs --exec or --startas
Try 'start-stop-daemon --help' for more information.
```

The generated init script `/etc/init/sync_gateway.conf` does not set the `$PIDFILE` environment variable:

`env PIDFILE=
`

As a result, Sync Gateway will fail to start automatically at boot and with `service sync_gateway start` command.

Fixing this involved changing the appropriate line in `/etc/init/sync_gateway.conf` to:

`env PIDFILE=/var/run/sync-gateway.pid
`

**Comment by adamcfraser** [comment] 2018-02-26 23:40
This sounds like a duplicate of https://github.com/couchbase/sync_gateway/issues/3300.  Has been fixed post-beta.

**Closed as completed** 2018-02-26 23:42 UTC
Labels: P1: high
