### ISSUE TITLE
SG-Replicator throughput is not increasing with SG-Accelerator

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2536] opened 2017-05-08 11:28 UTC
### Sync Gateway version
1.4.1

### Operating system
RedHat 7.2

### Config file
"server":"http://prod-CBS-V1.service.com:8091",
            "bucket":"data",
            "channel_index": {
                    "server": "http://prod-CBS-V1.service.com:8091",
                    "bucket": "channelbucket"
                    },
            "revs_limit" : 60,
            "feed_type":"DCPSHARD",

No syncfunction mentioned.

###Setup Details
2* syncgateway
3*CBS nodes
1*replicator(* channel based replication)
1*sg-accelerator

### Expected behavior
After adding sg-accelerator replication should be faster and throughput should increase with scaling of sg-replicators

### Actual behavior
No performance improvement in sg-replication after adding sg-accelerator.
Even after scaling sg-replicator throughput is not increasing

### Steps to reproduce
1.  observe the throughput of sg-replicator with setup as mentioned above without and with sg-accel. could see no improvement in replicator throughput
2.  Add 1 sg-replicator and observer throughput

**Comment by ddash1** [comment] 2017-05-08 15:02
@adamcfraser @ssmotra Can you please advise?

**Comment by adamcfraser** [comment] 2017-05-08 17:03
When you say 'replicator' are you referring to sg-to-sg replication, or SG-to-couchbase-lite replication?

**Comment by ddash1** [comment] 2017-05-08 19:02
sg-to-sg replication using sg-replicate

**Comment by adamcfraser** [comment] 2017-05-26 18:55
Seems like duplicate of https://github.com/couchbase/sync_gateway/issues/2535 - see comments there.

**Closed as completed by adamcfraser** 2017-05-26 18:55 UTC
Labels: performance, ffc

**Comment by ArihantRk** [comment] 2017-06-01 09:36
This is separate issue from 2535.

We have 2 clusters, with 2 syncgateway  and 3 CBS nodes in each cluster and we are using sg-replicator to replicate between clusters.
When we add SG-accelerator to the cluster, sync gw replicator throughput is not increasing and does not see any improvement compared without sg-accelerator.
