### ISSUE TITLE
sync_gateway will intermittently take 1+ min to launch

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1333] opened 2015-12-08 01:36 UTC
Below are the logs (3 sync_gateways),

This was using CB server (4.1.0-4940 Enterprise Edition (build-4940))
Couchbase Sync Gateway/master(6b72a30)

All three were launched at the same time but 172-23-122-251 took over a minute. 

I believe this line may highlight the cause
https://gist.github.com/sethrosetter/2d4736f56ce25e9e0b74#file-172-23-122-251-log-L13

I will continue try the same scenario against CBS 3.1.1 and see I can reproduce the issue there.

**Comment by sethrosetter** [comment] 2015-12-08 01:41
Just for comparison:

https://gist.github.com/sethrosetter/2d4736f56ce25e9e0b74#file-172-23-122-251-log-L13 - 1m 5s
https://gist.github.com/sethrosetter/2d4736f56ce25e9e0b74#file-172-23-122-252-log-L13 - 5s
https://gist.github.com/sethrosetter/2d4736f56ce25e9e0b74#file-172-23-122-253-log-L13 - 1.5s

**Comment by adamcfraser** [comment] 2015-12-08 01:44
As seen in the logs - the root cause is a slow view call against the Principals view.  Given that the view call is being made against an empty bucket, it's unclear why the view call would take that long.

**Comment by sethrosetter** [comment] 2015-12-09 02:33
To follow up, I saw this behavior against CBS 3.1.1-1807 Enterprise Edition (build-1807) so it does not appear to be a regression. 

https://gist.github.com/sethrosetter/9a07a82cb92a5fe5f9f7#file-172-23-122-252-log-L18

**Comment by adamcfraser** [comment] 2015-12-09 06:37
I've never seen this issue testing locally, or heard it reported from the field, so I'm wondering whether it's a potential issue with the test harness.  I suppose it could be related to multiple Sync Gateways trying to initialize the view definitions concurrently - I don't know if we previously had tests that would start multiple Sync Gateways at almost the same time (I'm assuming that's what the test harness is doing here?).

**Comment by sethrosetter** [comment] 2016-01-07 03:20
@adamcfraser Yes. The harness is launching all sync_gateways concurrently

**Comment by adamcfraser** [comment] 2020-02-07 00:09
Closing based on age.

**Closed as completed by adamcfraser** 2020-02-07 00:09 UTC
Labels: icebox
