### ISSUE TITLE
Auto import of rapidly created / deleted docs does not delete all docs in the bucket

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2627] opened 2017-06-09 00:57 UTC
### Sync Gateway version
Couchbase Sync Gateway/1.5.0(411;f954590)

### Operating system
CentOS 7

### Config file
```javascript
{
        "adminInterface": "0.0.0.0:4985",
        "compressResponses": false,
        "databases": {
            "db": {
                "bucket": "data-bucket",
                "import_docs": "continuous",
                "password": "password",
                "server": "http://cbl.0:8091",
                "unsupported": {
                    "enable_extended_attributes": true
                },
                "username": "data-bucket",
                "users": {
                    "GUEST": {
                        "admin_channels": [
                            "*"
                        ],
                        "disabled": true
                    }
                }
            }
        },
        "interface": ":4984",
        "log": [
            "CRUD+",
            "Cache+",
            "HTTP+",
            "Changes+",
            "Import+",
            "DCP+"
        ],
        "maxCouchbaseConnections": 16,
        "maxFileDescriptors": 90000,
        "maxIncomingConnections": 0,
        "slowServerCallWarningThreshold": 500
    }
```

### Log output
https://gist.github.com/sethrosetter/de9302d8be45ae1f8d88b6b7a4705953

### Expected behavior
In this test, we are doing a `upsert_multi`, followed by a `remove_multi` from the SDK. Sync Gateway has autoimport enabled. I would expect that all documents would be deleted via sync gateway after detecting the deletion over DCP. However, a document remains in the bucket (`sdk_doc_9`). In the logs, it look like Sync Gateway is reimporting this document after the deletion.

### Actual behavior
I would expect all docs to be removed.

### Steps to reproduce
1.  Run https://github.com/couchbaselabs/mobile-testkit/blob/feature/test-doc-resurrection-xattrs/testsuites/syncgateway/functional/tests/test_xattrs.py#L967-L1064

**Comment by adamcfraser** [comment] 2017-06-09 03:53
Are docs originally being written by Sync Gateway, or is the initial insert done by the upsert_multi?  

Based on the logs, all of the docs are being identified as SG writes when the initial import is evaluated, e.g.:

```
2017-06-09T00:32:15.093Z Import+: During import, existing doc (sdk_doc_8) identified as SG write.  Canceling import.
2017-06-09T00:32:15.093Z CRUD+: Failed to update document "sdk_doc_8" w/ xattr: Document already imported
```

**Comment by adamcfraser** [comment] 2017-06-09 19:33
'identified as SG write' logging looks like it happens in the case where the doc gets deleted before the original SG import can complete.  Need to review whether that can be logged as 'doc no longer exists' instead of 'SG write'.

**Comment by adamcfraser** [comment] 2017-06-09 19:44
Need to ensure that delete mutations don't generate a new SG revision if there was never a previous SG revision (e.g. the xattr is empty).

**Comment by adamcfraser** [comment] 2017-06-16 00:13
I haven't been able to repro this locally - I've got a python script doing upsert_multi followed by remove_multi, and all documents are removed from the bucket.

Going to try to repro the scenario by artificially sending a delete mutation over the DCP feed without a corresponding create.

**Comment by adamcfraser** [comment] 2017-06-16 06:36
I haven't been able to reproduce this issue locally.  Tried the following, and wasn't able to reproduce the issue:

1. Don't import insert, attempt to import delete (looks closest to the logs above).
Result: Correct behaviour - delete doesn't get imported, because document body is empty.

2. Add delay during initial import, so that document is deleted in the bucket when cas write happens.  
Result: Correct behaviour - document isn't imported (when doc is not found during write), and subsequent delete mutation doesn't trigger import.

3. Add delay after import is triggered, but before it checks the current state of the document.  
Results: Correct behaviour - when it finds the document deleted, import is cancelled.

It's not out of the question that it's related to the open server issue on centos.  In the meantime, I've made some general improvements around delete handling (so that the delete scenario isn't reported as a SG Write), and merged these with improved diagnostics which should make it easier to identify exactly what's going on.  

@sethrosetter Can you rerun this test with SG build 430 or later and post the logs if it's still failing?

**Comment by tleyden** [comment] 2017-06-26 17:56
Update:

* We may need to uptake the server enhancement to support deleting a doc and updating it't xattr in a single operation.  GoCB SDK update: https://issues.couchbase.com/browse/GOCBC-210 
* The SG uptake has some complex bits
* Mostly likely this issue was present in the first Developer Preview

**Comment by tleyden** [comment] 2017-07-31 17:59
After we can re-enable single op delete in master (#2739), this can be closed and re-tested

**Comment by adamcfraser** [comment] 2017-08-04 23:18
Single-op delete has been re-enabled in master - closing.

**Closed as completed by adamcfraser** 2017-08-04 23:18 UTC
Labels: bug, functional-test-failure
