### ISSUE TITLE
XATTRs: Unexpected 409 conflicts for deletes, Distributed Index

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2681] opened 2017-06-24 00:03 UTC
### Sync Gateway version
1.5.0-446 

### Operating system
CentOS 7

### Config file
```javascript
{
        "adminInterface": "0.0.0.0:4985", 
        "cluster_config": {
            "bucket": "data-bucket", 
            "data_dir": ".", 
            "password": "password", 
            "server": "http://XXX:8091", 
            "username": "data-bucket"
        }, 
        "databases": {
            "db": {
                "bucket": "data-bucket", 
                "channel_index": {
                    "bucket": "index-bucket", 
                    "password": "password", 
                    "server": "http://XXX:8091", 
                    "username": "index-bucket", 
                    "writer": false
                }, 
                "event_handlers": {
                    "db_state_changed": [
                        {
                            "handler": "webhook", 
                            "url": "http://XXX:8080"
                        }
                    ], 
                    "document_changed": [
                        {
                            "handler": "webhook", 
                            "url": "http://XXX:8080"
                        }
                    ]
                }, 
                "password": "password", 
                "server": "http://XXX:8091", 
                "unsupported": {
                    "enable_extended_attributes": true
                }, 
                "username": "data-bucket"
            }
        }, 
        "interface": ":4984", 
        "log": [
            "CRUD+", 
            "Cache+", 
            "HTTP+", 
            "Changes+"
        ]
    }
```

### Log output
https://gist.github.com/sethrosetter/5019a7825bc6d2ccb8b3402f0b3424f6

### Expected behavior
There should be not conflicts

### Actual behavior
There are conflicts

### Steps to reproduce
1.  Seeing this in Jenkins - http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-di/664/testReport/junit/testsuites.syncgateway.functional.tests/test_webhooks/test_webhooks_crud_webhooks_webhook_False_/

**Comment by djpongh** [comment] 2017-06-27 17:49
needs: https://issues.couchbase.com/browse/GOCBC-210 ?

**Comment by tleyden** [comment] 2017-06-29 00:36
Steps to repro:

Update base_di cluster_config to point back to OSX machine

```
[webhook_ip]
tf1 ansible_host=192.168.11.24
```

Run pytest with mode=di

```
pytest -s --xattrs --mode=di --server-version=5.0.0-3193 --sync-gateway-version=1.5.0-455 -k "test_webhooks_crud[webhooks/webhook-False]"  testsuites/syncgateway/functional/tests/
```

**Comment by tleyden** [comment] 2017-06-29 00:56
Still not able to reproduce with above pytest command.

In the console where pytest is running, I'm seeing:

```
Still waiting for webhook events. Expecting: 200, We have only seen: 197
Getting posted webhook data ...
Still waiting for webhook events. Expecting: 200, We have only seen: 197
Getting posted webhook data ...
```

**Comment by tleyden** [comment] 2017-06-29 02:03
When trying to reproduce locally, I'm reproducing a **different** error.  I created a separate ticket: [XATTRS | DI mode: Not sending all webhooks](https://github.com/couchbase/sync_gateway/issues/2698)

**Comment by tleyden** [comment] 2017-06-29 18:49
I wasn't able to reproduce this on jenkins using Sync Gateway 1.5.0-455.  See [sync-gateway-functional-tests-base-di/675](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/675/parameters/)

**Comment by tleyden** [comment] 2017-06-29 18:53
I'm rerunning the functional test against the original Sync Gateway version (1.5.0-446) to see if I can reproduce with that version.  [cen7-sync-gateway-functional-tests-base-di/682](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/682/)

Also, with the latest Sync Gateway build: (1.5.0-456):  [cen7-sync-gateway-functional-tests-base-di/683](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/683/)

**Comment by tleyden** [comment] 2017-06-29 19:56
> I'm rerunning the functional test against the original Sync Gateway version (1.5.0-446) to see if I can reproduce with that version. cen7-sync-gateway-functional-tests-base-di/682

@sethrosetter I can't repro on jenkins, even with the original Sync Gateway build.  Can you review to see if I'm doing anything differently other than running a single test vs entire suite?

**Comment by tleyden** [comment] 2017-06-30 18:05
@sethrosetter need your help reproducing this locally

**Comment by sethrosetter** [comment] 2017-07-05 22:33
I can repro this in Jenkins and with Docker. With docker I was using the `--ci` flag. I think multiple servers helps to reproduce this.

**Comment by tleyden** [comment] 2017-07-06 23:53
I was able to repro with these steps:

* Run docker setup
* Modify `resources/cluster_configs/base_di` to have:

```
[webhook_ip]
tf1 ansible_host=mobile-testkit ansible_connection=docker
```

* Run pytest

```
pytest -s --xattrs --mode=di --skip-provisioning --server-version=5.0.0-3193 --sync-gateway-version=1.5.0-455 -k "test_webhooks_crud[webhooks/webhook-False]"  testsuites/syncgateway/functional/tests/
```

The first time it passed, the second time it failed with 409 errors: https://gist.github.com/tleyden/d57a189405b726ebf14fa45af550789a

**Comment by tleyden** [comment] 2017-07-07 00:31
> needs: https://issues.couchbase.com/browse/GOCBC-210 ?

I just applied the changes in http://review.couchbase.org/#/c/80075/ and http://review.couchbase.org/#/c/80076/ (still under code review), but they did not fix the issue.  I re-ran the funtional test three times, and on the third time it failed w/ the same error in https://github.com/couchbase/sync_gateway/issues/2681#issuecomment-313550175

**Comment by tleyden** [comment] 2017-07-07 18:00
> I just applied the changes in http://review.couchbase.org/#/c/80075/ and http://review.couchbase.org/#/c/80076/ 

I later realized that I forgot to update the Sync Gateway code to uptake the upstream change, so this test was probably invalid.

Going back to diagnosing the issue.

**Comment by tleyden** [comment] 2017-07-07 23:21
With added logging, the code is failing [here](https://github.com/couchbase/sync_gateway/blob/master/base/bucket_gocb.go#L1239-L1260) 

```
		// If this is a tombstone, we want to delete the document and update the xattr
		if deleteDoc {
			// TODO: replace with a single op when https://issues.couchbase.com/browse/MB-24098 is ready
			removeCas, removeErr := bucket.Remove(k, cas)
			if removeErr == nil {
				// Successful removal - update the cas for the xattr operation
				cas = removeCas
			} else if removeErr == gocb.ErrKeyNotFound {
				// Document body has already been removed - continue to xattr processing w/ same cas
			} else if isRecoverableGoCBError(removeErr) {
				// Recoverable error - retry WriteUpdateWithXattr
				continue
			} else {
				// Non-recoverable error - return
				return emptyCas, removeErr
			}

			// update xattr only
			casOut, writeErr := bucket.WriteCasWithXattr(k, xattrKey, exp, cas, nil, updatedXattrValue)
			if writeErr != nil && writeErr != gocb.ErrKeyExists && !isRecoverableGoCBError(writeErr) {
				LogTo("CRUD", "Update of new value during WriteUpdateWithXattr failed for key %s: %v", k, writeErr)
				return emptyCas, writeErr
			}
```

with [logs](https://gist.github.com/tleyden/ac97732cf4dbec7cef975380df31e5e2#file-409conflict-L16-L18)

```
2017-07-07T23:02:40.216Z CRUD+: Successful removal - update the cas for the xattr operation.  cas: 1499468560216162304
  | 2017-07-07T23:02:40.219Z CRUD+: calling bucket.WriteCasWithXattr() with key: sdk_user_doc_53, xattrkey: _sync
  | 2017-07-07T23:02:40.219Z CRUD+: called bucket.WriteCasWithXattr() with key: sdk_user_doc_53, xattrkey: _sync.  casOut: 0 writeErr: key already exists, if a cas was provided the key exists with a different cas

```

vs the [success case logs](https://gist.github.com/tleyden/ac97732cf4dbec7cef975380df31e5e2#file-200ok-L28-L30) 

```
2017-07-07T23:02:40.195Z CRUD+: Successful removal - update the cas for the xattr operation.  cas: 1499468560195649536
  | 2017-07-07T23:02:40.196Z CRUD+: calling bucket.WriteCasWithXattr() with key: sdk_user_doc_52, xattrkey: _sync
  | 2017-07-07T23:02:40.197Z CRUD+: called bucket.WriteCasWithXattr() with key: sdk_user_doc_52, xattrkey: _sync.  casOut: 1499468560196829184 writeErr: <nil>
```

**Comment by tleyden** [comment] 2017-07-10 17:21
In https://github.com/couchbase/sync_gateway/commit/41204f2480180e853332e25becc081b1f0da67d9 I modified sync gateway to call `bucket.Bucket.MutateInEx`, and I'm no longer able to repro the 409 conflicts issue.  

I'm going to clean up the change and push a PR.  We'll also need to point to updated gocb once the https://issues.couchbase.com/browse/GOCBC-210 changes are merged.

As @sethrosetter pointed out, https://github.com/couchbase/sync_gateway/issues/2648 might also be related.  I am going to run that test against https://github.com/couchbase/sync_gateway/commit/41204f2480180e853332e25becc081b1f0da67d9 to see if I'm still able to repro

**Comment by tleyden** [comment] 2017-07-13 22:58
Added failing unit test in 303846b00a09c437a154b2746d68d2b8d5416677, which deletes the doc body in between the "get status" and the "mutation" phase (inject simulated race condition)

**Comment by tleyden** [comment] 2017-07-17 21:49
I tried [reworking the algorithm](https://github.com/couchbase/sync_gateway/blob/ebdf9f63500bcb7fba556e73eb315cfdc5e0e402/base/bucket_gocb.go#L1106-L1180) to:

```
// Try to delete body + xattr in single op
// If fails
// 		- Do get w/ xattr (get cas)
// 		- Cas-safe delete just the xattr
```

But it's failing [TestDeleteWithXattrWithSimulatedRaceRessurect](https://github.com/couchbase/sync_gateway/blob/ebdf9f63500bcb7fba556e73eb315cfdc5e0e402/base/bucket_gocb_test.go#L1419-L1473) which introduces an artificial race condition that resurrects the doc during the invocation of `DeleteWithXattr()` 

With the [previous algorithm](https://github.com/couchbase/sync_gateway/blob/ebdf9f63500bcb7fba556e73eb315cfdc5e0e402/base/bucket_gocb.go#L1183-L1286), [TestDeleteWithXattrWithSimulatedRaceRessurect](https://github.com/couchbase/sync_gateway/blob/ebdf9f63500bcb7fba556e73eb315cfdc5e0e402/base/bucket_gocb_test.go#L1419-L1473)  passes.

**Comment by tleyden** [comment] 2017-07-17 22:46
Fixed in later version by aborting delete if doc was resurrected

PR up here: https://github.com/couchbase/sync_gateway/pull/2721

**Closed as completed** 2017-07-20 20:53 UTC
Labels: P1: high, functional-test-failure
