### ISSUE TITLE
blipHandler can't get doc warning

### ISSUE THREAD

**Issue by pasin** [couchbase/sync_gateway#3281] opened 2018-02-07 02:09 UTC
This is originally from https://github.com/couchbase/couchbase-lite-ios/issues/2052 reported by @	jayzhanghs. 

> For one of our environments with Sync Server 5.5 and CBL 2.0 the sync of couchbase constantly gets stuck after a certain number of documents get pulled. The server side log indicates the CBL is trying to get a few documents of out-dated revision and thus gets stuck. 

```
2018-01-31T19:29:12.579Z WARNING: blipHandler can't get doc "a80713c7-478b-4ce3-9aec-b2f17ba0095e"/2-5a6533b41b9f1426b9ca9bf1475f794d: 404 missing -- rest.(*blipHandler).sendRevision() at blip_sync.go:374
2018-01-31T19:29:12.611Z WARNING: blipHandler can't get doc "691b6456-3342-4a5d-afff-2ed1cc7b1bab"/2-3a7269ade423c08b26e9436f863dda8f: 404 missing -- rest.(*blipHandler).sendRevision() at blip_sync.go:374
2018-01-31T19:29:12.611Z WARNING: blipHandler can't get doc "83fd613a-e17c-49e1-917c-67a32fba9dc6"/2-91f4fc4044c08c46a2796352490736be: 404 missing -- rest.(*blipHandler).sendRevision() at blip_sync.go:374
```

> Since I don't specify any revision at all, I'm wondering if this is some bug on the CBL 2.0 which is similar to a bug a few years ago: https://github.com/couchbase/couchbase-lite-ios/issues/377

* Version:   CBL 2.0 DB21
* Client OS: iOS 11
* Server:    Sync Server 5.5

**Comment by pasin** [comment] 2018-02-07 02:13
From @gajohnson:

@snej On fresh installations of our ios app running couchbase lite 2.0 DB 21, the initial blip sync for this user never reaches the complete state. After we timeout and restart sync in our own application, sync never leaves busy state. Sync logs show 2 or 3 documents are missing (404 errors show below). These warnings are logged on every sync attempt for this user, not just the initial attempt.

It seems like there is some issue either in the client or the sync gateway where it is hanging on to an old revision rather than picking up the change. Also worth noting that all 3 of these documents are flagged as deleted, and all have the same "tombstoned_at" value of 1515238392.

Here is a snippet of the sync logs showing the relevant requests from blip sync along with 1 of the documents that 404's on every sync. We have completely removed and reinstalled the ios app but continue to see this problem where the device is requesting and old revision repeatedly. 

```2018-02-01T16:23:15.924Z HTTP:  #1639654: POST /db/_session  (ADMIN)
2018-02-01T16:23:16.488Z HTTP:  #1639655: GET /db/_blipsync  (as XXXXXXXXX@example.com)
2018-02-01T16:23:18.032Z changes_view: Query took 1.383185457s to return 25632 rows, options = db.Body{"stale":false, "startkey":[]interface {}{"AccountName::Customer::*", 0x1}, "endkey":[]interface {}{"AccountName::Customer::*", 0x10debc5}}
2018-02-01T16:23:18.342Z changes_view: Query took 308.987077ms to return 9643 rows, options = db.Body{"stale":false, "startkey":[]interface {}{"AccountName::CustomerGroup::55aa4536-9693-482d-93dd-0c802e080ede::Catalog", 0x1}, "endkey":[]interface {}{"AccountName::CustomerGroup::55aa4536-9693-482d-93dd-0c802e080ede::Catalog", 0x10284bb}}
2018-02-01T16:23:20.314Z changes_view: Query took 1.972389088s to return 76408 rows, options = db.Body{"startkey":[]interface {}{"AccountName::UserGroup::*", 0x1}, "endkey":[]interface {}{"AccountName::UserGroup::*", 0x10df970}, "stale":false}
2018-02-01T16:23:20.575Z changes_view: Query took 253.250962ms to return 10341 rows, options = db.Body{"stale":false, "startkey":[]interface {}{"AccountName", 0x1}, "endkey":[]interface {}{"AccountName", 0x10280fe}}
2018-02-01T16:23:20.836Z changes_view: Query took 261.039358ms to return 8758 rows, options = db.Body{"stale":false, "startkey":[]interface {}{"AccountName::CustomerGroup::06a5a692-5e0e-49e0-8ef2-afd0e8bcb1b1::Catalog", 0x1}, "endkey":[]interface {}{"AccountName::CustomerGroup::06a5a692-5e0e-49e0-8ef2-afd0e8bcb1b1::Catalog", 0x193d09}}
2018-02-01T16:23:21.099Z changes_view: Query took 263.226548ms to return 9034 rows, options = db.Body{"stale":false, "startkey":[]interface {}{"AccountName::CustomerGroup::1cfcdae2-a6c2-4117-8af1-027868c2fa91::Catalog", 0x1}, "endkey":[]interface {}{"AccountName::CustomerGroup::1cfcdae2-a6c2-4117-8af1-027868c2fa91::Catalog", 0x10283d5}}
2018-02-01T16:23:22.013Z changes_view: Query took 913.602292ms to return 35047 rows, options = db.Body{"startkey":[]interface {}{"AccountName::Manufacturer::*", 0x1}, "endkey":[]interface {}{"AccountName::Manufacturer::*", 0x10defd0}, "stale":false}
2018-02-01T16:24:16.917Z WARNING: blipHandler can't get doc "a80713c7-478b-4ce3-9aec-b2f17ba0095e"/2-5a6533b41b9f1426b9ca9bf1475f794d: 404 missing -- rest.(*blipHandler).sendRevision() at blip_sync.go:374
2018-02-01T16:24:17.565Z WARNING: blipHandler can't get doc "691b6456-3342-4a5d-afff-2ed1cc7b1bab"/2-3a7269ade423c08b26e9436f863dda8f: 404 missing -- rest.(*blipHandler).sendRevision() at blip_sync.go:374
2018-02-01T16:24:17.565Z WARNING: blipHandler can't get doc "83fd613a-e17c-49e1-917c-67a32fba9dc6"/2-91f4fc4044c08c46a2796352490736be: 404 missing -- rest.(*blipHandler).sendRevision() at blip_sync.go:374


691b6456-3342-4a5d-afff-2ed1cc7b1bab
{
  "$hs": {
    "account": "AccountName",
    "type": "AccountName::Address"
  },
  "$schema": "",
  "_deleted": true,
  "_sync": {
    "rev": "3-77d627eafffec1c12045eab8602dd8cb",
    "flags": 1,
    "sequence": 5491383,
    "recent_sequences": [
      1074645,
      5131067,
      5491383
    ],
    "history": {
      "revs": [
        "2-3a7269ade423c08b26e9436f863dda8f",
        "3-77d627eafffec1c12045eab8602dd8cb",
        "1-728445d860af974f5ee902dd4364964a"
      ],
      "parents": [
        2,
        0,
        -1
      ],
      "deleted": [
        1
      ],
      "channels": [
        null,
        null,
        [
          "AccountName::Customer::*",
          "AccountName::Customer::87318222-9089-4145-b9c7-d7480048db5d"
        ]
      ]
    },
    "channels": {
      "AccountName::Customer::*": {
        "seq": 5131067,
        "rev": "2-3a7269ade423c08b26e9436f863dda8f"
      },
      "AccountName::Customer::87318222-9089-4145-b9c7-d7480048db5d": {
        "seq": 5131067,
        "rev": "2-3a7269ade423c08b26e9436f863dda8f"
      }
    },
    "cas": "",
    "tombstoned_at": 1515238392,
    "time_saved": "2018-01-06T11:33:12.416220617Z"
  }
}```

**Comment by pasin** [comment] 2018-02-07 02:13
From @adamcfraser:

The "can't get doc" is being logged when the attempt to retrieve the revision returns an error - 404 missing in this case.

From the document above, it looks like rev 2 (the missing revision) is being returned by the subChanges call (even though rev 3 is the active tombstone) because it's the revision at which the document was removed from the user's channels.

This sounds like the equivalent of couchbase/sync_gateway#2815, but I'm not clear why that would resurface when using the 2.0 replicator.

**Comment by gajohnson** [comment] 2018-02-07 16:52
We ran into this issue on a development instance (this time hundreds of documents) so I took the time to dig in a little more. The documents that I spot-checked each had one additional revision but were not necessarily tombstoned as was the case in the earlier examples we saw of this issue.

First I took the gateway offline and issued a _resync. This completed successfully but did not solve the issue.

I also tried making a post to _changes through the public rest api with the following python script.

```
sync_url = 'https://%s:4984/db/_changes' % sync_host
cookies = {sync_session.get('cookie_name'): sync_session.get('session_id')}
res = requests.post(sync_url,
                    headers={'Content-Type': 'application/json'},
                    cookies=cookies,
                    json={
                        'style': 'all_docs',
                        'heartbeat': 300000,
                        'feed': 'normal',
                        'active_only': True,
                        'include_docs': True,
                        'limit': None,
                        'since': 0
                    })
```

Interestingly, this did not cause any 404s on the sync gatewaybut I do not see the missing documents in the response.

Finally, I noticed for these documents that the `revs` section of history has the revisions listed in non-numerical order, with the "missing" revision occurring before the earlier revisions. This seems like the most likely cause of the issue but it's unclear what is causing these revisions to be ordered incorrectly.

Thanks again for the help on this!

**Comment by adamcfraser** [comment] 2018-02-07 17:04
@gajohnson The ordering in _sync.revs is correct. They aren't expected to be in ascending order -the tree is built based on the 'parents' array.  

A _resync shouldn't change anything unless you're also modifying the sync function.  

Your changes request includes active_only, which will exclude removal notifications (which I think is at the heart of what's going on here).  Can you try the same changes request w/out the active_only flag?

Can you also confirm the set of channels assigned to the user attempting to replicate in this scenario?  I'm assuming they have access to either `AccountName::Customer::87318222-9089-4145-b9c7-d7480048db5d` or `AccountName::Customer::*`, but I'd like to confirm.

**Comment by gajohnson** [comment] 2018-02-07 17:18
Thanks @adamcfraser and sorry for the red herrings! Just to confirm your suspicions, we are not changing the sync function at all. Changing active_only to False causes the 404s to show up again in the logs. Good catch with those.

Here is another example `_sync` section from one of the docs:

```
"_sync": {
  "rev": "4-4c0a3f1b6038e331219d611f5f7ced65",
  "sequence": 1380892,
  "recent_sequences": [
    57333,
    468098,
    936680,
    1380892
  ],
  "history": {
    "revs": [
      "4-4c0a3f1b6038e331219d611f5f7ced65",
      "1-e510f8abfb617f9ea64756d95e03b9f8",
      "2-8c8d6a0dce2a1bebcd758e4280215e48",
      "3-641821d5a76d4b2beaa76e67d24cf296"
    ],
    "parents": [
      3,
      -1,
      1,
      2
    ],
    "channels": [
      [
        "AccountName::CustomerGroup::5108c3e8-93fa-4d70-9b6b-db4a869c914e::Catalog"
      ],
      [
        "AccountName"
      ],
      [
        "AccountName"
      ],
      [
        "AccountName::CustomerGroup::5108c3e8-93fa-4d70-9b6b-db4a869c914e::Catalog"
      ]
    ]
  },
  "channels": {
    "AccountName": {
      "seq": 936680,
      "rev": "3-641821d5a76d4b2beaa76e67d24cf296"
    },
    "AccountName::CustomerGroup::5108c3e8-93fa-4d70-9b6b-db4a869c914e::Catalog": null
  },
  "cas": "",
  "time_saved": "2018-02-06T23:52:55.646109115Z"
}
```

**Comment by gajohnson** [comment] 2018-02-07 18:21
And here is the list of channels for that user according to the response from `_user/username`

```
[
  "!",
  "AccountName",
  "AccountName::Customer::0fb7c8e3-7538-44c4-978b-a25d20c16e4f",
  "AccountName::CustomerGroup::0f06adb3-fd78-4b92-8279-1e24408ebb21::Catalog",
  "AccountName::CustomerOrder::0fb7c8e3-7538-44c4-978b-a25d20c16e4f",
  "AccountName::Manufacturer::*"
]
```

**Comment by adamcfraser** [comment] 2018-02-12 18:38
@tleyden Repro steps should just be:

1. Set up a user w/ access to channel A
2. Write two revision of a document (both in channel A)
3. Write two more revisions of the document, no longer in channel A
4. Have the user issue a rev request for rev 3.

Expected:
Users gets a removed:true response 

Actual:
User gets 404 missing

Would expect blip code to be hitting the same handling that's already included in crud.go, see https://github.com/couchbase/sync_gateway/pull/2821/files.

**Comment by tleyden** [comment] 2018-02-14 01:42
So far, I've been unable to reproduce this issue with this test:

https://github.com/couchbase/sync_gateway/blob/07d45dd2c61f74e0a13707227351194942f0a2d7/rest/blip_api_test.go#L812-L906

**Comment by tleyden** [comment] 2018-02-14 16:32
@gajohnson can you provide anything additional on how to reproduce this?  

For example:

- A standalone script that creates the documents in Sync Gateway via the REST API would be ideal 
- A standalone app that creates the data, that when pushed and then pulled, reproduces the issue?

I realize that either might be a lot of work on your end, but anything you could provide might help.

Some other questions:

- Does it break at the same point each time?
- Have you tried on the latest Sync Gateway beta version from https://www.couchbase.com/downloads?

**Comment by gajohnson** [comment] 2018-02-15 17:06
@tleyden Thanks for getting back. I am upgrading to sync gateway 2.0 beta now so I'll hopefully have more info for you when that is done. I'm not sure what specific conditions are required to reproduce this problem, only that our logs show repeated attempts to get old revisions of documents fail with a 404 and that it seems to happen when channels are changed on the documents.

I'll see if I can get a small script together that demonstrates the problem but it may take a bit.

**Comment by tleyden** [comment] 2018-02-15 18:24
@gajohnson ok keep us posted.  Feel free to ping me in https://gitter.im/couchbase/discuss (username: @tleyden)

Also I'd say the script to reproduce it would be the most helpful thing, because then we would be able to add it as a regression test to our suite.

**Comment by adamcfraser** [comment] 2018-02-20 18:24
Closing this as we haven't been able to repro w/ 2.0.  @gajohnson Please reopen if you hit this after moving to 2.0.

**Closed as completed by adamcfraser** 2018-02-20 18:24 UTC
Labels: P1: high, feature-blocker
