### ISSUE TITLE
Sync Gateway 2.8.1 goes into infinite loop over deleted doc

### ISSUE THREAD

**Issue by kabirsaheb** [couchbase/sync_gateway#4968] opened 2021-02-24 11:09 UTC
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
2.8.1

### Operating system
Ubuntu

### Config file
```javascript
function(doc, oldDoc) {
    console.log("Doc: " + JSON.stringify(doc));
    console.log("Old Doc: " + JSON.stringify(oldDoc));
if (doc.type) {
 //process
} 
 else {
        console.log("Sync Fn no rules to process");
    }
```

### Log output
```
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
[INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
[INF] Javascript: Sync Old Doc: null
[INF] Javascript: Sync Sync Fn no rules to process
```
### Expected behavior
What should have happened?
See actual, that should not happen.

### Actual behavior
What actually happened?
sync Gateway processes same document infinitely, (docId in logs 1576502740081-4825368-0f18a8-ddr_4228.jpg) 
Reverted to 2.8.0 and all ok.  It goes into infinite loop over same document, restart dint have any effect. It goes into it once in 15-20 minutes. 

### Steps to reproduce
No idea why this happens and to what.

**Comment by bbrks** [comment] 2021-02-24 11:54
It's difficult to tell from your report where the loop is happening or how to attempt to reproduce it, but we would like to investigate further.

If possible, are you able to provide debug level logs from a period of time when this issue is occurring? Or at least a larger set of info level logs, instead of just the sync function logging.

**Comment by kabirsaheb** [comment] 2021-02-24 14:45
There were no logs logged when this loop was ON and CPU went upto 100%. however I have logs of just before loop started but I dont see anything suspicious. Attaching file. I have * in logging ==> "log_keys": ["*"],
[logs.txt](https://github.com/couchbase/sync_gateway/files/6036756/logs.txt)

**Comment by bbrks** [comment] 2021-02-24 15:03
Looks like a scenario where a mobile client is pushing up a tombstone (rev 2) of a doc that SG hasn't seen before from the sync function logging.

I'll see if we can repro from our end based on that info alone, but without debug level logs it's still difficult to tell where exactly SG is getting stuck.

```
2021-02-24T15:50:32.064+05:30 [INF] HTTP:  #1019: POST /kamero/_bulk_docs (as GUEST)
2021-02-24T15:50:32.110+05:30 [INF] Javascript: Sync Old Doc: null
2021-02-24T15:50:32.110+05:30 [INF] Javascript: Sync Sync Fn no rules to process
2021-02-24T15:50:32.117+05:30 [INF] Javascript: Sync Doc: {"_deleted":true,"_id":"1576502740081-4825368-0f18a8-ddr_4228.jpg","_rev":"2-6f83165620f7c83db62527a9bfa21043"}
```

**Comment by bbrks** [comment] 2021-02-24 15:11
Can you also let us know which version of Couchbase Server you're running?

**Comment by kabirsaheb** [comment] 2021-02-24 16:34
Couchbase server 6.6.0 community editions. Couchbase lite Android and iOS are still at 1.5.x not updated to 2.x

**Comment by adamcfraser** [comment] 2021-02-24 17:51
@kabirsaheb Can you share a (sanitized) version of your full Sync Gateway config?  We haven't been able to reproduce yet with the information on the ticket, want to ensure we're running with the same config settings you're using.

**Comment by kabirsaheb** [comment] 2021-02-24 18:06
[config.txt](https://github.com/couchbase/sync_gateway/files/6037956/config.txt)

config except js sync fn, which i already mentioned above.

**Comment by adamcfraser** [comment] 2021-02-24 18:17
How many Sync Gateway nodes are you running?  Just one?

**Comment by kabirsaheb** [comment] 2021-02-24 18:18
3 nodes, 2 import_docs false. 1 import_docs true, rest config is same. This happened on all nodes sometime or the other.

**Comment by bbrks** [comment] 2021-03-07 17:16
Thanks for reporting @kabirsaheb. We've identified the issue and have 2.8.2 due to be released soon to address this.

https://issues.couchbase.com/browse/CBG-1341

**Comment by bbrks** [comment] 2021-03-11 10:53
Closing now 2.8.2 is out

https://docs.couchbase.com/sync-gateway/current/release-notes.html#lbl-rel282

**Closed as completed by bbrks** 2021-03-11 10:53 UTC
