### ISSUE TITLE
Control loglevel (INFO / ERROR / WARN) in config

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#1495] opened 2016-01-20 20:17 UTC
Right now we can control which tags are used, but it's not possible to filter on log level:

eg, `log_level`: ["INFO, DEBUG"]

**Comment by adamcfraser** [comment] 2016-01-21 00:16
Duplicate of https://github.com/couchbase/sync_gateway/issues/1021.

**Closed as completed by adamcfraser** 2016-01-21 00:16 UTC
