### ISSUE TITLE
Pull request to add JSON Schema for validation?

### ISSUE THREAD

**Issue by paulharter** [couchbase/sync_gateway#1288] opened 2015-11-13 14:10 UTC
Hi Adam, Chris et al.

I have a project with quite a few complex JSON documents. Maintaining procedural validation in the sync function is not ideal as its onerous and a possible source of hard to spot validation errors which might have security implications. I would prefer to use JSON Schema which provides a concise declarative way to manage validation that can be used across different languages in my project.

http://json-schema.org/ 

So I have added a new callback to the sync function:

``` javascript
validate(doc, "schema_name.json");
```

Would you consider a pull request to add this feature? You can see my implementation here:

https://github.com/paulharter/sync_gateway/tree/feature/jsonschema

This is done using a go version of JSON Schema validation from:

https://github.com/xeipuuv/gojsonschema

I don't really programme in go so it's probably a bit scrappy but I guess that this will perform better than validating with js functions, as its doing the hard work in go, but maybe not.

Thanks

Paul

**Comment by tleyden** [comment] 2016-01-06 02:15
@paulharter this would be easier to review if you just sent a PR

**Comment by paulharter** [comment] 2016-01-06 09:54
@tleyden thanks for looking at this.

I've made a pull request https://github.com/couchbase/sync_gateway/pull/1407

**Comment by tleyden** [comment] 2016-05-04 16:41
Closing this as a duplicate of https://github.com/couchbase/sync_gateway/pull/1470

**Closed as completed by tleyden** 2016-05-04 16:41 UTC
