### ISSUE TITLE
Missing changes since=0 after doing after doing large import (Docker only)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2662] opened 2017-06-20 23:05 UTC
### Sync Gateway version
1.5.0-435

### Server Version
5.0.0-3154

### Operating system
CentOS7

### Config file
```
https://gist.github.com/sethrosetter/6b6384e56efa75d2f9cf766994994ad8
```

### Log output

Contextual logs for missing doc from changes feed `sdk_20500`
```
368502 2017-06-20T22:08:37.222Z Cache:     #28939 ==> channel "*"
368503 2017-06-20T22:08:37.223Z Cache:   Received previously skipped out-of-order change (seq 29216, expecting 29879) doc "sdk_22042" / "1-f241412d729240981ea646005f61ef07"
368504 2017-06-20T22:08:37.223Z Cache+: LogEntries.appendChange: out-of-order sequence #29216 (last is #29878) - handling as insert
368505 2017-06-20T22:08:37.224Z Cache+: Pruned 1 old entries from channel "created_via_sdk"
368506 2017-06-20T22:08:37.224Z Cache:     #29216 ==> channel "created_via_sdk"
368507 2017-06-20T22:08:37.224Z Cache+: LogEntries.appendChange: out-of-order sequence #29216 (last is #29878) - handling as insert
368508 2017-06-20T22:08:37.225Z Cache+: Pruned 1 old entries from channel "*"
368509 2017-06-20T22:08:37.225Z Cache:     #29216 ==> channel "*"
368510 2017-06-20T22:08:37.225Z Cache:   Received previously skipped out-of-order change (seq 28886, expecting 29879) doc "sdk_20500" / "1-f241412d729240981ea646005f61ef07"
368511 2017-06-20T22:08:37.226Z Cache+: LogEntries.appendChange: out-of-order sequence #28886 (last is #29878) - handling as insert
368512 2017-06-20T22:08:37.226Z Cache+: Pruned 1 old entries from channel "created_via_sdk"
368513 2017-06-20T22:08:37.226Z Cache:     #28886 ==> channel "created_via_sdk"
368514 2017-06-20T22:08:37.227Z Cache+: LogEntries.appendChange: out-of-order sequence #28886 (last is #29878) - handling as insert
368515 2017-06-20T22:08:37.227Z Cache+: Pruned 1 old entries from channel "*"
368516 2017-06-20T22:08:37.227Z Cache:     #28886 ==> channel "*"
368517 2017-06-20T22:08:37.228Z Cache:   Received previously skipped out-of-order change (seq 28333, expecting 29879) doc "sdk_18906" / "1-f241412d729240981ea646005f61ef07"
368518 2017-06-20T22:08:37.228Z Cache+: LogEntries.appendChange: out-of-order sequence #28333 (last is #29878) - handling as insert
368519 2017-06-20T22:08:37.228Z Cache+: Pruned 1 old entries from channel "created_via_sdk"
368520 2017-06-20T22:08:37.229Z Cache:     #28333 ==> channel "created_via_sdk"
368521 2017-06-20T22:08:37.229Z Cache+: LogEntries.appendChange: out-of-order sequence #28333 (last is #29878) - handling as insert
368522 2017-06-20T22:08:37.229Z Cache+: Pruned 1 old entries from channel "*"
368523 2017-06-20T22:08:37.230Z Cache:     #28333 ==> channel "*"
368524 2017-06-20T22:08:37.230Z Cache:   Received previously skipped out-of-order change (seq 28013, expecting 29879) doc "sdk_18050" / "1-f241412d729240981ea646005f61ef07"
368525 2017-06-20T22:08:37.230Z Cache+: LogEntries.appendChange: out-of-order sequence #28013 (last is #29878) - handling as insert
```

### Expected behavior
After a large import, issuing a changes request for 30000 expected changes should return the 30000 changes

### Actual behavior
After a large import, issuing a changes request for 30000 changes is missing roughly 1800 expected changes

### Steps to reproduce
1.  `pytest --skip-provisioning -s --mode=cc --xattrs --server-version=5.0.0-3154 --sync-gateway-version=1.5.0-435 -k "test_large_initial_import[sync_gateway_default_functional_tests]"  testsuites/syncgateway/functional/tests/`

### Action items

- [ ] Add configuration values to allow a workaround

**Comment by sethrosetter** [comment] 2017-06-20 23:07
Initial thoughts: Some entries are being pruned from the cache due to the parallel import (auto + on demand). Sync Gateway is thinking the entries are in the cache and not going to the view even though it should.

**Comment by adamcfraser** [comment] 2017-06-20 23:53
As @sethrosetter mentioned - it looks like the missing entries were skipped during sequence buffering (concurrent imports causing higher-than-usual variation in sequence ordering over DCP), and by the time they arrived, they were no longer valid for the cache (too old).  At this point the expected behaviour is that they aren't added to the cache, and are retrieved via view based on a changes request.  It would appear that this isn't working as expected.

**Comment by adamcfraser** [comment] 2017-06-23 21:50
Some additional implementation notes:
 - During feed processing, sequences are buffered in order.  We wait up to 5 seconds for an entry to appear on the DCP feed.  If it doesn't arrive in that window, it is 'skipped': feed entries are 'skipped' and put into a skipped sequence queue:
https://github.com/couchbase/sync_gateway/blob/master/db/change_cache.go#L669

- When that sequence eventually arrives over the feed, we remove it from the skipped sequence queue and cache it
https://github.com/couchbase/sync_gateway/blob/master/db/change_cache.go#L583

- The channel cache can hold a maximum of 500 entries per channel: https://github.com/couchbase/sync_gateway/blob/master/db/channel_cache.go#L14
- The channel cache has a 'validFrom' sequence that's used to determine whether a cache request can be fully satisfied by what's in the cache, or if it needs to execute a view query

This bug looks like it's happening in the case where a skipped sequence is cached, but:
 - the channel cache is full
 - the skipped sequence is older than the oldest entry in the channel cache
 - the skipped sequence gets added to and then immediately pruned from the cache
 
After this happens, cache queries are returning the wrong results, in a way that looks like they are failing to properly query the view.  The most likely scenario is that the validFrom value for the cache is ending up in a bad state, and that's preventing the view queries from being invoked.

**Comment by adamcfraser** [comment] 2017-06-24 15:25
You should be able to use the approach taken in the TestLateArrivingSequence test to replicate this scenario:
 - set the channel cache limits to a small value (like 10) using CacheOptions
 - use cache.addToCache to add sequences 1-n, then n+1 to n+20 (skipping n, writing more than the cache limit after n)
 - use cache.AddLateSequence to add n
 - get changes since n (or since before n)

**Comment by adamcfraser** [comment] 2017-06-24 15:26
One last thought - it's possible that this issue is unrelated to the cache validFrom, and is instead a problem handling the Low sequence on the changes request (and is related to the failing LowSequence unit test @tleyden was looking into) - might want to get to the bottom of that failing test first.

**Comment by tleyden** [comment] 2017-06-26 18:27
> the failing LowSequence unit test @tleyden was looking into

Adding for xref purposes:

https://github.com/couchbase/sync_gateway/issues/2666

**Comment by sethrosetter** [comment] 2017-06-26 18:43
Not failing in Jenkins as of http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-cc/767, however due to races introduces with docker, this is likely to only fail locally.

**Comment by sethrosetter** [comment] 2017-06-27 21:46
I'm still seeing this with SG `1.5.0-453`. I will have to get @tleyden setup with Docker locally. This is the command to repro the issue `pytest -s --xattrs --mode=cc --server-version=5.0.0-3207 --sync-gateway-version=1.5.0-453 -k "test_large_initial_import[sync_gateway_default_functional_tests]" testsuites/syncgateway/functional/tests/`

**Comment by tleyden** [comment] 2017-06-28 23:23
>  and are retrieved via view based on a changes request. It would appear that this isn't working as expected.

Based on this comment from @adamcfraser, it could be related to https://github.com/couchbase/sync_gateway/issues/2682.  During testing of https://github.com/couchbase/sync_gateway/issues/2682 we saw the view return 70 / 200 expected results.

**Comment by tleyden** [comment] 2017-06-28 23:26
From @adamcfraser 

>  and is instead a problem handling the Low sequence on the changes request (and is related to the failing LowSequence unit test @tleyden was looking into)

That turned out to be an issue only related to the test code, and not the underling Sync Gateway code.

**Comment by tleyden** [comment] 2017-06-29 19:22
I think this should be repro'd against latest build 1.5.0-456 -- if it can't be repro'd, then it means it was fixed by https://github.com/couchbase/sync_gateway/issues/2682

@sethrosetter if this is easy for you, go for it.  Otherwise let's sync up and you can help me repro locally

**Comment by tleyden** [comment] 2017-06-29 22:04
> I think this should be repro'd against latest build 1.5.0-456

Seth tried this on his machine and was still able to repro the issue.

**Comment by tleyden** [comment] 2017-06-29 22:10
I was able to repro locally.  Test output: https://gist.github.com/tleyden/8dba27ecdf0b9326b81c300faa5a9808

**Comment by tleyden** [comment] 2017-06-29 22:18
@sethrosetter I think there might be some issues in the test.  According to the [test output](https://gist.github.com/tleyden/8dba27ecdf0b9326b81c300faa5a9808#file-gistfile1-txt-L1-L32), it's receiving more changes on the changes feed, and then it times out.  

I think `verify_docs_in_changes()` should be reworked to keep extending the timeout as long as it's getting new changes.  Eg, the timeout should be the amount of time that **no changes** are received before it gives up.

Also, the test seems to have an inherent race condition due to:

```
    # Let some documents process
    log_info('Sleeping 30s to let some docs auto import')
    time.sleep(30)
```

Instead of that, I think the test should basically do a polling loop against sync gateway and only unblock once the docs are known to be in Sync Gateway.  For example, it could take the last 100 doc id's that were added by the SDK, and do a `_bulk_get` request, and only consider the import finished once they were all known to be in Sync Gateway.

**Comment by sethrosetter** [comment] 2017-06-30 00:18
@tleyden I agree with the enhancement to `verify_docs_in_changes()` since there is a non-deterministic time it takes for the changes to propagate. 

The 30 sleep is added because we want some docs to process during import, however the hope is to trigger on demand importing (via bulk_get during import) as well. Although this too is a bit race-y in the sense that if the machine is fast enough, all docs could be imported before issuing the first bucket get.

**Comment by sethrosetter** [comment] 2017-06-30 00:21
I just saw this fail again locally and it looks a little more problematic than what you are seeing
```
  > Verify http://cbl.1:4984/db has 30000 docs in changes
GET http://cbl.1:4984/ 200
Using POST data: {'feed': 'longpoll', 'since': 0, 'timeout': 60000}
POST http://cbl.1:4984/db/_changes 200
Found 0 changes
Missing expected docs: 30000
last_seq: 0
GET http://cbl.1:4984/ 200
Using POST data: {'feed': 'longpoll', 'since': u'0', 'timeout': 60000}
POST http://cbl.1:4984/db/_changes 200
Found 29231 changes
Missing expected docs: 770
last_seq: 15183::29993
GET http://cbl.1:4984/ 200
Using POST data: {'feed': 'longpoll', 'since': u'15183::29993', 'timeout': 60000}
POST http://cbl.1:4984/db/_changes 200
Found 5376 changes
Missing expected docs: 743
last_seq: 30002
GET http://cbl.1:4984/ 200
Using POST data: {'feed': 'longpoll', 'since': u'30002', 'timeout': 60000}
POST http://cbl.1:4984/db/_changes 200
Found 0 changes
Missing expected docs: 743
last_seq: 30002
GET http://cbl.1:4984/ 200
Using POST data: {'feed': 'longpoll', 'since': u'30002', 'timeout': 60000}
POST http://cbl.1:4984/db/_changes 200
Found 0 changes
Missing expected docs: 743
last_seq: 30002
FAILEDTearing down test 'test_large_initial_import[sync_gateway_default_functional_tests]'
```

It stops seeing changes for 2 min, which I would not expected.

**Comment by tleyden** [comment] 2017-06-30 19:55
@sethrosetter after rebooting and uninstalling some software, it's failing with the same errors you are seeing: https://gist.github.com/tleyden/3ff6d326fec66f06a571cae687ec3347

**Comment by tleyden** [comment] 2017-06-30 23:19
I verified @adamcfraser's [hypothesis](https://github.com/couchbase/sync_gateway/issues/2662#issuecomment-310781018) on why this is happening by increasing these ChannelCache settings:

```
	DefaultChannelCacheMaxLength = 500000              // Don't put more than this many entries in cache
	DefaultChannelCacheAge       = 600 * time.Second // Keep entries at least this long
```

after those changes, I cannot repro the issue.  (Previous to that, repro'ing locally in docker every attempt)

**Comment by tleyden** [comment] 2017-06-30 23:46
I verified @adamcfraser's [hypothesis]() by running with modified cache settings:

```
	DefaultChannelCacheMaxLength = 500000              // Don't put more than this many entries in cache
	DefaultChannelCacheAge       = 600 * time.Second // Keep entries at least this long
	DefaultSkippedSeqMaxWait      = 600 * time.Minute // Max time we'll wait for an entry in the missing before purging
	DefaultCachePendingSeqMaxNum  = 1000000            // Max number of waiting sequences
```

and now it's passing consistently (before the change, failed consistently)

**Comment by tleyden** [comment] 2017-07-01 00:48
> This bug looks like it's happening in the case where a skipped sequence is cached, but:
> 
> 1. the channel cache is full
> 2. the skipped sequence is older than the oldest entry in the channel cache
> 3. the skipped sequence gets added to and then immediately pruned from the cache 

I added verbose logging, and what I'm seeing fits that description:

```
2017-07-01T00:41:36.021Z Cache: Received #651 after 198313ms ("sdk_7749" / "1-f241412d729240981ea646005f61ef07")
2017-07-01T00:41:36.023Z Cache:   Received previously skipped out-of-order change (seq 651, expecting 2327) doc "sdk_7749" / "1-f241412d729240981ea646005f61ef07"
2017-07-01T00:41:36.023Z Cache:     addToCache() (SKIPPED) docid: sdk_7749 seq #651 ==> channel "created_via_sdk"
2017-07-01T00:41:36.023Z Cache:      addToCache() oldest sequence: 1167  docid of oldest seq: sdk_9401
2017-07-01T00:41:36.024Z Cache+: LogEntries.appendChange: out-of-order sequence #651 (last is #2326) - handling as insert
2017-07-01T00:41:36.024Z Cache:     calling pruneCache() triggered by adding docid: sdk_7749 seq #651 ==> channel "created_via_sdk"
2017-07-01T00:41:36.024Z Cache:     pruning: 1 entries from channel cache to get below 500.  validfrom: 602
2017-07-01T00:41:36.024Z Cache:     pruning: over-max-len doc id sdk_7749 seq: 651
2017-07-01T00:41:36.025Z Cache:     pruning: new validFrom 652
```

another example from a different run:

```
2017-07-01T00:57:07.497Z Cache:   Received previously skipped out-of-order change (seq 25721, expecting 29802) doc "sdk_18187" / "1-f241412d729240981ea646005f61ef07"
2017-07-01T00:57:07.497Z Cache:     addToCache() (SKIPPED) docid: sdk_18187 seq #25721 ==> channel "created_via_sdk"
2017-07-01T00:57:07.498Z Cache:      addToCache() oldest sequence: 26079  docid: sdk_18872
2017-07-01T00:57:07.498Z Cache:      addToCache() most recent sequence: 29801  docid: sdk_29576
2017-07-01T00:57:07.498Z Cache+: LogEntries.appendChange: out-of-order sequence #25721 (last is #29801) - handling as insert
2017-07-01T00:57:07.499Z Cache:     calling pruneCache() triggered by adding docid: sdk_18187 seq #25721 ==> channel "created_via_sdk"
2017-07-01T00:57:07.499Z Cache:     pruning: 1 entries from channel cache to get below 500.  validfrom: 26075
2017-07-01T00:57:07.499Z Cache:     pruning: over-max-len doc id sdk_18187 seq: 25721
2017-07-01T00:57:07.499Z Cache:     pruning: new validFrom 25722
```

**Comment by tleyden** [comment] 2017-07-06 00:25
I added a unit test which reproduces my current understanding of the problem, and a "workaround fix" in a8db69ec19cb94c785f1c50bf79b3745740caae6 that increases the channel cache in certain cases, and the unit test now passes.

**Comment by tleyden** [comment] 2017-07-06 00:29
When re-testing the functional test, it's still failing.  It looks to be related to "old entries" pruned in this code:

```
	for len(c.logs) > c.options.ChannelCacheMinLength && time.Since(c.logs[0].TimeReceived) > c.options.ChannelCacheAge {
		c.validFrom = c.logs[0].Sequence + 1
		base.LogTo("Cache", "    pruning: old doc id %v seq: %v.  new validFrom: %v", c.logs[0].DocID, c.logs[0].Sequence, c.validFrom)
		delete(c.cachedDocIDs, c.logs[0].DocID)
		c.logs = c.logs[1:]
		pruned++
	}
```

which was not considered in https://github.com/couchbase/sync_gateway/commit/a8db69ec19cb94c785f1c50bf79b3745740caae6

In the SG logs during the functional test failure, I'm seeing:

```
2017-07-06T00:22:44.466Z Cache:     addToCache() (SKIPPED) docid: sdk_1519 seq #7843 ==> channel "created_via_sdk"
2017-07-06T00:22:44.467Z Cache:       addToCache() oldest seq: 21339
2017-07-06T00:22:44.468Z Cache+: LogEntries.appendChange: out-of-order sequence #7843 (last is #25927) - handling as insert
2017-07-06T00:22:44.468Z Cache:     calling pruneCache() triggered by adding docid: sdk_1519 seq #7843 ==> channel "created_via_sdk"
2017-07-06T00:22:44.469Z Cache:     pruning: old doc id sdk_1519 seq: 7843.  new validFrom: 7844
```

A skipped sequence is added to the cache late, and is immediately pruned.

**Comment by tleyden** [comment] 2017-07-06 20:02
Looks like the config already supports setting the channel cache settings.

I'm testing this config to make sure it passes the functional test:

```
    "databases":{
        "db":{
            {{ autoimport }}
            "unsupported": {
                {{ xattrs }}
            },
            "server":"{{ server_scheme }}://{{ couchbase_server_primary_node }}:{{ server_port }}",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password",
            "channel_cache_max_length": 500000,
            "channel_cache_expiry": 600
        }
    }
}
```

**Comment by tleyden** [comment] 2017-07-06 20:26
Looks like the settings workaround isn't passing consistently.  On the second attempt, it failed

* [mobile-testkit logs](https://gist.github.com/tleyden/d21e93c5b7fa11f609882ba7a2cb32c0)
* [sg logs](http://cbmobile-testkit-logs.s3.amazonaws.com/issue_2662/sync_gateway_error.log)

That was while testing locally on docker.

**Comment by tleyden** [comment] 2017-07-17 18:00
Proposed fix after chatting w/ @adamcfraser :

1. the channel cache is full
1. the skipped sequence is older than the oldest entry in the channel cache
1. discard the sequence, do NOT update valid from
1. other code should hopefully trigger view re-query

**Comment by tleyden** [comment] 2017-07-18 21:27
In 32912d1c9b04bfc472d811a83aa91e0e5d757f3c, I applied the fix mentioned in https://github.com/couchbase/sync_gateway/issues/2662#issuecomment-315832705 and the unit tests are updated and passing locally.  

Now I am going to try to re-run the functional tests.

**Comment by tleyden** [comment] 2017-07-18 22:42
The functional test is still not passing, here is a snippet of the logs:

```
Missing expected docs: 30000
last_seq: 0
GET http://cbl.1:4984/ 200
Using POST data: {'feed': 'longpoll', 'since': u'0', 'timeout': 60000}
POST http://cbl.1:4984/db/_changes 200
Found 23312 changes
Missing expected docs: 6689
last_seq: 7972::27381
GET http://cbl.1:4984/ 200
Using POST data: {'feed': 'longpoll', 'since': u'7972::27381', 'timeout': 60000}
POST http://cbl.1:4984/db/_changes 200
Found 15967 changes
Missing expected docs: 6063
last_seq: 14307::27381
GET http://cbl.1:4984/ 200
Using POST data: {'feed': 'longpoll', 'since': u'14307::27381', 'timeout': 60000}
POST http://cbl.1:4984/db/_changes 200
Found 9632 changes
Missing expected docs: 6063
last_seq: 19025::27381
```

One thing that looks suspect is that the low end of the compound sequence jumps from 14307->19025, yet no new changes are returned.  I will add some logging to try to diagnose what's going on.

**Comment by tleyden** [comment] 2017-07-20 22:18
Reproduced with extra logging:

* [sg logs](http://cbmobile-testkit-logs.s3.amazonaws.com/issue_2662/sync_gateway_error.log)
* [mobile-teskit logs](https://gist.github.com/tleyden/f94addd9131a7a73c88bfad3e2d64477)

**Comment by tleyden** [comment] 2017-07-21 00:02
After adding a possible workaround in dcbeb8c5bd420a746a8a43066738141d0740b345 which was supposed to fix the low seq from being incremented when it shouldn't be, I'm still seeing the issue.

* [sg logs](http://cbmobile-testkit-logs.s3.amazonaws.com/issue_2662/sync_gateway_error3.log)
* [mobile-testkit logs](https://gist.github.com/tleyden/50c7fd28254ff92dc2bc8c99e54cd772)

**Comment by tleyden** [comment] 2017-07-21 01:39
After adding import logging in d5c052d304c44f2ea8c93ccc12d5d4f71a9f967f, here are updated logs from a failed run:

* [mobile-testkit logs](https://gist.github.com/tleyden/2bdebbfcab9e85252201eea6d12a00cf)
* [sg logs](http://cbmobile-testkit-logs.s3.amazonaws.com/issue_2662/sync_gateway_error4.log)

**Comment by adamcfraser** [comment] 2017-07-21 06:10
After reviewing the logs, I think this logic is incorrect:
https://github.com/couchbase/sync_gateway/compare/feature/issue_2662_missing_changes_large_import_reworked2#diff-cf0ae6cd5d932015b8b7a8a241d5bfa2R127

The incoming sequence shouldn't necessarily be immediately pruned based on time received, if there are older entries resident in the cache.  
e.g. with this starting scenario:
 - ChannelCacheMaxLength = 100
 - ChannelCacheMinLength=50
 - ChannelCacheAge = 60s
 - number of entries in the cache = 50
 - oldest sequence in the cache = 1000

If a new entry with sequence 1500 arrives that's more than 60s old, it shouldn't be pruned immediately - pruning is always done in sequence order from the earliest sequence entry in the cache.  I believe the entirety of wouldImmediatelyBePruned should simply be a comparison of the incoming sequence with validFrom - if it's older than validFrom it can be skipped, otherwise the incoming sequence has the potential to push existing entries out of the cache, and the regular pruning algorithm should be run.

**Comment by tleyden** [comment] 2017-07-21 16:20
Applied fix suggested in https://github.com/couchbase/sync_gateway/issues/2662#issuecomment-316912899, but still able to repro issue locally (will post logs later).

I've never been able to repro this issue on the qedocker.sc.couchbase.com VM.  I retried with the https://github.com/couchbase/sync_gateway/issues/2662#issuecomment-316912899 fix attempt, (commit 1ab8ed23a8d6e7dbf39644860370ff83344c8c60) and it passed 25/25 times.

```
./repeat 25 pytest -s --skip-provisioning --mode=cc --xattrs --server-version=5.0.0-3154 --sync-gateway-version=local -k "test_large_initial_import[sync_gateway_default_functional_tests]" testsuites/syncgateway/functional/tests/
```

**Comment by tleyden** [comment] 2017-07-21 16:23
For https://github.com/couchbase/sync_gateway/issues/2662#issuecomment-316912899 test run:

Mobile-testkit logs: https://gist.github.com/tleyden/f5dd7e7b2ffd701150ac372cc6bed34d

**Comment by tleyden** [comment] 2017-07-22 00:23
After retesting 3866e444437b480e34de53427ecf046111d21d84 locally, which contains a possible fix, it passed several times, and then finally failed with:

```
tem_18', u'test_item_19'], u'_rev': u'1-f241412d729240981ea646005f61ef07', u'_id': u'sdk_29999'}
  > Verify http://cbl.1:4984/db has 30000 docs in changes
GET http://cbl.1:4984/ 200
Using POST data: {'feed': 'longpoll', 'since': 0, 'timeout': 60000}
POST http://cbl.1:4984/db/_changes 200
Found 15990 changes
Missing expected docs: 14011
last_seq: 204::24172
GET http://cbl.1:4984/ 200
Using POST data: {'feed': 'longpoll', 'since': u'204::24172', 'timeout': 60000}
POST http://cbl.1:4984/db/_changes 200
Found 23950 changes
Missing expected docs: 6051
last_seq: 384::24877
GET http://cbl.1:4984/ 200
Using POST data: {'feed': 'longpoll', 'since': u'384::24877', 'timeout': 60000}
POST http://cbl.1:4984/db/_changes 200
Found 24876 changes
Missing expected docs: 5125
last_seq: 5959::24877
FAILEDTearing down test 'test_large_initial_import[sync_gateway_default_functional_tests]'

```

However I don't think that's a valid failure, because it never got 0 changes.  It was just a timeout issue even though new changes were coming in.

In mobile_testkit constant.py, I changed `CLIENT_REQUEST_TIMEOUT` to 360, so hopefully that same timeout won't happen again.  Going to retest it with that new setting.

**Closed as completed** 2017-07-24 16:38 UTC
Labels: P1: high, functional-test-failure

**Comment by tleyden** [comment] 2017-07-24 18:14
I test 0961e03c8dc8b32aef1baf548311cb7265c27bba on the qedocker machine:

I ran a test loop of 50 repeated tests:

```
 ./repeat 50 pytest -s --skip-provisioning --mode=cc --xattrs --server-version=5.0.0-3154 --sync-gateway-version=0961e03c8dc8b32aef1baf548311cb7265c27bba -k "test_large_initial_import[sync_gateway_default_functional_tests]" testsuites/syncgateway/functional/tests/
```

With no failures
