### ISSUE TITLE
[Win 10] Vendor name and version stripped from SG response causing tests to fail

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/sync_gateway#2792] opened 2017-08-09 03:03 UTC
### Sync Gateway version
SG 1.5.0-516

### Operating system
CentOS 7

### Output
SG 1.5.0-515:
```
» http 192.168.33.23:4984  
HTTP/1.1 200 OK
Content-Length: 132
Content-Type: application/json
Date: Wed, 09 Aug 2017 03:00:28 GMT
Server: Couchbase Sync Gateway/1.5.0

{
    "couchdb": "Welcome",
    "vendor": {
        "name": "Couchbase Sync Gateway",
        "version": 1.5
    },
    "version": "Couchbase Sync Gateway/1.5.0(515;db6907a)"
}
```
SG 1.5.0-516:
```
» http 192.168.33.23:4984
HTTP/1.1 200 OK
Content-Length: 72
Content-Type: application/json
Date: Wed, 09 Aug 2017 03:01:27 GMT
Server: /1.5 branch/ commit/

{
    "couchdb": "Welcome",
    "vendor": {
        "name": "",
        "version": 1.5
    },
    "version": "/()"
}
```

### Expected behavior
Correct vendor, version details should be provided

### Actual behavior
Correct vendor, version details are stripped

**Comment by raghusarangapani** [comment] 2017-08-09 03:06
The server detail is also incorrect

**Comment by tleyden** [comment] 2017-08-09 03:43
I spent some time reviewing these files:

- https://github.com/couchbase/sync_gateway/blob/master/set-version-stamp.sh
- https://github.com/couchbase/build/blob/master/scripts/jenkins/mobile/sgw_unix_build.sh

and this build job:

- http://mobile.jenkins.couchbase.com/view/Sync_Gateway/job/sgw-unix-build/configure

And nothing is jumping out at me.  I also tried reverting to an older commit (271f32db0826c94aa6920671e61ccdcf44d5e9ab)

And running locally I still get the same result:

```
{"ADMIN":true,"couchdb":"Welcome","vendor":{"name":"","version":1.5},"version":"/()"}
```

(are these values supposed to be populated when building locally?)

I'm not sure how to proceed on this one.

@ajres do you understand how the `set-version-stamp.sh` script works?  In particular, when is this called by the jenkins mobile build job?  Or if not, do they have an equivalent script?

Does this look correct to you?

## git_info.go

```
$ cat godeps/src/github.com/couchbase/sync_gateway/rest/git_info.go
package rest

// The git commit that was compiled. This will be filled in by the compiler.
const GitProductName = ""
const GitCommit = ""
const GitBranch = ""
const GitDirty = ""
```

## git_info.go.bak

```
$ cat godeps/src/github.com/couchbase/sync_gateway/rest/git_info.go.bak
package rest

// The git commit that was compiled. This will be filled in by the compiler.
const GitProductName = "Couchbase Sync Gateway"
const GitCommit = "e7387a88d25ea7984dd28ce12d82275120cdb284"
const GitBranch = "feature/issue_1019_array_gocb_urls"
const GitDirty = ""
```

How do the values from the `git_info.go.bak` file make it into the compiled binary?

/cc @minddrive @kimtrang

**Comment by adamcfraser** [comment] 2017-08-09 04:19
I think there are two paths in the init() that's in base/version.go (that used to be in rest/api.go) - one used by the jenkins build, and one based on the dev build.  The jenkins build does a sed to update rest/api.go, while the dev build leverages git_info.go

See TEMPLATE_FILES in:

https://github.com/couchbase/build/blob/5e0f672a94fa30ba66dad8d1547a88823e25eee5/scripts/jenkins/mobile/sgw_unix_build.sh
https://github.com/couchbase/build/blob/5e0f672a94fa30ba66dad8d1547a88823e25eee5/scripts/jenkins/mobile/sgw_windows_build.bat

I'm thinking you just need to add base/version.go to the list of TEMPLATE_FILES to keep this working?  (I think you also want to retain rest/api.go, as that would break pre-1.5 builds).

**Comment by tleyden** [comment] 2017-08-09 14:48
Thanks @adamcfraser that sheds some light.  I'll add base/version.go to the list of TEMPLATE_FILES in the sgw_* builds and submit a gerrit review

I still don't get how the dev build is supposed to work.  Why does it replace values in the .bak file?  Where does this get used?

**Comment by adamcfraser** [comment] 2017-08-09 15:02
I think the .bak file is just the backup taken by sed when it modifies git_info.go (from the -i.bak flag in set-version-stamp.sh).  I don't see the motivation behind that backup - particularly since the backup gets overwritten due to the multiple sed commands - but it's git_info.go that's incorporated into the built binary.

What set of calls did you make to get into a state where your git_info.go is empty?  Even running somewhere you didn't have git context should still result in the GitProductName being populated.

**Comment by tleyden** [comment] 2017-08-09 15:30
I pushed up a gerrit PR for the sgw_unix_build.sh change at http://review.couchbase.org/#/c/82120/

Also, I'm creating a separate ticket to look at the Windows sgw_unix_build.bat file (probably better if someone who has access to a windows test machine to look at this)

**Comment by tleyden** [comment] 2017-08-09 15:34
> What set of calls did you make to get into a state where your git_info.go is empty? 

It's empty by default:

https://github.com/couchbase/sync_gateway/blob/master/base/git_info.go

**Comment by tleyden** [comment] 2017-08-10 17:36
Verified by downloading and installing http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.5.0/1.5.0-522/couchbase-sync-gateway-community_1.5.0-522_x86_64.rpm

```
# curl localhost:4984
{"couchdb":"Welcome","vendor":{"name":"Couchbase Sync Gateway","version":1.5},
"version":"Couchbase Sync Gateway/1.5.0(522;b60eae5)"}
```

**Comment by tleyden** [comment] 2017-08-10 19:44
Looks like sg-accel is reporting itself as sync gateway

```
{"ADMIN":true,"couchdb":"Welcome","vendor":{"name":"Couchbase Sync Gateway","version":1.5},"version":"Couchbase Sync Gateway/1.5.0(522;b60eae5)"}
```

but the test expects sg-accel

```
11:14:36 >           raise ProvisioningError("Wrong product info. Expected 'Couchbase SG Accel'")

```

**Comment by tleyden** [comment] 2017-08-10 19:57
Pretty sure I found the issue.

It's not using the bash array syntax here:

https://github.com/couchbase/build/blob/ee75d2598ac3e572ccf1222efe01ba1ccdc9a4a9/scripts/jenkins/mobile/sgw_unix_build.sh#L243

**Comment by adamcfraser** [comment] 2017-08-11 05:03
Should be addressed in 1.5.0-525

**Comment by raghusarangapani** [comment] 2017-08-14 04:56
Re-opening as the windows binaries are still broken

**Comment by adamcfraser** [comment] 2017-08-14 04:57
@raghusarangapani Can you update the issue title to make it clear it's Windows-specific?

**Comment by tleyden** [comment] 2017-08-14 18:43
To verify:

* Run sync_gateway from installer executable
* `curl locahost:4984`
* Make sure it has the correct version details.   Example output below:

```
{
  "couchdb": "Welcome",
  "vendor": {
    "name": "Couchbase Sync Gateway",
    "version": 1.5
  },
  "version": "Couchbase Sync Gateway/feature/issue_2725(a4a6ad7)"
}
```

It won't look exactly like this, but note that the name and version fields are non-empty

**Comment by kimtrang** [comment] 2017-08-14 23:49
The next build of sgw-windows-build should have the proper fix that you checked in.  There was no code changes required on my side.  Jenkin's job was mis-configured.  Will discuss offline with Ceej when he's back.  I've built it locally and verified the changes.

**Comment by tleyden** [comment] 2017-08-15 01:09
Thanks @kimtrang -- can you post a link to the commit?

**Comment by kimtrang** [comment] 2017-08-15 17:38
@tleyden There were no commit, Jenkins's job wasn't using the correct build script from git.  Build from 1.5.0.530+ should have the correct changes.

**Closed as completed by kimtrang** 2017-08-15 17:38 UTC
Labels: P1: high, functional-test-failure

**Comment by tleyden** [comment] 2017-08-15 17:43
@kimtrang ok thanks.  Can you post the filename of both the old build script and the new build script?  Could switching to the new build script cause any new regressions?

**Comment by kimtrang** [comment] 2017-08-15 17:46
@tleyden   diff between src_in_git vs. src_on_jenkins

```
$ diff sgw_windows_build.bat   sgw_windows_build.bat.jenkins
131d130
< if EXIST "godeps\src\github.com\couchbase\sync_gateway\base\version.go"  set TEMPLATE_FILE="godeps\src\github.com\couchbase\sync_gateway\base\version.go"
135,137c134
< set PRODUCT_NAME=%SG_PRODUCT_NAME%
< 
< echo ======== insert %PRODUCT_NAME% build meta-data ==============
---
> echo ======== insert build meta-data ==============
144c141
<     set LINEB=!LINEA:@PRODUCT_NAME@=%PRODUCT_NAME%!
---
>     set LINEB=!LINEA:@PRODUCT_NAME@=%SG_PRODUCT_NAME%!
156c153
< echo ======== build %PRODUCT_NAME% ===============================
---
> echo ======== build ===============================
185,211d181
< 
<     set PRODUCT_NAME=%ACCEL_PRODUCT_NAME%
< 
<     echo ======== remove build meta-data ==============
<     move  %TEMPLATE_FILE%.orig  %TEMPLATE_FILE%
< 
<     echo ======== insert %PRODUCT_NAME% build meta-data ==============
< 
<     setlocal disabledelayedexpansion
<     for /F "usebackq tokens=1* delims=]" %%I in (`type %TEMPLATE_FILE% ^| find /V /N ""`) do (
<         if "%%J"=="" (echo.>> %TEMPLATE_FILE%.new) else (
<         set LINEA=%%J
<         setlocal enabledelayedexpansion
<         set LINEB=!LINEA:@PRODUCT_NAME@=%PRODUCT_NAME%!
<         set LINEC=!LINEB:@PRODUCT_VERSION@=%VERSION%!
<         set LINED=!LINEC:@COMMIT_SHA@=%REPO_SHA%!
<         echo !LINED!>> %TEMPLATE_FILE%.new
<         endlocal )
<         )
<     endlocal
< 
<     dos2unix %TEMPLATE_FILE%.new
<     move     %TEMPLATE_FILE%       %TEMPLATE_FILE%.orig
<     move     %TEMPLATE_FILE%.new   %TEMPLATE_FILE%
```

**Comment by tleyden** [comment] 2017-08-15 18:51
Recap: looks like what happened is that at some point https://github.com/couchbase/build/blob/master/scripts/jenkins/mobile/build_sgw_windows.bat was copied into a local file on Jenkins, and the Jenkins job was updated to use the local file rather than the version in github, which is why the recent fix to the version in github was not picked up.

@kimtrang's change was primarily to reconfigure jenkins to use https://github.com/couchbase/build/blob/master/scripts/jenkins/mobile/build_sgw_windows.bat rather than the (duplicated) local file, so the fix was picked up.

**Comment by tleyden** [comment] 2017-08-15 18:52
@raghusarangapani were you able to verify this fix yet?

**Comment by raghusarangapani** [comment] 2017-08-15 21:06
Verified with 1.5.0-532:
```
» http 192.168.33.25:4985                                      
HTTP/1.1 200 OK
Content-Length: 145
Content-Type: application/json
Date: Tue, 15 Aug 2017 20:56:05 GMT
Server: Couchbase Sync Gateway/1.5.0

{
    "ADMIN": true,
    "couchdb": "Welcome",
    "vendor": {
        "name": "Couchbase Sync Gateway",
        "version": 1.5
    },
    "version": "Couchbase Sync Gateway/1.5.0(532;96208d5)"
}

» http 192.168.33.26:4985
HTTP/1.1 200 OK
Content-Length: 137
Content-Type: application/json
Date: Tue, 15 Aug 2017 21:03:37 GMT
Server: Couchbase SG Accel/1.5.0

{
    "ADMIN": true,
    "couchdb": "Welcome",
    "vendor": {
        "name": "Couchbase SG Accel",
        "version": 1.5
    },
    "version": "Couchbase SG Accel/1.5.0(532;96208d5)"
}
```
