### ISSUE TITLE
Implement a proper Linux service via RPM installation

### ISSUE THREAD

**Issue by krugster** [couchbase/sync_gateway#1164] opened 2015-09-23 17:03 UTC
At the moment we have a separate script that needs to be run to turn the Sync Gateway into a service but it has been rather error-prone and also doesn't seem to follow normal linux conventions of using init scripts and service registration.

It would be much more desirable to have the RPM/deb and even Windows installation paths handle this automatically for the user much as it does for the Couchbase Server installations.

**Comment by ajres** [comment] 2015-09-23 17:13
This looks like a duplicate of #1022

The sync_gateway_service_install.sh script does install init scripts and service registration for each platform, FYI  following is code block that does that.

```
#Install the service for the specific platform
case $OS in
    Ubuntu)
        case $OS_MAJOR_VERSION in
            12|14)
                setup_output_dirs
                render_template script_templates/upstart_ubuntu_sync_gateway.tpl > /etc/init/${SERVICE_NAME}.conf
                service ${SERVICE_NAME} start
                ;;
            *)
                echo "ERROR: Unsupported Ubuntu Version \"$VER\""
                usage
                exit 1
                ;;
        esac
        ;;
    RedHat|CentOS)
        case $OS_MAJOR_VERSION in
            6)
                setup_output_dirs
                render_template script_templates/upstart_redhat_sync_gateway.tpl > /etc/init/${SERVICE_NAME}.conf
                initctl start ${SERVICE_NAME}
                ;;
            7)
                setup_output_dirs
                render_template script_templates/systemd_sync_gateway.tpl > /usr/lib/systemd/system/${SERVICE_NAME}.service
                systemctl enable ${SERVICE_NAME}
                systemctl start ${SERVICE_NAME}
                ;;
            *)
                echo "ERROR: Unsupported RedHat/CentOS Version \"$VER\""
                usage
                exit 1
                ;;
        esac
        ;;
    Darwin)
        setup_output_dirs
        render_template script_templates/com.couchbase.mobile.sync_gateway.plist > /Library/LaunchDaemons/com.couchbase.mobile.sync_gateway.plist
        launchctl load /Library/LaunchDaemons/com.couchbase.mobile.sync_gateway.plist
        ;;
    *)
        echo "ERROR: unknown OS \"$OS\""
        usage
        exit 1
        ;;
esac
```

**Comment by krugster** [comment] 2015-09-23 17:30
Apologies for the duplication Andy.  Is that code block that you referenced already in SG as of 1.1.1 or is it something that will be coming in 1.2?

**Comment by zgramana** [comment] 2015-09-23 17:46
Closing as a duplicate of #1022.

**Closed as completed by zgramana** 2015-09-23 17:46 UTC

**Comment by ajres** [comment] 2015-09-23 17:55
That code block is in the 1.1.1 release.
