### ISSUE TITLE
Sync gateway to sync gateway stops syncing even if one document is rejected by sync function

### ISSUE THREAD

**Issue by erpankaj22** [couchbase/sync_gateway#3375] opened 2018-03-21 18:53 UTC
We have a expiry time in each document, this expiry time is in epoch. If the time has expired then we reject the document using sync function.

Sync gateway to sync gateway sync stops as soon as one document in the pipeline is rejected by the sync gateway. It goes into a loop where it will not continue syncing any document further.

We need to stop taking the document because we purge them, hence having minimum number of required document in the bucket. So the documents according to business rule will never come back after the purge. And even if they come the data is useless.

What is the workaround to not to stop sync. Is marking them _deleted is the only solution for this. If yes then will tombstone will also be cleared from the application automatically or a compact function call will be required.

the expiry is not the standard TTL. It is a cusom field in which we put date time in EPOCH after which updates of these documents will be discarded on the sync gateway and following is the sync function for the same we are using

function(doc,oldDoc)
{
var d = new Date();
var n = d.getTime();
if(doc.ExpiryDateEpoch!=null)
{
if(n >= doc.ExpiryDateEpoch)
{
throw( { forbidden: “Document Expired” } );
}
}
channel(doc.channels);
}

now in when the SG to SG replicate starts then this issue comes even if one of the document whose ExpiryDateEpoch has crossed is rejected by the function.

Following is the forum id :- https://forums.couchbase.com/t/sync-gateway-to-sync-gateway-stops-syncing-even-if-one-document-is-rejected-by-sync-function/16237/3

**Comment by tleyden** [comment] 2018-04-12 20:06
Closing as duplicate of https://github.com/couchbase/sync_gateway/issues/3387

**Closed as completed by tleyden** 2018-04-12 20:06 UTC
Labels: P1: high

**Comment by tleyden** [comment] 2018-04-27 21:44
@erpankaj22 Which version of Sync Gateway are you running?  From what I can tell, this should already be working as expected.  See https://github.com/couchbase/sync_gateway/issues/3387#issuecomment-385101541
