### ISSUE TITLE
[Distributed Index] _changes with quoted since value return 500 internal server error

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1168] opened 2015-09-24 00:09 UTC
Should both of these be valid queries?

 http://localhost:4985/db/_changes?since=220::222 (SUCCEEDS) 
http://localhost:4985/db/_changes?since="220::222" (FAILS) 

If the second query should be valid, your issue is here https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/db/sequence_id.go#L64.

 "\"220::222\"” gets split into ““220”, “:”, “:” “222”” and it blows up with an internal server error.

**Comment by ajres** [comment] 2015-09-24 11:24
Are you seeing this issue on master or the distributed-index branch?

On master the following call returns without error:

```
http://localhost:4985/db/_changes?since="220::222"
```

Support for JSON encoded strings was [added](https://github.com/couchbase/sync_gateway/commit/876243c08d9175990c9aa76c44e4ddfcb0a12733) as part of #988 

I have [added](https://github.com/couchbase/sync_gateway/pull/1169) two new unit test steps for the 3 part sequence ID's as those were not covered on master.

**Comment by tleyden** [comment] 2015-09-24 16:43
@ajres this was on the distributed_index branch

**Comment by ajres** [comment] 2015-09-24 16:46
The link to the code line above is for master, distributed_index has been updated considerably to support vector clock hash based sequences.

Can you post the stack trace to this ticket.

**Comment by tleyden** [comment] 2015-09-24 16:50
@ajres oh, hmm.  @sethrosetter weren't you testing this against distributed_index?

@ajres I guess the easy way to settle this is to cherry pick the commit onto the distributed_index branch and see if it passes.

**Comment by ajres** [comment] 2015-09-24 16:55
Looks like distributed_index should already support JSON encoded sequence values.

A stack trace would allow us to see the code path that caused the panic.

**Comment by sethrosetter** [comment] 2015-09-24 17:19
It was against the feature/distributed_index branch locally and failing due to not escaping the string. I will try to get you a stack trace.

**Comment by sethrosetter** [comment] 2015-10-12 17:23
here is a link to the error in the functional tests targeting the feature/distributed_index branch - https://gist.github.com/sethrosetter/e928647262c4cc9b9f47#file-error-log-L953-L956

**Comment by adamcfraser** [comment] 2015-10-16 18:55
This is just a case of something that's been fixed on master (#988), that hasn't been cherry-picked to distributed-index.  

This will work in 1.2 when we merge distributed-index down to master.  Leaving as-is until it's a blocker (or until merge happens).

**Comment by ajres** [comment] 2015-12-14 14:49
Confirmed this is fixed and has unit tests in master, do you want this cherry picked to the distributed_index branch?

**Comment by adamcfraser** [comment] 2015-12-14 17:24
No - this can wait for merge to master.

**Comment by ajres** [comment] 2016-01-04 16:11
Retested against latest master with distributed index merged, quoted three part since values are handles by _changes without error.

**Comment by ajres** [comment] 2016-01-04 16:11
Passing back to testing to close out.

**Comment by zgramana** [comment] 2016-01-20 19:06
@sethrosetter will double-check failing test, but passes locally.

**Comment by sethrosetter** [comment] 2016-01-20 22:33
was able to repo this against commit 046f5f1 (original commit that this was reported on ) - https://gist.github.com/sethrosetter/eeeeeeeca74c05c0af9d#file-test-046f5f1-log-L836-L837

Verified fixed in 185eb7b68d25c243168b10600ff1d103c1b407cc - https://gist.github.com/sethrosetter/c885f553f9d8e7b49149#file-test-185eb7-log-L1318-L1320

**Closed as completed** 2016-01-20 22:34 UTC
