### ISSUE TITLE
Gocb retry logic: _changes intermittently returning 0 results for distributed index 

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1253] opened 2015-10-30 17:26 UTC
Couchbase Sync Gateway/feature/distributed_index(d81a303)

Logs are filed in S3 - sync-gateway-logs/2015-10-30-9-59-sg_logs.zip

Looks like it is related to gocb timeouts

2015-10-30T09:48:59.762-07:00 WARNING: Error doing bulk get:%!(EXTRA gocb.timeoutError=The operation has timed out.) -- db.(_BitFlagStorage).bulkLoadEntries() at kv_channel_storage.go:330
2015-10-30T09:48:59.762-07:00 WARNING: Error unmarshalling entry for key%!(EXTRA string=_idx_entry:0:6) -- db.(_BitFlagStorage).bulkLoadEntries() at kv_channel_storage.go:345
2015-10-30T09:48:59.762-07:00 WARNING: Error unmarshalling entry for key%!(EXTRA string=_idx_entry:0:5) -- db.(*BitFlagStorage).bulkLoadEntries() at kv_channel_storage.go:345

**Comment by adamcfraser** [comment] 2015-11-03 23:31
Two possibilities here: bulk_get is failing under heavy load on gocb (coming from elsewhere), or we're doing a bulk_get with a very large number of keys, and it's timing out retrieving them all.

Could try to reproduce the second possibility first.

**Comment by adamcfraser** [comment] 2015-11-03 23:49
Discussed with Traun - the first step should be to get CouchbaseBucketGoCB to work similar to go-couchbase - by default, block/retry indefinitely.  This will get us to the same level of correctness provided by go-couchbase.

Next step would be to accept an input flag for operations indicating whether they should block.  This would allow us to start responding to backpressure more appropriately (e.g. stepping back polling frequency, etc).

**Comment by tleyden** [comment] 2015-11-13 20:11
Related to https://github.com/couchbase/sync_gateway/issues/1289

**Comment by tleyden** [comment] 2015-12-04 18:47
@adamcfraser do you think this can be considered a duplicate of #1289 or is the other work needed to be done?

**Closed as completed** 2015-12-15 17:46 UTC
Labels: bug
