### ISSUE TITLE
High Write Disk IO when requesting informations about a shadow bucket

### ISSUE THREAD

**Issue by stephanelorcy** [couchbase/sync_gateway#1328] opened 2015-12-06 16:08 UTC
We use the sync-gateway in front of a couchbase server to synchronize information beetwen a mobile device and our IS.

We have several channels and, for a given channel, documents are locally stored in a dedicated local database (one local database per channel).

In our use case, documents are read-only ones. And we synchronize only in a single way: from the server to the device. We use classic `_change` http request.

We have made some stressing tests in the worst scenario : 1000 users synchronize all the documents from scratch (local databases are emtpy). We have 20 channels and about 100 documents per channel. Documents are very light (less than 1 KO). Each channel is relied to a single couchbase bucket.

During these tests, we have discovered an abnormal write disk io activity even if we only made read access (documents pushed to the devices are never modified on these devices).

Specially, one single `vbucket` presents a suspicious write activity. We have discovered that this `vbucket` contains the `_syn:seq` document and that this document is modified after each request to obtain information about a db (we use this request in each device in order to obtain the last seq of the bucket).

So my question is: why this document is modified for each read request `/host/buckname` ? If 1000 users fire one information request per channel, these 20 000 requests generate 20 000 modifications of this document, which explains the abnormal activity of the `vbucket`. The modified attribute seems to be the `upstreamCAS` (and of course the `rev` attribute of the document). I precise that our sync-gateway use a `shadow bucket` to serve our documents through our channels.
This behaviour is very expensive for the memcached process of the couchabse node and, which is a bad news, even if we only make `reads` on our documents, and never `writes`. I understand that high modifications rate generates a high write activity but I'm surprised that we are in the same situation with only high read rate. 

Thank you very much for your explanations. Do you have any solution to avoid this behaviour ? I've found a workaround on the device client: I intercept each ''/host/bucketname`` request and use a cache with a short ttl (about 1 or 2 seconds) to avoid that the request reaches the gateway, but I don't think it's a sustainable solution.

**Comment by ajres** [comment] 2015-12-07 16:24
@stephanelorcy 

I have reproduced the behavior where calling 

```
curl -X GET http://host:4985/db/
```

Causes vBucket writes

This calls

```
func (s *sequenceAllocator) lastSequence() (uint64, error) {
```

in sequence_allocator.go which in turn calls 

```
func (s *sequenceAllocator) incrWithRetry(key string, numToReserve uint64) (uint64, error) {
```

in sequence_allocator.go, which calls 

```
s.bucket.Incr(key, numToReserve, numToReserve, 0)
```

On sgbucket,  with an increment of 0, it looks like this call causes the vBucket writes.

**Comment by zgramana** [comment] 2015-12-07 19:22
@stephanelorcy you seem to have a bunch of unusual use-cases. Can you explain a bit more about what you're solving?

**Comment by stephanelorcy** [comment] 2015-12-08 10:35
@zgramana I've tried to explicit my use case in my other ticket : #1327
You can read here : https://github.com/couchbase/sync_gateway/issues/1327

Thank you for your interest.

**Comment by adamcfraser** [comment] 2020-02-07 00:09
Closing, as bucket shadowing has been deprecated and replaced by shared bucket access.

**Closed as completed by adamcfraser** 2020-02-07 00:09 UTC
Labels: enhancement, performance, icebox
