### ISSUE TITLE
Sync Gateway should allow for the customization of session cookie names.

### ISSUE THREAD

**Issue by merrickcouchbase** [couchbase/sync_gateway#2183] opened 2016-11-30 01:13 UTC
Currently, Sync Gateway's session cookie name is not user-configurable.

It would be nice to have the ability to modify this so that for example, one could host multiple backend Couchbase buckets with the same domain without having to use the conventional approach to set cookies with a full path where session-based authentication against each individual bucket is required.

This would be a configuration setting that would be loaded at startup, not runtime.

**Comment by tleyden** [comment] 2016-11-30 01:32
Looks like a duplicate of https://github.com/couchbase/sync_gateway/issues/2096

@merrickcouchbase if there are some differences, feel free to re-open or add requirements to #2096

**Closed as completed by tleyden** 2016-11-30 01:32 UTC
