### ISSUE TITLE
Create and distribute a diagnostics tool

### ISSUE THREAD

**Issue by zgramana** [couchbase/sync_gateway#1331] opened 2015-12-08 01:25 UTC
Looking for an equivalent of `cbcollect_info`.

**Comment by zgramana** [comment] 2015-12-08 17:41
Currently [re-purposing](https://github.com/couchbase/sync_gateway/tree/issues/1331) `cbcollect_info` as `sgcollect_info`.

**Comment by mattcarabine** [comment] 2016-01-11 16:14
In support, we use tools to automatically parse cbcollect_infos, it would be very nice to be able to do this for sgcollect_infos too, as you are repurposing the system level information from cbcollect this should be possible.

I just have one ask and that is to easily be able to identify if the zip file if an sgcollect_info or a cbcollect_info, just something like 'sync gateway logs' at the top of one of the files would be great.

**Comment by b33f** [comment] 2016-01-11 16:16
cbcollect_info is also a moving target, would it be possible to have a shared library between sgcollect_info and cbcollect_info so that updates to system stats in one get reflected in the other ?

**Comment by mattcarabine** [comment] 2016-01-24 17:46
I realise my previous was very poorly defined, something along the lines of renaming `couchbase.log` (the main system level information) to `sync_gateway.log` would be fantastic. It means we can determine whether or not a zip file is a cbcollect or an sgcollect without even having to open and parse any of the contained files.

**Comment by zgramana** [comment] 2016-02-24 22:19
@mattcarabine good point. This is a WIP, so nows the time to throw in requests. :)

@b33f this is a good idea. The system tasks code alone would be very useful to have on PIP. The S3, CBSE tagging stuff, etc., probably not so much, but still a prime candidate for a module.

**Comment by tleyden** [comment] 2016-03-24 19:24
Closing as a dupe of https://github.com/couchbase/sync_gateway/issues/1640

**Closed as completed by tleyden** 2016-03-24 19:24 UTC
Labels: enhancement
