### ISSUE TITLE
The max ttl value of session is less than 259200 in sync gateway 1.1 + couchbase 3.0, but can be more than 259200 in sync gateway 1.1 + walrus: 

### ISSUE THREAD

**Issue by atom992** [couchbase/sync_gateway#974] opened 2015-07-06 07:16 UTC
By Sync Gateway(1.1) Admin REST API, the following request 

curl -X POST -H "Content-Type: application/json"  -d '{"name": "testuser", "password": "password","ttl":2592001}' 'http://127.0.0.1:4985/sgdb/_session'
return success:
{"session_id":"59ce075cf41e56ca6bfe7ba3e4d2e367be16560e","expires":"2015-08-05T14:50:54.427251703+08:00","cookie_name":"SyncGatewaySession"}
but I can not find this session in couchbase, at the same time, I can not get the session info by:
curl -X GET -H "Content-Type: application/json"  http://127.0.0.1:4985/sgdb/_session/59ce075cf41e56ca6bfe7ba3e4d2e367be16560e'
this will response:
{"error":"not_found","reason":"missing"}

and If I use walrus: to startup sync gateway(1.1) I can get the session info which ttl is larger than 2592000.

**Comment by ajres** [comment] 2015-07-06 15:32
I think the issue is related to using an int internally to store the ttl after it has been converted to milliseconds (*1000).

We should investigate changing to uint64 type.

**Comment by ajres** [comment] 2015-07-06 16:12
It looks like this is ultimately related to the Couchbase Server Document expiry.

Here is some info from the docs:

If you specify a TTL as a relative value of seconds into the future, it is actually stored in Couchbase Server as an absolute Unix time stamp. This means, for example, if you store an item with a two-day relative TTL, immediately make a backup, and then restore from that backup three days later, the expiration will have passed and the data is no longer there.

Here is how to specify a TTL:

To set a value of 30 days or less: If you want an item to live for less than 30 days, you can provide a TTL in seconds or as Unix time. The maximum value you can specify in seconds is the number of seconds in a month, namely 30 x 24 x 60 x 60. Couchbase Server removes the item the given number of seconds after it stores the item.
To set a value over 30 days: If you want an item to live for more than 30 days, you must provide a TTL in Unix time.

The 30day limit is exactly 2592000 seconds

If we want to support session ttl over 30days we need to pass valid UNIX epoc time values for document expiration.

**Comment by ajres** [comment] 2015-07-06 17:44
@atom992 

Can you share your use case for creating sessions with a ttl longer that a month?

Andy

**Comment by atom992** [comment] 2015-07-07 14:36
My app want to hold user's certificate for 3 month, so within 3 month, user needn't login again.

**Comment by tleyden** [comment] 2015-08-10 17:48
Closing as duplicate of #1049

**Comment by ajres** [comment] 2015-09-01 18:10
Ticket #1105 is dependent on this fix.

**Closed as completed** 2015-09-04 23:03 UTC
Labels: bug, enhancement, P3: low
