### ISSUE TITLE
SG to CB over SSL

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#1552] opened 2016-02-01 22:56 UTC
HOST ARRAY:
Looks like utl.go is not looking for array of hostnames to the CB cluster. It be nice to pass a few hostname just in case the CB cluster is missing the initial node and SG needs to get restarted. 

SSL PORT:
When I pass httpS://(hostname_here):18091 looks like SG hangs

**Comment by adamcfraser** [comment] 2016-02-01 23:04
For the host array issue - there's already an open ticket for that:
https://github.com/couchbase/sync_gateway/issues/1019

I haven't heard of any issues trying to use SSL between SG and Couchbase Server.  Can you share the SG logs when it hangs?

**Comment by househippo** [comment] 2016-02-01 23:24
modded basic-couchbase-bucket.json  with https://(hostname):18091
{
  "log": ["_"],
  "interface":"10.0.2.15:4984",
  "databases": {
    "db": {
      "server": "https://10.0.2.15:18091",
      "bucket": "default",
      "users": { "GUEST": { "disabled": false, "admin_channels": ["_"] } }
    }
  }
}

OUTPUT from bin/sync_gateway basic-couchbase-bucket.json 2>> ssl-log.log &

016-02-01T15:19:06.469-08:00 Enabling logging: [*]
2016-02-01T15:19:06.469-08:00 ==== Couchbase Sync Gateway/master(185eb7b) ====
2016-02-01T15:19:06.469-08:00 Configured process to allow 4096 open file descriptors
2016-02-01T15:19:06.469-08:00 Opening db /db as bucket "default", pool "default", server https://10.0.2.15:18091
2016-02-01T15:19:06.469-08:00 Opening Couchbase database default on https://10.0.2.15:18091

When I change it back to "server": "http://10.0.2.15:8091",  works without issue.

**Comment by househippo** [comment] 2016-02-01 23:52
Double checked that 18091 responds
INPUT curl https://10.0.2.15:18091/pools/ -k

OUTPUT (below)

{"pools":[{"name":"default","uri":"/pools/default?uuid=0f2ff6cf80eac7365c4a2f7073834edf","streamingUri":"/poolsStreaming/default?uuid=0f2ff6cf80eac7365c4a2f7073834edf"}],"isAdminCreds":false,"isROAdminCreds":false,"isEnterprise":true,"settings":{"maxParallelIndexers":"/settings/maxParallelIndexers?uuid=0f2ff6cf80eac7365c4a2f7073834edf","viewUpdateDaemon":"/settings/viewUpdateDaemon?uuid=0f2ff6cf80eac7365c4a2f7073834edf"},"uuid":"0f2ff6cf80eac7365c4a2f7073834edf","implementationVersion":"4.1.0-5005-enterprise","componentsVersion":{"lhttpc":"1.3.0","os_mon":"2.2.14","public_key":"0.21","asn1":"2.0.4","kernel":"2.16.4","ale":"4.1.0-5005-enterprise","inets":"5.9.8","ns_server":"4.1.0-5005-enterprise","crypto":"3.2","ssl":"5.3.3","sasl":"2.3.4","stdlib":"1.19.4"}}

**Comment by adamcfraser** [comment] 2016-02-02 00:08
When you say Sync Gateway appears to hang - do you see any errors when attempting to perform a basic SG operation (like a document PUT through the admin API)?  Or do requests time out?

**Comment by househippo** [comment] 2016-02-02 01:21
SG version: 1.2 (I pulled and built from source last Thursday - Friday~ish)

> When you say Sync Gateway appears to hang - do you see any errors when attempting to perform a basic SG operation (like a document PUT through the admin API)? Or do requests time out?

It never responds to any CRUD operations and I do not say any type ack in the logs. I think its b/c it never connects to CB cluster.

I do see connects get ESTABLISHED when I start SG though(Below).

Every 2.0s: netstat -at | grep 18091                                                                                                                                                                    Mon Feb  1 17:05:06 2016

tcp        0      0 _:18091                 *:_                     LISTEN
tcp        0      0 10.0.2.15:18091         10.0.2.15:55662         ESTABLISHED
tcp        0      0 10.0.2.15:55662         10.0.2.15:18091         ESTABLISHED

**Comment by adamcfraser** [comment] 2016-02-02 01:25
Can you try switching to log "*" to see if you get any additional diagnostics in the SG log?

**Comment by househippo** [comment] 2016-02-02 01:34
Adam,

In think github removed the star in the (above) log:[] ,but thats what what I was running with the star(all). Let me do a TCP dump tonight on 18091 and see whats being sent and received.

**Comment by adamcfraser** [comment] 2016-02-02 01:43
Thanks.  It's possible that go-couchbase doesn't yet support an SSL connection to Couchbase Server, but I would have expected the default TLS config on the golang Client to support it automatically.  I'll wait to hear what you find.

**Comment by househippo** [comment] 2016-02-02 08:52
**TEST:**
Start TCPdump via  sudo tcpdump -i any -w (somefile).pcap

**RESULT:**
(image attached below)

I can see the GET for /pools to the 18091 port in LINE 906(in BLUE). It looks like it  gets an ack from the CB cluster on LINE 907 then no more traffic. And thats when SG probably just stops ,reflecting the logs. 
but if you check out the full request looks like its only switching the port only.

<img width="1422" alt="screen shot 2016-02-02 at 12 28 15 am" src="https://cloud.githubusercontent.com/assets/4956099/12743663/0cbf5012-c944-11e5-9f5b-d7e1ee9e5c01.png">

**Comment by adamcfraser** [comment] 2016-02-02 16:58
It looks like it's trying to connect to the server via http, instead of https.

It looks like go-couchbase doesn't yet support connecting to Couchbase server over https - there are still a number of places it's hardcoding the protocol, including the pools call:
https://github.com/couchbase/go-couchbase/blob/master/pools.go#L491

**Comment by ryanthompson0123** [comment] 2016-12-16 18:48
go-couchbase now supports https as of [this commit](https://github.com/couchbase/go-couchbase/commit/9bac28777e8f2a58ad6bb16770289eb15f961104)

What's the status on this ticket? I need this ability to satisfy HIPAA requirements.

**Comment by adamcfraser** [comment] 2016-12-19 21:34
@ryanthompson0123 Sync Gateway 1.3.1 is on a later commit of go-couchbase, but we haven't done any internal testing of SSL between SG and CBS yet.

**Comment by tleyden** [comment] 2017-08-03 00:31
I just tried to test this out on the `feature/issue_1019_array_gocb_urls` branch (from https://github.com/couchbase/sync_gateway/issues/1019 in progress ticket), and I'm seeing these errors when pointing sync gateway to server URL `couchbases://cb1,cb2,cb3` (whereas it works with non-SSL URL `couchbase://cb1,cb2,cb3`):

```
2017-08-03T00:22:14.189Z WARNING: Error processing DCP stream - will attempt to restart/reconnect: Get https://cb1:8091/pools: http: server gave HTTP response to HTTPS client -- base.(*DCPReceiver).OnError() at dcp_feed.go:123
2017-08-03T00:22:14.191Z WARNING: Error processing DCP stream - will attempt to restart/reconnect: Get https://cb2:8091/pools: http: server gave HTTP response to HTTPS client -- base.(*DCPReceiver).OnError() at dcp_feed.go:123
2017-08-03T00:22:14.192Z Starting server on :4984 ...
2017-08-03T00:22:14.193Z WARNING: Error processing DCP stream - will attempt to restart/reconnect: Get https://cb3:8091/pools: http: server gave HTTP response to HTTPS client -- base.(*DCPReceiver).OnError() at dcp_feed.go:123
2017-08-03T00:22:14.193Z WARNING: Error processing DCP stream - will attempt to restart/reconnect: could not connect to any serverURL: []string{"https://cb1:8091", "https://cb2:8091", "https://cb3:8091"} -- base.(*DCPReceiver).OnError() at dcp_feed.go:123
2017-08-03T00:22:14.296Z WARNING: Error processing DCP stream - will attempt to restart/reconnect: Get https://cb1:8091/pools: http: server gave HTTP response to HTTPS client -- base.(*DCPReceiver).OnError() at dcp_feed.go:123
2017-08-03T00:22:14.298Z WARNING: Error processing DCP stream - will attempt to restart/reconnect: Get https://cb2:8091/pools: http: server gave HTTP response to HTTPS client -- base.(*DCPReceiver).OnError() at dcp_feed.go:123
2017-08-03T00:22:14.300Z WARNING: Error processing DCP stream - will attempt to restart/reconnect: Get https://cb3:8091/pools: http: server gave HTTP response to HTTPS client -- base.(*DCPReceiver).OnError() at dcp_feed.go:123
2017-08-03T00:22:14.300Z WARNING: Error processing DCP stream - will attempt to restart/reconnect: could not connect to any serverURL: []string{"https://cb1:8091", "https://cb2:8091", "https://cb3:8091"} -- base.(*DCPReceiver).OnError() at dcp_feed.go:123
```

Here is how I'm testing:

- Create a docker network called `cbl` based on https://github.com/couchbaselabs/mobile-testkit/tree/master/docker#creating-a-cluster
- Run a cluster of couchbase servers in that network

```
docker run -d --network cbl --name cb1 -p 8091-8094:8091-8094 -p 11210:11210 couchbase/server:5.0.0-beta2
docker run -d --network cbl --name cb2 -p 30000:8091 couchbase/server:5.0.0-beta2
docker run -d --network cbl --name cb3 -p 30001:8091 couchbase/server:5.0.0-beta2
```

- Manually configure couchbase server cluster via web ui
- Start another docker container in the same network to run Sync Gateway: `docker run -itd --network cbl --name sg1 -p 4986:4984 -p 4987:4985 tleyden5iwx/sg-docker-bootstrap /bin/bash`
- Cross-compile Sync Gateway to linux and `docker cp` the binary into the container
- Start SG with config

```
{
    "adminInterface":":4985",
    "log":[
        "*", "Feed+"
    ],
    "databases":{
        "db":{
            "feed_type":"DCP",
            "server": "couchbases://cb1,cb2,cb3",
            "bucket":"data-bucket",
            "password": "password",
            "revs_limit": 5,
            "view_query_timeout_secs_dis": 10,
            "users":{
                "GUEST":{
                    "disabled":true,
                    "admin_channels":[
                        "*"
                    ]
                },
                "foo":{
                    "disabled":false,
                    "admin_channels":[
                        "*"
                    ],
                    "password":"bar"
                }
            },
            "allow_empty_password":true
        }
    }
}
```

As mentioned, if I change the config to use `"server": "couchbase://cb1,cb2,cb3",`, it starts up without problems.

**Comment by tleyden** [comment] 2017-08-03 00:56
re https://github.com/couchbase/sync_gateway/issues/1552#issuecomment-319834996 -- @adamcfraser noticed that it was calling cbdatasource with port 8091 rather than port 18091, which was causing the error.

Fixed in 68ccd50b88719d6653bfab13a706bdb91cc91378, and now it seems to be starting up fine with the secure urls: `couchbases://cb1,cb2,cb3`

New Sync Gateway startup logs: https://gist.github.com/tleyden/0d30a6c978c21401ea1e4047d92d31e8

I haven't tested with Sync Gateway Accel yet.

**Comment by tleyden** [comment] 2017-08-03 01:13
The basic Sync Gateway Accel setup is working as well (tested commit bbe1d5b5d5d7013ff009f48e826dbcce6e0ef002)

[SG config](https://gist.github.com/tleyden/a0d78863bfb9841bef43da0362b89108)

[SG Accel config](https://gist.github.com/tleyden/b3f6f3538ab2abe420c2d752df1ab43b)

**Comment by tleyden** [comment] 2017-08-03 16:41
Closing this as a duplicate of https://github.com/couchbase/sync_gateway/issues/2496.  Re-open if there are differences in the tickets that I'm missing.

**Closed as completed by tleyden** 2017-08-03 16:41 UTC
Labels: P1: high

**Comment by adamcfraser** [comment] 2017-09-05 18:35
Fixed with https://github.com/couchbase/sync_gateway/pull/2772 - the support for multiple URLs also includes support for the couchbases:// protocol, used for SSL communication between SG and CBS.
