### ISSUE TITLE
Trailing slash in POST request to localhost:4984/:db

### ISSUE THREAD

**Issue by jamesnocentini** [couchbase/sync_gateway#643] opened 2015-02-09 09:50 UTC
Following the documentation, to create a document with the id generated by couchbase lite:

```
curl -X POST -H 'Content-Type: application/json' \
-d '{"type": "post", "text": "some text"}' \
http://localhost:4984/testdb
```

returns nothing in curl and in the SG logs the document doesn't appear to be stored. With a trailing slash, it's saved successfully:

```
curl -X POST -H 'Content-Type: application/json' \
-d '{"type": "post", "text": "some text"}' \
http://localhost:4984/testdb/
```

returns

```
{"id":"115b5bc08f36af3981305421978cab07","ok":true,"rev":"1-2efb2d7a0f2ff5adb50ba3cfce239147"}
```

Testing on version 1.0.3

**Comment by ajres** [comment] 2015-02-09 10:01
This is a duplicate of https://github.com/couchbase/sync_gateway/issues/338

You should be getting a 301 redirect response, but see notes about curl not handling the redirect correctly.

**Closed as completed** 2016-09-01 23:25 UTC
Labels: enhancement
