### ISSUE TITLE
Sync Gateway not handling server node autofailover

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2576] opened 2017-05-16 01:09 UTC
### Sync Gateway version
1.4.2-368   

### Couchbase Server version
5.0.0-2873

### Operating system
CentOS 7

### Config file
```
{
        "adminInterface": "0.0.0.0:4985",
        "compressResponses": false,
        "databases": {
            "db": {
                "bucket": "data-bucket",
                "import_docs": "continuous",
                "password": "password",
                "server": "http://cbl.0:8091",
                "unsupported": {
                    "enable_extended_attributes": true
                },
                "users": {
                    "GUEST": {
                        "admin_channels": [
                            "*"
                        ],
                        "disabled": true
                    }
                }
            }
        },
        "interface": ":4984",
        "log": [
            "CRUD+",
            "Cache+",
            "HTTP+",
            "Changes+"
        ],
        "maxCouchbaseConnections": 16,
        "maxFileDescriptors": 90000,
        "maxIncomingConnections": 0,
        "slowServerCallWarningThreshold": 500
    }
```

### Log output
https://gist.github.com/sethrosetter/81bd206b2b0d14673f8cad3b4137d77e#file-gistfile1-txt-L1487-L1801

### Expected behavior
When a server fails over in a multinode cluster, the sync gateway should be able to recover

### Actual behavior
Sync Gateway loses connection to the bucket and is unable to reconnect

### Steps to reproduce
1.  http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific-cc/463/testReport/junit/testsuites.syncgateway.functional.topology_specific_tests.multiple_servers/test_multiple_servers/test_server_goes_down_rebuild_channels/

**Comment by adamcfraser** [comment] 2017-05-17 20:48
Based on the logs, it looks like we're failing to reconnect to the bucket using gocb.  Requires some more in-depth investigation of why that's happening, and whether it's something we can avoid by either:
 - specifying multiple server URLs when connecting to gocb
 - change the way we attempt to reconnect to a gocb bucket

**Comment by sethrosetter** [comment] 2017-06-02 18:43
http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-topology-specific-cc/504/testReport/junit/testsuites.syncgateway.functional.topology_specific_tests.multiple_servers/test_multiple_servers/test_server_goes_down_rebuild_channels/

**Comment by tleyden** [comment] 2017-07-28 18:41
- Original tests (soft/graceful failover) are disabled.  Need to re-enable and retest to see if it's still failing
- We don't have a test for hard failover.  
- Can uncomment the rebalance functional test that might reproduce issues
- Also there are system tests that might repro the issue

TODO:

- Fix multiple urls issue
- Possibly write a functional test for hard failover

**Comment by tleyden** [comment] 2017-08-07 17:19
Once mobile-testkit is updated to support multiple urls, https://github.com/couchbaselabs/mobile-testkit/issues/1338, then this can be re-verified

**Comment by tleyden** [comment] 2017-08-07 17:20
Closing this since there is no action items aside from mobile-teskit changes and re-verifying.  @raghusarangapani / @sridevi-15 please re-open this if the test is still failing

**Closed as completed by tleyden** 2017-08-07 17:20 UTC
Labels: ffc, functional-test-failure

**Comment by sridevi-15** [comment] 2017-09-21 22:08
Verified on 1.5.0-573 and working fine.
