### ISSUE TITLE
sg-replicate is creating new local document for any change in sg-replicate configuration

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2116] opened 2016-10-05 11:30 UTC
I am using below sg-replicate configuration
"replications":[
   {
               "replication_id":"continuous-147-144",
               "source": "ptxdata",
               "target": "http://10.0.29.144:4985/ptxdata/",
               "changes_feed_limit":50,
               "continuous":true
        }]

any change in configurations(we have changed "changes_feed_limit" value), sg-replicate is creating new _local documents on remote site and replication is starting from sequence number =0

Is this normal behavior? if so , it will results delay in replication if we have more number of documents.
though replication ignores the documents replication with rev_diff but results unnecessary reads to local cluster.
any tuning in parameters results in more delay for latest documents replications.

**Comment by tleyden** [comment] 2016-10-05 15:25
Yes, it's expected behavior due to this code: https://github.com/couchbaselabs/sg-replicate/blob/master/synctube.go#L141-L175

However, looking at the [upstream code](https://github.com/couchbase/couchbase-lite-ios/blob/f4c6eca0a95ab0e05d7982c36ce801c1cf08c1c6/Source/CBL_ReplicatorSettings.m#L61-L82), it's actually a bug, since it should not be taking the changes_feed_limit into account.

**Comment by ArihantRk** [comment] 2016-10-06 05:33
Thanks for quick reply @tleyden , when sync gateway 1.4 is expected to release.

**Comment by tleyden** [comment] 2016-10-06 16:18
We have a conference coming up on nov 7-9 (can you make it?).  I know the 1.4 release will be after that, but don't have any more info

**Comment by ArihantRk** [comment] 2016-10-07 05:20
yup thanks@tleyden , if i am not wrong, i think its nov 8-10. will try to join on live stream.

**Comment by ddash1** [comment] 2017-01-31 00:00
@djpongh Is this bug descoped from 1.4?

**Comment by ddash1** [comment] 2017-09-14 00:05
@djpongh @tleyden 
Any update when this bug is going to be fixed?

**Comment by ddash1** [comment] 2017-09-15 00:04
@tleyden  Can you please update on this issue fix plan? this causes unnecessary full replication just on a change of hostname and or any of the replication {} block parameters. Practically these parameters can change quite often.

**Comment by adamcfraser** [comment] 2017-09-15 06:05
@ddash1 It's expected that changes to some of the replication{} block parameters - including hostname in source/target - gets identified as a different replication.  This matches the CBL replication behaviour, and is needed to differentiate between replications targeting different hosts.  If the goal is to be able to switch replication between multiple hosts in a single SG cluster, you'll currently need to target a load balancer fronting that cluster.  An enhancement to support defining multiple source/target hosts in the replication{} block might be feasible, but would be a separate enhancement request.

The fix described above is just to remove changes_feed_limit from the set of properties used to identify the replication checkpoint.  This isn't currently targeted for a release.

**Comment by ddash1** [comment] 2017-09-21 19:59
@adamcfraser We are good with the changes_feed_limit exclusion only. That's the one causing issue on our setup currently.

A unique scenario if the host is switched for the source then it is re-replicating full - let me explain. I have a host that has a file system mapped and cannot be extended. I move the filesystem to another host, All data intact,  and extend it. I do not want the replication to start again from the beginning as all data is already there.

**Comment by johnw123** [comment] 2017-11-27 16:58
If you’re looking for <a href="https://www.etech7.com/managed-it-services-in-nyc">Managed IT Services in NYC</a>, Etech7 is the right place for you. I’m a dummy in IT sphere, so all the time I need a good company to solve my IT problems. Finally I’ve found Etech7 and  when I need <a href="https://www.etech7.com/it-consulting">IT Consulting</a>, I’ll definitely call them.

**Comment by adamcfraser** [comment] 2020-03-24 22:32
Closing based on age.

**Closed as completed by adamcfraser** 2020-03-24 22:32 UTC
Labels: bug, icebox, P2: medium, ffc
