### ISSUE TITLE
Bucket shadowing: Failure to push rev

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2686] opened 2017-06-26 18:16 UTC
### Sync Gateway version
1.5.0-452

### Operating system
CentOS7

### Config file
```javascript
{
    "out.stdout": {
        "adminInterface": "0.0.0.0:4985", 
        "compressResponses": false, 
        "databases": {
            "db": {
                "bucket": "data-bucket", 
                "password": "password", 
                "revs_limit": 5, 
                "server": "http://XXX.sc.couchbase.com:8091", 
                "shadow": {
                    "bucket": "source-bucket", 
                    "password": "password", 
                    "server": "http://XXX.com:8091", 
                    "username": "source-bucket"
                }, 
                "username": "data-bucket"
            }
        }, 
        "interface": ":4984", 
        "log": [
            "*"
        ], 
        "maxCouchbaseConnections": 16, 
        "maxFileDescriptors": 90000, 
        "maxIncomingConnections": 0, 
        "slowServerCallWarningThreshold": 500
    }
```

### Log output
http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-topology-specific-cc/600/artifact/results/logs/test_bucket_shadow_low_revs_limit_repeated_deletes-2017-06-26-09-46-26-sglogs.zip

### Expected behavior
I would expect revs to be synchronized

### Actual behavior
Some revs do not get pushed

### Steps to reproduce
1. http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-topology-specific-cc/600/testReport/testsuites.syncgateway.functional.topology_specific_tests.multiple_sync_gateways/test_bucket_shadow/test_bucket_shadow_low_revs_limit_repeated_deletes/

**Comment by sethrosetter** [comment] 2017-06-26 18:51
Also failing against CBS 4.6.1. This looks like a regression. http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-topology-specific-cc/602/

**Comment by tleyden** [comment] 2017-06-30 17:59
From meeting: try to repro locally with 1.5.0-455.  Might only be reproducible due to loaded VM's.

**Comment by sethrosetter** [comment] 2017-06-30 20:56
@ajres This appears to be fixed.

This fails with 1.5.0-455. http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-topology-specific-cc/617/

It starts passing with 1.5.0-456. http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-topology-specific-cc/618/

Can you verify that the diff for that build explains why we are no longer seeing 409s for the test? If it is clear, we can close this.

**Comment by ajres** [comment] 2017-07-05 16:49
Need to get the SG repo commit hash's by tracking back from the Jenkins test builds.

**Comment by ajres** [comment] 2017-07-05 17:21
The commit hashes for the two builds are:

455 - cec6bf8d6c97a2529d896d6cefa93a9da406e95d
456 - 933d652092bb6de8f5786c1d37dd33d880d4e9b0

The diff between the two commits is as follows:

```
git diff cec6bf8d6c97a2529d896d6cefa93a9da406e95d 933d652092bb6de8f5786c1d37dd33d880d4e9b0
diff --git a/db/revtree.go b/db/revtree.go
index e05d781b..cf3ab275 100644
--- a/db/revtree.go
+++ b/db/revtree.go
@@ -17,8 +17,9 @@ import (
 
        "errors"
 
-       "github.com/couchbase/sync_gateway/base"
        "bytes"
+
+       "github.com/couchbase/sync_gateway/base"
 )
 
 type RevKey string
@@ -174,9 +175,6 @@ func (tree RevTree) GetLeaves() []string {
        return tree.GetLeavesFiltered(acceptAllLeavesFilter)
 }
 
-
-
-
 func (tree RevTree) GetLeavesFiltered(filter func(revId string) bool) []string {
 
        isParent := map[string]bool{}
@@ -343,8 +341,12 @@ func (tree RevTree) pruneRevisions(maxDepth uint32, keepRev string) (pruned int)
        }
 
        // Calculate tombstoneGenerationThreshold
-       genShortestNonTSBranch := tree.FindShortestNonTombstonedBranch()
-       tombstoneGenerationThreshold := genShortestNonTSBranch - int(maxDepth)
+       genShortestNonTSBranch, foundShortestNonTSBranch := tree.FindShortestNonTombstonedBranch()
+       tombstoneGenerationThreshold := -1
+       if foundShortestNonTSBranch {
+               // Only set the tombstoneGenerationThreshold if a genShortestNonTSBranch was found.  (fixes #2695)
+               tombstoneGenerationThreshold = genShortestNonTSBranch - int(maxDepth)
+       }
 
        // Delete nodes whose depth is greater than maxDepth:
        for revid, node := range tree {
@@ -365,15 +367,17 @@ func (tree RevTree) pruneRevisions(maxDepth uint32, keepRev string) (pruned int)
                }
        }
 
-       // Delete any tombstoned branches that are too old
-       for _, leafRevId := range leaves {
-               leaf := tree[leafRevId]
-               if !leaf.Deleted { // Ignore non-tombstoned leaves
-                       continue
-               }
-               leafGeneration, _ := ParseRevID(leaf.ID)
-               if leafGeneration < tombstoneGenerationThreshold {
-                       pruned += tree.DeleteBranch(leaf)
+       // If we have a valid tombstoneGenerationThreshold, delete any tombstoned branches that are too old
+       if tombstoneGenerationThreshold != -1 {
+               for _, leafRevId := range leaves {
+                       leaf := tree[leafRevId]
+                       if !leaf.Deleted { // Ignore non-tombstoned leaves
+                               continue
+                       }
+                       leafGeneration, _ := ParseRevID(leaf.ID)
+                       if leafGeneration < tombstoneGenerationThreshold {
+                               pruned += tree.DeleteBranch(leaf)
+                       }
                }
        }
 
@@ -425,13 +429,15 @@ func (tree RevTree) computeDepthsAndFindLeaves() (maxDepth uint32, leaves []stri
 // Find the minimum generation that has a non-deleted leaf.  For example in this rev tree:
 //   http://cbmobile-bucket.s3.amazonaws.com/diagrams/example-sync-gateway-revtrees/three_branches.png
 // The minimim generation that has a non-deleted leaf is "7-non-winning unresolved"
-func (tree RevTree) FindShortestNonTombstonedBranch() (generation int) {
+func (tree RevTree) FindShortestNonTombstonedBranch() (generation int, found bool) {
        return tree.FindShortestNonTombstonedBranchFromLeaves(tree.GetLeaves())
 }
 
-func (tree RevTree) FindShortestNonTombstonedBranchFromLeaves(leaves []string) (generation int) {
+func (tree RevTree) FindShortestNonTombstonedBranchFromLeaves(leaves []string) (generation int, found bool) {
 
+       found = false
        genShortestNonTSBranch := math.MaxInt32
+
        for _, revid := range leaves {
 
                revInfo := tree[revid]
@@ -442,9 +448,10 @@ func (tree RevTree) FindShortestNonTombstonedBranchFromLeaves(leaves []string) (
                gen := genOfRevID(revid)
                if gen > 0 && gen < genShortestNonTSBranch {
                        genShortestNonTSBranch = gen
+                       found = true
                }
        }
-       return genShortestNonTSBranch
+       return genShortestNonTSBranch, found
 }
 
 // Find the generation of the longest deleted branch.  For example in this rev tree:
@@ -563,7 +570,6 @@ func (tree RevTree) RenderGraphvizDot() string {
 
 }
 
-
 //////// ENCODED REVISION LISTS (_revisions):
 
 // Parses a CouchDB _rev or _revisions property into a list of revision IDs
@@ -652,4 +658,3 @@ func trimEncodedRevisionsToAncestor(revs Body, ancestors []string, maxUnmatchedL
        return true, trimmedRevs
 
 }
-
diff --git a/db/revtree_test.go b/db/revtree_test.go
index c810d52f..91c7dd00 100644
--- a/db/revtree_test.go
+++ b/db/revtree_test.go
@@ -19,6 +19,7 @@ import (
 
        "github.com/couchbase/sync_gateway/base"
        "github.com/couchbaselabs/go.assert"
+       "log"
 )
 
 // 1-one -- 2-two -- 3-three
@@ -336,6 +337,9 @@ func TestPruneRevisions(t *testing.T) {
 }
 
 
+
+
+
 func TestPruneRevsSingleBranch(t *testing.T) {
 
        numRevs := 100
@@ -466,7 +470,7 @@ func TestGenerationShortestNonTombstonedBranch(t *testing.T) {
 
        revTree := getMultiBranchTestRevtree1(3, 7, branchSpecs)
 
-       generationShortestNonTombstonedBranch := revTree.FindShortestNonTombstonedBranch()
+       generationShortestNonTombstonedBranch, _ := revTree.FindShortestNonTombstonedBranch()
 
        // The "non-winning unresolved" branch has 7 revisions due to:
        // 3 unconflictedBranchNumRevs
@@ -545,6 +549,33 @@ func TestPruneRevisionsPostIssue2651ThreeBranches(t *testing.T) {
 
 }
 
+func TestPruneRevsSingleTombstonedBranch(t *testing.T) {
+
+       numRevsTotal := 100
+       numRevsDeletedBranch := 99
+       branchSpecs := []BranchSpec{
+               {
+                       NumRevs:                 numRevsDeletedBranch,
+                       Digest:                  "single-tombstoned-branch",
+                       LastRevisionIsTombstone: true,
+               },
+       }
+
+       revTree := getMultiBranchTestRevtree1(1, 0, branchSpecs)
+
+       maxDepth := uint32(20)
+       expectedNumPruned := numRevsTotal - int(maxDepth)
+
+       expectedNumPruned += 1  // To account for the tombstone revision in the branchspec, which is spearate from NumRevs
+
+       numPruned := revTree.pruneRevisions(maxDepth, "")
+
+       log.Printf("RevTreeAfter pruning: %v", revTree.RenderGraphvizDot())
+
+       assert.Equals(t, numPruned, expectedNumPruned)
+
+}
+
 func TestLongestBranch1(t *testing.T) {
 
        branchSpecs := []BranchSpec{
```

**Comment by ajres** [comment] 2017-07-05 17:21
Removing functional-test-failure label as this is now passing consistently

**Comment by djpongh** [comment] 2017-07-19 20:11
@ajres if the test is not passing, why is this issue still open?

**Comment by ajres** [comment] 2017-07-20 13:49
I don't remember why we put this in the backlog rather than close.

I'm closing this out, re-open if this needs to be re-visted.

**Closed as completed by ajres** 2017-07-20 13:49 UTC
Labels: P1: high
