### ISSUE TITLE
Sync Gateway does not propagate user view errors from Couchbase Server view responses

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2682] opened 2017-06-24 00:18 UTC
### Sync Gateway version
1.5.0-446

### Operating system
CentOS7

### Config file
```javascript
# When relevant, copy-paste your sync gateway config here.  Remove any sensitive information
as appropriate (including addresses, passwords, etc).
```

### Test Failure
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/758/testReport/testsuites.syncgateway.functional.tests/test_user_views/test_user_views_sanity_user_views_user_views_/

## Possible causes

- Regression from https://github.com/couchbase/sync_gateway/pull/2655
- Couchbase Server regression (the test passes against 4.6.x, fails against 5.x)

**Comment by sethrosetter** [comment] 2017-06-26 20:57
Raising this to p1 High since I am seeing in every build now.

**Comment by sethrosetter** [comment] 2017-06-27 20:16
Seeing this fail again with CBS 5.0.0-3207. This is running against 4.6.1 - http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-cc/778/. When this is done, we'll see if server version has an effect on the test.

**Comment by tleyden** [comment] 2017-06-27 20:25
http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-cc/778/ is running the full suite.  Couldn't it just target that single test?

**Comment by sethrosetter** [comment] 2017-06-27 20:28
I queued up a rebuild with that single test - http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/779/

**Comment by sethrosetter** [comment] 2017-06-27 21:43
Update: the user views test succeeded with CBS 4.6.1 - http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/769/

**Comment by tleyden** [comment] 2017-06-28 17:34
Possible causes:

- Regression from https://github.com/couchbase/sync_gateway/pull/2655
- Server issue

**Comment by tleyden** [comment] 2017-06-28 17:51
@sethrosetter trying to revert that single commit is generating some merge conflicts which will take some time to go through.  How about just retesting the commit before the #2655 PR?  That commit hash is 92b6340513d5ff5e7ce443e640d914a6f4567fc5

If that consistently passes against Couchbase 5.x, then at least we've isolated the issue to that change.

**Comment by tleyden** [comment] 2017-06-28 18:19
@sethrosetter ok here is the commit with master and the https://github.com/couchbase/sync_gateway/pull/2655 reverted: 9435064ed2c074d63972ff02d58c6c1ce96e7e9d it's the latest commit on [feature/issue_2682_views_intermittent_0_docs](https://github.com/couchbase/sync_gateway/tree/feature/issue_2682_views_intermittent_0_docs)

**Comment by sethrosetter** [comment] 2017-06-28 18:54
@tleyden I have kicked off the following. They are pending
- User view test,  Latest SG with Latest 5.0.0 server, http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/785/ (expecting to fail)
- User view test,  Latest SG with reverted view change with Latest 5.0.0 server, http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/786/ (?)

**Comment by sethrosetter** [comment] 2017-06-28 20:20
Running the test in isolation passes - http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-cc/788/

Need to keep digging.

**Comment by sethrosetter** [comment] 2017-06-28 22:00
I think we have figured out possible root cause.

Steps to the solution:
- I ran the test in a loop in the Jenkins environment (passed everytime)
- Started running more jobs on the same hypervisor to increase load (finally failed)

```
    def validate_rows(rows, num_expected_rows, expected_id_prefixes, number_of_prefixed_docs):
        log_info("Validating rows has length: {}".format(num_expected_rows))
>       assert len(rows) == num_expected_rows
E       assert 71 == 200
E        +  where 71 = len([{'id': 'create_doc_10', 'key': None, 'value': ['Create']}, {'id': 'create
```

We only get partial results for the view, even though all of the the doc have been added via Sync Gateway and we are issuing the following view query `http -a seth:pass http://172.23.121.46:4984/db/_design/test_views/_view/filtered\?stale\=false` through Sync Gateway. 

This is is the snippet of the SG logs showing the query
```
2017-06-28T17:06:05.592-04:00 Cache:     #404 ==> channel "*"
2017-06-28T17:06:05.592-04:00 Changes+: Notifying that "data-bucket" changed (keys="{*, Edit}") count=409
2017-06-28T17:06:08.049-04:00 HTTP:  #017: PUT /db/_design/test_views  (ADMIN)
2017-06-28T17:06:08.104-04:00 HTTP+: #017:     --> 201 OK  (54.5 ms)
2017-06-28T17:06:08.107-04:00 HTTP:  #018: GET /  (ADMIN)
2017-06-28T17:06:08.107-04:00 HTTP+: #018:     --> 200   (0.1 ms)
2017-06-28T17:06:08.108-04:00 HTTP:  #019: GET /
2017-06-28T17:06:08.109-04:00 HTTP+: #019:     --> 200   (0.0 ms)
2017-06-28T17:06:08.111-04:00 HTTP:  #020: GET /db/_design/test_views/_view/filtered?stale=false  (as seth)
2017-06-28T17:06:08.111-04:00 HTTP: JSON view "test_views"/"filtered" - opts map[stale:false]
2017-06-28T17:06:08.843-04:00 HTTP+: #020:     --> 200   (733.0 ms)
2017-06-28T17:06:55.207-04:00 Cache+: Pruned 4 old entries from channel "*"
2017-06-28T17:07:05.208-04:00 Cache+: Pruned 264 old entries from channel "*"
2017-06-28T17:07:05.208-04:00 Cache+: Pruned 50 old entries from channel "Create"
2017-06-28T17:07:05.208-04:00 Cache+: Pruned 50 old entries from channel "Download"
2017-06-28T17:07:05.208-04:00 Cache+: Pruned 50 old entries from channel "Upload"
2017-06-28T17:07:07.708-04:00 Cache+: Pruned 86 old entries from channel "*"
2017-06-28T17:07:07.708-04:00 Cache+: Pruned 50 old entries from channel "Edit"
2017-06-28T17:32:07.570-04:00 HTTP:  #021: GET /
2017-06-28T17:32:07.570-04:00 HTTP+: #021:     --> 200   (0.1 ms)
2017-06-28T17:32:37.687-04:00 HTTP:  #022: GET /db/  (as seth)
2017-06-28T17:32:37.688-04:00 HTTP+: #022:     --> 200   (98.0 ms)
2017-06-28T17:32:51.855-04:00 HTTP:  #023: GET /db/_design/test_views/_view/filtered  (as seth)
2017-06-28T17:32:51.855-04:00 HTTP: JSON view "test_views"/"filtered" - opts map[]
2017-06-28T17:32:51.882-04:00 HTTP+: #023:     --> 200   (27.7 ms)
2017-06-28T17:33:11.494-04:00 HTTP:  #024: GET /db/_design/test_views/_view/filtered?stale=false  (as seth)
2017-06-28T17:33:11.494-04:00 HTTP: JSON view "test_views"/"filtered" - opts map[stale:false]
2017-06-28T17:33:11.528-04:00 HTTP+: #024:     --> 200   (34.7 ms)
2017-06-28T17:35:18.016-04:00 HTTP:  #025: GET /db/_design/test_views/_view/filtered  (as seth)
2017-06-28T17:35:18.016-04:00 HTTP: JSON view "test_views"/"filtered" - opts map[]
2017-06-28T17:35:18.033-04:00 HTTP+: #025:     --> 200   (17.8 ms)
```

After the test failed, a couple minutes went by and the following queries were executed as part of the investigation

Expected number of results: 200

Without stale=false: 
```
http -a seth:pass http://172.23.121.46:4984/db/_design/test_views/_view/filtered
```

```
HTTP/1.1 200 OK
Content-Length: 3934
Content-Type: application/json
Date: Wed, 28 Jun 2017 21:32:51 GMT
Server: Couchbase Sync Gateway/1.5.0

{
    "Collator": {},
    "rows": [
        {
            "id": "create_doc_10",
            "key": null,
            "value": [
                "Create"
            ]
        }, ...
       ],
    "total_rows": 71
```

With stale=false: 
```
http -a seth:pass http://172.23.121.46:4984/db/_design/test_views/_view/filtered\?stale\=false`
```
```
HTTP/1.1 200 OK
Content-Length: 3934
Content-Type: application/json
Date: Wed, 28 Jun 2017 21:32:51 GMT
Server: Couchbase Sync Gateway/1.5.0

{
    "Collator": {},
    "rows": [
        {
            "id": "create_doc_10",
            "key": null,
            "value": [
                "Create"
            ]
        }, ...
       ],
    "total_rows": 200
```

Without stale=false: 
```
http -a seth:pass http://172.23.121.46:4984/db/_design/test_views/_view/filtered
```

```
HTTP/1.1 200 OK
Content-Length: 3934
Content-Type: application/json
Date: Wed, 28 Jun 2017 21:32:51 GMT
Server: Couchbase Sync Gateway/1.5.0

{
    "Collator": {},
    "rows": [
        {
            "id": "create_doc_10",
            "key": null,
            "value": [
                "Create"
            ]
        }, ...
       ],
    "total_rows": 200
```

A few theories:
- SG is not passing stale=false properly to GOCB
- GOCB is not passing stale=false properly to Couchbase Server
- There is a bug in Couchbase Server related to views

**Comment by sethrosetter** [comment] 2017-06-28 22:19
Full SG logs - https://gist.github.com/sethrosetter/ee663965cb0a936fb647ecc48ac5be88

**Comment by tleyden** [comment] 2017-06-28 22:44
I ran the functional test locally, and during the test, examined the HTTP traffic between Sync Gateway and Couchbase Server views port 8092:

```
$  ngrep -d eth1 -W byline port 8092
```

The view query HTTP Requests from SG have the `stale=false` parameter:

```
T 192.168.33.11:50347 -> 192.168.33.10:8092 [AP]
GET /data-bucket/_design/test_views/_view/filtered?stale=false HTTP/1.1.

T 192.168.33.11:50347 -> 192.168.33.10:8092 [AP]
GET /data-bucket/_design/test_views/_view/filtered_more?stale=false HTTP/1.1.

```

So from that it looks like the stale=false parameter is making it to Couchbase Server

**Comment by tleyden** [comment] 2017-06-28 23:01
Can it be reproduced under VM load if Couchbase Server 4.6 is used?  Or only with 5.x?

**Comment by raghusarangapani** [comment] 2017-06-28 23:05
I tried to reproduce this issue too. I was not able to reproduce it with 1 CBS and 1 SG. I switched the number of servers to 3 and hit the issue with the very first try.

https://gist.github.com/raghusarangapani/8d0c792109111ba787b4f5e3c656eeee

**Comment by sethrosetter** [comment] 2017-06-28 23:08
I have only seen this issue with Couchbase Server 5.0.0-X

**Comment by sethrosetter** [comment] 2017-06-28 23:13
@raghusarangapani Can you see if you are able to repro with 4.6.2?

**Comment by raghusarangapani** [comment] 2017-06-28 23:26
Unable to reproduce with 4.6.2. Test has been running in a loop and has passed more than 15 times.

**Comment by sethrosetter** [comment] 2017-06-28 23:32
Thanks. This appears to be a server regression. I filed a tracking ticket - https://issues.couchbase.com/browse/MB-25068

**Comment by sethrosetter** [comment] 2017-06-29 01:12
I tried to repo with Sync Gateway out of the mix with this script - https://gist.github.com/sethrosetter/c8296c69ec8d9d36843c4d6554922fe9. I cant reproduce.

**Comment by tleyden** [comment] 2017-06-29 01:46
In https://github.com/couchbase/sync_gateway/issues/2682#issuecomment-311816270, @raghusarangapani mentioned he was able to reproduce more easily w/ 3 couchbase servers.

Also, what about trying this:

> Started running more jobs on the same hypervisor to increase load (finally failed)

**Comment by raghusarangapani** [comment] 2017-06-29 02:43
I reproduced the issue `assert 69 == 200` with 5.0.0-3217.

**Comment by raghusarangapani** [comment] 2017-06-29 03:07
I reproduced the issue `assert 69 == 200` with 5.0.0-2873.

**Comment by tleyden** [comment] 2017-06-29 03:18
@raghusarangapani using which steps/script?

**Comment by raghusarangapani** [comment] 2017-06-29 03:19
`while true; do; pytest --pdb --ci --mode=cc --server-version=5.0.0-3207 --sync-gateway-version=1.5.0-455 -k 'test_user_views_sanity[user_views/user_views]'
testsuites/syncgateway/functional/tests/ --skip-provisioning; done`

**Comment by raghusarangapani** [comment] 2017-06-29 03:42
Running in a loop with 4.6.2, I ran into a different issue:
```
        # These are defined in the config
>       assert len(users) == 2 and "seth" in users and "raghu" in users
E       assert (1 == 2)
E        +  where 1 = len(['raghu'])

testsuites/syncgateway/functional/tests/test_user_views.py:63: AssertionError
```
Seems like SG crashed:
```
2017-06-29T03:37:28.222Z     Created user "raghu"
2017-06-29T03:37:28.223Z Changes+: Notifying that "data-bucket" changed (keys="{_sync:user:raghu}") count=6
2017-06-29T03:37:28.223Z Cache: Received #3 ("_user/raghu")
2017-06-29T03:37:28.224Z Cache:     #3 ==> channel "*"
2017-06-29T03:37:28.224Z Changes+: Notifying that "data-bucket" changed (keys="{*}") count=7
2017-06-29T03:37:28.307Z Access: Computed channels for "seth": !:1
2017-06-29T03:37:28.384Z Access: Computed roles for "seth":
2017-06-29T03:37:28.460Z Auth: Saved _sync:user:seth: &{{seth Create:4  %!s(uint64=4)  %!s(*uint16=<nil>)} { %!s(bool=false) $2a$10$ro/2LZyfU0wWZXMpiVHt4uPyYxnnq7ov7NHgj7ckPawChY6oh/bVW <nil> Scientist:4  []} %!s(*auth.Authenticator=&{0xc42007f050 0xc420199680}) []}
2017-06-29T03:37:28.460Z     Created user "seth"
2017-06-29T03:37:28.460Z Starting admin server on 0.0.0.0:4985
2017-06-29T03:37:28.463Z Starting server on :4984 ...
2017-06-29T03:37:28.466Z Changes+: Notifying that "data-bucket" changed (keys="{_sync:user:seth}") count=8
2017-06-29T03:37:28.466Z Cache: Received #4 ("_user/seth")
2017-06-29T03:37:28.466Z Cache:     #4 ==> channel "*"
2017-06-29T03:37:28.466Z Changes+: Notifying that "data-bucket" changed (keys="{*}") count=9
2017-06-29T03:37:28.956Z HTTP:  #001: GET /db/_user/  (ADMIN)
2017-06-29T03:37:29.043Z HTTP+: #001:     --> 200   (86.8 ms)
```

**Comment by tleyden** [comment] 2017-06-29 18:01
@sethrosetter / @raghusarangapani were able to reproduce with a python SDK script that talked directly to Couchbase Server, without SG involved.

I'll leave this open for tracking purposes, but re-assigning to @djpongh since I don't have any action items

**Comment by raghusarangapani** [comment] 2017-06-29 23:37
After several trial and errors, I see that the server returns `{"from":"192.168.33.21:8092","reason":"{<<\"unknown_error\">>,<<\"view_undefined\">>}"}` to SG but I do not see this error in the API response from SG.

Here is a gist of the stdout / stderr of a failing run:
https://gist.github.com/raghusarangapani/8271b666964e934f80067111f630396f

This is the ngrep gist of the failing test case on SG:
https://gist.github.com/raghusarangapani/1299886e5ab6ecd6a3b6bd281bbd383d

**Comment by tleyden** [comment] 2017-06-30 18:16
This isn't a regression from the previous 1.5 beta release, so it's being postponed

**Comment by tleyden** [comment] 2017-08-03 17:28
Unless gocb has any better API for capturing partial view errors, just propagate them as-is back to caller.

**Comment by tleyden** [comment] 2017-08-03 19:15
After digging into the GoCB code a little, I'm seeing a field name mismatch that makes me think that partial view errors are getting ignored completely.  Filed https://issues.couchbase.com/browse/GOCBC-224

**Comment by adamcfraser** [comment] 2017-08-10 17:08
Fixed with https://github.com/couchbase/sync_gateway/pull/2788

**Closed as completed by adamcfraser** 2017-08-10 17:08 UTC
Labels: P1: high

**Comment by sridevi-15** [comment] 2017-09-21 22:09
Verified on 1.5.0-573 and working fine.
