### ISSUE TITLE
SG crashes after restarting with bucket shadowing and revs limit

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#994] opened 2015-07-21 23:05 UTC
SG commit 6736fd4e65f1b5ac5de99247dba96a9cb8add632

found when implemented tests for https://github.com/couchbase/sync_gateway/issues/961
( seems like I got the same steps as they are in the ticket above)

my SG config

```
{
  "interface":":4984",
  "adminInterface":":4985",
  "log":["REST", "HTTP", "Shadow", "CHANGES"],
  "verbose":"true",
  "databases":{
    "sync_gateway" :{
      "server":"http://localhost:8091",
      "revs_limit" : 3,
      "users": { "GUEST": { "disabled": false, "admin_channels": ["*"] } },
      "bucket": "sync_gateway",
      "shadow": {
        "server": "http://localhost:8091",
        "bucket": "default"
      },
      "sync":`function(doc){
if (doc.deleted) {
channel("deleted")
} else if (doc.isExpired) {
channel("expired")
} else {
channel("active")
}
}`
}
}
}
```

when I kill SG I continue to load data in CB lite with continuous pull replication.

after SG restarting it crashes:

```
/home/andrei/couchbase_src/sync_gateway/bin/sync_gateway /home/andrei/couchbase_src/sync-gateway-tests/config/961.json 
2015-07-22T01:51:53.917+03:00 Enabling logging: [REST HTTP Shadow CHANGES]
2015-07-22T01:51:53.917+03:00 ==== Couchbase Sync Gateway/master(6736fd4+CHANGES) ====
2015-07-22T01:51:53.917+03:00 Configured Go to use all 8 CPUs; setenv GOMAXPROCS to override this
2015-07-22T01:51:53.917+03:00 Configured process to allow 4096 open file descriptors
2015-07-22T01:51:53.917+03:00 Opening db /sync_gateway as bucket "sync_gateway", pool "default", server <http://localhost:8091>
2015-07-22T01:51:53.917+03:00 Opening Couchbase database sync_gateway on <http://localhost:8091>
2015/07/22 01:51:53  Trying with selected node 0
2015/07/22 01:51:53  Trying with selected node 0
2015-07-22T01:51:53.985+03:00 Shadow: Watching doc changes...
2015-07-22T01:51:53.987+03:00     Reset guest user to config
2015-07-22T01:51:53.987+03:00 Opening Couchbase database default on <http://localhost:8091>
2015-07-22T01:51:54.006+03:00 Database "sync_gateway" shadowing remote bucket "default", pool "default", server <http:localhost:8091/>
2015-07-22T01:51:54.006+03:00 Starting admin server on :4985
2015-07-22T01:51:54.009+03:00 Starting server on :4984 ...
2015-07-22T01:51:54.020+03:00 Shadow: Reading history of external bucket
panic: parent id "2-236a9f5c7ce8456a92d8586d9470fe1a" is missing

goroutine 81 [running]:
runtime.panic(0x8f9da0, 0xc208348c60)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/couchbase/sync_gateway/db.RevTree.addRevision(0xc2082f1a40, 0xc2082f1fb0, 0x22, 0xc2082f1c50, 0x22, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/revtree.go:241 +0x3d0
github.com/couchbase/sync_gateway/db.func·032(0xc2082788f0, 0x1a, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/shadower.go:124 +0x55f
github.com/couchbase/sync_gateway/db.func·019(0xc208178d04, 0x63b, 0x63b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:475 +0x28f
github.com/couchbase/sync_gateway/base.func·001(0xc208178d04, 0x63b, 0x63b, 0x0, 0x0, 0x0, 0xecd40c40a, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/bucket.go:94 +0x7a
github.com/couchbase/go-couchbase.func·016(0xc208178d04, 0x63b, 0x63b, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/go-couchbase/client.go:724 +0x9b
github.com/couchbase/go-couchbase.(*Bucket).update(0xc208166820, 0xc208297de0, 0x1a, 0x0, 0xc208353950, 0x0, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/go-couchbase/client.go:703 +0xc8
github.com/couchbase/go-couchbase.(*Bucket).WriteUpdate(0xc208166820, 0xc208297de0, 0x1a, 0x0, 0xc2083539b8, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/go-couchbase/client.go:729 +0xde
github.com/couchbase/sync_gateway/base.CouchbaseBucket.WriteUpdate(0xc208166820, 0xc20800fc00, 0x15, 0xac96b0, 0x7, 0xc208001cd0, 0xc, 0x0, 0x0, 0x0, ...)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/bucket.go:98 +0x9e
github.com/couchbase/sync_gateway/base.(*CouchbaseBucket).WriteUpdate(0xc208004480, 0xc208297de0, 0x1a, 0x0, 0xc208185180, 0x0, 0x0)
    <autogenerated>:76 +0xf3
github.com/couchbase/sync_gateway/db.(*Database).updateDoc(0xc208212020, 0xc208297de0, 0x1a, 0xa35400, 0xc2082f1980, 0x0, 0x0, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/crud.go:650 +0x3d0
github.com/couchbase/sync_gateway/db.(*Shadower).pullDocument(0xc2080b6240, 0xc208297de0, 0x1a, 0xc208356033, 0x474, 0x474, 0x0, 0x13f317ee04620000, 0x0, 0x0, ...)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/shadower.go:132 +0x26b
github.com/couchbase/sync_gateway/db.(*Shadower).readTapFeed(0xc2080b6240)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/shadower.go:77 +0x293
created by github.com/couchbase/sync_gateway/db.NewShadower
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/shadower.go:36 +0x188

goroutine 16 [IO wait]:
net.runtime_pollWait(0x7fdc5acfdff0, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208184fb0, 0x72, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208184fb0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc208184f50, 0xd3f478, 0x0, 0x7fdc5acf83f0, 0xb)
    /usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc2081387d8, 0xc2080dec68, 0x0, 0x0)
    /usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc2081387d8, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
net/http.(*Server).Serve(0xc20806a5a0, 0x7fdc5ad07718, 0xc2081387d8, 0x0, 0x0)
    /usr/local/go/src/pkg/net/http/server.go:1698 +0x91
github.com/couchbase/sync_gateway/base.ListenAndServeHTTP(0xc208001728, 0x5, 0x0, 0x0, 0x0, 0x7fdc5acf8638, 0xc208296da0, 0x0, 0x0, 0x0, ...)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/http_listener.go:52 +0x48c
github.com/couchbase/sync_gateway/rest.(*ServerConfig).serve(0xc2080a41c0, 0xc208001728, 0x5, 0x7fdc5acf8638, 0xc208296da0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:455 +0xa7
github.com/couchbase/sync_gateway/rest.RunServer(0xc2080a41c0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:495 +0x696
github.com/couchbase/sync_gateway/rest.ServerMain()
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:510 +0x34
main.main()
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:33 +0x113

goroutine 19 [finalizer wait]:
runtime.park(0x413530, 0x10f52c0, 0x10f2ce9)
    /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x10f52c0, 0x10f2ce9)
    /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
    /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
    /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 22 [chan receive]:
main.func·001()
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:27 +0x58
created by main.main
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/main.go:31 +0x10c

goroutine 17 [syscall]:
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 33 [IO wait]:
net.runtime_pollWait(0x7fdc5acfe360, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20802a060, 0x72, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20802a060, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc20802a000, 0xc2080ac000, 0x1000, 0x1000, 0x0, 0x7fdc5acf83f0, 0xb)
    /usr/local/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc2080e4008, 0xc2080ac000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/net.go:122 +0xe7
net/http.noteEOFReader.Read(0x7fdc5acfe410, 0xc2080e4008, 0xc2080a6058, 0xc2080ac000, 0x1000, 0x1000, 0x1108b20, 0x0, 0x0)
    /usr/local/go/src/pkg/net/http/transport.go:1203 +0x72
net/http.(*noteEOFReader).Read(0xc2081340a0, 0xc2080ac000, 0x1000, 0x1000, 0xc20804e830, 0x0, 0x0)
    <autogenerated>:124 +0xca
bufio.(*Reader).fill(0xc20807ff80)
    /usr/local/go/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).Peek(0xc20807ff80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/bufio/bufio.go:132 +0x101
net/http.(*persistConn).readLoop(0xc2080a6000)
    /usr/local/go/src/pkg/net/http/transport.go:782 +0x95
created by net/http.(*Transport).dialConn
    /usr/local/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 34 [select]:
net/http.(*persistConn).writeLoop(0xc2080a6000)
    /usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
    /usr/local/go/src/pkg/net/http/transport.go:601 +0x957

goroutine 52 [IO wait]:
net.runtime_pollWait(0x7fdc5acfe2b0, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208076990, 0x72, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208076990, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc208076930, 0xc2082138c0, 0x18, 0x18, 0x0, 0x7fdc5acf83f0, 0xb)
    /usr/local/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc2080e4028, 0xc2082138c0, 0x18, 0x18, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/net.go:122 +0xe7
io.ReadAtLeast(0x7fdc5acfe410, 0xc2080e4028, 0xc2082138c0, 0x18, 0x18, 0x18, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/io/io.go:289 +0xf7
io.ReadFull(0x7fdc5acfe410, 0xc2080e4028, 0xc2082138c0, 0x18, 0x18, 0x7fdc5aceff80, 0x0, 0x0)
    /usr/local/go/src/pkg/io/io.go:307 +0x71
github.com/couchbase/gomemcached.(*MCRequest).Receive(0xc208152ae0, 0x7fdc5acfe410, 0xc2080e4028, 0xc2082138c0, 0x18, 0x18, 0xc208148e89, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/gomemcached/mc_req.go:130 +0xe9
github.com/couchbase/gomemcached/client.(*Client).runFeed(0xc20807d230, 0xc208004960, 0xc2082138a0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/gomemcached/client/tap_feed.go:270 +0x126
created by github.com/couchbase/gomemcached/client.(*Client).StartTapFeed
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/gomemcached/client/tap_feed.go:251 +0x23d

goroutine 27 [chan receive]:
github.com/couchbase/sync_gateway/base.func·002()
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/bucket.go:137 +0x69
created by github.com/couchbase/sync_gateway/base.CouchbaseBucket.StartCouchbaseTapFeed
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/bucket.go:147 +0x1ff

goroutine 26 [select]:
github.com/couchbase/go-couchbase.(*TapFeed).run(0xc208041fc0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:58 +0x331
created by github.com/couchbase/go-couchbase.(*Bucket).StartTapFeed
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:42 +0x14d

goroutine 25 [sleep]:
time.Sleep(0x1a3185c5000)
    /usr/local/go/src/pkg/runtime/time.goc:39 +0x31
github.com/couchbase/sync_gateway/db.func·004()
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:120 +0x66
created by github.com/couchbase/sync_gateway/db.(*changeCache).Init
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:122 +0x2c8

goroutine 24 [sleep]:
time.Sleep(0x9502f900)
    /usr/local/go/src/pkg/runtime/time.goc:39 +0x31
github.com/couchbase/sync_gateway/db.func·003()
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:113 +0x66
created by github.com/couchbase/sync_gateway/db.(*changeCache).Init
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_cache.go:115 +0x29b

goroutine 28 [chan receive]:
github.com/couchbase/sync_gateway/db.func·010()
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_listener.go:49 +0xe1
created by github.com/couchbase/sync_gateway/db.(*changeListener).Start
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/change_listener.go:66 +0x2d6

goroutine 29 [chan receive]:
github.com/couchbase/sync_gateway/db.(*DatabaseContext).watchDocChanges(0xc20822c1c0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/assimilator.go:16 +0xc0
created by github.com/couchbase/sync_gateway/db.NewDatabaseContext
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/db/database.go:118 +0x477

goroutine 53 [select]:
github.com/couchbase/go-couchbase.(*TapFeed).forwardTapEvents(0xc208041fc0, 0xc2082138a0, 0xc2080046c0, 0xc208150860, 0xf)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:104 +0x277
created by github.com/couchbase/go-couchbase.(*TapFeed).connectToNodes
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:96 +0x379

goroutine 30 [select]:
github.com/couchbase/go-couchbase.(*TapFeed).run(0xc2080b6200)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:58 +0x331
created by github.com/couchbase/go-couchbase.(*Bucket).StartTapFeed
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:42 +0x14d

goroutine 31 [chan receive]:
github.com/couchbase/sync_gateway/base.func·002()
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/bucket.go:137 +0x69
created by github.com/couchbase/sync_gateway/base.CouchbaseBucket.StartCouchbaseTapFeed
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/bucket.go:147 +0x1ff

goroutine 54 [IO wait]:
net.runtime_pollWait(0x7fdc5acfe150, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208194060, 0x72, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208194060, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc208194000, 0xc2082ec000, 0x18, 0x18, 0x0, 0x7fdc5acf83f0, 0xb)
    /usr/local/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc208138008, 0xc2082ec000, 0x18, 0x18, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/net.go:122 +0xe7
io.ReadAtLeast(0x7fdc5acfe410, 0xc208138008, 0xc2082ec000, 0x18, 0x18, 0x18, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/io/io.go:289 +0xf7
io.ReadFull(0x7fdc5acfe410, 0xc208138008, 0xc2082ec000, 0x18, 0x18, 0x7fdc5ad05050, 0x0, 0x0)
    /usr/local/go/src/pkg/io/io.go:307 +0x71
github.com/couchbase/gomemcached.(*MCRequest).Receive(0xc20832d7a0, 0x7fdc5acfe410, 0xc208138008, 0xc2082ec000, 0x18, 0x18, 0xc20835c019, 0x0, 0x0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/gomemcached/mc_req.go:130 +0xe9
github.com/couchbase/gomemcached/client.(*Client).runFeed(0xc208244150, 0xc2082e0060, 0xc2081960a0)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/gomemcached/client/tap_feed.go:270 +0x126
created by github.com/couchbase/gomemcached/client.(*Client).StartTapFeed
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/gomemcached/client/tap_feed.go:251 +0x23d

goroutine 55 [runnable]:
github.com/couchbase/go-couchbase.(*TapFeed).forwardTapEvents(0xc2080b6200, 0xc2081960a0, 0xc20806a000, 0xc2080f3f60, 0xf)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:104 +0x277
created by github.com/couchbase/go-couchbase.(*TapFeed).connectToNodes
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/go-couchbase/tap.go:96 +0x379

goroutine 82 [IO wait]:
net.runtime_pollWait(0x7fdc5acfe0a0, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208308060, 0x72, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208308060, 0x0, 0x0)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc208308000, 0xd3f478, 0x0, 0x7fdc5acf83f0, 0xb)
    /usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803a050, 0xc208236168, 0x0, 0x0)
    /usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc20803a050, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
net/http.(*Server).Serve(0xc20825a000, 0x7fdc5ad07718, 0xc20803a050, 0x0, 0x0)
    /usr/local/go/src/pkg/net/http/server.go:1698 +0x91
github.com/couchbase/sync_gateway/base.ListenAndServeHTTP(0xc208001760, 0x5, 0x0, 0x0, 0x0, 0x7fdc5acf8638, 0xc2082eb840, 0x0, 0x0, 0x0, ...)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/base/http_listener.go:52 +0x48c
github.com/couchbase/sync_gateway/rest.(*ServerConfig).serve(0xc2080a41c0, 0xc208001760, 0x5, 0x7fdc5acf8638, 0xc2082eb840)
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:455 +0xa7
created by github.com/couchbase/sync_gateway/rest.RunServer
    /home/andrei/couchbase_src/sync_gateway/src/github.com/couchbase/sync_gateway/rest/config.go:493 +0x58e
```

**Comment by andreibaranouski** [comment] 2015-07-21 23:08
test to reproduce https://github.com/couchbaselabs/sync-gateway-tests/commit/5be449a96d0c787c6411274d2831ae485619c848

**Comment by tleyden** [comment] 2015-07-23 21:19
@andreibaranouski can this be reproduced on the Jenkins machine?  Please provide details/links.

**Comment by andreibaranouski** [comment] 2015-07-27 06:52
I have the job for bucket shadowing only on QA jenkins http://qa.hq.northscale.net/view/mobile/job/cen006-p0-mobile-sync-gateway-tests-android_cb_bucket_shadowing/11/console

**Comment by tleyden** [comment] 2015-07-27 17:49
Seems like a duplicate of https://github.com/couchbase/sync_gateway/issues/959

**Closed as completed** 2015-07-27 17:50 UTC
