### ISSUE TITLE
(CORS) Cannot delete _session

### ISSUE THREAD

**Issue by ricsmania** [couchbase/sync_gateway#1310] opened 2015-11-23 17:44 UTC
I'm using Angular to sync with Sync Gateway using cookie-based auth. The web server and Sync Gateway are running on different domains, so I configured CORS on the sync.json to accept requests from the web server.

I can sucessfully login by sending a POST to db/session, but I cannot logoff by sending a DELETE. 

Environment:
Machine 1:
Windows 10 Pro 64-bit
Ionic CLI 1.7.7
Chrome 46.0.2490.86 m (64-bit)

Machine 2:
Ubuntu 15.04 64-bit
Couchbase Sync Gateway/1.1.1(10;2fff9eb)

My login request:

``` js
$http.post(`${$rootScope.syncDb}/_session`, {name: $scope.data.username, password: $scope.data.password}).then((result) => {
                  $scope.loggedInUser = result.data.userCtx.name
                  myPopup.close()
                }
```

My logoff request:

``` js
$scope.logoff = () => {
      $http.delete(`${$rootScope.syncDb}/_session`).then((result) => {
        $scope.loggedInUser = ""
      })
    }
```

And the response:

``` json
{"error":"Bad Request","reason":"No CORS"}
```

Reading the source I saw that the domain is checked on the POST method but not on DELETE. On the DELETE method, the handler only checks if the "Origin" header exists and return an error if it does. Shouldn't CORS be treated the same way on both methods? Or am I doing something wrong on my request?

I also configured Angular to always send credentials:

``` js
.config(['$httpProvider',
function($httpProvider) {
  $httpProvider.defaults.withCredentials = true;
}
```

POST handler:

``` go
// CORS not allowed for login #115 #762
originHeader := h.rq.Header["Origin"]
    if len(originHeader) > 0 {
        matched := ""
        if h.server.config.CORS != nil {
            matched = matchedOrigin(h.server.config.CORS.LoginOrigin, originHeader)
        }
        if matched == "" {
            return base.HTTPErrorf(http.StatusBadRequest, "No CORS")
        }
    }
```

DELETE handler:

``` go
if len(h.rq.Header["Origin"]) > 0 {
        // CORS not allowed for login #115
        return base.HTTPErrorf(http.StatusBadRequest, "No CORS")
    }
```

**Comment by stefanhenzeyodle** [comment] 2016-03-09 23:58
Im experiencing the same behavior using sync gateway with Angular. For testing purposes, I log in using basic auth that the browser offers when first accessing the gateway. To log out, I'm trying to delete the session via the admin port on the server

```
curl -X DELETE  https://127.0.0.1:4985/test-database/_user/user1/_session -k
```

The gateway console logs the delete and I receive a 200 response code

```
2016-03-09T18:56:56.156-05:00 HTTP:  #69157: DELETE /test-database/_user/user1/_session  (ADMIN)
```

The problem is that I still have access to the gateway from the browser afterwards. The situation is similar to the OP's in that the gateway is hosted under a different domain than the website and I'm using CORS.

**Comment by adamcfraser** [comment] 2020-02-07 00:04
Closing based on age - could be revisited based on support cases.

**Closed as completed by adamcfraser** 2020-02-07 00:04 UTC
Labels: icebox, P2: medium
