### ISSUE TITLE
Resolve performance issues related to go 1.8 -> 1.10 upgrade

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3446] opened 2018-04-12 16:56 UTC
We want to move to go 1.10, in particular to use the `DisallowUnknownFields` option added to encoding/json for config validation.

To do that, we need to get to the bottom of the performance degradation we hit when upgrading to go 1.9.

**Comment by adamcfraser** [comment] 2018-07-09 17:50
We'd like to get a build enhancement to select the go version based on a property in product config - that will let us run perf with multiple versions and dig into the differences.

**Comment by bbrks** [comment] 2018-07-20 17:29
~Note that Go 1.10 is the last version to support Windows XP. If we need to support this platform going forwards, we may be stuck at 1.10!~

~https://github.com/golang/go/issues/23380~

Edit: Based on our [supported platforms](https://developer.couchbase.com/documentation/mobile/2.0/installation/sync-gateway/index.html#supported-platforms), this isn't an issue.

**Comment by bbrks** [comment] 2018-08-22 15:05
Sent build using Go 1.10.3 to Perf to run it through their testing.

**Comment by bbrks** [comment] 2018-09-13 09:10
Based on the results from perf, it looks like the 1.9 perf regression was fixed in Go 1.10. #3737 will bump our Go version for current builds.

**Closed as completed** 2018-09-13 16:20 UTC
Labels: performance, P1: high
