### ISSUE TITLE
slight delay in changed feed for 10 docs on getting branched revision with build 526 (DI)

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#2799] opened 2017-08-11 20:43 UTC
### Sync Gateway version
1.5.0.-526

### Operating system
Cent OS 7

### Expected behavior
 when branched revisions are created, changes feed should show branched revisions without any delay

### Actual behavior
Should wait for couple of seconds to get branched revisions on changes feed

### Steps to reproduce
1.  Create 10 docs via sync-gateway
2.  update docs via SDK
3.  updates docs via sync-gateway with New_edits=false -> which creates 2 branched revisions
4. update docs via SDK

Result : Get the changes feed by hitting  "_changes?style=all_docs". You will see old branched revisions.
Delay for a second and hit the "_changes?style=all_docs" -> you will get actual current branched revisions.
It could be milliseconds delay, As I run the automated test which is so quick which hits _change?style=all_docs as soon as update docs Via SDK is done . It may be hard to reproduce manually.
Creating around 10000 docs can be manually reproduceble

I will update the test name here once I push the test.

**Comment by adamcfraser** [comment] 2017-08-11 21:09
Based on discussion with Sridevi, I don't think there should be any delay required, because the call to GetDocSyncData being done during changes processing should be triggering an on-demand import once the doc has been updated via the SDK.  (i.e. we shouldn't have to wait for the doc to show up on the DCP feed).

**Comment by sridevi-15** [comment] 2017-08-11 21:17
Also forgot to mention that it works fine without any delay on build sync-gateway 1.5.0-513

**Comment by adamcfraser** [comment] 2017-08-16 23:31
There was a potential regression (duplicate doc retrieval) that's been fixed with https://github.com/couchbase/sync_gateway/pull/2804, and is in the latest build.

Can you update on whether you're still seeing this delay with the latest build?

**Comment by sridevi-15** [comment] 2017-08-17 21:47
@adamcfraser , I verified with build 535 and I still see this delay issue after sdk update

**Comment by adamcfraser** [comment] 2017-08-22 00:08
I'm not able to repro this on the latest build - I've written a unit test that replicates the above steps, and the on-demand import is being triggered as expected.

@sridevi-15 Can you provide a link to a failing functional test, so that I can review the associated SG logs?

**Comment by sridevi-15** [comment] 2017-08-22 13:54
@adamcfraser , Here is the Jenkins link for test failure.
http://uberjenkins.sc.couchbase.com/job/sync-gateway-interop-shared-updates/1/testReport/

**Comment by adamcfraser** [comment] 2017-08-22 15:59
Looking at those logs, the failing tests are running in distributed index mode, which I hadn't realized, and isn't mentioned on the ticket above.  Is that intentional?

The changes aren't being returned immediately because sg_accel hasn't yet indexed the user doc.  It looks to me like there is some clock skew between the accel and SG hosts, based on the logs, so it's difficult to identify how long it's taking for the user doc to be included in the stable sequence.

However, it looks like expected behaviour - the changes aren't being sent immediately because the user doc hasn't yet been indexed by sg_accel.  

I've kicked off the test against 1.5.0-513 to see the behaviour in the passing case.

**Comment by sridevi-15** [comment] 2017-08-22 20:42
@adamcfraser , I ran with mode cc against build 540 and see the test failed. I attached sg logs.
Also I included log key : import+

[sync_gateway_error.log.zip](https://github.com/couchbase/sync_gateway/files/1243310/sync_gateway_error.log.zip)

**Comment by adamcfraser** [comment] 2017-08-23 01:13
I've reviewed this in detail, and believe the behaviour is as expected.  Since you're running a bulk_get to initially verify each operation, it's that bulk get that will trigger the import.  This doesn't guarantee that the document has arrived over the DCP feed and been cached, though, and the updated entry isn't expected to show up on the changes feed until that point.

Looking at the attached logs, the latency between import and caching appears within normal range - less than 80ms: 

2017-08-19T22:13:30.742Z CRUD: Stored doc "sg_doc_0" / "3-03dbf2c8b35e620a39927506637793c1"
2017-08-19T22:13:30.810Z Cache: Received #41 after  68ms ("sg_doc_0" / "3-03dbf2c8b35e620a39927506637793c1")

Based on this, I'm closing this as a test issue - the test should be following the same pattern used by other tests, and doing looping/retry on the changes requests before asserting errors.

**Closed as completed by adamcfraser** 2017-08-23 01:13 UTC
Labels: P1: high, functional-test-failure

**Comment by sridevi-15** [comment] 2017-09-21 22:08
Verified on 1.5.0-573 and working fine.
