### ISSUE TITLE
Intermittent unit test failure

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#2541] opened 2017-05-09 00:17 UTC
Intermittent unit test failure on TestPostChangesUserTiming.

http://mobile.jenkins.couchbase.com/view/Sync_Gateway/job/sgw-unix-build/2555/consoleFull

**Comment by tleyden** [comment] 2017-10-18 18:39
Closing as dupe of https://github.com/couchbase/sync_gateway/issues/2978

**Closed as completed by tleyden** 2017-10-18 18:39 UTC
Labels: P1: high, ffp
