### ISSUE TITLE
:4985/{db}/_user returns deleted users

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1557] opened 2016-02-03 02:42 UTC
Using Couchbase Sync Gateway/1.2.0(77;490449e)

Steps to reproduce
- Create two users 

```
curl -X "POST" "http://localhost:4985/db/_user/" \
    -H "Content-Type: application/json" \
    -d "{\"admin_channels\":[\"KTEK\"],\"admin_roles\":[\"DJ\"],\"name\":\"seth\",\"password\":\"password\",\"email\":\"seth@seth.me\",\"disabled\":false}"
```

```
curl -X "PUT" "http://localhost:4985/db/_user/traun" \
    -H "Content-Type: application/json" \
    -d "{\"admin_channels\":[\"KTEK\"],\"admin_roles\":[\"DJ\"],\"name\":\"traun\",\"password\":\"password\",\"email\":\"seth@seth.me\",\"disabled\":false}"
```
- Get the users

```
curl -X "GET" "http://localhost:4985/db/_user/"
```

Response:

```
[
  "seth",
  "traun"
]
```
- Delete one user

```
curl -X "DELETE" "http://localhost:4985/db/_user/seth"
```
- Try to get the deleted user by name

```
curl -X "GET" "http://localhost:4985/db/_user/seth"
```

Response:

```
{
  "error": "not_found",
  "reason": "missing"
}
```

It appears the user has been deleted.
- Get all the users again.

```
curl -X "GET" "http://localhost:4985/db/_user/"
```

Response:

```
[
  "seth",
  "traun"
]
```

Expected: The deleted user would not show up in the last step.
Actual: The deleted user shows up in the last step.

**Comment by tleyden** [comment] 2016-02-03 03:07
@sethrosetter can you post a gist with sync gw logs?

**Comment by sethrosetter** [comment] 2016-02-03 03:22
@tleyden Perhaps that warning has something to do with the issue https://gist.github.com/sethrosetter/3b3f32479112594fab4c#file-gistfile1-txt-L20

**Comment by tleyden** [comment] 2016-02-03 03:27
I searched the text of the error:

```
2016-02-02T19:20:44.782-08:00 WARNING: changeCache: Error unmarshaling doc "_sync:user:seth": unexpected end of JSON input -- db.(*changeCache).processPrincipalDoc() at change_cache.go:407
```

Looks like a very similar error was reported in https://github.com/couchbase/sync_gateway/issues/672

**Comment by adamcfraser** [comment] 2016-02-03 06:38
The db/_user endpoint is a view query.  It's a stale=false view, but it looks like the delete operation doesn't pass the indexable flag (which would be required to ensure that subsequent stale=false view queries see the change).  I'd be curious whether a later call to _user reflects the delete.

**Comment by adamcfraser** [comment] 2016-02-03 06:40
Also applies to deleted roles - see the details on #1558.

**Comment by jamescooke** [comment] 2016-02-21 13:40
Am also suffering from this issue. I've not worked with view queries (yet) - is there any way to flush this view after making a `DELETE` on the user?

**Comment by pasin** [comment] 2016-06-03 00:02
I have seen the same issue while working on the admin UI. The user itself is deleted correctly but doesn't get removed from the user list.

**Comment by pasin** [comment] 2016-06-13 21:56
I have tested with CB Server, and the issue doesn't happen when connecting to the CB Server instead of Walrus.

**Comment by ArihantRk** [comment] 2017-03-03 06:08
@djpongh any functional impact from these warnings?

**Comment by kirangandhi** [comment] 2017-03-27 06:10
Any functional impact from these warnings or these warnings can be ignored?

**Comment by adamcfraser** [comment] 2017-03-27 16:30
@kirangandhi This bug isn't about the 'Error unmarshaling doc "_sync:user:..." warning.  

I believe @tleyden had asked you to file a new bug for that issue, with steps to reproduce (on #672).  If you can do that, we can investigate further.

**Comment by kirangandhi** [comment] 2017-03-28 10:30
@adamcfraser, Thanks for the update. We will raise a new bug.

**Comment by adamcfraser** [comment] 2020-03-24 21:09
Closing as this is a Walrus-only issue.

**Closed as completed by adamcfraser** 2020-03-24 21:09 UTC
Labels: icebox
