### ISSUE TITLE
Sync Gateway encodes special characters when importing docs

### ISSUE THREAD

**Issue by JFlath** [couchbase/sync_gateway#3722] opened 2018-08-28 14:39 UTC
### Sync Gateway version
Tested with 2.0 GA

### Config

```
{
  "log": ["*"],
  "databases": {
    "db": {
      "server": "http://localhost:8091",
      "bucket": "test",
      "username": "test",
      "password": "password",
      "import_docs": "continuous",
      "enable_shared_bucket_access":true,
      "users": { "GUEST": { "disabled": false, "admin_channels": ["*"] } }
    }
  }
}
```

### Expected behaviour
Documents added via import from SDK ops should not be altered.

### Actual behaviour
Documents imported are encoded, for example `{"test": "&"}` becomes `{"test": "\u0026"}`.

### Steps to reproduce
1.  Run Sync Gateway with the above config
1. Add a doc via `cbc` (or SDK of choice):

    ```
    cbc-create -U couchbase://localhost/test -u test -P password test_import -V '{"test": "&"}'
    ```

1. Confirm this is imported successfully:

    ```
    2018-08-28T15:33:19.827+01:00 Import+: Attempting to import doc "test_import"...
    2018-08-28T15:33:19.827+01:00 CRUD+: Doc test_import is not an SG write, based on cas. cas:154f12eb50180000 syncCas:""
    2018-08-28T15:33:19.827+01:00 Import: Created new rev ID 1-c960e2953bdf347c1f4fb8ad54783795
    2018-08-28T15:33:19.827+01:00 CRUD+: Invoking sync on doc "test_import" rev 1-c960e2953bdf347c1f4fb8ad54783795
    2018-08-28T15:33:19.828+01:00 CRUD+: Saving doc (seq: #2, id: test_import rev: 1-c960e2953bdf347c1f4fb8ad54783795)
    2018-08-28T15:33:19.829+01:00 CRUD: Stored doc "test_import" / "1-c960e2953bdf347c1f4fb8ad54783795"
    2018-08-28T15:33:19.829+01:00 Import+: Imported test_import (delete=false) as rev 1-c960e2953bdf347c1f4fb8ad54783795
    ```

1. Stop Sync Gateway

1. Add another similar document: 

    ```
    cbc-create -U couchbase://localhost/test -u test -P password test_non_import -V '{"test": "&"}'
    ```

1. Check the two documents with `cbc`, notice that the imported document has been mutated:

    ```
    cbc-cat -U couchbase://localhost/test -u test -P password test_import test_non_import
    test_import          CAS=0x154f12eb50300000, Flags=0x0, Size=17, Datatype=0x01(JSON)
    {"test":"\u0026"}
    test_non_import      CAS=0x154f12f93afa0000, Flags=0x0, Size=13, Datatype=0x01(JSON)
    {"test": "&"}
    ```

**Comment by JFlath** [comment] 2018-08-28 14:46
Digging into this a little more deeply, it seems like we write the full document back with subdoc on every import, is this right/expected (see `Mutation spec [ 2 ]`)?

```
Couchbase Protocol, Subdoc Multipath Mutation Request, Opcode: 0xd1, VBucket: 0x17
    Magic: Request (0x80)
    Opcode: Subdoc Multipath Mutation (0xd1)
    Key Length: 11
    Extras Length: 1
    Data Type: 0x00
        .... ...0 = JSON: Not set
        .... ..0. = Snappy: Not set
        .... .0.. = XATTR: Not set
    VBucket: 23 (0x0017)
    [Value Length: 300]
    Total Body Length: 312
    Opaque: 0x13000000
    CAS: 0x154f12eb50180000
    Extras
        Subdoc Doc flags: 0x01, MKDOC
            .... ...1 = MKDOC: Set
            .... ..0. = ADD: Not set
            .... .0.. = ACCESS_DELETED: Not set
            0000 0... = Reserved fields: 0x00
    Key: test_import
    Mutation spec [ 0 ]
        Opcode: Subdoc Dictionary Upsert (0xc8)
        Subdoc flags: 0x04, XATTR_PATH
            .... ...0 = MKDIR_P: Not set
            .... .1.. = XATTR_PATH: Set
            ...0 .... = EXPAND_MACROS: Not set
            000. 0.0. = Reserved fields: 0x00
        Path Length: 5
        Value Length: 228
        Path: _sync
        Value: {"rev":"1-c960e2953bdf347c1f4fb8ad54783795","sequence":2,"recent_sequences":[2],"history":{"revs":["1-c960e2953bdf347c1f4fb8ad54783795"],"parents":[-1],"channels":[null]},"cas":"","time_saved":"2018-08-28T15:33:19.827993+01:00"}
    Mutation spec [ 1 ]
        Opcode: Subdoc Dictionary Upsert (0xc8)
        Subdoc flags: 0x14, XATTR_PATH, EXPAND_MACROS
            .... ...0 = MKDIR_P: Not set
            .... .1.. = XATTR_PATH: Set
            ...1 .... = EXPAND_MACROS: Set
            000. 0.0. = Reserved fields: 0x00
        Path Length: 9
        Value Length: 17
        Path: _sync.cas
        Value: "${Mutation.CAS}"
    Mutation spec [ 2 ]
        Opcode: Set (0x01)
        Subdoc flags: 0x00
            .... ...0 = MKDIR_P: Not set
            .... .0.. = XATTR_PATH: Not set
            ...0 .... = EXPAND_MACROS: Not set
            000. 0.0. = Reserved fields: 0x00
        Path Length: 0
        Value Length: 17
        Value: {"test":"\u0026"}
```


[Import_Subdoc.pcapng.zip](https://github.com/couchbase/sync_gateway/files/2328538/Import_Subdoc.pcapng.zip)

**Comment by JFlath** [comment] 2018-08-28 15:17
Sidenote: if checking in the UI, looks like the new UI in recent Couchbase Server versions (tested on 5.5) will decode this silently. I'd recommend checking with either `cbc` or the *Classic Document Editor* in the UI

**Comment by JFlath** [comment] 2018-08-28 15:37
Thinking about this a little more, I suspect the reason we write the full body is to handle the case where the current winning revision changed. I suspect it's non-trivial, but it would be nice (and potentially a bit efficiency saving) to:

1. Avoid this if there was no metadata before (i.e. a brand new import).
1. Avoid this if the current winning revision didn't change.

**Comment by JFlath** [comment] 2018-09-05 09:59
This also appears to affect numbers, e.g. `123456789123` becomes `1.23456789123e+11`. From a brief test, this doesn't seem to lose precision (we just include the additional decimal places for larger numbers) but I haven't tested exhaustively.

**Comment by adamcfraser** [comment] 2018-09-05 23:18
@JFlath Sync Gateway shouldn't need to rewrite the document body during import - I'm looking into why that's occurring.

I've been able to reproduce the special character conversion, but not the case where your integers are being switched to scientific notation.  Can you provide steps to repro that scenario?

**Comment by JFlath** [comment] 2018-09-06 07:33
Hmm, you're right. I have some documents that have got into that state, but I can't reproduce it. I'll try and find out what happened, but fair to say we can shelve that bit for now :)

**Comment by adamcfraser** [comment] 2018-09-06 23:42
The special character handling is consistent with a write of the same document/property directly through SG.

This is an additional rationale for SG to pass raw bytes through to Couchbase Server when shared bucket access is enabled (because SG doesn't need to modify the document body in this scenario).  

This is already being tracked by https://github.com/couchbase/sync_gateway/issues/2932 - I'd propose to include tests to verify import handling along with that ticket, and close this as a duplicate.  

@JFlath Please reopen if you think there's an issue not addressed by that approach.

**Closed as completed by adamcfraser** 2018-09-06 23:42 UTC
Labels: P1: high
