### ISSUE TITLE
[Distributed Index] Index writers intermittantly fail to register with CBGT

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#1392] opened 2016-01-01 00:21 UTC
I was running a perf scenario targeting 2 IR / 2 IW 
Couchbase Sync Gateway/feature/distributed_index(807177a)

The run parameters were 10k pushers / 10k pullers for the entire cluster. 

I kicked it off using the following command

```
python performance_tests/run_tests.py --use-gateload --gen-gateload-config --reset-sync-gw --number-pushers=5000 --number-pullers=5000 --test-id="10k-10k-2IR-2IW"
```

Once the test started, I nothing was being written to the index bucket and saw the following error in the logs.
https://gist.github.com/sethrosetter/780ccff52cf7ac5852e4#file-gistfile1-txt-L13

Full logs here - https://s3.amazonaws.com/sync-gateway-logs/snapshot-2015-12-31-15-38-57-sglogs.zip

Unfortunately, this is not reproducible every time. When I reran the test, all of the writers registered correctly.

**Comment by tleyden** [comment] 2016-01-05 19:27
@sethrosetter was seeing this in performance tests as well.

**Comment by tleyden** [comment] 2016-01-07 02:05
I just reproduced this while testing the changes in https://github.com/couchbaselabs/sync-gateway-testcluster/issues/192.
- [Sync Gateway index writer 6029f3e7b24e155f logs](https://gist.github.com/tleyden/d14bb3d2801a832e47fc)  -- this one gets all of the pindexes assigned to it
- [Sync Gateway index writer c31eb50eea9c5a83 logs](https://gist.github.com/tleyden/64e4f04ac4b1cb7123c4)  -- this one doesn't get any pindexes assigned to it
- [CBGT CFG output](https://gist.github.com/tleyden/873383ff7481ab6bbbff)
- [CBGT diag output](https://gist.github.com/tleyden/bf13cab87f46576ad22d)

The test code waited 60 seconds for the pindexes to get spread among the index writers before giving up.

The test is querying Sync Gateway node 6029f3e7b24e155f to query the CBGT REST API, but when I manually queried node c31eb50eea9c5a83 I got the same response.

@steveyen I think I'm going to need your help debugging CBGT on this one.  Btw we're using CBGT commit f654301a739cfe122fc6ca7f8e3368d654db5503 from December 18, 2015.

**Comment by tleyden** [comment] 2016-01-07 02:30
The issue looks like it's easily reproducible.. the second time I ran it I got the same error.

```
python performance_tests/run_tests.py --number-pullers 1000 --number-pushers 1000 --use-gateload --gen-gateload-config --reset-sync-gw --test-id="perftest"
```

**Comment by steveyen** [comment] 2016-01-07 02:44
On the main issue...

From the "CBGT CFG output", only a single node is listed there, so probably need to sit down (virtually) with @tleyden tomorrow to understand this test better.

On a side issue...

The  "CBGT diag output", somehow there was junk in that file that made it not-JSON (not json parsable), which I manually cleaned up and gist'ed here...

https://gist.github.com/steveyen/92bd56519c5d2cadfb87

I think it wasn't valid JSON output because sync-gateway's PIndex implementation seems to not be implementing the Dest.Stats() method correctly...

https://godoc.org/github.com/couchbase/cbgt#Dest

I see the sync-gateway implementation looks like...

https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/base/sgw_pindex.go#L352

Instead, here's an example, "bare minimum" no-op implementation...

https://github.com/couchbase/cbgt/blob/master/pindex_impl_blackhole.go#L124

**Comment by steveyen** [comment] 2016-01-07 03:20
Some other thoughts, btw, in case you wanted to diagnose a little before we can hook up (or can do this together).
- each node has its own diag output, so if you grab cbgt diag from each node, that would help.
- one thing I would double check is to make sure the nodes are pointed at the same cfg backend and can both successfully access that shared cfg database/bucket.

Given that, my next step would be to check that they both have the same view of the cfg.

**Comment by tleyden** [comment] 2016-01-07 22:49
Reproduced with valid diag:
- https://gist.github.com/bdc3e2f3b819d3cd358b
- https://gist.github.com/0b41ce1f2238e2c0097a

**Comment by tleyden** [comment] 2016-01-07 22:59
Unexpected errors:
- [TotPlannerKickErr 3](https://gist.github.com/tleyden/0b41ce1f2238e2c0097a#file-sg2_diag-json-L3595)
- [TotPlannerKickErr 14](https://gist.github.com/tleyden/bdc3e2f3b819d3cd358b#file-sg1_diag-json-L2459)

**Comment by tleyden** [comment] 2016-01-07 23:56
Current theory:
- There is a race condition in CBGT that happens when Sync Gateways are started up at the exact same time
- Each CBGT pulls it's CFG from Couchbase Server and caches locally
- Each CBGT writes itself to the NodeDefsKnown
- Each CBGT does a non-Cas Set to Couchbase Server
- One CBGT clobbers the other one, which becomes "lost"

**Comment by steveyen** [comment] 2016-01-08 01:01
Thanks for finding this!

cbgt fix up for review here: http://review.couchbase.org/#/c/58359/1

**Comment by steveyen** [comment] 2016-01-08 01:10
Also, a branch pushed up here for testing if you need: https://github.com/steveyen/cbgt/tree/fix-CfgCB-no-caching

**Comment by tleyden** [comment] 2016-01-08 01:48
@steveyen still seeing this error:

```
2016/01/08 01:44:15 MCResponse status=KEY_EEXISTS, opcode=SET, opaque=0, msg: Data exists for key
```

Full SG logs: https://gist.github.com/tleyden/f7265c748f247351499f

**Comment by tleyden** [comment] 2016-01-08 02:27
@steveyen after doing a few more tests with the latest [experimental cbgt commit](https://github.com/steveyen/cbgt/commit/d4804f0e23b3adb30238e3f300dbeccd4bec52bd) I saw this situation happen once:

https://gist.github.com/tleyden/1c506f3f6de8c5ffd885
- Both nodes are in nodeDefsKnown
- All pindexes are assigned to a single node  (even after the test waited approximately 60 seconds)

Sync Gw logs:
- https://gist.github.com/tleyden/0b15c0a042ba033e2b37
- https://gist.github.com/tleyden/32a96c3ce933e13b8779

I guess the only noteworthy thing is that the Sync Gw that didn't get any pindexes had this log message:

```
2016/01/08 02:19:45 Error checking view version: MCResponse status=KEY_ENOENT, opcode=GET, opaque=0, msg: Not found
```

but the Sync Gateway process didn't immediately exit in this case .. which might have something to do with the Sync Gateway code.

**Comment by steveyen** [comment] 2016-01-08 03:43
Thanks @tleyden - in that last one, looks like both nodes made it into nodeDefsKnown, but only one node made it into nodeDefsWanted, which explains the unbalanced pindex assignments.

The KEY_ENOENT response code is surprising, so I'll have to come up with some explanation for that.  

I have a theory, though, for the previous experiment where you reported the KEY_EEXISTS error response, and am in progress of thinking of some solution.

**Comment by steveyen** [comment] 2016-01-08 04:04
Hi @tleyden - on the KEY_ENOENT, that actually doesn't look like cbgt related error message, and I couldn't find it from grep'ing cbgt codebase.  Perhaps it's a sync-gateway related error message?  I see it comes from go-couchbase...

https://github.com/couchbase/go-couchbase/blob/master/util/viewmgmt.go#L34

Related, iirc, cbgt doesn't use views.

**Comment by steveyen** [comment] 2016-01-08 05:27
Hi @tleyden 
I pushed an additional commit up to the branch...

https://github.com/steveyen/cbgt/tree/fix-CfgCB-no-caching
https://github.com/steveyen/cbgt/commit/9f80823e174343c24a784da726cd5bdd0b58c604

Could you give that a retry/retest?
Thanks,
Steve

**Comment by tleyden** [comment] 2016-01-08 09:13
@steveyen the first try passed!  running it in a loop ...

**Comment by tleyden** [comment] 2016-01-08 09:28
I saw this failure:

https://gist.github.com/tleyden/23db536678911c0b6472

Sg logs:
- https://gist.github.com/tleyden/57d3bb940d36906f5d8b
- https://gist.github.com/tleyden/ae275ec95dbd41ab7681

**Comment by steveyen** [comment] 2016-01-08 14:51
Saw there was a report of...

```
2016/01/08 09:22:19 planner: PlannerOnce, err: planner: CheckVersion err: version: could not save VERSION to cfg, err: MCResponse status=KEY_EEXISTS, opcode=SET, opaque=0, msg: Data exists for key
```

And, looks like there's an early read-modify-write code pathway related to version checking that didn't retry if there was a CAS race, which I think explains this latest error and situation.

I push another commit up to...

https://github.com/steveyen/cbgt/tree/fix-CfgCB-no-cachinghttps://github.com/steveyen/cbgt/commit/9450dbf73a9b577ce9a7e0d273f67cfa24a4375e

Can you grab that and through it through your gauntlet?

Thanks,
Steve

**Comment by tleyden** [comment] 2016-01-08 16:15
Ok retesting in progress.

**Comment by tleyden** [comment] 2016-01-08 16:35
Here's the results for [9450dbf73a9b577ce9a7e0d273f67cfa24a4375e](https://github.com/steveyen/cbgt/tree/fix-CfgCB-no-cachinghttps://github.com/steveyen/cbgt/commit/9450dbf73a9b577ce9a7e0d273f67cfa24a4375e), looks like  one of the Sync Gateways exited on startup:

https://gist.github.com/tleyden/e892996c7b7d89b07fca

I'm assuming the `2016/01/08 16:27:57 MCResponse status=KEY_EEXISTS, opcode=SET, opaque=0, msg: Data exists for key` message is coming from CBGT due to the format of the date string.  Not sure what is causing it to exit, I'm assuming there is some sync gateway code that calls exit... will try to track that down and improve the logging.

Here is the cbgt diag output for the SG node that didn't exit:

https://gist.github.com/9b5f39a1d89fc55eb775

**Comment by tleyden** [comment] 2016-01-08 16:40
^^ updated previous comment to add the cbgt diag output

**Comment by steveyen** [comment] 2016-01-08 16:44
Thanks @tleyden - I see another bug in my attempted bug fix.  Another fix coming shortly.

**Comment by steveyen** [comment] 2016-01-08 16:58
Hi @tleyden 
Yet another fix just pushed up to...

https://github.com/steveyen/cbgt/tree/fix-CfgCB-no-caching

https://github.com/steveyen/cbgt/commit/66190973e1311b5a06fc173b64765292126c1051

**Comment by tleyden** [comment] 2016-01-08 18:09
Tested cbgt commit 66190973e1311b5a06fc173b64765292126c1051, looks like both nodes are still not in nodedefsknown:

https://gist.github.com/tleyden/5e49cb5ef6cbd427eb93

SG logs:

https://gist.github.com/tleyden/c85c54b8fe4bbef9ee04

**Comment by tleyden** [comment] 2016-01-08 18:16
^^ updated comment with logs

**Comment by tleyden** [comment] 2016-01-08 19:40
@steveyen actually in this last test, I think the pindexes are correctly partitioned, it's just that the nodeDefsKnown isn't accurate.  I am going to change the validation to look at the pindex distribution rather than nodeDefsKnown, unless you have any major objections.

**Comment by tleyden** [comment] 2016-01-08 22:01
@steveyen indeed, changing the verification code to ignore `nodeDefsKnown and just look at the pindex distribution under`planPIndexes` seems to have worked -- it's run about 5 times so far without detecting any issues, so it looks fixed from our end.

If you make any further fixes regarding `nodeDefsKnown` and you want me to retest, let me know.

**Comment by tleyden** [comment] 2016-01-08 22:11
@steveyen actually I take it back!  Shortly after writing https://github.com/couchbase/sync_gateway/issues/1392#issuecomment-170140067, I saw another case  with an unbalanced pindex distribution:

Diag:
- https://gist.github.com/49cb411ca2faade21601
- https://gist.github.com/aa8b099f500415146490

Sg logs:
- https://gist.github.com/7aa381512ca9d1be20cd
- https://gist.github.com/6e2ba819ce759862824f

**Comment by tleyden** [comment] 2016-01-08 23:10
I added a functional test running under Jenkins to detect this error.
- [10 runs passed](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/226/console)
- [3 runs passed, then detected issue](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/227/consoleFull)

**Comment by tleyden** [comment] 2016-01-08 23:24
Note to self: steps to re-run

# Get sync gw code (one time)
- `git clone sync gateway`
- switch to feature/issue_1392_cbgt branch
- `git submodule init && git submodule update`

# Update cbgt submodule
- `cd to cbgt submodule`
- `git checkout -t fix-CfgCB-no-caching`
- `git pull` (to get latest commit)
- `cd to sync gw project dir`
- git add .
- git commit .. git push

# Build on Jenkins
- Kick off new build here: http://mobile.jenkins.couchbase.com/view/Sync_Gateway_Dev/job/sync-gateway-dev-build/ 
- Wait for build number, eg, 522

# Kick off functional test
- Kick off build here: http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/build?delay=0sec
- Use same parameters as http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/227/consoleFull, except increment the build number

**Comment by steveyen** [comment] 2016-01-09 22:13
Note sure why, but the next clue to followup on (for me) is that on one of the nodes, halfway through one of the logs (sg1.log), the nodedef got unregistered or disappeared from the nodesdefs-wanted...

```
2016/01/08 22:02:43 planner: PlannerOnce, err: planner: no NodeDef, uuid: 632e8da1877161a9
```

In here: https://gist.github.com/tleyden/7aa381512ca9d1be20cd

**Comment by tleyden** [comment] 2016-01-11 19:17
Tested cbgt commit f8ec14652230214ac01ed6c67a689d1de7c0fa79 locally via:

```
$ python provision/install_sync_gateway.py --branch feature/issue_1392_cbgt
$ for NUM in `seq 1 1 100`; do python -m pytest --capture=no functional_tests/test_cbgt_pindex.py; done
```

Got the following cbgt diag output:
- [1st sg index writer cbgt diag output](https://gist.github.com/tleyden/fd50aaf7bf50889484f2#file-diag1)
- [2nd sg index writer cbgt diag output](https://gist.github.com/tleyden/fd50aaf7bf50889484f2#file-diag2)

**Comment by tleyden** [comment] 2016-01-11 19:44
Since I didn't capture the SG logs in the previous run, I did another run on cbgt commit f8ec14652230214ac01ed6c67a689d1de7c0fa79, this time with the sg logs:
- [1st sg index writer cbgt diag output](https://gist.github.com/tleyden/e97b04c46268affe2e3d#file-diag1)
- [2nd sg index writer cbgt diag output](https://gist.github.com/tleyden/e97b04c46268affe2e3d#file-diag2)
- [1st sg log](https://gist.github.com/tleyden/e97b04c46268affe2e3d#file-sg1-logs)
- [2nd sg log](https://gist.github.com/tleyden/e97b04c46268affe2e3d#file-sg2-logs)

**Comment by tleyden** [comment] 2016-01-11 21:55
Tested cbgt commit 77314d030a687affd1925bb603f1f35fa2188b5d:
- [1st sg index writer cbgt diag output](https://gist.github.com/tleyden/998b2b4d4aa7c8177817#file-diag1)
- [2nd sg index writer cbgt diag output](https://gist.github.com/tleyden/998b2b4d4aa7c8177817#file-diag2)
- [1st sg log](https://gist.github.com/tleyden/998b2b4d4aa7c8177817#file-sg1-logs)
- [2nd sg log](https://gist.github.com/tleyden/998b2b4d4aa7c8177817#file-sg2-logs)

**Comment by tleyden** [comment] 2016-01-11 22:04
@steveyen for this last test, I was surprised that there was nothing in the sg logs that said anything about [adding pindexes](https://gist.github.com/tleyden/6e2ba819ce759862824f#file-sg2-log-L54-L118)

**Comment by tleyden** [comment] 2016-01-11 22:44
Testing cbgt commit 63e659a47b9058d3ef825867ba4e787c87f79c75:
- [combined cbgt diag output](https://gist.github.com/tleyden/4d511fb8980a78154f8d#file-diag-combined)
- [1st sg log](https://gist.github.com/tleyden/4d511fb8980a78154f8d#file-sg1-logs)
- [2nd sg log](https://gist.github.com/tleyden/4d511fb8980a78154f8d#file-sg2-logs)

**Comment by tleyden** [comment] 2016-01-11 23:37
Tested cbgt commit f01d8cd4500302f73e955060536610a52a0d68bd, got a fatal error initializing cbgt:

```
2016/01/11 23:31:00 Fatal Error initializing CBGT: Unable to initialize CBGT index: manager_api: could not save indexDefs, err: CAS mismatch
```

Full logs:

https://gist.github.com/tleyden/c334446a104be58f06cb#file-sg1-logs-L128

**Comment by tleyden** [comment] 2016-01-12 01:04
Testing cbgt commit ece3eb8a68fc584cd59dd8f8552c4c75e670b0b0

So far 31/31 runs have passed

**Comment by steveyen** [comment] 2016-01-12 01:44
pushed that set of cbgt commits to master, ending here: https://github.com/couchbase/cbgt/commit/06193ca74e834ca91bc28c7555205aedd8e7fa80

**Comment by tleyden** [comment] 2016-01-12 02:03
[50 functional tests passed](http://qa.sc.couchbase.com/view/mobile/job/centos-syncgateway-functional-tests-distributed-index/228/)

**Closed as completed** 2016-01-12 04:54 UTC
Labels: bug
