### ISSUE TITLE
Incomplete _changes feed on one node in an array of Sync Gateways

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#506] opened 2014-11-17 15:44 UTC
Created to track issue originally raised in forum post, [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mobile-couchbase/eM0NC6C8n1I/M6RD_MIglQsJ)

**Comment by adamcfraser** [comment] 2015-03-20 21:11
Closing as duplicate of #525.

**Closed as completed** 2015-03-20 21:11 UTC
Labels: P1: high
