### ISSUE TITLE
Sync_gateway is going in loop when client is asking for changes.

### ISSUE THREAD

**Issue by sudhanitk** [couchbase/sync_gateway#1309] opened 2015-11-23 11:48 UTC
SyncGW Release version: 1.1.1-10
Couchbase Release version: 4.0.0-4047
1)  Client requests the list of docs “since=0”.
2)  Sync GW responds with list of changes and last_seq as “371875::372157”
# Below sync gateway output for the client request

<method>GET</method>
<url>http://13.9.4.28:8080/pttdata/_changes?timeout=25000&amp;style=all_docs&amp;since=0&amp;limit=100&amp;_nonce=1448256264603</url>

{"seq":"362546","id":"co11_s919591803622_Contact.doc","changes":[{"rev":"6-8379d536b2859d2b6669149283a9aadd"}]}
,{"seq":"362816","id":"co11_s919591803623_Contact.doc","changes":[{"rev":"3-deb937bf0cee4e0c0a0e37fd7ba433ea"}]}
,{"seq":"369575","id":"co11_s919591803621_Contact.doc","changes":[{"rev":"7-fa8837db4a0056594493fe424538f5d0"}]}
,{"seq":"371557","id":"s919591803633_ClientProfile.doc","changes":[{"rev":"12-737881cacba0b632ce275758f7ebca89"}]}
,{"seq":"371632","id":"s919591803621_ContactPresence.doc","changes":[{"rev":"42-36ddafcddca723a3c97e34454b2e2cc2"}]}
,{"seq":"371875::371926","id":"s919591803623_ContactPresence.doc","changes":[{"rev":"20-8fdf291fadb1db16daa9db0ad8406ba4"}]}
,{"seq":"371875::372028","id":"dc1k1ugvxt9sbxh_CCallLog","changes":[{"rev":"89-08eaf6a1e7e8421e71d14b3fb67a7f43"}]}
,{"seq":"371875::372054","id":"dc1k1ugvxt9sbxh_CAlertLog","changes":[{"rev":"48-43e51e3be56d91cd668dd377ffe94412"}]}
,{"seq":"371875::372119","id":"s919591803621_Location.doc","changes":[{"rev":"104-48223a30a399e60accb3e7416ece4adc"}]}
,{"seq":"371875::372142","id":"s919591803622_Location.doc","changes":[{"rev":"66-96f677efdf49593e01ce8c6801f69613"}]}
,{"seq":"371875::372157","id":"s919591803622_ContactPresence.doc","changes":[{"rev":"38-ecb957965c1a6d7f1791117971e43a17"}]}
],
"last_seq":"371875::372157"}

3)  Client requests again with the last seq number 

<method>GET</method>
<url>http://13.9.4.28:8080/pttdata/_changes?timeout=25000&amp;style=all_docs&amp;since=371875%3A%3A372157&amp;limit=100&amp;_nonce=1448256265344</url>

200 OK Response

{"seq":"371875::371926","id":"s919591803623_ContactPresence.doc","changes":[{"rev":"20-8fdf291fadb1db16daa9db0ad8406ba4"}]}
,{"seq":"371875::372028","id":"dc1k1ugvxt9sbxh_CCallLog","changes":[{"rev":"89-08eaf6a1e7e8421e71d14b3fb67a7f43"}]}
,{"seq":"371875::372054","id":"dc1k1ugvxt9sbxh_CAlertLog","changes":[{"rev":"48-43e51e3be56d91cd668dd377ffe94412"}]}
,{"seq":"371875::372119","id":"s919591803621_Location.doc","changes":[{"rev":"104-48223a30a399e60accb3e7416ece4adc"}]}
,{"seq":"371875::372142","id":"s919591803622_Location.doc","changes":[{"rev":"66-96f677efdf49593e01ce8c6801f69613"}]}
,{"seq":"371875::372157","id":"s919591803622_ContactPresence.doc","changes":[{"rev":"38-ecb957965c1a6d7f1791117971e43a17"}]}
],
"last_seq":"371875::372157"

Sync Gw logs as below
2015-11-22T23:26:54.195-06:00 HTTP:  #523919: GET /pttdata/_changes?timeout=25000&style=all_docs&since=371875%3A%3A372157&limit=100&_nonce=1448256410641  (as 919591803633)
2015-11-22T23:26:54.195-06:00 Changes: MultiChangesFeed({*}, {Since:371875::372157 Limit:100 Conflicts:true IncludeDocs:false Wait:false Continuous:false Terminator:0xc217607ce0 HeartbeatMs:0 TimeoutMs:25000}) ...   (to 919591803633)

4)  With the last_seq in (3), client is in loop requesting GET similar to (3). 

Question is why sync GW is responding with a list of documents starting with 371875 when client has specifically requested “371875::372157". Expectation is to return the doc with just one  value i.e
{"seq":"371875::372157","id":"s919591803622_ContactPresence.doc","changes":[{"rev":"38-ecb957965c1a6d7f1791117971e43a17"}]}

**Comment by ajres** [comment] 2015-11-23 14:14
@sudhanitk

Sync Gateway sequences can have three parts:

LowSeq:TriggeredBy:Seq

In your case last sequence is being returned as LowSeq::Seq

The LowSeq value is the last stable document sequence ID known by Sync Gateway, this means that some higher sequence ID's have not been seen by Sync Gateway and it is waiting for them to arrive.

When you use that sequence as as the since value SG will resend the sequences higher than the LowSeq value. In this case it appears that the missing sequences have still not arrived and the same last_seq is returned with the same LowSeq value .

How long did you leave the client sync'ing, depending on the cause of the missing doc sequences it may take some time for them to arrive.

You should see warning messages in your SG logs, search for the word 'skipped' (case insensitive), indicating that the sequence has not appeared for the maximum wait time and the sequence will not be sent on the changes feed.

Can you post your full SG log for the period leading up to the sync issue (to a gist) and link here.

**Comment by sudhanitk** [comment] 2015-11-24 17:56
@ajres  Thanks for your reply.

After long time (approximately > 1hr) started syncing the missing sequences it seems. 

CacheSkippedSeqMaxWait is default value i.e. 1hr. 

SG logs are uploaded in https://gist.github.com/anonymous/e397a3ca585e16f4d962 
Skipped Sequence warning message is not observed for {400595::402218} sequence. Instead it is observed for different sequence numbers.

2015-11-24T01:54:47.686-06:00 WARNING: Skipped Sequence 400596 didn't show up in MaxChannelLogMissingWaitTime, and isn't available from the \* channel view.  If it's a valid sequence, it won't be replicated until Sync Gateway is restarted. -- db.func·005() at change_cache.go:206
2015-11-24T01:54:47.686-06:00 Cache:   Querying 'channels' view for "_" (start=#400597, end=#400597, limit=0)
2015-11-24T01:54:47.721-06:00 Cache:     Got no rows from view for "_"
2015-11-24T01:54:47.721-06:00 WARNING: Skipped Sequence 400597 didn't show up in MaxChannelLogMissingWaitTime, and isn't available from the \* channel view.  If it's a valid sequence, it won't be replicated until Sync Gateway is restarted. -- db.func·005() at change_cache.go:206
2015-11-24T01:54:47.721-06:00 Cache:   Querying 'channels' view for "_" (start=#400598, end=#400598, limit=0)
2015-11-24T01:54:47.727-06:00 Cache:     Got no rows from view for "_"

We tried to reduce CacheSkippedSeqMaxWait interval to 5 min but it is not affecting.

**Comment by sudhanitk** [comment] 2015-11-25 19:32
Looks like the sync gateway responds with the same "LowSeq::Seq"  everytime client makes a request. Thus forcing the client to be in loop. Is there a way I can have the client recover the loop situation. The sync gateway seems to be giving the same pattern for a long period (more than 30min). We tried changing the cache time(CacheSkippedSeqMaxWait) to 5mins but still don’t seem to recover. If we restart sync gateway we see sequence numbers in integers being returned.

**Comment by ddash1** [comment] 2015-11-25 20:26
@ajres 
I am in the same team with @sudhanitk . 

What will help us understand is :
1. Is this a possible bug in SG code?
2. Why are we not having the same issue for the CouchbaseLite clients used on mobile handsets? How is pouch interaction different from CBL interaction?

Thx

**Comment by adamcfraser** [comment] 2015-11-25 22:07
@ddash1 @sudhanitk Based on the requests/responses, this looks like the correct behaviour from Sync Gateway.  The since value of 371875::372157 means that there may be data between sequences 371875 and 372157 that the client hasn't seen, and Sync Gateway needs to resend everything it knows between those records to ensure the client isn't missing anything.  So at first glance, I don't think this looks like a SG bug.

Regarding the difference between Pouch clients and Couchbase Lite - what type of Couchbase Lite clients are you using?  iOS clients doing background replication wouldn't hit this issue, as they would be doing continuous replication.  I'm curious whether you'd see this with Android clients.  My expectation is that you shouldn't - I believe we've got handling in place to avoid exactly this scenario.  If possible, it would be useful to compare the _changes requests being issued by the Pouch and CBL clients, to see if there are any differences in the parameters used.

I assume you already saw the feedback on https://github.com/couchbase/sync_gateway/issues/1312, about how to set the max wait property correctly.  With that set, I'd expect you to see the "Skipped Sequence 400597 didn't show up in ..." message earlier (i.e. after 5 mins), and for subsequent client requests to get a simple integer as the last_seq.

**Comment by sudhanitk** [comment] 2015-11-27 10:03
@adamcfraser 
As suggested in #1312,  "max_wait_skipped": 300000 interval is set to 5 min and restarted syncgw.
Skipped Sequence is observed as "Skipped Sequence 400596 didn't show ......" for {400595::402218} sequence.
After setting "max_wait_skipped" parameter value to 5 minutes, Sync_gateway is going in loop when client is asking for changes. Client is not recovering from loop.

Anything else do we need to configure in syncgateway to overcome from this loop issue?

**Comment by jchris** [comment] 2015-11-27 16:44
Maybe related to #1313 ?

**Comment by adamcfraser** [comment] 2015-11-27 17:50
There are two issues to diagnose here:
1. Why is there a sequence being allocated that's not showing up on the feed (triggering the skipped sequence handling in the first place)?  As Chris suggests - this could be related to #1313 - if PouchDB is trying to send _local docs as part of a bulk docs call, it might be allocating a sequence for those documents, but having the subsequent update fail or be cancelled.
2. Why is PouchDB looping when receiving a sequence with a LowSeq value.  I recall that this scenario was tested with an Android client doing longpoll replication (which should be a similar scenario), and it didn't trigger infinite looping.

**Comment by DanailMinchev** [comment] 2015-11-27 19:12
@adamcfraser

According # 2:
The test was done with Android client, but it is also does not work on desktop Chrome with Ubuntu.

**Comment by adamcfraser** [comment] 2015-11-27 19:31
Reviewed the code, and there's handling in place specifically to avoid this looping when serving longpoll changes requests (as used by Android for continuous replication).

It looks like this scenario is using repeated one-off, non-longpoll _changes requests, and so isn't picking up this handling.

This could be modified on the Sync Gateway side to also include this handling for one-off requests, although the real fix for this scenario is to identify why sequences are being skipped frequently in the first place (possibly the inclusion of _local in bulk_docs, #1313).

**Comment by adamcfraser** [comment] 2015-11-27 20:01
@ddash1 To help understand the sequence gaps - is this a single Sync Gateway instance, or a cluster of SGs?

**Comment by ddash1** [comment] 2015-11-29 17:00
@adamcfraser 
We are currently only having one SG instance but plan to go to a multi node SG deployment for prod.

**Comment by ddash1** [comment] 2015-12-01 22:16
Any updates on this?

**Comment by adamcfraser** [comment] 2015-12-11 17:56
Will apply the same handling used for longpoll to one-off changes requests.

**Closed as completed** 2016-01-05 05:54 UTC
Labels: bug, P2: medium

**Comment by colinjlacy** [comment] 2016-01-16 18:56
I'm having the same problem listed here in an Ionic 2 app using PouchDB. I've made sure to update everything as best I can. I'm using a Sync Gateway build from the Master branch (`app/Sync Gateway/sync_gateway`), and PouchDB 5.1.0.  I've got the repo [on my GitHub](https://github.com/colinjlacy/offline-ionic-2/tree/pouch) with the infinite loop logs [in the readme](https://github.com/colinjlacy/offline-ionic-2/tree/pouch#problems).  The config I'm using is also in that repo.

To summarize, it usually only happens when I refresh a second or third time, or two to open two different clients to the same Sync Gateway.  I'll be able to edit data, and I'll see the sync take place both in the Sync Gateway console, and in my browser console.  If I'm running one client, I'll make changes on a few items, and then refresh.  I'll do that two or three times before the Sync Gateway hits an infinite loop.

If I have two clients open, it usually happens when I make changes in one, wait for the sync to travel all the way through - confirming with console logs in both clients - and then refresh the client that didn't initiate the data change.

**Comment by DanailMinchev** [comment] 2016-01-17 23:58
@colinjlacy Have you tried latest PouchDB 5.2.0 ?

I have Ionic 1 app which works fine for now with "Couchbase Sync Gateway/master(ff5a4f0)" / https://github.com/couchbase/sync_gateway/tree/ff5a4f01be07a85fca40dc70a86875c6dfd953f5 and PouchDB 5.2.0.

However, I did not test with latest master version of Couchbase Sync Gateway or Ionic 2 .. Could you try https://github.com/couchbase/sync_gateway/tree/ff5a4f01be07a85fca40dc70a86875c6dfd953f5 ?

**Comment by colinjlacy** [comment] 2016-01-19 03:42
Still bad luck with it, despite updating PouchDB and trying that branch of the Sync Gateway.

**Comment by adamcfraser** [comment] 2016-01-19 05:42
@colinjlacy From the logs on listed here https://github.com/colinjlacy/offline-ionic-2/tree/pouch#problems,  that definitely looks like the issue with PR #1402, which is fixed on Sync Gateway master as of commit https://github.com/couchbase/sync_gateway/commit/db919442b6e20cd0cd8a01036a416558f5c89b26.  If you're still reproducing the issue when running against that build or later of Sync Gateway, can you provide updated log output from that run?

**Comment by colinjlacy** [comment] 2016-01-19 23:56
I pulled master for Sync Gateway and now it's finally working.  Thanks for all of the help and feedback!

**Comment by adamcfraser** [comment] 2016-01-19 23:58
@colinjlacy Excellent - thanks for letting us know.
