### ISSUE TITLE
[distributed_index] Excessive DCP rollback messages in log

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/sync_gateway#1104] opened 2015-09-01 15:12 UTC
part of https://github.com/couchbase/sync_gateway/issues/1079
SG commit bea245220

config file https://gist.github.com/andreibaranouski/1f658f93e6212eb0028f
with only "REST+" log level

SG spam output whttps://friendpaste.com/2BayCv2bZVFNu4XO2rR0eH output

**Comment by andreibaranouski** [comment] 2015-09-01 15:50
@adamcfraser could you fix it or provide workaround. I'm going to post some new issues but it's difficult to catch them in such huge quantities of logs

**Comment by adamcfraser** [comment] 2015-09-01 15:52
@tleyden - it looks like it's DCP rollback logging.  Assigning to Traun to investigate the root cause.

**Comment by tleyden** [comment] 2015-09-01 23:05
Going to assume it's related to https://github.com/couchbase/sync_gateway/issues/1098, so I'm closing as a duplicate.

**Closed as completed by tleyden** 2015-09-01 23:05 UTC
