### ISSUE TITLE
Improvement - multiple hostname of Couchbase Server Cluster

### ISSUE THREAD

**Issue by househippo** [couchbase/sync_gateway#2070] opened 2016-09-09 01:03 UTC
It be great to pass in an array of host name of Couchbase Server
Like Below.

{
  "log": ["_"],
  "databases": {
    "db": {
      "server": ["http://8.8.8.8:8091",""http://9.9.9.9:8091],
      "bucket": "default",
      "users": { "GUEST": { "disabled": false, "admin_channels": ["_"] } }
    }
  }
}

**Comment by tleyden** [comment] 2016-09-09 01:07
```
{
  "log": ["*"],
  "databases": {
    "db": {
      "server": ["http://8.8.8.8:8091",""http://9.9.9.9:8091],
      "bucket": "default",
      "users": { "GUEST": { "disabled": false, "admin_channels": ["*"] } }
    }
  }
}
```

**Comment by tleyden** [comment] 2016-09-09 01:08
Duplicate of https://github.com/couchbase/sync_gateway/issues/1019 + https://github.com/couchbase/sync_gateway/issues/2058

**Closed as completed by tleyden** 2016-09-09 01:08 UTC
