### ISSUE TITLE
No notification to CBL-Client changes_feed with channel filter for doc mutations when TAP response is received out of order

### ISSUE THREAD

**Issue by ArihantRk** [couchbase/sync_gateway#2358] opened 2017-03-02 16:06 UTC
### Sync Gateway version
1.3.1

### Operating system
Redhat 7.2

### Log output

Sync gateway is not responding to _changes feed with channel filtering whenever document is assigned to a channel. and responding later when different document is assigned to a same channel.

https://gist.github.com/ArihantRk/44c69dd7c1abab69630134b6abd631fe

Full log information is in below

[sync_gateway_access_log.txt](https://github.com/couchbase/sync_gateway/files/814286/sync_gateway_access_log.txt)

### Expected behavior
client should be notified by syncgateway immediately on receiving TAP response to _changes feed with channel filter if doc is assigned to channel.

### Actual behavior
_changes request is holding response to client eventhough doc is assigned to channel and correspondin TAP response has received which is mentioned in _changes parameter. The same is notified when a different doc is assigned to same channel.

### Steps to reproduce
1. CBL-Client A does changes_feed (long pool, on channel-A), and SGW holds changes_feed response.
2. CBL-Client A pushes attachment document X to SGW, and SGW is waiting for TAP response for doc X.
3. Some other document Y update happens at SGW by server component which assigns to channel-A, and SGW is waiting for TAP response for doc Y.
4. SGW received TAP response for document Y before receiving for previously sent document X. SGW is not notifying to CBL-Client A about document Y mutation in changes_feed response (SGW log snippet appeared: Deferring #37733 (1 now waiting for #37732...#37732)).
5. CBL-Client B does changes feed, and it gets the document Y changes, which were deferred in 4.
6. Some other document Z update happens at SGW by server component which assigns to channel-A, and SGW is waiting for TAP response for doc Z.
7. On receiving TAP response for document Z, now SGW notifies to CBL-Client A about document Y mutation (along with doc Z) in changes_feed response.

Shouldn't Sync Gateway notify about doc mutations Y immediately when TAP response received as it is doing in 5 (to other client B) and 7 (to same client A) above?

**Comment by adamcfraser** [comment] 2017-03-02 16:25
Thanks for the detailed report - I'll review and let you know what I find.

**Comment by adamcfraser** [comment] 2017-03-03 17:44
Can you provide some more specifics on your underlying question, as it relates to the docs/users in the attached logs?

More specifically - what do clients A and B, and documents X, Y and Z correspond to in the attached logs?

**Comment by adamcfraser** [comment] 2017-03-03 17:52
It looks like the initial push of `s919845012121_ptx1488269984168_a1488269984168_attachment.doc` is failing (item #4478) when the client resets the connection:

`
13:50:41.569506 2017-02-28T13:50:41.569+05:30 HTTP: #4478:     --> 500 Internal error: multipart: Part Read: read tcp 192.168.30.119:4984->192.168.30.5:7532: read: connection reset by peer  (42446.5 ms)`

It's possible this failed update has allocated a sequence that doesn't get reused/buffered until a subsequent write.  Need the info from the above question to investigate further.

**Comment by ArihantRk** [comment] 2017-03-06 04:18
@adamcfraser ,

client A -> 919845012121
client B -> 919845013131

doc X --> s919845012121_ptx1488269984168_a1488269984168_attachment.doc
doc Y --> s919845012121_ptx1488269984168_meta.doc
doc Z --> s919845013131_ptx1488269937478_s919845012121_DR.doc

please find the below CBL and Sync-GW log snippet for issue 
https://gist.github.com/ArihantRk/2ce03b0f6dbbf779ec1ceda1cafc992a

[poc_couch_logs.txt](https://github.com/couchbase/sync_gateway/files/821343/poc_couch_logs.txt)

**Comment by ArihantRk** [comment] 2017-03-10 05:10
@adamcfraser , any insights on this. This issue is seen very regularly. would be happy to provide more info if required.

**Comment by tleyden** [comment] 2017-06-09 00:36
@ArihantRk I tried to break these down into annotated steps to understand it better:

https://gist.github.com/tleyden/90c57a856806e7c17bb345b99990baec

Can you try to explain from those annotated steps what the actual vs expected behavior is?   You could copy and paste that into a new gist and add your own annotations.  I did see your gist at https://gist.github.com/ArihantRk/44c69dd7c1abab69630134b6abd631fe but had trouble understanding it.  I think mentioning SG <-> Couchbase Server communication such as TAP confuses the issue.  The best way to describe this is in terms of Client <-> SG communication while highlighting actual vs expected behavior.

How long are you seeing changes being delayed?  For example, in [Client A changes feed request #4: Finish](https://gist.github.com/tleyden/90c57a856806e7c17bb345b99990baec#client-a-changes-feed-request-4-finish) it looks like there a delay of approximately 3 mins 30 seconds delay between this [doc update](https://gist.github.com/tleyden/90c57a856806e7c17bb345b99990baec#doc-y-rev-4-channels-ptx-919845012121-meta-ch-ptx-919845013131-meta-ch-)  and [Client A changes feed request #4: Start](https://gist.github.com/tleyden/90c57a856806e7c17bb345b99990baec#client-a-changes-feed-request-4-start).  Is that the amount of delay you are seeing?

Also, in [PUT Doc Y rev 1](https://gist.github.com/tleyden/90c57a856806e7c17bb345b99990baec#put-doc-y-rev-1), I'm not able to see from the logs which channel(s) this doc has in it's first revision.  Do you know what channels that document is in initially?

An observation from looking at the logs: in [Client A changes feed request #4: Start](https://gist.github.com/tleyden/90c57a856806e7c17bb345b99990baec#client-a-changes-feed-request-4-start) the 919845012121 user appears to have access to channels: **{919845012121-CH, PTX-919845012121-meta-CH}**, but the [Doc X rev 2 update](https://gist.github.com/tleyden/90c57a856806e7c17bb345b99990baec#doc-x-rev-2-channels-ptx-919845012121-content-ch-ptx-919845013131-content-ch-) is adding the doc to channels **{PTX-919845012121-content-CH, PTX-919845013131-content-CH, '*'}**  -- which has no overlap.  Is this intentional?

Is it possible to share your sync function so that we can check if there are any access grants happening?

**Comment by tleyden** [comment] 2017-06-12 17:46
@ArihantRk there is a chance that https://github.com/couchbase/sync_gateway/issues/2626 is the root cause of this issue, and it has just been fixed in the master branch.  

Is it possible that you can retest against the [SG 1.5 build 421](http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.5.0/1.5.0-421/) and see if it fixes this issue?  (note: the build is still in progress.)

**Comment by tleyden** [comment] 2017-06-12 17:47
I'm going to proactively close this and assume that the fix for #2626 covers this.  If not, it can be re-opened.

**Closed as completed by tleyden** 2017-06-12 17:47 UTC
Labels: P1: high, ffc

**Comment by ArihantRk** [comment] 2017-06-27 10:12
Thanks @tleyden. We are verifying with SG 1.5 build 421. Will update the test results.

**Comment by ArihantRk** [comment] 2017-06-28 05:00
@tleyden Verified the 1.5.0_421 build with both DCP and TAP feeds. Issue is not observed/reproduced. Issue is seems to be fixed.

**Comment by ArihantRk** [comment] 2017-09-16 00:12
@tleyden is this included in 1.4.1.2 ?
