### ISSUE TITLE
XATTR:Sync Gateway returns 404 for successful DELETE intermittently

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/sync_gateway#2648] opened 2017-06-14 18:54 UTC
### Sync Gateway version
1.5.0-428

### Operating system
CentOS 7

### Config file
```javascript
{
        "adminInterface": "0.0.0.0:4985",
        "compressResponses": false,
        "databases": {
            "db": {
                "bucket": "data-bucket",
                "import_docs": "continuous",
                "password": "password",
                "server": "http://cbl.0:8091",
                "unsupported": {
                    "enable_extended_attributes": true
                },
                "username": "data-bucket",
                "users": {
                    "GUEST": {
                        "admin_channels": [
                            "*"
                        ],
                        "disabled": true
                    }
                }
            }
        },
        "interface": ":4984",
        "log": [
            "CRUD+",
            "Cache+",
            "HTTP+",
            "Changes+"
        ],
        "maxCouchbaseConnections": 16,
        "maxFileDescriptors": 90000,
        "maxIncomingConnections": 0,
        "slowServerCallWarningThreshold": 500
    }
```

### Log output
https://gist.github.com/sethrosetter/21403daad50d3d62909fd2cad4e01042

### Expected behavior
A successful DELETE should return 200

### Actual behavior
Intermittently, a successful DELETE will return a 404

### Steps to reproduce
1.  http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/709/testReport/junit/testsuites.syncgateway.functional.tests/test_xattrs/test_purge_sync_gateway_default_functional_tests_True_/

Link to the failing scenario - https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/syncgateway/functional/tests/test_xattrs.py#L453-L659

**Comment by sethrosetter** [comment] 2017-06-14 19:09
I just saw this in another scenario that does not even involve SDK. I think you make be able to repro this with xattrs enabled and a GET / DELETE loop of a lot of docs.

**Comment by djpongh** [comment] 2017-06-16 18:49
Most likely related to:  https://issues.couchbase.com/browse/MB-24868

**Comment by sethrosetter** [comment] 2017-06-23 21:18
I can't repro this locally anymore with 1.5.0-446. Waiting on this http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/758/ to validate if it still shows up in the Jenkins environment.

**Comment by adamcfraser** [comment] 2017-06-23 23:49
Still pending uptake of single-op delete (https://issues.couchbase.com/browse/MB-24868) - need to apply that and see if this is still failing.

**Comment by adamcfraser** [comment] 2017-06-23 23:51
Potentially a race between a feed-based import and an API-based delete.

**Comment by sethrosetter** [comment] 2017-06-23 23:51
https://gist.github.com/sethrosetter/f35bf4bd7818b1954e5d93f15d760bf7#file-gistfile1-txt-L17-L23. Still seeing this after the uptake of the server fix.

**Comment by sethrosetter** [comment] 2017-06-26 21:57
I not sure, but could be related to https://issues.couchbase.com/browse/GOCBC-210

**Comment by djpongh** [comment] 2017-06-28 17:37
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/664/testReport/junit/testsuites.syncgateway.functional.tests/test_xattrs/test_purge_sync_gateway_default_functional_tests_True_/

**Comment by tleyden** [comment] 2017-06-29 23:04
Tried to repro several times (5) with:

```
pytest -s --xattrs --mode=di --skip-provisioning --server-version=5.0.0-3193 --sync-gateway-version=1.5.0-452 -k "test_purge[sync_gateway_default_functional_tests-True]"  testsuites/syncgateway/functional/tests/
```

But it's passing each time.  

[Test output](https://gist.github.com/tleyden/41b94c506e6467a93ac1de86731162e8)

**Comment by tleyden** [comment] 2017-06-30 18:07
@sethrosetter need help reproducing locally

**Comment by sethrosetter** [comment] 2017-07-05 18:47
I'm not sure this is reproducible in docker but I'm seeing it in Jenkins - http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/805/testReport/junit/testsuites.syncgateway.functional.tests/test_xattrs/test_purge_sync_gateway_default_functional_tests_True_/

**Comment by sethrosetter** [comment] 2017-07-05 19:54
```
2017-06-29T18:26:24.956-07:00 HTTP:  #029: DELETE /db/sg_2?rev=1-ed7537344fbe5548609a306c38f918ff  (as seth)
2017-06-29T18:26:24.961-07:00 CRUD+: Invoking sync on doc "sg_2" rev 2-b2edabf78064cce02122330de5ad4aa8
2017-06-29T18:26:24.961-07:00 CRUD+: Saving old revision "sg_2" / "1-ed7537344fbe5548609a306c38f918ff" (20904 bytes)
2017-06-29T18:26:24.962-07:00 CRUD+: Backed up obsolete rev "sg_2"/"1-ed7537344fbe5548609a306c38f918ff"
2017-06-29T18:26:24.963-07:00 CRUD: 	Doc "sg_2" in channels "{}"
2017-06-29T18:26:24.965-07:00 CRUD+: Saving doc (seq: #23, id: sg_2 rev: 2-b2edabf78064cce02122330de5ad4aa8)
2017-06-29T18:26:24.969-07:00 Import+: Attempting to import doc "sg_2"...
2017-06-29T18:26:24.973-07:00 CRUD: Update of new value during WriteUpdateWithXattr failed for key sg_2: key not found
2017-06-29T18:26:24.973-07:00 CRUD+: Did not update document "sg_2" w/ xattr: key not found
2017-06-29T18:26:24.989-07:00 CRUD+: Released unused sequence #23
2017-06-29T18:26:24.989-07:00 HTTP: #029:     --> 404 missing  (39.4 ms)
2017-06-29T18:26:24.989-07:00 Cache: Received #23 (unused sequence)
2017-06-29T18:26:24.991-07:00 CRUD+: Doc sg_2 is not an SG write, based on cas. cas:14ccc1e994450000 syncCas:"0x0000226de9c1cc14"
2017-06-29T18:26:24.991-07:00 Import: Created new rev ID 2-b2edabf78064cce02122330de5ad4aa8
2017-06-29T18:26:24.991-07:00 CRUD+: Invoking sync on doc "sg_2" rev 2-b2edabf78064cce02122330de5ad4aa8
2017-06-29T18:26:24.992-07:00 CRUD+: Got old revision "sg_2" / "1-ed7537344fbe5548609a306c38f918ff" --> 20904 bytes
2017-06-29T18:26:24.993-07:00 CRUD: 	Doc "sg_2" in channels "{}"
```

**Comment by sethrosetter** [comment] 2017-07-05 19:56
Full logs - https://gist.githubusercontent.com/sethrosetter/495bd4e50e8924a7b92ef3018ad2fd9b/raw/02c1bc251fe9e6f55942a7df2260b285b3877b1d/gistfile1.txt

**Comment by sethrosetter** [comment] 2017-07-05 19:57
This repro's every time in Jenkins - http://uberjenkins.sc.couchbase.com:8080/job/cen7-sync-gateway-functional-tests-base-cc/809/testReport/

**Comment by sethrosetter** [comment] 2017-07-05 20:09
I was able to repro this locally with docker on the second run.

**Comment by sethrosetter** [comment] 2017-07-05 20:38
Logs with "gocb" log tag enabled - https://gist.githubusercontent.com/sethrosetter/279945a81dacc0ae5b82f7c152c160c8/raw/4a1d7cbb1a0884f28c404e571db37bea544df915/gistfile1.txt

**Comment by sethrosetter** [comment] 2017-07-05 21:13
Packet capture. 
[pc2.pcap.zip](https://github.com/couchbase/sync_gateway/files/1126051/pc2.pcap.zip)

Open in Wireshark and filter "couchbase".

The failing delete response is packet 16406.

**Comment by tleyden** [comment] 2017-07-10 18:11
I tried testing https://github.com/couchbase/sync_gateway/commit/41204f2480180e853332e25becc081b1f0da67d9 (from https://github.com/couchbase/sync_gateway/issues/2681), but it appears to be failing for a different reason in my first test run attempt:

```
./repeat 20 pytest -s --xattrs --mode=cc --skip-provisioning --server-version=5.0.0-3217 --sync-gateway-version=1.5.0-456 -k "test_purge[sync_gateway_default_functional_tests-True]"  testsuites/syncgateway/functional/tests/
```

Fails with:

```
DELETE http://cbl.1:4984/db/sdk_9?rev=1-ed7537344fbe5548609a306c38f918ff 200
GET http://cbl.1:4984/db/sdk_8?conflicts=true&revs=true 200
DELETE http://cbl.1:4984/db/sdk_8?rev=1-ed7537344fbe5548609a306c38f918ff 200
GET http://cbl.1:4984/db/sdk_2?conflicts=true&revs=true 200
DELETE http://cbl.1:4984/db/sdk_2?rev=1-ed7537344fbe5548609a306c38f918ff 200
GET http://cbl.1:4984/db/sdk_3?conflicts=true&revs=true 200
DELETE http://cbl.1:4984/db/sdk_3?rev=1-ed7537344fbe5548609a306c38f918ff 200
GET http://cbl.1:4985/db/_raw/sg_7 200
Verifying XATTR (expected num revs: 2, expected num channels: 1000)
FAILEDTearing down test 'test_purge[sync_gateway_default_functional_tests-True]'

...

>           assert len(sg_sync_meta['recent_sequences']) == expected_number_of_revs
E           assert 1 == 2
E            +  where 1 = len([9])
```

@sethrosetter can you update the assertion to emit the actual number of revs?  Also, it might be useful to dump the revs when the assertion fails.  

Also [this code](https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/syncgateway/functional/tests/test_xattrs.py#L1488) looks like a potential bug:

```
assert len(sg_sync_meta['history']['channels']) == expected_number_of_revs
```

Should that be comparing against expected number of channels?

**Comment by sethrosetter** [comment] 2017-07-10 18:14
~~Oh good. Catch. I think this has been failing before this on the deletes for a long time that it hasn't hit this test issue.~~ Update: Upon inspection, the test looks fine.

**Comment by tleyden** [comment] 2017-07-10 18:58
The test is failing because the doc only has one rev (the rev is not incremented during the delete)

```
[root@256df097ce5e mobile-testkit]# curl http://cbl.1:4985/db/_raw/sdk_2 | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 47062  100 47062    0     0  4163k      0 --:--:-- --:--:-- --:--:-- 4595k
{
  "_deleted": true,
  "_sync": {
    "rev": "1-ed7537344fbe5548609a306c38f918ff",
    "sequence": 18,
    "recent_sequences": [
      18
    ],
    "history": {
      "revs": [
        "1-ed7537344fbe5548609a306c38f918ff"
      ],
      "parents": [
        -1
      ],
```

**Comment by tleyden** [comment] 2017-07-10 19:47
> The test is failing because the doc only has one rev (the rev is not incremented during the delete)

After 5b91bd698dd3f061b02f4ef8f19b98bbdb66e87b, the test passed on the first repro attempt, but on second repro attempt got error:

```
2017-07-10T19:42:50.968Z CRUD+: called bucket.WriteCasWithXattr() with key: sg_3, xattrkey: _sync.  casOut: 0 writeErr: <nil>
2017-07-10T19:42:50.968Z CRUD: purging document = sg_6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47a8f0]

goroutine 148 [running]:
panic(0xae1140, 0xc42000e040)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbase/sync_gateway/base.CouchbaseBucketGoCB.WriteUpdateWithXattr(0xc42028c1b0, 0xc42018aa60, 0x11, 0xba549b, 0x7, 0xc42018d1c0, 0xb, 0x0, 0x0, 0xf57760, ...)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/base/bucket_gocb.go:1264 +0x810
github.com/couchbase/sync_gateway/base.(*CouchbaseBucketGoCB).WriteUpdateWithXattr(0xc42028c240, 0xc420ba42e4, 0x4, 0xba2e95, 0x5, 0x0, 0xc420ca4600, 0x42e610, 0xc4212e8598, 0x300000002)
	<autogenerated>:484 +0xde
github.com/couchbase/sync_gateway/db.(*Database).updateAndReturnDoc(0xc4214309a0, 0xc420ba42e4, 0x4, 0x1, 0xc420f1e3c0, 0x1, 0x1, 0x0, 0x30, 0xc4205d7b90)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:980 +0x1f37
github.com/couchbase/sync_gateway/db.(*Database).ImportDoc(0xc4214309a0, 0xc420ba42e4, 0x4, 0xc420ca45a0, 0xc4212b6201, 0x14d00f8c3fe40000, 0x0, 0xc420166000, 0xc421430962, 0x7ff4a1213960)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:685 +0x274
github.com/couchbase/sync_gateway/db.(*Database).ImportDocRaw(0xc4214309a0, 0xc420ba42e4, 0x4, 0x0, 0x0, 0x0, 0x1, 0x14d00f8c3fe40000, 0x0, 0x0, ...)
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/crud.go:626 +0x199
github.com/couchbase/sync_gateway/db.(*changeCache).DocChanged.func1()
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/change_cache.go:371 +0x1233
created by github.com/couchbase/sync_gateway/db.(*changeCache).DocChanged
	/Users/tleyden/Development/sync_gateway/godeps/src/github.com/couchbase/sync_gateway/db/change_cache.go:471 +0x2b3
```

**Comment by tleyden** [comment] 2017-07-10 20:11
After f16ca9e638c4278815671d126c2ab8d390cf96cb, I'm seeing this error when running the
while running `test_purge[sync_gateway_default_functional_tests-True]` test in a repeat loop.  Have only seen once so far

```
        # Verify that all docs have been deleted
        sg_deleted_doc_scratch_pad = list(all_doc_ids)
        for error in errors:
>           assert error['status'] == 404
E           assert 403 == 404
```

Full testkit-logs:

https://gist.github.com/tleyden/861ead1308c8baa6cf7c4e9e6bbbf993

**Comment by tleyden** [comment] 2017-07-11 17:35
The test is failing after the purge operation, which eventually calls down to `DeleteWithXattr()`, and I can see that we are still using the non-transactional xattr delete here:

```
func (bucket CouchbaseBucketGoCB) DeleteWithXattr(k string, xattrKey string) error {

	bucket.singleOps <- struct{}{}
	defer func() {
		<-bucket.singleOps
	}()
	gocbExpvars.Add("Delete", 1)


	removeCas, err := bucket.Bucket.Remove(k, 0)
	if err != nil && err != gocb.ErrKeyNotFound {
		return err
	}

	_, deleteXattrErr := bucket.Bucket.MutateInEx(k, gocb.SubdocDocFlagAccessDeleted, removeCas, 0).
		RemoveEx(xattrKey, gocb.SubdocFlagXattr).
		Execute()

	if deleteXattrErr != nil && deleteXattrErr != gocbcore.ErrSubDocSuccessDeleted {
		return deleteXattrErr
	}

	return nil
}
```

Going to switch over to use the transaction delete doc + xattrs and see if it fixes it.

**Comment by tleyden** [comment] 2017-07-12 00:09
After fixing the code mentioned in https://github.com/couchbase/sync_gateway/issues/2648#issuecomment-314517632 and working w/ Brett to review the gocb usage, 6ce5a3a146f14579a3a214bb693cee1cc3e16a27 looks like it's passing in a repeated test loop.  

I still have some questions on the usage, and sent out an email to the KV team

**Comment by tleyden** [comment] 2017-07-20 20:54
Fixed in https://github.com/couchbase/sync_gateway/pull/2721

**Closed as completed by tleyden** 2017-07-20 20:54 UTC
Labels: P1: high, functional-test-failure
